### ISSUE TITLE
Filter/Map Either's Right to a Left

### ISSUE THREAD

**Issue by gordonwatts** [louthy/language-ext#101]
Say I have the following method:

        public async Task<Either<Exception,int>> GetCurrentJobNumber()
        {
            // Build the job URI, which will then return the JSON.
            return (await _server.FetchJSON<JenkinsJob>(GetJobURIStem()))
                .Map(v => v.lastCompletedBuild)
                .Map(v => v.number);
        }

The FetchJSON will return an Either<Exception, JenkinsJob>. I'd like to then filter on lastCompletedBuild being null. However, if it is null, then I want to convert the Either to be a Right (new Exception("No job has been run")).

Is there a way to accomplish this?

Many thanks for the library! I'm just starting to try to use it. it is quite viral, but it turns functions like above from 10 lines of code into 3 very clear ones.

**Comment by gordonwatts** [comment]
Ok, I think I'm getting it... but it looks very ugly.

            var r = (await jk)
                .Right(j => j.lastBuild == null ? Left<Exception, JenkinsJob>(new ArgumentException("No build completed")) : Right<Exception, JenkinsJob>(j))
                .Left(e => Left<Exception, JenkinsJob>(e))
                .Map(j => j.lastBuild.number);

where "jk" is the result from _server.FetchJSON<>

Perhaps there is a way to clean that up? It isn't very readable as it stands. :-)

**Comment by louthy** [comment]
@gordonwatts It's a slightly awkward one, but a general rule-of-thumb if you want to change the monad itself rather than the value stored within it is to use `Bind`:

So where `Map` has the signature `Func<T, R>`; `Bind` has the signature `Func<T, M<R>>` where `M` is the monad.  

With your example you're switching from `Right` to `Left` and therefore working on the monad, rather than just mapping the values within.

This is an example with `Bind`
```c#
    public static async Task<Either<Exception, int>> GetCurrentJobNumber() =>
        (await _server.FetchJSON(GetJobURIStem()))
            .Bind(job => job.lastBuild == null
                ? Left<Exception, int>(new ApplicationException("No build completed"))
                : Right<Exception, int>(job.lastBuild.number));
```
It's still not super pretty because `Either` required two generic type params and therefore the type-inference is non-existing.  What I'll often do when using `Either` is to create some `static` helper functions for creating the `Right` and `Left` states for the common `<L,R>` pairs.  

For example with a couple of functions (and `using static ...`):
```c#
        static Either<Exception, int> Success(int value) =>
            Right<Exception, int>(value);

        static Either<Exception, int> AppError(string msg) =>
            Left<Exception, int>(new ApplicationException(msg));
```
The code becomes much more declarative:
```c#
    public static async Task<Either<Exception, int>> GetCurrentJobNumber() =>
        (await FetchJSON(GetJobURIStem()))
            .Bind(job => job.lastBuild == null
                ? AppError("No build completed")
                : Success(job.lastBuild.number));
```

With cunning use of extension methods targeted at specific types (in this case `JenkinsJob`):
```c#
    static Either<Exception, int> EnsureCompletedBuild(this JenkinsJob self) =>
        self.lastBuild == null
            ? AppError("No build completed")
            : Success(self.lastBuild.number);
```
Then you have a reusable function that is super clear:
```c#
    public static async Task<Either<Exception, int>> GetCurrentJobNumber() =>
        (await FetchJSON(GetJobURIStem()))
            .Bind(EnsureCompletedBuild);
```
You could go even further and use the `NewType` system to give meaning to your `int` (and make it type-safe):
```c#
    public class JobId : NewType<int> 
    { 
        public JobId(int id) : base(id) { } 
    }
```
And update the helper functions to use it:
```c#
    static Either<Exception, JobId> EnsureCompletedBuild(this JenkinsJob self) =>
        self.lastBuild == null
            ? AppError("No build completed")
            : Success(new JobId(self.lastBuild.number));

    static Either<Exception, JobId> Success(JenkinsBuildId value) =>
        Right<Exception, JobId>(value);

    static Either<Exception, JobId> AppError(string msg) =>
        Left<Exception, JobId>(new ApplicationException(msg));
```
Then your resulting function looks like this:
```c#
    public static async Task<Either<Exception, JobId>> GetCurrentJobNumber() =>
        (await FetchJSON(GetJobURIStem()))
            .Bind(EnsureCompletedBuild);
```
The final result is a function that declares its intentions entirely.

Hope that helps! :)

**Comment by gordonwatts** [comment]
Ah, thanks. The Bind rule of thumb is exactly the sort of thing I'm interested in. Also, the breakdown and refactoring is a huge help as well.

**Comment by glen-nicol** [comment]
I cannot seem to replicate this using newer versions of the library (3.4.15). I am trying to convert from ```EitherAsync<Error,Result>``` to ```OptionAsync<Error>``` because the final step in my pipeline returns a unit and I figure the Option monad is more "correct" then Either<Error,Unit>. I could be wrong there since I am new to the monad world.

In the newest version of the library Bind is forced to return an EitherAsync of various flavors where L stays the same. So it seems that the best option is to back up 1 step and then ``` .Match(x => doFinal(x), error => SomeAsync(error))```. But that returns a ```Task<OptionAsync<Error>>``` Which sadly doesn't compose well with the overall return of just ```OptionAsync<Error>```.  

I am new to the library so I haven't learned the tricks to make these seemingly simple transitions either. It seems like an ```Task<OptionAsync<T>>``` should have some way to coalesce to an ```OptionAsync<T>``` without going through match to return the ```Task<T```> just to be rewrapped again.

**Comment by TysonMN** [comment]
> I am trying to convert from `EitherAsync<Error,Result>` to `OptionAsync<Error>` because the final step in my pipeline returns a unit and I figure the Option monad is more "correct" then Either<Error,Unit>. I could be wrong there since I am new to the monad world.

Since you are new to monads, I recommended matching at the top level and handling all cases as you like.

If you insist though, then you can do this.

```csharp
EitherAsync<string, int> x = ...
OptionAsync<string> y =
  x
  .Match(_ => None, Some)
  .ToAsync();
```

> It seems like an `Task<OptionAsync<T>>` should have some way to coalesce to an `OptionAsync<T>` without going through match to return the `Task<T`> just to be rewrapped again.

I think this works.

```csharp
Task<OptionAsync<T>> x = ...
OptionAsync<T> y =
  x
  .Bind(z => z.ToOption())
  .ToAsync()
```

**Comment by glen-nicol** [comment]
Both of those work. Thanks so much!

Can you share why I should prefer to keep either rather than option? When I write a function in isolation I see it only needs the error so I figure why include the Either and Unit stuff that could be confusing with respect to its usage. 

Also is there any guidance or thought process you can give me to try and figure out the exact combinations of Match(async) and ToOption, ToAsync that make the transitions? Especially with Match I find it secretly resolving to the Task<Unit> return because it uses the action parameters instead of func parameters.

Happy Thanksgiving!

**Comment by TysonMN** [comment]
> Can you share why I should prefer to keep either rather than option? When I write a function in isolation I see it only needs the error so I figure why include the Either and Unit stuff that could be confusing with respect to its usage.

I you really only need the error, then this fine.

When people are new to the monadic composition, I often see them unable to "simultaneously" consider what to do in each case.  Instead, they want to think more impratively and first do some action if in one state and then do some action if in the other state. 

> Especially with Match I find it secretly resolving to the Task return because it uses the action parameters instead of func parameters.

Is that because you are using `Task`?  Never use `Task`.  Instead, always use `Task<Unit>`.

> is there any guidance or thought process you can give me to try and figure out the exact combinations of Match(async) and ToOption, ToAsync that make the transitions?

Practice and experience are the best way to help you figure out smaller / shorter ways to express certain transformations.  I remember when I first started using `language-ext`.  I wrote some transformation, and I knew it was very verbose, but I also didn't know any way to improve it.  I decided that I should be satisfied for now that I got the types correct and that over time I would figure out the "right way" to express that transformation.

**Comment by glen-nicol** [comment]
No not using bare Task. The overloads for a lot of the functions resolve to Func<Task> or Action when the return types of multiple functions don't align. This causes the overall return to usually involve Unit. Which ends up being confusing because there is no syntax error about the types not matching like they should. 

If I had a crystal ball to go back I would suggest the variants that end up with Unit returns like this should have a slightly different name to avoid that. But once again, experience is probably necessary. Just so used to the awesome C# compiler telling me when I need to go learn something new!

Can you tell me more about what you mean by simultaneously considering each case?

**Comment by TysonMN** [comment]
Yes, I have also been frustrated by a compile error involving multiple overloads.

I have seen people write code something like
```csharp
Option<int> option = ...
if (option.IfSome) Console.WriteLine("I have int " + option.Value);
else Console.WriteLine("I have no int");
```

Better is
```csharp
option.Match(
  i => Console.WriteLine("I have int " + i),
  () => Console.WriteLine("I have no int"))
```

Best (in my opinion) is
```csharp
option
  .Map(i => "I have int " + i)
  .IfNone("I have no int")
  .Apply(Console.WriteLine) // though might have to eta-expand this to .Apply(s => Console.WriteLine(s)) in order to compile
```

**Comment by glen-nicol** [comment]
wait.... .Value() I didn't even know that was possible! I had been thinking man it kinda seems impossible to map some of these to other interfaces without direct access. Well you've ruined me now!

For context, I had an ```IEnumerable<Validation<Error, T>>``` and the only way I could reason about getting the valid ones was to do a where IsSuccess and then select match(t => t, err => throw). I couldn't find an extension to get valid ones if one exists.

What is the main use or purpose of ```Apply```? In your example it looks like the place where side effects are introduced. But I have also ended up using it like this to start a chain. ```unit.Apply(_ => GetEitherAsync())....``` Which I guess is kinda side effect related since it is from a unit.

**Comment by TysonMN** [comment]
> wait.... .Value() I didn't even know that was possible! I had been thinking man it kinda seems impossible to map some of these to other interfaces without direct access. Well you've ruined me now!

Actually, I don't see `Option<>.Value` in `language-ext`.  I was either getting confused between [F#'s `Option<>.Value`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-option-1.html#Value) or a custom extension method like the following that someone could write for `Option<>` in `language-ext`.
```csharp
public static A Value<A>(this Option<A> ma) => ma.IfNone(() => throw new ArgumentException());
```

Either way, I have still seen people write (bad) code like that even if it wasn't exactly C# and vanilla `language-ext`.

> For context, I had an `IEnumerable<Validation<Error, T>>` and the only way I could reason about getting the valid ones was to do a where IsSuccess and then select match(t => t, err => throw). I couldn't find an extension to get valid ones if one exists.

Here is how you get the valid ones.
```csharp
IEnumerable<A> validOnes = sva.Map(va => va.ToOption()).Somes()
```

> What is the main use or purpose of `Apply`? In your example it looks like the place where side effects are introduced. But I have also ended up using it like this to start a chain. `unit.Apply(_ => GetEitherAsync())....` Which I guess is kinda side effect related since it is from a unit.

In C# (and my other programming languages), the syntax for function application uses a prefix notation.
```charp
f(x)
```
The purpose of `Apply` is to change function application (if you "squint") to a postfix notation.
```charp
x.Apply(f)
```

I wrote about this in [this post](https://tysondw.blogspot.com/2019/01/syntax-for-composition-of-functions.html) on my old blog.  (I need to port that new [my new blog](https://tysonwilliams.coding.blog/).)
