### ISSUE TITLE
Activity.Current is null in 4.0.9-beta

### ISSUE THREAD

**Issue by seungyongshim** [louthy/language-ext#1028]
Excuse, me

My product is broken to 4.0.9-beta. I read to https://github.com/louthy/language-ext/commit/492eeb7d47a5d80d5f96f9e21c95db82cd393d73, but I don't understanding. Please help, us.

## Sample Code
* https://github.com/seungyongshim/poc-activity-null
```csharp
var q = from _1 in unitAff
        from _2 in use(from _a in unitAff
                       let _b = activitySource.StartActivity()
                       select _b,
                       a => Eff(() => Activity.Current ?? throw new Exception("Bug?")).ToAsync())
        select unit;

var r = await q.Run();
r.ThrowIfFail();
```

## Expect
* same result between 4.0.8-beta and 4.0.9-beta 

## Actual
* 4.0.8-beta : pass
* 4.0.9-beta : exception

**Comment by louthy** [comment]
@seungyongshim It isn't obvious just yet, the changes from `4.0.8-beta` to `4.0.9-beta` was large for `Eff` and `Aff`, so I'll need some time to investigate, it appears to be related to the threading context (not being passed through the async/await chain) - beyond that, I'm not 100% sure atm.  

So, it'd be better to revert to `4.0.8-beta` until I can narrow it down.  This is why we beta :)

**Comment by louthy** [comment]
After a bit of digging, this isn't an issue with `Aff`.  You were likely to hit the same problem with the old version of `Aff`, and the only reason you didn't see it is because there used to be a synchronous-only path when `Aff` was used with only pure values (i.e. no async/await machinery had been called). 

I can reproduce the same issue with `Task`:

```c#
public static async Task Main()
{
    using var listener = new ActivityListener
    {
        ShouldListenTo = _ => true,
        Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllData,
        ActivityStarted = activity => Console.WriteLine($"{activity.ParentId}:{activity.Id} - Start"),
        ActivityStopped = activity => Console.WriteLine($"{activity.ParentId}:{activity.Id} - Stop")
    };

    ActivitySource.AddActivityListener(listener);
    var activitySource = new ActivitySource("what?!");
    
    await SomeAsyncOperation(activitySource);

    Console.WriteLine(Activity.Current);
}

public static async Task<Activity?> SomeAsyncOperation(ActivitySource src)
{
    await Task.Delay(1);
    return src.StartActivity("example");
}
```
When the `Console.WriteLine` is called, the value of `Activity.Current` is `null`.  Internally `Activity.Current` is an `AsyncLocal`, so it's surprising that it doesn't work.  However if you look at `Activity.Current` right after the call to `StartActivity`, you can see it's set, but on exit from `SomeAsyncOperation` it's `null`.  

But really, relying on global state like this isn't the best way to write code - especially with async-local values that could just evaporate, or be wiped out by modification to the thread's execution/sync context.  

I realise it's baked into the BCL, but we can do better than that in functional programming.  The way to do it is to make the 'current activity' part of the _runtime_ in a an `Aff<RT, A>` (`RT` being the runtime).

So, I've added a new package: `LanguageExt.SysX` - it's like `LanguageExt.Sys`, except it's for .NET5+ features (`LanguageExt.Sys` is .netstandard 2.0, and I'd like to keep it like that).

In there is a type: [`LanguageExt.SysX.Diag.Activity<RT>` ](https://louthy.github.io/language-ext/LanguageExt.SysX/SysX/Diag/index.html) which works with an `ActivitySource` that's passed through the runtime (`RT`), and automatically knows the current `Activity`, and will automatically link child Activities to its parent.

You can wrap an `Eff` or an `Aff` operation with an activity-span, and it will start the activity, link to the parent, and clean up automatically:

```c#
    Activity<RT>.span("foo", ma);   // ma is the Aff or Eff to wrap
```

Here's something a bit like your original example, but it has two nested spans:

```c#
    using LanguageExt;
    using LanguageExt.Sys;
    using LanguageExt.SysX.Diag;
    using LanguageExt.SysX.Live;
    using static LanguageExt.Prelude;

    var q = Activity<Runtime>.span("outer",
                from n in Activity<Runtime>.operationName 
                from _ in Console<Runtime>.writeLine(n.IfNone("[not set]"))
                from rs in Activity<Runtime>.span("inner",
                    from n in Activity<Runtime>.operationName 
                    from _ in Console<Runtime>.writeLine(n.IfNone("[not set]"))
                    select unit)
                select rs);

    var r = q.Run(Runtime.New());
```
The `Runtime` type is the one built in to `LanguageExt.SysX`, you could build your own if you want to expand its capabilities.  

There's also functions in `Activity<RT>` for adding tags and baggage, as well as accessing the current `Activity`.

Apologies if this means changes to your current code, but I couldn't really see any obvious way that these `AsyncLocal` values could be safely supported.

**Comment by louthy** [comment]
Ok, after sleeping on it, there's a way to make it work with `Aff` as it is today.  The fact that `AsyncLocal` acts like a local, means that the `Aff` passed to `use` in the original example loses its local context after being run (to get the `IDisposable`)

So, you can do that yourself.  Here's an example of `span` that will maintain the context properly (and link the child to the parent):

```c#
public static Aff<A> span<A>(string name, ActivitySource? src, Aff<A> ma) =>
    AffMaybe(async () =>
    {
        var act = Activity.Current is null
          ? src?.StartActivity(name)
          : src?.StartActivity(name, ActivityKind.Internal, Activity.Current.Context);
            
        using (act)
        {
            return await ma.Run().ConfigureAwait(false);
        }
    });
```

It's still questionable whether you'd want to do this, but as long as the thread context isn't wiped out, it _should_ flow through.  Instead of using `Activity.Current` directly, I'd encourage you two wrap it up (it means it can be changed later also):

```c#    public static Eff<Activity?> current =>
        Eff(() => Activity.Current);
```

Then you can build other friendly accessors from that:
```c#
    public static Eff<string?> operationName =>
        current.Map(a => a?.OperationName);
```

Now if I just add some helper functions to force my next example to be an `Aff` and to allow writing to the console:
```c#
    public static Aff<Unit> delay(int ms) =>
        Aff(async () =>
        {
            await Task.Delay(ms);
            return unit;
        });

    public static Eff<Unit> writeLine(string line) =>
        Eff(() =>
        {
            Console.WriteLine(line);
            return unit;
        });
```

We can then rewrite my example from before:

```c#
    var src = new ActivitySource("what?!");

    var q = span("outer", src,
        from d in delay(1)
        from n in operationName 
        from _ in writeLine(n)
        from rs in span<Unit>("inner", src,
            from n in operationName 
            from _ in writeLine(n)
            select unit)
        select rs);

    var r = await q.Run();
```

> NOTE: You have to propagate the `ActivitySource` manually, which you don't have to do with the `Aff<RT, A>` version.  

This will do exactly as you expect, without the need to use the runtime version of `Aff` (although I'd encourage you to use that, as it's the best way to capture global state, and do injectable IO).

**Comment by seungyongshim** [comment]
I have a lot to be thanksful for. I will try that.
