### ISSUE TITLE
Schedule.Recurs is not a schedule anymore.

### ISSUE THREAD

**Issue by bmazzarol** [louthy/language-ext#1047]
@louthy thanks for merging my PR! I realy appreciate it. 

As is always the way, found something after the merge, while reading the wiki.

The way Recurs is defined differs from the old schedule. Its a schedule transformer, not a schedule in its own right.

It means that it cannot be used on its own like in the wiki example. 

One option might be an implicit conversion to Schedule, this would be odd to me, but might be possible. Just feed the transformer Schedule.Forever

Another option, revert it back to a schedule, this requires a change to the definition of union, it needs to stop with the shortest schedule. This behavior differs from Zio, but might still be acceptable. 

Final option, treat it as breaking, fix documentation and wear the change.

Once we have an answer here I can create a PR.

**Comment by louthy** [comment]
I'm doing a bit more in-depth reviewing now that it's on my machine  - mostly just tidying up a few bits here and there with the documentation (so it looks good in the API docs), and a few minor perf improvements;  So, thanks for the heads up, leave that with me, I'll take a look and find a way that I'm happy will work well for the users 👍

**Comment by louthy** [comment]
@bmazzarol  So, I tried a few things:

* Add an extra overload for all the functions/methods that took a `Schedule` to also take a `ScheduleTransform`, which would apply `Schedule.Forever` to it
  * This would have worked, but the burden was too high in terms of duplicated code and possible knock on effects to the users
* Then I tried making `Schedule` into a discriminated-union type that had two cases: `TimeSeries` and `Transformer`.  This would allow for a single `Schedule` type.  This was OK, but the `Intersect`, `Union`, and `Append` methods (amongst others) were leaky abstractions.
* I thought about the other two options you mentioned:
  *  Making `Recurs` return a `Schedule` - I didn't like that idea, it feels like it's hiding the intent, and I suspect there would be side-effects to that approach that would manifest as bugs
  * The implicit conversion to `Schedule` with `Forever` applied.  I think this is a little bit 'magic', which isn't ideal, but then I thought about it a little more.... (carried on below, because it's the option I picked)

If I call `repeat(Schedule.Identity, mx)`.  I would expect it to repeat forever.  If I call `retry(Schedule.Identity, mx)`.  I would expect it to retry forever.  I think there's an implied infinite stream of zero-length durations.  And so: `repeat(Schedule.recurs(5), mx)` implies a clamp of that.  

> As I am writing this, I just went to check `Schedule.Identity`, and I realise it was returning `Schedule` when it should have been `ScheduleTransformer`.  And now I'm changing my mind again!  That's now screaming unexpected side-effects, or maybe it's not a big deal - I'll have a break for this evening and come back to it tomorrow fresh!
 
[Other slight refinements to the Schedule updates (please have a review and let me know your thoughts)](https://github.com/louthy/language-ext/commit/1def300fe63868759edca2481d0e538160c10ff4):

* Moved non-Prelude extensions back into the Schedule type
* Added Prelude functions
* Refactored ScheduleTransformer to be a struct.  Allows it to be composed independently of any schedules
* Added some of the basic LINQ operators to Schedule to reduce the need to call `AsEnumerable()` followed by `ToSchedule()`
* Removed lock from `SingletonRandom` and changed to use `memoUnsafe` which never frees the result. 
* Updated the names of the constructor functions in Schedule to:
   * `TimeSeries` for the  `Schedule` ctor
   * `Transform` for the  `ScheduleTransformer` ctor
 * Made the names of the other functions that make schedules (but shouldn't technically be called ctors) to be consistent with the rest of the library (i.e. use camelCase).  The old ones are marked `Obsolete`

**Comment by bmazzarol** [comment]
@louthy changes are fantastic.

They align it with the other parts of the library, which I was not sure I could do in the same way.

Only 2 things jump out at me on first pass,

1. https://github.com/louthy/language-ext/commit/1def300fe63868759edca2481d0e538160c10ff4#diff-48d4718c01e8c4a93101f0a69e966f8efc27ebd3c1de8d0614f99a3ca386d843R209 did you mean fix here? I think fixed might be more in line with the other names.
2. https://github.com/louthy/language-ext/commit/1def300fe63868759edca2481d0e538160c10ff4#diff-48d4718c01e8c4a93101f0a69e966f8efc27ebd3c1de8d0614f99a3ca386d843L463 I had the ToSeq for schedules that are not backed by a repeatable enumerable. So I think it might still be required, (And potentially in other places that need to run the schedule again). Another unit test might be required to cover this, I might have selected a repeatable enumerable as the base schedule, which would keep working with this change in the current test https://github.com/louthy/language-ext/commit/1def300fe63868759edca2481d0e538160c10ff4#diff-05b46a1f4971bb9e56f78a96755d9234ca26482583fdf3d0f52449c8e4d73376R434.

**Comment by louthy** [comment]
1. fixed is a keyword.  I tried to pick something concise.  Open to suggestions though
2. My concern there was that Seq can’t handle infinite streams, as it needs to be memory backed to cache the results, this would have real costs for no apparent gain - unless I’m missing something? The cost of re-evaluating the enumerable is low so I figured ToSeq didn’t gain anything.

**Comment by bmazzarol** [comment]
1. Some other ideas: (pre)determined, set, allotted, defined, exact, rigid, specified 
2. I understand, was planning on adding a warning to all the transformers that call ToSeq that it will not work on infinite sequences

This test should outline the issue,

``` c#
        
        [Fact]
        public static void RepeatTest2()
        {
            var results = Schedule.linear(1 * sec) | Schedule.recurs(3) | Schedule.repeat(3);
            
            results
                .AsEnumerable()
                .Should()
                .HaveCount(9)
                .And
                // this fails because the linear Schedule is not replayable and is stateful so keeps running the sequence
                .Equal(
                    1 * sec, 2 * sec, 3 * sec,
                    1 * sec, 2 * sec, 3 * sec,
                    1 * sec, 2 * sec, 3 * sec);
        }

```

Options,

1. Create a transformer that applies the ToSeq to the schedule, could call it freeze or something, then use that before calling repeat, then the user is in control over that
2. Add ToSeq back where required, and add clear warnings on the transformer for users, I would pair this with the first option
3. Remove the transformer(s), It can be constructed if required now, is it worth having around if there are edge cases? With this it also applies to any transformer that calls ToSeq

**Comment by louthy** [comment]
@bmazzarol 

1. `rigid` was the only other one I thought might work (and `fixedInterval` - which is probably better, but less concise).  

2. The way to fix this is to [turn `Schedule` into a DSL](https://github.com/louthy/language-ext/commit/dd395615f7fe3eba73f5145269e821a2a3638110), then we control the various stages of evaluation, rather than allowing unknown free variables to be captured in the enumerators.  

If you check the link to the latest commit, you'll see what I mean.  `Schedule` now has many sub-types, one being `SchItems` which is a simple `IEnumerable`, the rest are operations on the schedule, or schedule generators.  I've stopped `Schedule` from deriving from `IEnumerable` and renamed `AsEnumerable()` to `Run()`, to indicate there's more going on.

It would still be possible for the end user to bake a free-variable into an `IEnumerable` passed to the `Schedule.TimeSeries(...)` constructor, or in the lambda passed to the `Schedule.Transform(...)` constructor; but that then would be a user error, rather than something fundamentally hidden in the underlying Schedule system.

It passes all tests and your example above returns the expected values too.  Let me know what you think.

**Comment by bmazzarol** [comment]
@louthy 

I think fixedInterval is the best one so far.

I think its great. I'm impressed and annoyed that I did not think of it at the same time.

Would you consider altering SchItems so that it did not take a IEnumerable? It would then shut off the possibility of misuse. 

Use a collection type that is immutable and strict?

Then if for some reason the provided array of schedule building blocks and combinators is not enough (crazy but not impossible), the developer will need to extend Schedule and if they still mess it up at that point I have no sympathy.

**Comment by louthy** [comment]
I think that’s a fair call.  I think making ScheduleTransformer into a DSL makes sense too, then whole schedules can be prebuilt and cached to reduce at-point-of-use allocations

**Comment by louthy** [comment]
> I think making ScheduleTransformer into a DSL makes sense too

I tried this.  It was adding too much complexity for too little gain.  I might go back to it later, but I think it's OK for now.

Latest is committed with `fix` renamed to `fixedInternal`

**Comment by louthy** [comment]
[Deployed as `v4.2.2`](https://github.com/louthy/language-ext/releases/tag/v4.2.2) thanks for the efforts Ben 👍

**Comment by bmazzarol** [comment]
@louthy cheers mate, going to refactor some schedules today!
