### ISSUE TITLE
Scope Question

### ISSUE THREAD

**Issue by jerrywiltse** [louthy/language-ext#107]
I'm a novice trying to move into C#, and I really want to maximize functional style.  This library looks both brilliant and thorough, so thank you very much for creating it.  If you say that you intend to keep this library alive and relevant long-term, I will be using it as a foundation for all my first few open source C# projects.  I am also very interested in the .net core support, as I do want to write apps for linux. 

However, I'm a little bit surprised by the concurrency element. This seems to me to be a completely separate set of concerns, although I do see the relationship.  Have you considered separating the concurrency model out into it's own project?

**Comment by louthy** [comment]
@jerrywiltse Hi Jerry,

>  If you say that you intend to keep this library alive and relevant long-term, I will be using it as a foundation for all my first few open source C# projects. I am also very interested in the .net core support

It will indeed be maintained for the long-term.  It is included in www.meddbase.com which is a decade old project, and I'm using it to bring more control to the OO headache.  It's fundamental to my own long-term project (I'm the CTO), so hopefully that should give you some comfort. 

>  I am also very interested in the .net core support, as I do want to write apps for linux.

I have everything ready to go, but the .NET Core tooling crashes when I compile it.  I have been talking to the team at Microsoft about it, but are yet to rectify it.  However they _were_ able to build it, so I need to get a clean machine.  But in the meantime you can get the latest source and build and it will build .NET Core targets.  The versions deployed to Nu-get already have DNX builds, and therefore should also work on any .NET Core projects.

> This seems to me to be a completely separate set of concerns, although I do see the relationship.

It's not a separate set of concerns when you consider the primary purpose of this library: to make C# safer to use and to tame the difficulties of using OO for large projects.  The Core is all functional types because as data-types they are safer than say `Dictionary<T>`, `List<T>`, or nullable references.  The `Process` system is there to deal with the problems of shared and mutable state in a concurrent environment.

That's why this library is called 'language-ext', rather than 'functional C#', or something like that.  It directly targets the issues I've personally bumped into many times using C#.

> Have you considered separating the concurrency model out into it's own project?

I have, but I don't see any value to me, other than making it slightly easier to write documentation for.  The projects are deployed as separate nu-get packages, so there's no requirement to bring in the Process system if you don't need it.

**Comment by jerrywiltse** [comment]
Thats separation of the nuget packages really is the key, so that works. I guess the only other factor is for those wanting to fork and contribute have to get the whole project, but it's so small and well divided that I guess it doesn't matter.  I really hope to see the functional pieces get noticed and picked up by other projects, which will draw other contributors and thus increase the chances of survival and it's ability to adapt with related changes (C# 7 etc). 

Thanks again for your contribution and effort.
