### ISSUE TITLE
BindAsync throws LanguageExt.ValueIsNoneException

### ISSUE THREAD

**Issue by moikot** [louthy/language-ext#1076]
I'm not entirely sure if my code is correct but it compiles and runs ok as soon as I comment `await Task.Yield()` out, otherwise it throws LanguageExt.ValueIsNoneException.

```csharp
        [Fact]
        public async Task BindAsyncFailure()
        {
            _ = await ProblematicBindAsync();
        }

        public static async Task<Option<string>> ProblematicBindAsync()
        {
            Option<string> thing = "foo";
            return await thing.BindAsync(
                async _ => await GetBarAsync()
            );
        }

        private static async Task<Option<string>> GetBarAsync()
        {
            await Task.Yield();
            return "bar";
        }
```

Any help is greatly appreciated!

**Comment by louthy** [comment]
You're combining `OptionAsync<A>` with `Task<A>` in the `async\await` blocks, so the `GetAwaiter()` appears to be getting confused.  

There may well be a bug, but honestly, I regret building in the `GetAwaiter()` feature into the `OptionAsync`, it always breaks when used side-by-side with regular Tasks.  

That may well be due to my lack of understanding of the hellish hack that is `AsyncMethodBuilder` - but ultimately, the problem is that the type-system gives no indication of possible issues, and just blindly runs it - even though the types are incompatible.  

The idiomatic way to do what you want would be this:

```c#
    static OptionAsync<string> BindAsyncFailure() =>
        ProblematicBindAsync();

    static OptionAsync<string> ProblematicBindAsync() =>
        from thing in SomeAsync("foo")
        from bar   in GetBarAsync()
        select bar;
    
    static OptionAsync<string> GetBarAsync() =>
        SomeAsync("bar");
```

No mixing of `Task` and `OptionAsync`.  My fix will almost certainly be to remove the `GetAwaiter()` from `OptionAsync`, so the above approach is the best way to compose optional tasks (or even better, use the `Aff` type, which has optional tasks with robust error handling.
