### ISSUE TITLE
Replace current Result<T>.Match syntax

### ISSUE THREAD

**Issue by Hulkstance** [louthy/language-ext#1141]
Why not create something like the following? Your current `Result<T>.Match` / `IfSucc` syntax looks a bit weird and so is the name `IfSucc`.

```cs
if (result.IsSuccess)
{
    var data = result.Data; // compiler won't comply for nullability issues because it was successful
}

if (result.IsFaulted)
{
    var error = result.Error; // compiler won't comply for nullability issues because it was faulted
}
```

instead of

```cs
 _ = result.IfSucc(data =>
{
    // that way I could access the data but it ain't as pretty as the one above.
});
```

I assume the reason you didn't is because you were not aware of the `MemberNotNullWhen`/`NotNullWhen`  attributes.

```cs
public sealed record CallResult<T>(
    [property: MemberNotNullWhen(true, nameof(CallResult<T>.Data))]
    [property: MemberNotNullWhen(false, nameof(CallResult<T>.Error))]
    bool Success, T? Data, Error? Error)
{
    public CallResult(T data) : this(true, data, default)
    {
    }

    public CallResult(Error error) : this(false, null, error)
    {
    }
}

public abstract record Error(int? Code, string Message, object? Data);
```

**Comment by wxxedu** [comment]
Maybe a little irrelevant to this, but may I ask why in the `Match` function, the left is handled on the right and the right is handled on the left? Thanks!

**Comment by louthy** [comment]
@wxxedu Which `Match` function are you referring to?  This issue is around `Result<A>` which has `Succ` and `Fail` parameters (and `Result` has been deprecated in `v5`, so I'd advise moving away from it and to `Fin<A>`).  

If you mean the `Match` on `Either` then that would be a separate issue.  In `v5` you'll [see that the parameters have been swapped](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Either/Either.cs#L94) for `Either`.

It is however good practice to use named parameters when using `Match`, so you can have the order whatever way makes sense to you:

```c#
var result = either.Match(
    Left: l => ...,
    Right: r => ...);
```
This labelling of parameters is more declarative and makes code easier to read for others (with no cost overhead).

In `v5` you can also use C#/s pattern-matching:

```c#
var result = either switch 
{
    Either.Left<L, R> l => ...,
    Either.Right<L, R> r => ...,
};
```

**Comment by wxxedu** [comment]
Hi @louthy, thanks so much for the quick and detailed reply. Yes I was meaning the `Either` type, sorry for the omission. I realised we did not update the version of the package, and were using the older version. Thanks so much for your help!
