### ISSUE TITLE
Using record as a Key in Map<K, V>, ToMap() Fails

### ISSUE THREAD

**Issue by alarya** [louthy/language-ext#1166]
I want to use a Map which has a `record` as the key.  Does Map support this? I am able to declare a Map with a record as a key. However, when  I tried to use `ToMap()` to an IEnumerable of a tuple, it failed with the following error:

```
At least one object must implement IComparable.
```

I understand that `record` does not implement `IComparable`. Is there a way around this?

**Comment by alarya** [comment]
I was able to alleviate the issue by implementing `IComparable` in the record.

**Comment by louthy** [comment]
Was this a C# record or a [languag-ext record](https://github.com/louthy/language-ext/wiki/Code-generation#record--product-types)?

**Comment by alarya** [comment]
> Was this a C# record or a [languag-ext record](https://github.com/louthy/language-ext/wiki/Code-generation#record--product-types)?

I should've clarified that I was talking about the C# record.

**Comment by louthy** [comment]
> EDIT: I now realize that HashMap<K,V> is the type to be used for non-sortable keys (without IComparable implementation) and Map<K,V> is to be used only for sortable keys.

That is true, but also the reason for not constraining the type with `IComparable` is because there is a type-class instance resolving system that 'looks' for implementations of `Ord<K>`.  This means if you have a type called `Person` and an implementation of `Ord<Person>` called `OrdPerson` then `Map<K, V>` will auto-resolve to using it.  If it can't find `OrdPerson` then it will fall back to the `Comparer<Person>.Default`.  

The idea is to be able to give ordering capabilities to types ad-hoc, which is useful when you have a type from a library that you didn't write and you want to make them work in Maps, etc.

> This system will be improved for future versions of language-ext to have even better type resolving capabilities, as the system is a little basic right now (it won't work with generic types, for example). 

Due, to the nature of the discovery process, It can only be resolved at runtime right now - which means runtime errors.  Obviously that is frustrating, but it should only happen the first time you test your code.

You can also use the `Map<OrdK, K, V>` version of `Map` which allows you to specify the an ordering instance to use, rather than the default, in the type-signature.

As you've seen and similar thing happens with `HashMap`, except it tries to resolve `EqPerson` first, then falls back to `EqualityComparer.Default`.

It should also be noted that unless you need ordered maps then `HashMap` is significantly faster than `Map` due to the use of the advanced CHAMP data-structure.
