### ISSUE TITLE
Error comparison in @catch doesn't work anymore?

### ISSUE THREAD

**Issue by kirill-gerasimenko-da** [louthy/language-ext#1171]
Hi! 

I've got two error instances, with the same code, but different message and comparison with `==` operator gives `false`, but should (I think) be giving `true`, since these are both expected errors, and should compare by code as in documentation. Here are examples which fail: 

```csharp
    [Fact]
    public void fails()
    {
        var e1 = Error.New(100, "this is error");
        var e2 = Error.New(100, "another text");

        Assert.True(e1 == e2);
    }

    [Fact]
    public async void fails2()
    {
        var aff1 =
            from _1 in unitAff
            from _2 in guard(false, Error.New(1000, "error"))
            select unit;

        var aff2 =
        (
            from _ in aff1
            select unit
        ) | @catch(Error.New(1000, "another text"), unitAff);

        var result = await aff2.Run();
        Assert.True(result.IsSucc);
    }
```

The second case with `@catch` is what I think was working previously. 

Please advise.

**Comment by louthy** [comment]
Errors use structural equality since they’ve been refactored to support different error types and aggregate errors.  The way to test if one error is an instance of another error is to use: errorA.Is(errorB)

In your fails2 example, you can just provide the error code integer: @catch(1000, unitAff)

I agree though that there’s been an inadvertent change of behaviour with @catch though (the variant that takes Error as a match argument); it is using == and should instead use .Is

**Comment by kirill-gerasimenko-da** [comment]
Thanks for your reply! Will use the code for now.

**Comment by louthy** [comment]
@kirill-gerasimenko-da This should be fixed in the latest release.

**Comment by kirill-gerasimenko-da** [comment]
> @kirill-gerasimenko-da This should be fixed in the latest release.

thank you!
