### ISSUE TITLE
Effectful producer

### ISSUE THREAD

**Issue by timmi-on-rails** [louthy/language-ext#1177]
## Problem

I would like to repeat a given `Producer` indefinitely with a delay _after_ each producer finishes.
A delay _before_ each producer starts, was no problem.

So here is an example of the observed behavior using console output instead of delays.

```csharp
static Effect<RT, Unit> effect
    => repeat(producer) | consumer;

static Producer<RT, int, Unit> producer =>
    from _1 in Console<RT>.writeLine("before")
    from _2 in enumerate(new[] { 1, 2, 3 })
    from _3 in Console<RT>.writeLine("after")
    select unit;

static Consumer<RT, int, Unit> consumer =>
    from i in awaiting<int>()
    from _ in Console<RT>.writeLine(i.ToString())
    select unit;
```

The console output is:

```
before
1
2
3
before
1
2
3
before
1
2
... and so on
```

What I actually expect is, that both console output `Eff`s are run:

```
before
1
2
3
after
before
1
2
3
after
before
1
2
... and so on
```

Did I misunderstood the meaning of an effectful producer or is this a bug?
How can I accomplish an effect _after_ the producer finishes?

I also did not find functions that chain producers. (There is only `merge`, `repeat`, ...)

**Comment by louthy** [comment]
> Did I misunderstood the meaning of an effectful producer or is this a bug?

I did a bit of digging and it seems there may be an issue in that nothing runs after a `yield` (within the same `Producer`), which means something is shortcutting the monadic operation and returning early.  This is pretty odd.

I've poured over the source and the original Haskell Pipes source (that this is based on) and I can't see anything obviously wrong.  There were some changes I made to reduce the need for excessive recursion, but I controlled for that and still can't see the issue.  It's a really hard system to debug unfortunately.  So it might take a bit of time to resolve as I have a lot of other commitments right now.

If anybody else interested in having a go at resolving it then I have [a little example in my `TestBed` application](https://github.com/louthy/language-ext/blob/main/Samples/TestBed/PipesTest.cs#L26).

```c#
    public static Effect<Runtime, Unit> effect =>
        producer(10) | consumer;

    static Consumer<Runtime, int, Unit> consumer =>
        from i1 in Consumer.awaiting<Runtime, int>()
        from _x in Consumer.lift<Runtime, int, Unit>(Console<Runtime>.writeLine(i1.ToString()))
        select unit;

    static Producer<Runtime, int, Unit> producer(int x) =>
        from _1 in Producer.lift<Runtime, int, Unit>(Console<Runtime>.writeLine("before"))
        from _  in Producer.yield<Runtime, int>(x)
        from nx in x > 0 
                      ? producer(x - 1)
                      : Producer.Pure<Runtime, int, Unit>(unit) 
        from _3 in Producer.lift<Runtime, int, Unit>(Console<Runtime>.writeLine("after"))
        select unit;
```
This uses a recursive `Producer` that calls itself `10` times to yield the values as it counts down to `0`.  The code after the `Producer.yield<Runtime, int>(x)` doesn't run, and so it only yields `10`.

I've :

* Used the full-generic versions of each function to take the backing `PureProxy` out of the equation
* Tried using the [original recursive effect loop](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Pipes/Effect/Effect.cs#L35) rather than the [`while` loop flattened replacement](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Pipes/Effect/Effect.cs#L154).
* Checked the `CoreTypes` for [`Request` (await) and `Respond` (yield)](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Pipes/RequestRespond/CoreTypes.cs)
* As well as he `CoreTypes` for the [monad-transformer `M`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Pipes/Proxy.cs#L308)
* The four methods `ReplaceRequest`, `ReplaceRespond`, `PairEachRespondWithRequest`, and `PairEachRequestWithRespond` appear to match the operators in [`Pipes.Core`](https://hackage.haskell.org/package/pipes-4.3.16/docs/src/Pipes.Core.html)

Stepping through the debugger isn't straight forward because it's a DSL that has elements of itself replaced when the compositions happen, so just F10ing when you get to `yield` doesn't work. If I find some more time to dig in I'll surely resolve it, but more eyes might help.

**Comment by louthy** [comment]
Bit of an update:  The core system is sound and does do what is expected.  In my testing I forgot to put a recursive loop in the consumer too (you can see it's an infinitely looping consumer).  The recursive loop in the consumer stops the pure value in the `select` being reached (pure values quit the effect).

This does very similar to what you are asking, but with recursion:

```c#
    public static Effect<Runtime, Unit> effect =>
        beforeAndAfter | consumer;

    static Producer<Runtime, int, Unit> beforeAndAfter =>
        from _1 in Console<Runtime>.writeLine("before")
        from _3 in producer(10)
        from _2 in Console<Runtime>.writeLine("after")
        select unit;
    
    static Producer<Runtime, int, Unit> producer(int x) =>
        from _ in yield(x)
        from r in x > 0 
                     ? producer(x - 1)
                     : Pure(unit) 
        select r;
 
    static Consumer<Runtime, int, Unit> consumer =>
        from i1 in awaiting<int>()
        from _x in Console<Runtime>.writeLine(i1.ToString())
        from r  in consumer
        select r;
```
The above code yields the following console output:
```
before
10
9
8
7
6
5
4
3
2
1
0
after
```
Which is expected.  The recursion in the consumer doesn't cause a stack-overflow, but one in the producer can do.  That's why I extended language-ext Pipes to have `repeat` and `enumerate` cases in the DSL (and for performace).

Below is similar to your example but with recursion in the consumer, which stops the effect from exiting.  

```c#
    public static Effect<Runtime, Unit> effect => 
        producer | consumer;

    static Producer<Runtime, int, Unit> producer =>
        from _1 in Console<Runtime>.writeLine("before")
        from _2 in enumerate(new[] { 1, 2, 3 })
        from _3 in Console<Runtime>.writeLine("after")
        select unit;
    
    static Consumer<Runtime, int, Unit> consumer =>
        from i in awaiting<int>()
        from _ in Console<Runtime>.writeLine(i.ToString())
        from r in consumer
        select unit;
```

`enumerate` however is playing `"after"` on each iteration.  
```
before
1
after
2
after
3
after
```

That's not right, and is the next thing for me to look into.

**Comment by louthy** [comment]
[Fixes are in the latest release](https://github.com/louthy/language-ext/releases/tag/v4.4.1)

**Comment by timmi-on-rails** [comment]
@louthy: Thanks a lot, I will try it later.

You also solved my next issue, which I was about to post. How to concat producers. I wasn't able to and hopefully am with the new & operator on producers.
My workaround for concats would have been an implementation similar to Producer.merge.

Little heads up for my next issue: Producer.merge needs error handling. If a producer fails, it is swallowed. Does Haskell pipes have a merge producer function?

**Comment by timmi-on-rails** [comment]
@louthy: Probably related (new) issue, tested with v4.4.1.

```csharp
static Effect<RT, Unit> effect
    => (Producer.yield<RT, int>(1) & Producer.yield<RT, int>(2)) | consumer;

static Consumer<RT, int, Unit> consumer =>
    from i in awaiting<int>()
    from _ in Console<RT>.writeLine(i.ToString())
    select unit;
```

Console output is:
```
1
```

I would expect:
```
1
2
```

If you confirm my expectation, then I can create a new issue.

**Comment by louthy** [comment]
> My workaround for concats would have been an implementation similar to Producer.merge.

Concatenation is simply monadic bind:

```c#
    yield(1).Bind(_ => yield(2))     // yields `1` then `2`
```
You can use a series of `from` in LINQ also:

```c#
    from _1 in yield(1)
    from _2 in yield(2)
    select unit;
```
The `&` operator merely removes the need for the intermediate variables.

```c#
    yield(1) & yield(2)
```

> Probably related (new) issue, tested with v4.4.1.

Short answer: There's no issue, you need to make your consumer recursive.

Long answer: The way to think about Pipes is that `yield` creates a _hole_ in the `Producer` expression.  So when you compose something with a `Producer` (that has a yield hole), that hole gets filled - making a single linear expression.  Each `yield` must be paired with an `awaiting`.  So, in your example you filled/replaced the first `yield` hole with one `awaiting` from `consumer`.  

But when `consumer` gets to the end of its expression it simply ends (`select unit`).  This creates a `Pure` value, which is the terminating case for the pipes DSL.  So your entire effect ends at that point.  You may think, well it should just loop back up to after the first `yield` and continue; but the way Pipes is setup is that they can be ended at any point by just returning a `Pure` value (in a `Producer`, `Pipe`, or `Consumer`).  

And so, to fill the second `yield` hole in the `Producer`, the consumer must open up another `awaiting` - it can do this by doing two `awaiting` in a row:
```c#
    static Consumer<Runtime, int, Unit> consumer =>
        from i1 in awaiting<int>()
        from i2 in awaiting<int>()
        from _  in Console<Runtime>.writeLine($"{i1}, {i2}")
        select unit;
```
Or by recursively calling `consumer`:

```c#
    static Consumer<Runtime, int, Unit> consumer =>
        from i in awaiting<int>()
        from _ in Console<Runtime>.writeLine(i.ToString())
        from r in consumer                     // < recursive call keeps asking "is there more?" 
        select r;
```
You could think of this as a little but like doing a `Zip` between two sequences.  The left sequence is the `yield` expressions, and the right is the `awaiting` expressions; they get paired up so the values can flow between the two.

The improved `yieldAll` functionality doesn't need the Consumer to be recursive, and that's because the [`Enumerate` case in the DSL holds](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Effects/Pipes/Enumerate/CoreTypes.cs#L28):
* A collection of `X` values
* A function that when called with an `X` returns a `Proxy` (called `Yield`)
* A function that when called with a `Unit` returns a `Proxy` (called `Next`)

By looping over the `X` values in the collection and calling `Yield` for each value, it effectively continually pairs the `awaiting` in your `Consumer` with the `yield` in your `Producer`.  So, you don't need that recursive call to `consumer`, the `Enumerate` case is doing the work for you.  

As soon as you are doing the `yield` manually, and not via `yieldAll`, you will need the recursion.  My advice would be to always use recursion in the `Consumer`.  

As an aside, that's what `repeat` was originally for, to avoid the recursion.  But it's got a similar problem to the old `enumerate` behaviour.  `repeat` _should_ be looping without the need for recursion but I need to do some work to the `Repeat` case in the DSL to change it to work like the new `Enumerate` case (which fixed the `yieldAll` issues).  At the moment `repeat` will _'spread'_ when composed:

```c#
    // When composed, the repeat grows to encapsulate the composition
    z = repeat(x) | y

    // The result is this
    z = repeat(x | y)
```
There are good reasons why that happens, but it's not right (from an expectation PoV), and needs a better solution so that it only repeats what's inside of it.  

I'll look at the merge error handling.

**Comment by timmi-on-rails** [comment]
Thank you very much for your detailed answer.
Your effort to maintain this library and teach people like me, is incredible.

The _holes_ explanation clarified for me, that the producer/consumer pattern is not just another `Observable` syntax.

The pipes formalism offers composability (along with streaming and effects).
I am still unsure how to properly document the structure of a producer, which might be used in different places.
The problem is, that the number of `yield`s (i.e. internal structure) is not clear from the method signature.

Your recommendation is implementing all consumers recursively, which leaves the 'work' to the 'user' of the producer.
In my case I consider the number of `yield`s an implementation detail and don't want the 'user' be bothered with it.
So I thought of another solution. Instead of making the consumer recursive, I made the producer 'flat'.
I assume the naming of 'flat' might be strange, maybe 'enumerate' is better.

What do you think about the implementation? Is it useful in general? Is there another more structural way how to 'flatten' a producer with multiple `yield`s? Is it maybe possible to create a pipe, that turns a recursive producer into an enumerating one (utilizing pairing `yieldAll` with `awaiting` mechanics)?

Maybe this is all unnecessary with the correct mindset. I don't know the Haskell implementation.
But if the implementation there is completely recursive and you introduced enumeration only to not run into stackoverflows in C#, then always using recursive consumers as 'user' doesn't sound so bad anymore.

PS: Maybe my error handling approach can be utilized in `Producer.merge` as well.

```csharp
static Producer<RT, OUT, Unit> Flatten<OUT>(Producer<RT, OUT, Unit> producer)
{
    return from env in Producer.lift<RT, OUT, RT>(runtime<RT>())
        from t in Eff<RT, (IAsyncEnumerable<OUT> Items, ValueTask<Unit> Task)>(_ => Go(env))
        from _1 in Producer.yieldAll<RT, OUT>(t.Items)
        from _2 in t.Task.ToAff()
        select unit;

    (IAsyncEnumerable<OUT> Items, ValueTask<Unit> Task) Go(RT env)
    {
        var channel = Channel.CreateUnbounded<OUT>();

        var task = (producer | ConsumeRecursive(channel))
            .RunEffect()
            .Run(env)
            .Do(_ => channel.Writer.Complete())
            .Map(f => f.ThrowIfFail());

        return (channel.Reader.ReadAllAsync(env.CancellationToken), task);
    }

    static Consumer<RT, OUT, Unit> ConsumeRecursive(Channel<OUT> channel)
        => from v in awaiting<OUT>()
           from _1 in Aff<RT, Unit>(async env =>
           {
               await channel.Writer.WriteAsync(v, env.CancellationToken);
               return unit;
           })
           from _2 in ConsumeRecursive(channel)
           select unit;
}
```
