### ISSUE TITLE
Enforce Some<T> is not null

### ISSUE THREAD

**Issue by OzieGamma** [louthy/language-ext#119]
Hi,

To enforce Some<T> is not left uninitialized, you might want to look into Roslyn Analyzers.

In your intro you mention it might not have been the best idea to have included Some<T> in the first place.

If you're interested I might be able to help.

**Comment by louthy** [comment]
> If you're interested I might be able to help.

I'd be interested in anything that would make `Some` more effective, yes.  I am actually looking into using Roslyn to generate the HKT.cs instead of the quite shonky T4 template system.  But it's still pretty early days [in my full understanding of what's possible].  So feel free to propose any ideas you have.

**Comment by OzieGamma** [comment]
Ok, Ill write a small analyzer whenever I have time this week !

**Comment by Lonli-Lokli** [comment]
Seems like both ideas goes into nothing ;(
