### ISSUE TITLE
Question: Higher Order Polymorphism

### ISSUE THREAD

**Issue by OzieGamma** [louthy/language-ext#120]
Hi,

You probably have more experience with functional programming than I do (I usually only use the libraries). I was wondering whether you agree that the only reason we have to write sooooo many identical functions for each M-type (I am not an expert and don't come attacking me on some theory, I don't care) instead of just supplying bind and return is because the CLI doesn't support Higher Order Polymorphism ?

**Comment by louthy** [comment]
Yes, that is the case.  But (unknown to many) C# can do ad-hoc polymorphism, which allows for Haskell-like type-class and instances.  I am actually working on this now for lang-ext 2 (Take a look at the type-class branch: https://github.com/louthy/language-ext/tree/type-classes)

There are some major limitations though:
 * C#'s type-inference is terrible, which leads to 'a lot' of manual type-providing.  But if you want to write functions that take `Functor<T>` so you can call `Map`, or you want to create a numeric-type and only write your maths functions once (not many times for `double`, `float`, `int`, etc.) then this will work.
* The instance types must be structs.  That causes boxing for the higher-order types like `Monad`, `Functor`, `Applicative`, etc.
* For types like `Monad` they will return `Monad<B>` for the standard `Bind` function, so that means your `Option` would become more generic (it's possible to cast).

Some real examples:

__Eq type-class__

* Type-class definition (an interface): https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Eq/Eq.cs
* Instance definition (a struct): https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/Instances/EqFloat.cs
* Unit-tests that all call the same `IsEqualGeneral` function with different numeric types: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Tests/TypeClassEQ.cs

__Monoid type-class__

* Type-class definition (an interface): https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Monoid/Monoid.cs
* `TInt` instance (struct), which is in the `Ord`, `Num`, and `Monoid` type-class: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/Instances/TInt.cs
* `TLst` instance (struct), which is in the `Monoid` and `Difference` type-class: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/Instances/TLst.cs
* `TString` instance (struct), which is in the `Monoid` and `Ord` type-class: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/Instances/TString.cs
* Unit-tests that call the same `mconcat` function with different types that understand the concatenation behaviour for each: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Tests/TypeClassMonoid.cs
* Implementation of `mconcat` and `mempty` - https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Monoid/Monoid_Prelude.cs

__Monad type-class__
* Type-class definition (interface): https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Monad/Monad.cs
* Once only definition of `Bind`, `Fail`, `Join`: https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Monad/Monad_Extensions.cs

__"So, does this mean I can create a new struct derived from `Monad<T>` and it just work with LINQ etc???"__

Yes.

However, because of the limitations I am still going to manually implement all of the overrides and extension methods (I'm working on a Rosyln based plugin that will do general case extension method generation).  

So unfortunately for me the typing required has pretty much doubled, but for the consumers of this library they'll be able to write totally general case code that works with the type-class interfaces and struct instances.

btw, I definitely _wouldn't_ advise getting the type-class branch.  The changes are in the very early stages.  It's pretty much a re-write of the core of this library and will take a while to come to fruition.

**Comment by OzieGamma** [comment]
I am writing T4 generation to do the job. That would be specialisation at compile time. Solving the code size problem at least for types defined in the lib.

The problem I see with your "type classes" is that the return types are of type Monad<A> which is not very interesting ...

Option.map the returns Monad. Type accuracy is lost ! So it might be there for convenience if users define their own but doesnt replace the original type ...

**Comment by louthy** [comment]
> Option.map the returns Monad. Type accuracy is lost ! So it might be there for convenience if users define their own but doesnt replace the original type ...

Only when they're used in their more generic state of `Monad<T>`, when they're used as `Option<T>` map will return an `Option<T>` (https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/Option/Option.cs#L218).  I'm doing the legwork of providing the explicit overrides _and_ the generic functionality.  

For example if I write a function that takes a `Monad`:
```c#
    Monad<A> AddMonads<NUM, A>(Monad<A> lhs, Monad<B> rhs) where NUM : struct, Num<A> =>
      from a in lhs
      from b in rhs
      select add<NUM>(a,b);
```
Then I can call it with any combination of monadic type, but I must expect to get a generic response:
```c#
    Option<int> lhs = 10;
    Either<string, int> rhs = 10;

    Monad<int> result = AddMonads<TInt, int>(lhs, rhs);
```
However if I wrote it with a specific monadic type:
```c#
    Option<A> AddMonads<NUM, A>(Option<A> lhs, Option<B> rhs) where NUM : struct, Num<A> =>
      from a in lhs
      from b in rhs
      select add<NUM>(a,b);
```
Then I will maintain the type, but lose the ability to call it with any type of monad.  If you want typed variants then you're back in the land of code generation, or lots of typing.  

As it stands this library (and all others that try to implement monads) only work on the specialised type, and therefore the benefits are limited.  In fact it severely limits the use of monads, applicatives, and functors, to the point where it's difficult to really call them that if they can't be used generally.  Being able to write functions that work on monads, and not options, eithers, etc. is the goal here.  That is what you get with Haskell and any other language that supports type-class like functionality.

T4 generation (which is what lang-ext currently uses) is very limited in terms of understanding the inheritance graph.  For example, with `Monad<B> Bind(Monad<A> ma, Func<A, Monad<B>> f)` you need to provide the basic typed variants:
```c#
    Option<B> Bind(Monad<A> ma, Func<A, Option<B>> f);
    Either<L, B> Bind<L>(Monad<A> ma, Func<A, Either<L, B>> f);
    Try<B> Bind(Monad<A> ma, Func<A, Try<B>> f);
    ...
```
That allows different monadic types to be combined without losing the specialised type.  If you don't do the type-class stuff I've done, then it becomes (and this is what HKT.tt is like now):
```c#
    Option<B> Bind(Option<A> ma, Func<A, Option<B>> f);
    Either<L, B> Bind<L>(Option<A> ma, Func<A, Either<L, B>> f);
    Try<B> Bind<L>(Option<A> ma, Func<A, Try<B>> f);
    Option<B> Bind<L>(Either<L, A> ma, Func<A, Option<B>> f);
    Either<L, B> Bind<L>(Either<L, A> ma, Func<A, Either<L, B>> f);
    Try<B> Bind<L>(Either<L, A> ma, Func<A, Try<B>> f);
    Option<B> Bind(Try<A> ma, Func<A, Option<B>> f);
    Either<L, B> Bind<L>(Try<A> ma, Func<A, Either<L, B>> f);
    Try<B> Bind(Try<A> ma, Func<A, Try<B>> f);
    ...
```
Then to do add the super-useful transformer functionality you need to do that all again with every combination of transformed monadic types (`Option<Option<T>>`, `Option<Either<L, T>>`, etc.)

It gets very complicated, very quickly, when working with monadic types that are delegates that require input (like the `State`  and `Reader` monad), or when the outer type implements a function that the inner type doesn't, or when trying to work out the default behaviour for functions that return a non-monadic result.  So for example `Fold`, `Count`, etc.  I stopped with the T4 template idea when I got to a dozen or so of the most useful functions.  

The main issue then is that the types are hard-coded to work with each other.  Bringing in lang-ext and then writing your own monadic type doesn't magically make it work with the lang-ext monads.  But with the type-class system it does.
