### ISSUE TITLE
Wrong method usage when translating string with ToOption<T>

### ISSUE THREAD

**Issue by vayqerlukashakkarainen** [louthy/language-ext#1203]
Hi!

I've recently started using language-ext, and I most firstly say that it's a great library, I really like the concept of functional programming.

## Issue
So when using `ToOption()` on string causes the usage of the following method:
```
public static Option<A> ToOption<A>(this IEnumerable<A> self) => self.Match<A, Option<A>>((Func<Option<A>>) (() => Option<A>.None), (Func<A, Seq<A>, Option<A>>) ((x, _) => Option<A>.Some(x)));
```

Which is not what I want, and this is because `string` inherits from `IEnumerable<char>`

I want to use the method located inside `LanguageExt.NullableExtensions` which is:
```
public static Option<T> ToOption<T>(this T? self) where T : struct => !self.HasValue ? (Option<T>) Prelude.None : Prelude.Some<T>(self.Value);
```

The reason why it chooses the wrong method seems to be because `ListExtensions` is missing a namespace and will thus, be used inside the whole project.

## Solution
I suggest to wrap `ListExtensions` inside it's own namespace like `namespace LanguageExt.ListExtensions`. It might even be worth to considerate and wrap `NullableExtensions` in its own namespace as well.

**Comment by MrWuffels** [comment]
The ToOption-extension is not meant to lift up pure values, so this is no error. As you correctly found out the Method you're searching for is Optional

**Comment by louthy** [comment]
Pretty much all of the methods that start with `To*` are [natural transformations](https://en.wikipedia.org/wiki/Natural_transformation).  Below is a way to get a mental model of the different types of transformation in this library:

| Type                   | Abstract       | Description                                                                                               | Examples                                                                                                                                                                                                            |
|------------------------|----------------|-----------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Lifting                | `A -> F<A>`   | Takes a 'lower type' and 'lifts' it into a 'higher type', usually via constructor functions.              | Lower = `int`, Higher = `Option<int>` lift function: `Some(123)`                                                                                                                                                    |
| Functor mapping        | `F<A> -> F<B>` | Takes the values 'within' a higher type and transforms them.                                              | `Some(123).Map(x => x.ToString())` transforms `Option<int>` to `Option<string>`. Note: the structure/'container' (in this case `Option<>`) is left unchanged.                                                       |
| Natural transformation | `F<A> -> G<A>` | Takes the structure/'container' of the higher type and transforms it, leaving the value-type within alone | `Some(123).ToSeq()` transforms a `Option<int>` to `Seq<int>`.  Note: the value-type is unchanged, but the values themselves may change; for example if we did `Seq(1,2,3).ToOption()` the result would be `Some(1)` |

**Comment by steven-panxd** [comment]
I faced a similar issue when using the latest version 4.4.9 on Nuget, where I have a parameter in my function that is `IReadOnlyCollection` typed. However, I can access its `Length` function, which is revoked to the Length function in `ListExtension`.

![image](https://github.com/user-attachments/assets/5cc4e8ed-0ee3-4589-bc40-0ccb67828c52)
![image](https://github.com/user-attachments/assets/d160c56e-13e4-443c-b693-ca84e2850f0f)

Funny thing is that, in Microsoft's document [here](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlycollection-1?view=net-8.0#extension-methods) and [here](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1?view=net-8.0), `IReadOnlyCollection` and its parent interface `IEnumerable<T>` do not have a Length function in their interface definition. 

![image](https://github.com/user-attachments/assets/4340b16b-1a62-49d0-b959-2f514823bcd9)

I assume it is because the `ListExtension` class does not have a namespace, so the Length function in it applied all classes/interfaces that implement `IEnumerable<T>` (since the static extension method takes `this IEnumerable<T> list`), which includes the interface `IReadOnlyCollection`.

I saw the version 5.0 beta added namespace for `ListExtension`, so I guess the issue will be solved after it is released.
