### ISSUE TITLE
EitherUnsafe MapLeft throws ResultIsNullException

### ISSUE THREAD

**Issue by jogivanknobi** [louthy/language-ext#1225]
Hi,

I'm a new user of this library and trying to integrate it into some of my projects.
Now I stumbled upon a behavior which I don't understand and I'm wondering whether this is a bug:

This code throws a `ResultIsNullException` on my system using LanguageExt v4.4.3: 

`    
RightUnsafe<Exception, object>(null).MapLeft(ex => ex);
`

Why is MapLeft() throwing here?

**Comment by evermanwa** [comment]
Out of curiosity, what is the purpose in using a null in this use-case?

How I have been taught, null should be avoided as much as possible when it comes to FP.

**Comment by jogivanknobi** [comment]
Actually it stumbled upon it while doing something like

`Try(CouldReturnNullOrThrow()).ToEitherUnsafe().MapLeft(...)`

**Comment by louthy** [comment]
EitherUnsafe supports null (that's the 'unsafe' aspect of it), so this sounds like a bug.  I'll take a look over the weekend.

The other comments about avoiding null is worth considering, either make the Right have a 'zero' state, or consider making null into a Left error state. 

It's much better to be intentional with your type definitions than to have an 'undefined' state.
