### ISSUE TITLE
internal class Cluster

### ISSUE THREAD

**Issue by architrent** [louthy/language-ext#124]
I feel like I must be overlooking something obvious here, but it continues to elude me, so here goes.

I'm building a system around Process with Redis.  However, I'm running into a very fundamental problem, which is that I can't connect to Redis via your libraries because the Cluster class is not public, and therefore I cannot invoke its Connect function from my code, as shown in your sample code.

I downloaded the source code and found the sample code doesn't work, either, for the same reason.  I marked Cluster public to get the sample apps to work.  Obviously, I can't do that in the compiled version available via NuGet, which is what I'm referencing in my project code.

Does Process provide another means of connecting to the Redis cluster, and I'm just overlooking it?  I don't see anything else documented.

**Comment by louthy** [comment]
@architrent Sorry, yes that mechanism is deprecated.  I am yet to update the docs.  It's been replaced with the `ProcessConfig` system.

To use redis for messaging you must first call:
```c#
    RedisCluster.register();
```
That registers the Redis implementation of `ICluster` with the core `Process` library factory.

To achieve similar to the docs, then you can use:
```c#
    ProcessConfig.initialise("sys", "web-front-end", "web-front-end-1", "localhost", "0");
```
* `"sys"` is the 'system name', but easier to think of it as the name of the cluster as a whole.  That means you can call it with a different value and point it at another Redis db for multiple clusters.  But for now it's easier to call it `sys` and leave it.
* `"web-front-end"` is the role, you can have multiple nodes in a role and the role based dispatchers allow you to implement high-availability and load balancing strategies.
* `"web-front-end-1"` is the name of this node, and should be unique in the cluster
* `"localhost"` is the Redis connection (can be comma separated for multiple Redis nodes)
* `"0"` is the Redis catalogue to use (`"0" - "15"`)

__However!__ I would encourage you to use the configuration file approach, because it offers a ton of useful features for configuring processes and staging environments.  Depending on the type of application you're building, you should call:

   `ProcessConfig.initialiseFileSystem();` -- for desktop and console apps
   `ProcessConfig.initialiseWeb();` -- for web-apps

They both look in the root folder of your application for `cluster.conf` and `process.conf` files.

In `cluster.conf` you set-up what the node 'is' in the cluster.  i.e.
```
    cluster web-front-end-1 as web:
        role: "web-front-end"
        node-name: "live1.yourdomain.com"
        connection: "localhost"
        database: "0"
```
The first line starts the definition of the node in the cluster.  `web-front-end-1` is the name of the cluster variable, `web` is an optional alias.  This allows you to specify multiple staging environments, e.g.
```
    cluster test as app:
        node-name: "test.yourdomain.com"
        ...

    cluster local as app:
        node-name: "local.yourdomain.com"
        ...

    cluster production as app:
        node-name: "yourdomain.com"
        ...
```
The `role` is the role of the node, i.e. the job that it does in the cluster.  That allows you to have multiple services running that fulfil the same role, and use the role-based dispatchers to do broadcast, round-robin, etc. (useful for load balancing, and high availability strategies) without needing to know the actual name of the nodes you're targeting.

`node-name` is exactly that, but for web-apps make this match your web-app's host-name.  The difference between `Process.initialiseFileSystem` and `Process.initialiseWeb` is that `Process.initialiseWeb` will automatically decide on the cluster specification to use based on the host-name.  If you're doing a web-app the there must be a live `HttpContext` available, so in `Application_BeginRequest` do this:

```c#
        bool started = false;
        object sync = new object();
		protected void Application_BeginRequest(object sender, EventArgs e)
		{
            if (!started)
            {
                lock (sync)
                {
                    if (!started)
                    {
                        // Let Language Ext know that Redis exists
                        RedisCluster.register();

                        // Connect to the Redis cluster and setup configuration
                        ProcessConfig.initialiseWeb();

                        started = true;

                        // start initialising processes after this point because the 
                        // system is live
                        DoYourSetupOfInitialProcessesHere();
                    }
                }
            }
        }
```
It's a touch ugly for web-apps, but it saves a lot of hassle with making sure you're providing the config system with the correct app and host settings.

Back to the `cluster.conf` settings...

`connection` is the Redis instance address, you can comma separate these if you're running multiple Redis nodes in a cluster, or with master/slave replication. 

`database` is the Redis catalogue ("0" - "15")

The `process.conf` allows you to configure individual `Process` and `Router` settings.  For example:
```
    process my-svc:
        pid: /role/user/my-service
        flags: [persist-inbox]
```
That declares that anything in the current `role` (the `/role` bit) with a leaf of `/user/my-service` that is spawned will have its inbox persisted to Redis:
```c#
    spawn<Msg>("my-service", Service.Inbox);
```
Note also that the name `my-svc` is registered in the current role.  So any other service can find it like so: 
```c#
    tell("@web-front-end:my-svc", msg);
```
If you're already running within the `web-front-end` role, then this will work:
```c#
    tell("@my-svc", msg);
```
So it's a kind of DNS for roles and names.

If you don't want to use `process.conf`, then you can achieve the same like so:
```c#
    var pid = spawn<Msg>("my-service", Service.Inbox, ProcessFlags.PersistInbox);
    register("my-svc", pid);
```

[I'd take a look at some of the samples](https://github.com/louthy/language-ext/tree/master/Samples), as this is all done in those.  [This is an example of quite a complex `process.conf` that uses the strategy system](https://github.com/louthy/language-ext/blob/master/Samples/Strategies/process.conf).  Strategies are mini-computations that run when the Process fails, and can match on exception types, and can provide directives to the Process system on how to handle the failure.  It also declares variables that can be read using `ProcessConfig.read` and `ProcessConfig.write`.  

The [PingPong](https://github.com/louthy/language-ext/tree/master/Samples/ProcessSample) sample has quite a [fun config file](https://github.com/louthy/language-ext/blob/master/Samples/ProcessSample/process.conf) that shows off the power (it's actually a strictly-typed language), you'll notice declaration of variables, references to vars in the scope of the cluster, and ternary operations.

**Comment by architrent** [comment]
I see.  Very helpful response.  Thanks.  We'll go with the config file approach, then.

The in-code process configuration you show for "my-service" is how I am currently handling spinning up the processes.  That all worked fine.  It was just getting Redis into the picture so the processes didn't have to be local that was holding me up.

You mention that with the config file approach, the processes are also registered.  That's great, since that's what we want.  I was doing that in code, also, and shutting them down on app shutdown.  You don't mention it, but, using the config file approach, do I still need to do that or is the framework going to handle shutdown for me?

I have some other questions about the best way of solving certain problems using language-ext.  Do you have a preferred medium for discussing those?  They don't belong here, since they aren't issues.

**Comment by louthy** [comment]
@architrent 

Registered processes are essentially permanent residents if they have any persistence flags set (`persist-inbox`, `persist-state`, `remote-publish`, `remote-state-publish`).  The idea is that if a service goes down then other services can still post to them (with the messages backing up in Redis until it comes back online).  

A process is only removed from Redis (its inbox and meta-data) when you call `Process.kill(pid)` from outside of the Process, or `Process.kill()` from within its message-loop.  `kill` also removes any registration automatically as well.  So you don't need to call `Process.deregisterById(pid)`

If you want to stop a Process locally, but still have it be 'visible' to receive messages whilst it is offline then you can call `Process.shutdown(pid)`.  This unloads the Process from the local tree but leaves the inbox, meta-data, and registration alone.

When you unload your app-domain (not sure if you're web or regular app), then you can call `Process.shutdownAll()` which does a more managed shutdown.  This is most useful for the IIS app-pool resets where sometimes static data can hang around.  On the whole though there are finalizers in place that will still deal with all of this automatically if you don't do it.  The shutdown of Redis is also handled automatically.

Again `Process.shutdownAll()` is like `Process.shutdown()` in that it doesn't remove the inboxes or meta-data related to the live Processes.  When you restart your service, and you restart your Processes they will recover their state and inboxes if persisted, and start handling the backlog.

There is a `Process.PreShutdown` observable that you can subscribe to, which has a message-type of `ShutdownCancellationToken`.  You can use this to cancel a shutdown if necessary.  And `Process.Shutdown` can be subscribed to for the post-shutdown event.

One final thing to note about registered processes is that multiple services can register a Process with the same name.  What happens when you `tell` a registered name (or in fact any operation on a `ProcessId`), is it builds a broadcast dispatcher, so that all Processes registered under that name will get the messages you send.  You can use the functions in the `Dispatch` class to modify this behaviour, e.g.
```c#
    tell(Dispatch.random("@reg-name"), msg);
    tell(Dispatch.roundRobin("@reg-name"), msg);
    tell(Dispatch.leastBusy("@reg-name"), msg);
```
If you're not happy building the `"@role:name"` strings you can use `find(role, name)`. So the above would be:
```c#
    tell(Dispatch.random(find("reg-name")), msg);
    tell(Dispatch.roundRobin(find("reg-name")), msg);
    tell(Dispatch.leastBusy(find("reg-name")), msg);
```
There is also a per-process setting in the `conf` files that allows you to modify the default dispatch mechanism:
```
    process my-proc:
        pid: /role/user/my-process
        dispatch: first
```
Valid values are: `broadcast` (default), `least-busy`, `round-robin`, `random`, `hash`, `first`, `second`, `third`, `last`.

To give you an idea of what's happening behind the scenes, this is the code that runs to register the Process after it has been created:
```c#                
ActorContext.System(actor.Id).Settings.GetProcessDispatch(actor.Id)
    .Match(
        Some: disp => Process.register(regName, Disp[$"role-{disp}"][Role.Current].Append(actor.Id.Skip(1))),
        None: () => Process.register(regName, actor.Id)
        );
```
So if you don't specify a `dispatch` setting (the `None` branch above) then the Process is registered with its regular path. If you do specify a setting (the `Some` branch) then a role-dispatcher is built.  That allows functions like `tell` to work out how to dispatch the message.  And because it's using the role dispatcher system, it always works on 'liveness'.  i.e.  if you use `round-robin`, then the `tell` will only send to nodes that are currently alive.

A final note about the configuration file.  Be a little wary of error line numbers.  What happens internally is that `cluster.conf` and `process.conf` are loaded and appended before being parsed, so error line numbers for the `process.conf` are off by the number of lines in `cluster.conf`.  I'll fix that up at some point!

> I have some other questions about the best way of solving certain problems using language-ext. Do you have a preferred medium for discussing those? They don't belong here, since they aren't issues.

Happy to answer here, or if you want to use the gitter room the link is on the home page.  I desperately need to get around to writing a lot of this stuff up; the Process system has grown quite a lot from its humble origins!

**Comment by architrent** [comment]
I see.  Thanks.  I'll post other questions in gitter, and close this issue.  (Sorry for the delay.  Life intervened.)
