### ISSUE TITLE
Refit.ApiException: 'An error occured deserializing the response.'

### ISSUE THREAD

**Issue by Akomspatrick** [louthy/language-ext#1313]
I  want to use refit to generate an sdk but am getting the error => : The JSON value could not be converted to LanguageExt.Either`2

 **`this is my  controller`**
        [HttpGet(template: DocumentVersionManagerAPIEndPoints.Model.Get, Name = 
       DocumentVersionManagerAPIEndPoints.Model.Get)]
        public Task<IActionResult> Get(CancellationToken cToken) => _sender.Send(new GetAllModelQuery(), cToken).ToActionResult();

**_This is my refit interface_**
         [Get("/api/v1/Models")]
         Task<Either<GeneralFailure, ModelResponseDTO>> Get(CancellationToken cToken);
**_I also tried using_**          [Get("/api/v1/Models")]
         Task<IActionResult> Get(CancellationToken cToken);

in both cases I got 
**_An error occured deserializing the response._**
Please I need help is there a way I can correctly have Either Result in my controller return type  and still  Use Refit  for my  SDK development ?

**Comment by louthy** [comment]
Sorry for the slow reply on this.  It seems you'll need a bespoke serialiser for `Either`.  Or you could convert the `Either` to a type that is friendly with your JSON library.

Serialisation support has been removed from the `Core` library because each serialisation library works differently and trying to support them all is like playing whack-a-mole.

The roadmap for next year is to provide serialisation-library specific support (so `LanguageExt.Serialisation.Newtonsoft`, `LanguageExt.Serialisation.System.Json`, etc.), but that's not in place yet, so you need to deal with serialisation yourself in the short-term.
