### ISSUE TITLE
Either.Bind triggers memory allocation unlike Either.BindLeft

### ISSUE THREAD

**Issue by AkilaeTribe** [louthy/language-ext#1337]
Given the version 4.4.8, the following benchmark, and its results:

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

using LanguageExt;

using static LanguageExt.Prelude;

namespace Benchmarks.Lext
{
    [SimpleJob(RuntimeMoniker.Net80, baseline: true)]
    [MemoryDiagnoser]
    public class EitherAllocationBenchmark
    {
        private const string SomeString = "Hello World";

        [Benchmark]
        public Either<string, int> EitherLeft()
        {
            return Either<string, int>.Left(SomeString);
        }

        [Benchmark]
        public Either<string, int> EitherLeft_BindLeft()
        {
            return Either<string, int>.Left(SomeString).BindLeft(Either<string, int>.Left);
        }

        [Benchmark]
        public Either<int, string> EitherRight()
        {
            return Either<int, string>.Right(SomeString);
        }

        [Benchmark]
        public Either<int, string> EitherRight_Bind()
        {
            return Either<int, string>.Right(SomeString).Bind(Either<int, string>.Right);
        }

        [Benchmark]
        public Option<string> Option_Bind()
        {
            return Optional(SomeString).Bind(value => value.Length > 0 ? value : Option<string>.None);
        }
    }
}


```

| Method              | Mean       | Error     | StdDev    | Ratio | Gen0   | Allocated | Alloc Ratio |
|-------------------- |-----------:|----------:|----------:|------:|-------:|----------:|------------:|
| EitherLeft          |  0.0521 ns | 0.0108 ns | 0.0096 ns |  1.00 |      - |         - |          NA |
|                     |            |           |           |       |        |           |             |
| EitherLeft_BindLeft | 16.3677 ns | 0.3091 ns | 0.3307 ns |  1.00 |      - |         - |          NA |
|                     |            |           |           |       |        |           |             |
| EitherRight         |  0.0151 ns | 0.0010 ns | 0.0008 ns |  1.00 |      - |         - |          NA |
|                     |            |           |           |       |        |           |             |
| EitherRight_Bind    | 32.2848 ns | 0.4346 ns | 0.4065 ns |  1.00 | 0.0017 |      88 B |        1.00 |
|                     |            |           |           |       |        |           |             |
| Option_Bind         |  3.0604 ns | 0.0483 ns | 0.0452 ns |  1.00 |      - |         - |          NA |

We can see that Either.Bind consumes memory, but Either.BindLeft does not. 

---

The implementation is different in the main branch:
- 4.4.8 : https://github.com/louthy/language-ext/blob/v4-latest/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Either/Either/Either.cs#L1279
- main : https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Monads/Alternative%20Value%20Monads/Either/Either.Right.cs#L135

I assume the future versions (5.0.0 ?) of LanguageExt will not trigger allocation for the Either.Right method, but can we also expect it for a minor version (4.X.Y) ?

**Comment by harrhp** [comment]
in version 5 Either is a class, so all methods in your benchmark are going to allocate memory

**Comment by louthy** [comment]
> That's unfortunate, I assume the change to a class was needed for specific reasons ?

The reasons are:
* To be able to leverage the first-class pattern matching support in C#
  * This alone reduces allocations, because you don't need to allocate lambdas for matching
  * It gives a much more powerful feature set than `Match(..., ...)` because of the ability to use `when` clauses
* Removes the need for a 'bottom' state
  * This is an unfortunate artefact of a `struct` based `Either`.  
* Allow nesting of types that work with the [new monad-transfomers and higher-kinds](https://paullouth.com/higher-kinds-in-c-with-language-ext/) without complex casting operations.  

I do mostly try to minimise allocations where I can, but ultimately programming using the functional programming paradigm will always create lots of small ephemeral objects.  They do of course create some GC pressure, but I really don't think in the big scheme of things they're a cause for concern:

* We have a much better GC than we had 10 years ago when I created this library
* The objects are small and ephemeral, meaning they'll likely get collected in a Gen-0 collection
* Leveraging Gen-0 is good for cache locality

My personal opinion is people tend to worry far too much about using memory and the GC and don't necessarily understand how small an issue it is.  However, if you're writing performance critical code -- where you absolutely cannot have a GC collection during an operation -- then I of course understand that this isn't ideal.  In those circumstances I'd advise not using FP techniques at all.  The vast majority of code does not fall into this category and your memory and the GC should be used for its intended purpose.

> but can we also expect it for a minor version (4.X.Y) ?

No.  I have stopped development on `4.*.*`.  I don't have the bandwidth to manage two versions.  So `v5` is where my effort is going.  The only `4.*.*` releases I will do from this point on will be for bug fixing ([like this](https://github.com/louthy/language-ext/pull/1334), which I will release soon).

**Comment by aloslider** [comment]
There's also a good page on this project's wiki called ["Performance"](https://github.com/louthy/language-ext/wiki/Performance), I suggest you to read it as well. 
Basically, I think you better go full-imperative for performance critical code, but you can make a wrapper that is written in functional style, or, if you have some spare time, make a small FP high-performance toolkit, as you probably don't need all of the features language-ext provides.

**Comment by louthy** [comment]
> There's also a good page on this project's wiki called ["Performance"](https://github.com/louthy/language-ext/wiki/Performance), I suggest you to read it as well.

@aloslider Thanks for sharing that.  Just a note that it's a little out of date now and could do with an update, but the reasoning is all sound.

**Comment by AkilaeTribe** [comment]
Thank you very much for all the interesting responses.

In a nutshell, two years ago, I worked on a program that forwards events from one service to another during the day, in real time. Over the months, the quantity of events handled greatly increased. As a consequence, the startup times during a day, and the memory consumption are higher. Sometimes, there are also random (every minutes or hours) performance drops, and I am trying to fix that.

Fortunately, the program is not critical enough to require that the GC never happens. Though, until this day, I am still unable to explain the performance drops, and I am considering everything; thread pool starvation, GC, ... Until I can pinpoint the actual causes, I am aiming for low-hanging fruits, like trying to minimize allocations. This is how I ended up here, requesting clarifications about the allocation...

@aloslider I will confess that the intent behind the program was to give the clean code architecture and some odd design choices a try. Although it made it easier to debug and understand it, I probably did a mistake somewhere, and I am now trying to find what is causing those performances drops 😅

**Comment by louthy** [comment]
GC pauses are tiny these days and modern GCs (including the .NET one) do much of their processing on parallel threads so that the pauses (when needed) are minimal.  So stop the world events are very short and are unlikely to the cause of your problems (based on what you've stated).  I seriously doubt that the GC is your issue.

Startup time problems + sporadic performance issues would cause me to look at thread-pool/task-scheduler starvation first.  If you run out of threads then it can take **seconds** to spin up brand new ones.  This can cause slow startup problems (as you're waiting for the threads to be 'commissioned') and can cause scheduler pauses during regular operations if there aren't enough free threads -- I've seen this plenty of times before.

Focusing on queuing solutions (where you manage a set of queues that deal with your events) is usually the best way to handle massive throughput in a controlled way (for example by using actors, or reactive streams).  So, instead of launching a `Task` per event or a `Thread` per event, pre-launch `n` threads (say, matching the number of processors in the machine), each with a blocking queue on it, and then process the event-items serially per-thread.  If you get back-pressure after implementing a solution like that then you're probably hitting the physical limit of the machine (or you might need to optimise the event handlers themselves!)

If your throughput is enormous you also need to consider whether the actual hardware is up to it.

Always profile though ;-)

**Comment by louthy** [comment]
Because it was small I added a fix to `Bind` to remove the need for an allocation. It's live now in `4.4.9`

**Comment by AkilaeTribe** [comment]
Thank you very much ! I really appreciate all the responses ! 

So, over the last days, I was trying to find a solution to get myself out of the mess I created. Although my program has some kind of producer consumer, it also has a custom, poor version of the actor model, through multiple Reactive EventLoopScheduler instances. It was an attempt to dodge some concurrencies issues, related to the program.

Unfortunately, although I am working on it (and it is going slowly), I am still outrageously untrained in profiling an application, so the uncertainty about whether and when I would be able to find something was high.

After seeing your nice code proposals, the idea of just making the code simpler (or, not more complicated than needed), more compacted (keep in the same class things that are used together, instead of spreading them), started to grow in my mind, and I believe it is the best course of action.

When I manage to do it, I hope to bring a happy conclusion to this little off topic discussion !

In the meantime, thank you very much for your efforts, and I wish you well !
