### ISSUE TITLE
[bug] ParserResult.<T>ToString() displays error message when IsFaulted is false

### ISSUE THREAD

**Issue by jcoder58** [louthy/language-ext#135]
I noticed this in the debugger.  Which takes precedent, IsFaulted or the error message?  

![capture3](https://cloud.githubusercontent.com/assets/342910/18250515/d914513c-7351-11e6-8035-5475cfc45e30.JPG)

**Comment by louthy** [comment]
If `IsFaulted` is true then there's an error, otherwise there isn't and the `Result` is your parsed value.  

Because parsers are nested, failures can propagate up the chain which then are not considered errors higher up (say within an `either`), the parser combinator needs to keep capturing errors in-case it needs to show the full set of expected results later, so sometimes you will see errors from lower down - this is the  expected behaviour of the Parser type and not a bug. 

End-of-stream errors means you have built a parser that doesn't know when it's complete.  This can happen by default with parsers like comments parsers.  So often it's just easier to just confirm that the `State` is also empty if you have a looser parser (that's assuming you expect to parse all available text).

I have used an extension method in the past to simplify this, which you're welcome to use:
```c#
    public static class ParserExt
    {
        public static Either<ParserError, T> Run<T>(this Parser<T> p, string source)
        {
            var res = p(source.ToPString());
            return res.IsFaulted || res.Reply.State.ToString().Length > 0
                ? Left<ParserError, SourceFile>(res.Reply.Error)
                : Right<ParserError, SourceFile>(res.Reply.Result);
        }
    }
```
