### ISSUE TITLE
Modifying object in a fluent way

### ISSUE THREAD

**Issue by marss72** [louthy/language-ext#1350]
I know I can make an extension method for this, like:

```cs
public static T Mod<T>(this T instance, Action<T> action)
{
    action(instance);
    return instance;
}
```

but is there any built-in function in language-ext to do this? As I don't want to screw things up by pull request, or if it would be even accepted, I'm not going to do a PR for this, but, is this already implemented, or will it be?

My goal is for example to modify an object in a read-only field when initializing without a constructor.

**Comment by louthy** [comment]
No, there's not a function like that in lang-ext, mostly because it's not in the spirit of the library.  Mutating an object (in-place), whilst OK in certain circumstances, goes against the direction of travel, which is _pure_ functional programming.  The 'pure' part of that statement is definitely what `Mod` isn't.

The closest to `Mod` that exists in lang-ext is [`Atom`](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/Concurrency/Atom/Atom.cs).  `Atom` allows for _atomic_ mutations of values.  The idea is that we can't get away from mutations entirely (unless we make our entire code-base pure, which in C# is sometimes unreasonable), so let's make mutations safer by making them atomic.

So, let's say you have a static reference to a value:

```c#
var atom = Atom(new MyValue(...));
```
You can then modify it using `Swap`:
```c#
atom.Swap(value => ... do something to mutate the value ...)
```
If, while running the `Swap` some other thread changes the atom before we finish, then the `Swap` function is re-run using the new value.  This will continue until there are no cross-thread conflicts.  That means it's important not to put any side effects in the swap function, or dependencies on external state that could change the nature of the update (because it could be run multiple times to deal with conflicts).  

[The 'Concurrency' section of the Wiki](https://github.com/louthy/language-ext/wiki/Concurrency) has more on atoms; as well at the Software Transactional Memory (`Ref`) system, and atomic data structures such at `AtomHashMap` and `AtomSeq`.  

I'm not sure if this is quite what you're after, but it's the closest thing to support of mutable structures in lang-ext.

**Comment by marss72** [comment]
Got it, thanks.
