### ISSUE TITLE
Why are the NewTypes gone?

### ISSUE THREAD

**Issue by danya02** [louthy/language-ext#1352]
Recently, [the newtype features were removed](https://github.com/louthy/language-ext/commit/e2512844a424930e8b8f0254df3f8adff4d0da5e). I find this unfortunate, because I was just thinking of using them in my own project.

In [a wiki page](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Function-Signatures), the newtypes are used to do some pretty neat things. From that commit, it seems that the new examples use `record` types instead, but they don't entirely replace newtypes: for example, it doesn't look like the comparison operators other than Equals are automatically defined.

Additionally, I can't even use record types in my project, because for various reasons I'm stuck on C# 6.0 and can't easily upgrade to a version that has record types. A pretty big selling point of this library was that I could integrate it into the project with no upgrades required -- though I understand that having to support such an old language/framework version is probably not a high priority.

What is the reason for the removal of newtypes, and what is the recommended alternative/upgrade path?

**Comment by louthy** [comment]
> What is the reason for the removal of newtypes

As noted, records now do 99% of the job.  As you say, they don't do comparison operators automatically, but I feel that for the few types where we need comparison operators, it's not too much effort to implement by hand.  Records can also be `readonly struct`, which will be more efficient for simple new-types like identifiers.

I am also slowly moving towards the [universal domain-type traits](https://github.com/louthy/language-ext/tree/main/LanguageExt.Core/Traits/Domain) -- based on the ideas from [this article](https://mmapped.blog/posts/25-domain-types).  The idea is to define what it means to be an identifier, a loci, a quantity, or an amount.  So, more structure to the abstract concepts behind new-types.

With the defined traits I can write support code that works with identifiers, quantities, amounts, etc.  Taking the core idea of new-types to another next level. They're not fully fleshed out yet, but they will be by the time `v5` is released.

The end goal here is to use source-generators instead of runtime IL generation.  That removes the initial runtime hit (I'm working on trying to reduce startup times also).

> I understand that having to support such an old language/framework version is probably not a high priority.

That decision has already been made, `v5` is .NET8+ only, it is required for the new trait system, so there's no going back.  I will be supporting `v4` for a reasonable period (bug fixes and security patches only), but I have already waited quite a long time to move away from `netstandard` and it was holding the library back.

Language-Ext is 10 years old this year.  The upcoming `v5` release is a once-per-decade refresh of the library.  And so, I'm taking the opportunity to do as much as I can to make all aspects of the library relevant.  C# has improved significantly in that time and certain parts of this library are either not relevant any more or should evolve.  The impact isn't small, but it will only happen once at this scale.

**Comment by danya02** [comment]
Thanks for the reply!

It makes sense that since such a big release is coming up, that a lot of things will have to change. Due to my project's constraints, I guess I'll stay on v4 for now -- it wouldn't be the first library that we had to do so for. 

Part of the confusion on my part was due to the fact that Google's search results still have info about newtypes (as of writing this comment at least, it'll probably get reindexed before long).

There's actually been a few instances where I got confused by the docs because I thought they applied to the version I was running, while they're actually about the latest version available. I'd prefer it if a stable version of the docs were available, but I guess I can build and host them myself.

Also, since "newtype" is such a common name for "I want a datatype that's wrapping a primitive", and that's what people would be looking for, how about putting up a page titled "newtypes are obsolete, use <blank> instead", so that people like me don't get lost looking for this?

**Comment by louthy** [comment]
I'm working through the documentation as we speak. The API reference is currently being updated, the home-page and wiki will be done after.

**Comment by danya02** [comment]
Any thoughts about the idea of providing a stable documentation that matches a release? I can try figuring out how to do it myself for my team, but maybe an official source is a good idea too?

**Comment by louthy** [comment]
The `v4` API documentation is here: https://louthy.github.io/language-ext-v4
