### ISSUE TITLE
Stuck on simple problem in applying function to a sequence of Eithers... :-(

### ISSUE THREAD

**Issue by ABIOLI-COM** [louthy/language-ext#1373]
Very simply, I expected that if I build an anonymous record, for example like in

`(Either<ERROR, int> ei1, Either<ERROR, int> ei2)`

I could apply it to a function like

`Either<ERROR, int> f(int i1, int i2) => ...`

With something like
`
var result = (Either<ERROR, int> ei1, Either<ERROR, int> ei2).Apply((i1, i2) => f(i1, i2));`

Where the idea is: if any of the input either is in error, return the error, otherwise return the result of applying the f to the (correct) values.
But it doesn't work... :-(

**Comment by micmarsh** [comment]
Assuming you're using v4, since with v5 every applicative (including `Either` ) should have the `Tuple.Apply` method you're trying to use.

With v4 (and v5, fwiw), you get your intended result monadically using  LINQ syntax
```csharp
from i1 in ei1
from i2 in ei2
select f(i1, i2)
```

**Comment by louthy** [comment]
It works in `v5`** but not in `v4`.  Because in v5 the apply behaviour has been generalised and allows all applicatives to use the tuple-based technique (which in `v4` only exists for `Validation`).

You can also use (in v4):
```c#
var mr = fun((int x, int y) => x + y).Apply(mx).Apply(my);
```
> Those applicative behaviours are available in `v4` for most types.

Or (in v5),
```c#
var mr = fun((int x, int y) => x + y).Map(mx).Apply(my);
```


Finally, as @micmarsh says, you can use LINQ, which for most applicatives is the easier option.  The main reason to use `Apply` is to leverage the difference in the applicative behaviour compared to the monadic behaviour.  `Validation` (for example) collects multiple errors, `Either` doesn't, so there's little benefit to using `Apply` with `Either` unless you already have a lifted function.

** Sometimes C#'s type-system doesn't allow the tuple-based approach (it can't infer the inherited `K<F, A>` interfaces from the variable (yeah, I know, idiotic).  I think this is mostly with structs.  So, the above `Map`/`Apply` approach is the ones that will always succeed and can chain any number of values.

**Comment by ABIOLI-COM** [comment]
I'm really sorry, my question was really that simple.  
I made confusion between Either and Validation, where of course I was *thinking* I was using Validation, that works as expected.  
Thank you for the further clarifications, it's always a good thing to learn anyway something new, and important! :-)
