### ISSUE TITLE
Is Result.cs going to be included in V5.x?

### ISSUE THREAD

**Issue by dorlandode** [louthy/language-ext#1375]
I am looking at using LanguageExt.Common.Result.  I see it in v4.4.9, but not in the latest V5.x beta.

**Comment by micmarsh** [comment]
As @louthy mentioned in another recent disccusion, `Result` was never intended to be used by library consumers outside of serving as an intermediate type for `Try`s https://github.com/louthy/language-ext/issues/1371#issuecomment-2367722953

If you change all of your usages of `Result` to `Fin` (French for 'end'/'finished'), you'll get the fully-featured error monad for both v4 and v5. It's unfortunate since so many "intro to error handling in FP" tutorials define a `Result` monad, but that's why it's going to be completely removed moving forward.

**Comment by louthy** [comment]
@micmarsh is correct.  I've now [started an FAQ ](https://github.com/louthy/language-ext/wiki/Frequently-Asked-Questions) which covers this and will expand as I get nearer to `v5` RTM
