### ISSUE TITLE
Would Either<L, R> be better?

### ISSUE THREAD

**Issue by donners77** [louthy/language-ext#14]
Hi.

I'm new to functional programming and I really appreciate your efforts to bring it to C#.

I'm wondering in the current implementation of Either<R, L> why the right type is specified on the left and the left type is specified on the right?

Would it make more sense to specify the types the other way around?

Kind regards,
Craig.

**Comment by tejacques** [comment]
+1

**Comment by louthy** [comment]
_(Sorry about the slowness of replying, my real-world workload is off the scale at the moment)_

I'm sure I had a good reason for this at the time.  This is the second implementation of Either that I've done (the first in the csharp-monad project).  I seem to remember feeling that the 'subject' of a multivalue type should be first in the list.  Because Left means 'wrong', or 'other', in this sense, I felt it should be last in the list.  But I can see your PoV.

My concern with changing this is that it's a horrible breaking change for others using the library.  I guess the other way to think about it, is it's the right way around if you're an Either looking out, rather than a human looking in ;-)

Anyway, I think I'd like some more views from people already using the library before making any change.

**Comment by louthy** [comment]
Ok, I decided to bite the bullet and change this.  It's a pretty tedious breaking change (I've just been through my own code fixing it up), but I think you're both right overall.  I also had the same comments on my other monad project, so I think it's time to accept that I was wrong and just fix it.

There's a new github and nuget release.
