### ISSUE TITLE
Using Map with a key type that doesn't implement IComparable results in runtime exceptions

### ISSUE THREAD

**Issue by monkeyhell** [louthy/language-ext#144]
`Map<K,V>` does not constrain its key type to implement `IComparable`, so it's possible to accidentally create a map for which the key type doesn't have a natural ordering, and you don't find out about this until runtime.  It would be nice if the compiler told you about this instead.

**Comment by louthy** [comment]
@monkeyhell That's an unfortunate side-effect of `Comparer<T>.Default`, which has various fallback strategies if the type isn't `IComparable` which makes it slightly more flexible.  I'm following the same pattern as the .NET Immutable Collections library, so I'll probably leave it as-is I'm afraid.

**Comment by monkeyhell** [comment]
Interesting.  I had hitherto assumed that `ImmutableSortedDictionary<K,V>` had a type constraint to ensure its key type was `IComparable`, but as you say, it doesn't.  I think perhaps the reason I've never made the same mistake with the Microsoft immutable collections is that the name of the type includes the word 'sorted', so it forces you to think about your key type.

**Comment by louthy** [comment]
If you don't need a sorted collection you can use `HMap`.

**Comment by monkeyhell** [comment]
Got it.  I'll just have to get into the mindset that maps are sorted by default, and unsorted only if you explicitly say so.  Looks like the same is true for `Set` vs `HSet`.

This library looks really useful.  I've been frustrated by the amount of boilerplate when using the Microsoft immutable collections, and as a result it's been quite a hard sell when trying to convince others to use them.  Using this library instead makes everything much easier on the eye.  Thanks!

**Comment by louthy** [comment]
> I'll just have to get into the mindset that maps are sorted by default

With immutable structures `Map` and `Set` are also slightly more efficient (Because an `HMap` is a `Map<int, Lst<IMapItem<K, V>>>` and `HSet` is a `Map<int, Lst<T>>`).  So the only reason for using `HMap` and `HSet` would be because of the issues around orderable keys as you specified.

> Using this library instead makes everything much easier on the eye. Thanks!

Indeed.  It was a big frustration for me also.  As well as having a coherent functional 'base class library', rather than disparate collections libraries, option types, etc.  None of which can make use of each other.  So I've been trying to bring in as much of what would be considered the core of a functional language's framework.  

I'm working on v2 now in a separate branch which will hopefully take it to the next level again, with support for Ad Hoc polymorphism, which hasn't really been done before in C#; and if it has it's been in a limited form, whereas I'm hoping to provide a type-class system similar to Haskell.  Microsoft themselves are [investigating the technique](https://github.com/CaptainHayashi/roslyn/blob/master/concepts/docs/concepts.md) for a future version of C# (and looking into new grammar to support it), but I wouldn't expect anything until C# 10+.  So in the meantime I'm trying to bring it into lang-ext.  I don't know if that helps with the hard sell ;)

**Comment by monkeyhell** [comment]
Re the implementation of `HMap` and `HSet`, that's interesting because I would have assumed that a hashmap/hashset would be backed by a hashtable, and would therefore have O(1) lookup, but in this case it's actually O(log(n)).  Good to know.

Re v2, sounds good, I'll keep an eye out for it!
