### ISSUE TITLE
Option<T> == null produces surprising result

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#155]
````
            var opt = Some(123);
            var shouldBeFalse = opt == null;
            opt = None;
            var arguablyShouldBeTrue = opt == null;

            Console.WriteLine(shouldBeFalse);
            Console.WriteLine(arguablyShouldBeTrue);
````

I don't know if anything can be done about this, or if it is simply a compiler limitation, but the above code compiles and produces (to me) a surprising result. I would hope that None == null would return true, or that it wouldn't compile. But it actually returns false. As it is, this creates a refactoring headache when attempting to replace Nullables with Options.

**Comment by OlduwanSteve** [comment]
On further investigation, you can override the compiler-supplied nullable comparison operators. I think a good course of action would be to implement them as 'expected' but mark them obsolete to discourage use and highlight problems during refactoring. I'll make a patch in case you agree.

**Comment by louthy** [comment]
@OlduwanSteve I'm not sure I agree.  `None` isn't `null`.  It's a distinct single instance value.  The fact that `null` can be implicitly coerced to `None` doesn't also imply equivalence. 

Your pull request appears to be related to Nullable options, whereas your example above isn't.  I am confused as to the refactoring headache you're referring to and the problems caused.  It doesn't make sense to add hacks to deal with lazy refactoring.

**Comment by OlduwanSteve** [comment]
The example above _does_ deal with nullable options, because the compiler helpfully converts Option<int> to Option<int>? before it performs the comparison.

The problem with refactoring isn't really a question of effort. If you replace a nullable with an option (quite a likely thing to do) then there is no good way of finding all the places where comparison to null is happening, but anywhere it is happening the logic will break.

**Comment by louthy** [comment]
> I think a good course of action would be to implement them as 'expected'

I don't agree that your solution is what's expected, `Option<T>?` is a type that _correctly_ has three states: `null`, `None`, `Some(x)`.  
```c#
    null != None
```

I don't think you have made a strong enough case for breaking that.  I'm not quite sure why refactoring from `Nullable<T>` to `Option<T>` would require `Option<T>?`.  It seems a little odd ([the only use-case I can think of is in an immutable `With` method](https://stackoverflow.com/questions/38575646/general-purpose-immutable-classes-in-c-sharp/38596298#38596298)).  But in general, once you have changed the variable's type, I don't then see why you wouldn't (as a natural part of the refactoring process), find all usages of the variable and validate it.

I'm going to reject this I'm afraid, because it ignores the explicit type declaration by the programmer.

**Comment by OlduwanSteve** [comment]
As I understand it, the point of `Option<T>` is to be a 'better' `Nullable<T>`. You wouldn't ever _use_ `Option<T>?` because it's a tautology. In addition to that, you're actively discouraging the use of null throughout the library. Bearing those things in mind, it's not clear to me what's getting broken by the proposed change.

The main advantage I see to the proposal is simply that doing this:

> find all usages of the variable and validate it.

...is hard and unreliable. Thanks to type inference and anonymous types, it's very easy for the type of a variable to be passed on to other variables. Tracing all of that manually is likely to fail at some point.  If the compiler does it for you then it's much more reliable.

**Comment by louthy** [comment]
You state "You wouldn't ever *use* Option<T>? because it's a tautology",
but then your pull-request dealt with Nullable<Option<T>>.  If you have a
Nullable<Option<T>> then it's likely to be for a good reason - like the
With use-case that I mentioned before - which explicitly expects a
tri-state variable; that would break with your change.  I know we have code
in our code-base that would fail because of that, others might too.

**Comment by OlduwanSteve** [comment]
I think I can justify the pull request better. If you look [here](http://stackoverflow.com/questions/1972262/c-sharp-okay-with-comparing-value-types-to-null) it describes how, for types which overload the equality operator, the compiler automatically implements a 'lifted' equality operator with nullable arguments.

In the current lang-ext, when I call this :

````
var arguablyShouldBeTrue = opt == null;
````

The compiler is calling the auto-generated method:

````
public static bool operator ==(Option<T>? lhs, Option<T>? rhs)
````

where `lhs` is never null (because it's lifted a struct). In order to change this default behaviour I had to override that method so the default implementation isn't created (or the compiler prefers mine... not sure which).

The point is whenever you compare `Option<T>` with null, that's the overload that will get called. So my pull request is only dealing with `Nullable<Option<T>>` because that's how you overload comparison between a struct and null.

You're right about the 'With' use-case, but actually this only breaks if you use the conditional operator. With my changes you get an 'obsolete' warning and VS underlines it with a green squiggle:

![image](https://cloud.githubusercontent.com/assets/809808/19323922/f0b5b9fc-90b6-11e6-9de6-63be1782ae49.png)

If you use the coalescing operator then it works perfectly, and is a bit neater:

![image](https://cloud.githubusercontent.com/assets/809808/19323948/0ea684fa-90b7-11e6-90bb-d3ca4a791533.png)

FWIW, by compiling our code base against my fork of lang-ext, I've already found some minor bugs that slipped through the refactoring net.
