### ISSUE TITLE
LanguageExt.Core NuGet dependencies

### ISSUE THREAD

**Issue by gordey4doronin** [louthy/language-ext#163]
Hi,

Does `LanguageExt.Core` really depend on `System.Reactive` packages?
I've checked the code and it seems it does not.

I suppose these dependencies occurred after splitting up base package `LanguageExt` to sub-packages? Correct me if I'm wrong.

I would like to use `LanguageExt.Core` package from `NuGet` for monads only, and I don't want to bring `System.Reactive` dependencies for no purpose.

I wonder if it's possible to update `LanguageExt.Core` package in `NuGet` to be dependency-less?

**Comment by louthy** [comment]
Yep, it's really used.  All of the monadic types have `MatchObservable` for asynchronous matching.

**Comment by gordey4doronin** [comment]
Oops, sorry, I see now. Thanks for the answer.

So closing the issue?
Unless you don't want to extract the reactive methods part to `LanguageExt.Core.Reactive` for example.
However, maybe it is over-engineering and it is more obvious just to install one redundant dependency for consumers of the library (like me).

P.S. Some preface. I was searching for monads for C# and found your `csharp-monad` project. Then I discovered this `language-ext` project, and it looks more complete and useful. So I decided to take monads from here rather than `csharp-monads`.

**Comment by louthy** [comment]
> So closing the issue?

Yep, I think although in the longer term a dedicated `LanguageExt.Reactive` project might be a good idea, right now (when I have the bonnet up on a ton of the core library code), it's probably best to leave as-is.

> So I decided to take monads from here rather than csharp-monads.

`csharp-monad` was my first attempt at a functional library in C#.  It's OK, but it suffered from not having the supporting framework that is `language-ext`.  This is much more complete, useful, and maintained.  I keep the `csharp-monad` library ticking over because it's linked to from the Monads page on Wikipedia, but it's essentially mothballed.

**Comment by louthy** [comment]
No, sorry.
