### ISSUE TITLE
Usage of Process from Async API-Gateway

### ISSUE THREAD

**Issue by stefc** [louthy/language-ext#169]
I've a question about using the Actor System behind an API-Gateway. 

In my case I have an Actor "CommandStore" and "QueryStore", it's part of a CQRS System. 

The API Gateway get a http POST request, this call `tell(commandStore, IDomainCommand, replyToActor)`
the commandStore is connected to the queryStore and map the IDomainCommand to a sequence of IDomainEvents and add it to an immutable EventStream (it's the state of the command-store). 
And the end of the receive it forward the IEnumerable<IDomainEvent> to the 'queryStore' like 
`tell(queryStore, IEnumerable<IDomainEvent>, Sender)`
The queryStore hold's an aggregate which is updated via a fold. The resulting aggregate state should be returned to the original Caller (replyToActor). 

My question is how can I handel this szenario if the API Gateway itself is implemented in an async manner. 

```
 public async Task<State> PostCommand(IDomainCommand domainCommand) {

    tell(commandStore, domainCommand, refReplyToActor) 
    await  continueWith(
        refReplyToActor lastAggregate
}
```

I currently have not an idea because the actor model is single threaded, but the http://api-call I want to implement async with waiting for the result receives in the refReplyToActor. Should I pass a correlationId to the message and wait for that Id returned?

**Comment by louthy** [comment]
@stefc There's always a mismatch at the edges of an actor system, and unfortunately you've hit one of those.  I'm struggling to follow your description, but one approach could be this:

* As you state, you have a correlationId, this should be passed through
* In your `refReplyToActor`, simply `publish` the response:
```c#
    public void Inbox(ReplyMsg msg) =>
       Process.publish(msg);
```
* Get your `PostCommand` to subscribe to the `refReplyToActor`:
```c#
public async Task<State> PostCommand(IDomainCommand domainCommand) 
{
    var task = Process.observe<AggregateValue>(refReplyToActor)
                      .Where(x => x.CorrelationId == correlationId)
                      .Take(1)
                      .ToTask();
    tell(commandStore, domainCommand, refReplyToActor) 
    return await task;
}
```
One thing to note, is that `refReplyToActor` should be an absolute path, not a registered name, or a router, and it's better if it's local.  The pub-sub code isn't quite a good as it could be and needs some improvement.  

I think will eventually put in some async variants of `ask`.  The main reason for not doing it before was to discourage use within actors, but I could protect against that quite easily.  In fact you could probably just use something like this:
```c#
    public static Task<R> askAsync<R>(ProcessId pid, object message) =>
        Task.Run(() => ask<R>(pid, message));
```
Even though `ask` is blocking, it does release the thread whilst it's waiting for a reply, so it'll be as efficient as it can be and not hog a ton of threads.  _Just make sure you don't use this within a Process message-loop, because otherwise you'll kill the single threadedness of the actor-model_.

Let me know how you get on.

**Comment by stefc** [comment]
Thanks for your large answer. I think I'll try the first pattern you mentioned (publish, observe). As a future enhancement of your framework I would suggest to make passing additional message context easier (i.g. correlationId). Perhaps it can be a Monad ;) 

The enhancement of ask in an async way I would not like, because it break's the actor-model. As you mentioned ask is blocking and that is what I not wanted if I use an Actor Model, so there must be another solution for this problem. This also belongs to the sync ask method!  
Perhaps you can mark the ask method with a warning at compile-time (deprecated or something similar) ;)
