### ISSUE TITLE
Choice of SelectMany overloads in HKT

### ISSUE THREAD

**Issue by la-yumba** [louthy/language-ext#176]
Hi Paul, 

I've been looking at your implementation of HKT, which effectively allows one to stack monads, at least 2 of them. This is great, but after some thought and experimentation I think I disagree with the exact overloads of SelectMany you choose to implement. 

Consider, for example: 

```
var oa = Some(1);
var lb = List(2);

var r1 =
   from a in oa
   from b in lb
   select a + b;
```

This works, although a purist would argue that it's perfoming a *map* with the syntax of a *bind*. But screw the purists, let's put readability first: the above gives you what you want with minimal syntactic overhead. The problem with this approach (getting LINQ to do what you want by adding overloads of SelectMany) is that it's not general enough, and you soon find cases like this:

```
var oa = Some(1);
var lb = List(2);
var oc = Some(3);

var r2 =
   from a in oa
   from b in lb
   from c in oc
   select a + b + c;
```

Which don't work, i.e.: are not covered by the overloads to SelectMany that `language-ext` provides. What's worse, if you try to add an overload that caters for this case, it conflicts with the existing overloads, so that the compiler doesn't know how to interpret the LINQ query. 

I've come up with a solution, which is as follows. For any pair of monads A and B, if you want to be able to treat `A<B<T>>` as a monad over `T`, then you should _only_ define the following overload of `SelectMany`:

```
public static A<B<RR>> SelectMany<T, R, RR>
   ( this A<B<T>> self
   , Func<T, A<B<R>>> bind
   , Func<T, R, RR> project )
```

Which can be implemented ad hoc, or in a general way, in terms of `Map`, `Bind` and `Traverse`.

Once you've done this, you need to explicitly 'lift' your `A<>` and `B<>` values into the `A<B<>>` monad, so the example above would have to be rewritten as follows:

```
var oa = Some(1);
var lb = List(2);

var r1 =
   from a in oa.Map(List)  // a : int
   from b in Some(lb)      // b : int
   select a + b;
```

This means that this simple scenario will have a bit more overhead. On the other hand, you can now compose any function that returns an `A<>`, a `B<>`, or an `A<B<>>` in a single LINQ query, which is much more flexible in the general case.

**Comment by louthy** [comment]
@la-yumba Hi Enrico, thanks for getting in touch.  I haven't quite got time to review this at the moment, but rest assured I'm revisiting this with `v2` of language-ext.  I'm looking into the best approach for the code-gen part, and considering all options for monad-transformers (including creating transformer types like `OptionT`, `LstT`, etc.  

One thing I'm looking at very seriously right now is creating a Haskell-ish to C# transpiler.  Primarily to reduce the massive amount of boilerplate I need to write to make language-ext work and to support the type-classes feature (as well as reduce the risk of error);  out of that should come a better transformer code-gen story.

**Comment by louthy** [comment]
@la-yumba Hi Enrico, I followed your pattern for the latest transformer type extensions.  [The template for generating the extension methods](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/HKT.LINQ.Template.txt#L12) are implemented [in terms of the new `Trans` type](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/Trans.cs#L17), which provides a default and bulletproof way of nesting any types that have a `Monad<MA, A>` class instance.

So for example, nesting `Lst` and `Option` as `Lst<Option<A>>`:
```c#
    var mt = Trans<MLst<Option<int>>, Lst<Option<int>>, MOption<int>, Option<int>, int>.Inst;

    var x = List(Some(1), Some(2), Some(3));
    var y = List(Some(1), Some(2), None);

    var totalx = mt.SumT(x);  // 6
    var totaly = mt.SumT(y);  // 0

    Option<Lst<int>> seqx = mt.Sequence(x); // Some(List(1, 2, 3))
    Option<Lst<int>> seqy = mt.Sequence(y); // None
```
Using `Bind` is a bit more heavyweight as I'm sure you can imagine (and that's why they're all wrapped up in extension methods!
```c#
    var u = mt.Bind<MOption<Lst<int>>, Option<Lst<int>>, MLst<int>, Lst<int>, int>(
            x, a => Some(a * 2));

    // u == List(Some(2), Some(4), Some(6)) 

    var v = mt.Bind<MOption<Lst<int>>, Option<Lst<int>>, MLst<int>, Lst<int>, int>(
            y, a => Some(a * 2));

    // v == List(Some(2), Some(4), None) 
```

**Comment by louthy** [comment]
Oh, from your original comment, this doesn't really make sense unless they're all promoted to sequence types:
```c#
var oa = Some(1);
var lb = List(2);
var oc = Some(3);

var r2 =
   from a in oa
   from b in lb
   from c in oc
   select a + b + c;
```
Because the outer type would be an `Option`.  I have had to make all of the core monadic types derive from `IEnumerable<A>` so they work with Json.NET.  And whilst that causes a few headaches, it will promote the above expression to an `IEnumerable<int>`, but if you always work with the same monadic type it doesn't.  That seems like a pretty useful feature.
