### ISSUE TITLE
[Opinion] add LiftA2, LiftA3, LiftA4 to some prelude types

### ISSUE THREAD

**Issue by jonschoning** [louthy/language-ext#189]
the implementation of these methods are fairly short but which removes boilerplate allowing expressions 
such as 
`apply(apply(map(a, curry(f)), b), c)`
   to simply be expressed as
`liftA3(f, a, b, c)`

of course each type (Either, Option, etc..) would need to provide their implementations.

**Comment by louthy** [comment]
@jonschoning This will probably be dealt with in V2 of lang-ext.  It will have full support for applicatives.

https://github.com/louthy/language-ext/blob/type-classes/LanguageExt.Core/TypeClasses/Applicative/Applicative.Prelude.cs

It also won't need implementations for Either, Option, etc.  (although I probably would add them to remove the inconvenience of the generic parameters).

**Comment by jonschoning** [comment]
I see. Thanks..

This is a side node, but looking at
```
        public static MB apply<MONADAB, MONADA, MONADB, MAB, MA, MB, A, B>(MAB x, MA y)
            where MONADAB : struct, Monad<MAB, Func<A, B>>
            where MONADA  : struct, Monad<MA, A>
            where MONADB  : struct, Monad<MB, B> =>
            default(MONADAB).Bind<MONADB, MB, B>(x, a =>
            default(MONADA ).Bind<MONADB, MB, B>(y, b =>
            default(MONADB ).Return(a(b))));
```
I see that using apply implies a Monad constraint.  This may work for those Applicatives which are also Monads, but it reverses the dependency.  Applicative should not require Monad; sometimes you cannot make something a Monad, but you can make something an Applicative (i.e. there are more Applicatives than Monads).  For example, AccValidation has a nice Applicative Instance but it cannot be made a Monad in any way that makes sense 

http://hackage.haskell.org/package/validation-0.5.4/docs/Data-Validation.html#t:AccValidation

**Comment by louthy** [comment]
@jonschoning Yep, I had a version that used an `Applicative` interface, but unfortunately the solution isn't quite as elegant as Haskell (or the C# monad version).  So I dropped it.  It was a pragmatic decision due to this being an ad-hoc polymorphic solution rather than a type-class and class-instance solution; and therefore any call to `apply` or its variants can have an ad-hoc `Bind` and `Return` implementation and can therefore support both monadic and applicative behaviour.

I may revisit this again at some point, the new API isn't fully locked down yet.

**Comment by jonschoning** [comment]
Ah, ok!
