### ISSUE TITLE
Hashing with IEqualityComparer?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#194]
Are there plans to allow Comparers in langauge-ext keyed data types?
Or are there reasons against this?

I'm looking for something to replace e.g.

`new System.Collections.Generic.HashSet<string>(StringComparer.OrdinalIgnoreCase)`

**Comment by louthy** [comment]
@StefanBertels I hadn't planned, but I cam offer a solution I'm sure.  What's the urgency on this?

I think what I'd want to do is use the new `Ord` ad-hoc polymorphic types to support this (rather than using `IComparer`).

The problem with using immutable types is that you need to get comparer in at the start, i.e.:  `HashSet<string>.Empty`.  But obviously that's currently a readonly static property to remove the need for that initial allocation.  The other way would be to pass an `Ord` in via the constructors:
```c#
    var set = HashSet(EqStringIgnoreCase.Inst, "one", "two", "three");
```
That works OK, but then you have a problem of type safety:
```c#
    var setA = HashSet(EqString.Inst, "one", "two", "three");
    var setB = HashSet(EqStringIgnoreCase.Inst, "One", "Two", "Three");
```
Both are sets of strings, but they behave differently.  The set functions: `Union`, `Intersect`, `==`, etc. are undefined.
So the real type-safe way to do this is to add the `Ord` to the generic arguments list:
```c#
    public struct HashSet<OrdA, A> : ...
        where OrdA : Ord<A>
    {
        ...
    }
```
You would declare like so:
```c#
    var setA = HashSet<EqString, string>("one", "two", "three");
    var setB = HashSet<EqStringIgnoreCase, string>("One", "Two", "Three");
```
They would be fundamentally different types, you couldn't intersect `setA` and `setB`.

I'd probably have to provide 
* `HashSet<A>`
* `HashSet<OrdA, A>`
* `Set<A>`
* `Set<OrdA, A>`
* `HashMap<K, A>`
* `HashMap<OrdK, K, A>`
* `Map<K, A>`
* `Map<OrdK, K, A>`

I am happy to do all of this, and if you need it soon then I'll start this evening.  You will need to be using version 2.0 though.

**Comment by louthy** [comment]
@StefanBertels This is now complete on `v2.0.3-alpha`.  
```c#
    var set = HashSet<EqStringOrdinalIgnoreCase, string>("one", "two", "three");

    Assert.True(set.Contains("one"));
    Assert.True(set.Contains("ONE"));

    Assert.True(set.Contains("two"));
    Assert.True(set.Contains("Two"));

    Assert.True(set.Contains("three"));
    Assert.True(set.Contains("thREE"));
```
As mentioned above there are four new types: `HashSet<EqA, A>`, `Set<OrdA, A>`, `HashMap<EqK, K, V>`, `Map<OrdK, K, V>`.  

The first argument should be the 'class instance'.  Which is a term stolen from Haskell.  Essentially it must be a `struct` that derives from a 'type class' (an interface in C#).  I know C# doesn't have type-classes and class-instances, but it's the easiest way to discuss this stuff (especially if you know a bit of Haskell already).

This is what the `Eq` type-class looks like:

```c# 
    public interface Eq<A>
    {
        /// <summary>
        /// Equality test
        /// </summary>
        /// <param name="x">The left hand side of the equality operation</param>
        /// <param name="y">The right hand side of the equality operation</param>
        /// <returns>True if x and y are equal</returns>
        bool Equals(A x, A y);

        /// <summary>
        /// Get the hash-code of the provided value
        /// </summary>
        /// <returns>Hash code of x</returns>
        int GetHashCode(A x);
    }
```
And this is the default string equality 'class instance':
```c#
    public struct EqString : Eq<string>
    {
        public static readonly EqString Inst = default(EqString);

        /// <summary>
        /// Equality test
        /// </summary>
        /// <param name="a">The left hand side of the equality operation</param>
        /// <param name="b">The right hand side of the equality operation</param>
        /// <returns>True if a and b are equal</returns>
        public bool Equals(string a, string b) { return a == b; }

        /// <summary>
        /// Get hash code of the value
        /// </summary>
        /// <param name="x">Value to get the hash code of</param>
        /// <returns>The hash code of x</returns>
        public int GetHashCode(string x) =>
            x == null ? 0 : x.GetHashCode();
    }
```
Because `EqString` is a `struct` the methods on it can be called like so:
```c#
    default(EqString).Equals("one", "two");
```
So by passing an `Eq<A>`, or `Ord<A>` as an argument to `Set`, `HashSet`, `Map`, `HashMap` and constraining it to be a `struct`, I can inject the ordering an equality functionality, with zero run-time cost (the `default(EqA)` gets optimised out in release builds and becomes a direct call).
```c#
    public struct Set<OrdA, A> :
        where OrdA : struct, Ord<A>
        ...
```
To your request for `StringComparer.OrdinalIgnoreCase`, I have added class-instances for `OrdinalIgnoreCase`, `Ordinal`, `CurrentCultureIgnoreCase`, and `CurrentCulture`.

```c#
    public struct EqStringOrdinalIgnoreCase : Eq<string>
    {
        public bool Equals(string a, string b) =>
            StringComparer.OrdinalIgnoreCase.Equals(a, b);

        public int GetHashCode(string x) =>
            StringComparer.OrdinalIgnoreCase.GetHashCode(x);
    }
```
One thing to note is that the resulting type-name is a bit long:
```c#
    Set<OrdStringOrdinalIgnoreCase, string> set;
    HashSet<EqStringOrdinalIgnoreCase, string> hashset;
```
There's nothing stopping you implementing your own class instances though.  Maybe if you have it standardised app-wide:

```c#
    public struct EqStr : Eq<string>
    {
        public bool Equals(string a, string b) =>
            StringComparer.OrdinalIgnoreCase.Equals(a, b);

        public int GetHashCode(string x) =>
            StringComparer.OrdinalIgnoreCase.GetHashCode(x);
    }
```
Then the type is a bit easier to manage:
```c#
    HashSet<EqStr, string> hashset;
```
One important aspect (which I mentioned in my post above) is that if you use different class-instances for equality and ordering, then the resulting types won't be compatible.  This takes the type-safety to the next level.
```c#
    var setA = HashSet<EqStringOrdinal, string>("one", "two", "three");
    var setB = HashSet<EqStringCurrentCulture, string>("one", "two", "three");

    // These lines won't compile, because the types aren't compatible.
    var x = setA == setB;        
    var y = setA.Intersect(setB);
```

**Comment by StefanBertels** [comment]
This is really great! Thank you for this good designed and fast solution.
