### ISSUE TITLE
Request TryParse method for JObject.Parse()

### ISSUE THREAD

**Issue by solvingJ** [louthy/language-ext#195]
I was surprised to find that Json.Net does not include any simple mechanism for evaluating a string to identify whether it is valid JSON or not without throwing an exception.  Thus, if you're in the business of parsing foreign JSON, you have to employ TryCatch as part of your business logic. 

While JOBject is not a primitive, nor is the library a native part of .NET, Json.Net does seem to be among most widely used modern libraries.  Also, parsing text to produce objects is a fairly low level operation, and similar in nature to the other parse methods. 

Hope to see it in a future version. Until then, I'm doing things like this (which don't feel great): 

```csharp
public static Result<dynamic> ParseJson(string inputMessage)
        {
            try
            {
                return (dynamic)JObject.Parse(inputMessage);
            }
            catch (Exception e)
            {
                return Result.Fail<dynamic>("Failed to Parse Input as JSON");
            }
            
        }
```

Note: the result class is just a container like optional from another library.

**Comment by louthy** [comment]
@solvingJ isn't this an issue for the JSON.net repo?

**Comment by solvingJ** [comment]
I just realized that I made a bit of an error in the title of this request.  I was meaning to request a functional parseJson method to go along with the others.  Sure, it would be good if Json.Net to implement TryParse but I would still prefer the parseJson in the context of this library. 

Does that make a bit more sense :)

**Comment by louthy** [comment]
Makes more sense now, yes :).  Unfortunately I don't want the additional dependency in the `Core` project (I've been turning myself inside out over the past few weeks trying to get the core types like `Option`, `Lst`, `Map`, etc. serialisable (by JSON.NET, which seems to struggle with the immutable structs) without Json.NET included.

By the way, you could use `Try` for your `ParseJson` implementation.
```c#
public static Try<dynamic> ParseJson(string inputMessage) =>
    (dynamic)JObject.Parse(inputMessage);
```
You then get all the benefits of the `Try` API.

**Comment by louthy** [comment]
@solvingJ Oh, and finally, I'm not sure if you're aware of the `JsonConvert.DeserializeObject<T>(...)` method?  I'm assuming that you used `JObject.Parse` because you're getting JSON in an unknown schema.  But just in case you're not aware `DeserializeObject<T>` will return `null` if the `string` can't be deserialised.
```c#
public static Option<T> ParseJson<T>(string inputMessage) => 
    JsonConvert.DeserializeObject<T>(inputMessage);
```
Then you can get a typed object back:
```c#
    var x = ParseJson<MyObject>(json);
```

**Comment by solvingJ** [comment]
Your suggestion of just using Try<dynamic> is perfect.  No need for the helper method.   I completely understand about the dependency.  

Your assumption about unknown schema is correct. 

Thanks again on the hard work you're doing for the library. I read something about your efforts on Json.Net and know it must be hard. Someday i hope to contribute.

**Comment by louthy** [comment]
>  I read something about your efforts on Json.NET and know it must be hard.

The main issue with it is that it seems to be a moving target.  I have fixed the serialisation issues twice before and found out last night that it's not working again.  My most recent attempt that has subsequently stopped working was by implementing `ISerializable`, which is the proper way to serialise types (when a serialiser can't auto-resolve).  It's bizarre, because the Json.NET documentation explicitly says it will use the `ISerializable` interface if it exists (and it worked for a short period - the unit tests said so ;) ).  

I realise Json.net has to perform some secret magic behind the scenes to make everything work (and my cases are a little unusual); but that also means it's a bit of a black box of uncertainty.  It could also be the moving target of .NET Core, and perhaps that's affecting Json.NET.  Whatever it is, it's frustrating - for me, and for people who rely on this library and it suddenly fails for no apparent reason.

For future reference for anyone that's reading this, I achieved the result I wanted by making everything derive from `IEnumerable<T>` and had to provide a constructor that takes an `IEnumerable<T>` which it uses to populate the types.  

* For `Option<T>` and `OptionUnsafe<T>` it's either an empty `IEnumerable<T>` or has exactly one element.
* For `Either<L, R>` and `EitherUnsafe<L, R>` I have created a DTO object called `EitherData<L, R>` and derived the types from `IEnumerable<EitherData<L,R>>`
* For `HashSet<T>`, `Set<T>`, `Que<T>`, `Stck<T>` they're just regular enumerables
* For `Map<K, V>` and `HashMap<K, V>` I had to change its derivation from `IEnumerable<IMapItem<K, R>>` to `IEnumerable<(K Key, V Value)>` because json.net couldn't handle an interface, and it also struggled with the concrete type `MapItem<K, V>`.  This is actually a nicer interface for when C#7 is officially live, but it does come with allocation costs.

Luckily it mostly makes sense for all of these types to be `IEnumerable`, although the `Either` implementation isn't super-nice.  Still, I'd prefer it to work than not, and hopefully the implementation doesn't 'leak' too much.

> Thanks again on the hard work you're doing for the library. 

My pleasure.  I'm glad people are finding it useful!

> Someday i hope to contribute.

No worries on that front.  But if you're ever considering it, then looking for parts of the API not covered by unit tests (and covering them) would be an easy way in.  The same for documentation.  I have a very limited amount of time, and I'll often prioritise features/bug-fixes over docs/tests.  Especially as writing functionally tends to lead to minimal errors.  But it definitely doesn't lead to zero errors!  So more coverage is always welcome.

**Comment by solvingJ** [comment]
This information seems to deserve it's own wiki page.  As you said, it's been a recurring issue, and Json.Net, .NET Core are not likely to "stop moving" any time soon.  In any case, those types of articles are helpful "warnings" to people who are new to using language-on-language frameworks about the nuances surrounding compatibility with third party.  My first language was Groovy which is written on top of Java, and there were nuances there as well.  Highlighting the known stumbling blocks is a good courtesy if you have the time. I think you do a good job.
