### ISSUE TITLE
[2.0] Is there (no) difference between SetItem and TrySetItems?

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#200]
Documentation differs, but I don't understand what is meant.
Implementations in HashSetInternal look identical. => ??

Maybe SetItem should throw an Exception when no existing value found?

BTW: I first thought SetItem would be working like AddOrUpdate. Maybe misleading name?
I associated it with something like hashset[key] = value (which is AddOrUpdate in .NET HashSet).
No more problem for me -- I know it now ;-) -- but... Just two alternative names: SetExistingItem (explicit, but long) oder UpdateItem (would match AddOr**Update**). Or just Update (there is no Add**Item**, too).

**Comment by louthy** [comment]
There was a bug in the `HashSet` implementation of `TrySetItem`.  Please get the latest nuget package.

`SetItem` is in line with other .NET collection types, in that it will try to set the item (which must already exist).  If the item is missing it throws an exception
`TrySetItem` attempts to set the item (which must already exist), and if it succeeds will return the new collection, otherwise returns `this`.
`Add` will add a new item.  If it already exists, will throw an exception.
`TryAdd` will add a new item if one doesn't already exist.  Otherwise returns `this`.
`AddOrUpdate` will add a new item if it's missing, otherwise it will `SetItem`.

The naming is consistent with other .NET types, so I don't think they're misleading ... well, no more so than the rest of the types.  But it's easier to learn one set of poorly named names, than many.  They do all have slightly different semantics.  So I don't necessarily think a single `Update` is good enough.

**Comment by StefanBertels** [comment]
Thank you for fixing this very fast!
