### ISSUE TITLE
failwith lazy vs. instant throw

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#203]
Hi Paul, thanks for releasing 2.0 as beta.

Is this difference intended? I mean: first one is lazy, but second (generic) one not.

```
        public static Action failwith(string message) =>
            () => { throw new Exception(message); };

        public static R failwith<R>(string message)
        {
            throw new Exception(message);
        }
```

I guess "yes" because of your comments and maybe the generic version cannot distinguish between Func and non-func usage?

**Comment by louthy** [comment]
They're both just convenience methods for different scenarios.  The first one is to make it easy to drop into a function that expects a Action delegate.  Like the side-effecting version of `Match` on `Option`.  

The second one was added to the library because `throw` in C# isn't an expression.  But from C#7 they will be.
