### ISSUE TITLE
Json serilization of Map different to Dictionary ("Item1", "Item2")

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#204]
Hi Paul,

you probably already thought about this, so might be "as intented".

I serialize a map to json (Newtonsoft.Json). This results in an json array of each map item and each map item is represented as Tuple(key, value) which means a json key-value-pair "Item1" => <key> and a json key-value-pair "Item2".

I think it would be better to have the same serialization like e.g. .NET Collection Dictionary which results in a "natural" json representation.

This would be
- a bit smaller in size
- I hope more long time stable (will "Item1"/"Item2" mapping be supported in C# for Tuple forever?)
- **compatible** (save Dictionary, load Map and vice versa)

I'm sure you favored Tuple for good reasons (very generic, especially for enumerators, new language features) but I'm concerned about storing or exchanging those json files.

Currently I think about manually adding my own serialization adapter but I guess this could be useful for other users, too. Are there options to generally change this in the library?

**Comment by louthy** [comment]
Unfortunately it isn't possible without compromising the types.  Json.NET doesn't play nice with the lang-ext types, and I've been through 3 or 4 different strategies to try and make it work (some worked until JSON.NET changed and broke it again).  So it has to be the way it is I'm afraid.  

It does have some benefits in that the data can then be consumed by a list type rather than a map.
