### ISSUE TITLE
How to use Option IfSome with async

### ISSUE THREAD

**Issue by feugen24** [louthy/language-ext#206]
Hi,
I have migrated some exiting code to async but in existing code i use IfSome and now I can't get back the task, but only Unit.
eg:            
```
            Option<int> opt = 4;
            Unit unit  = opt.IfSome(async (i) => await DoWork());
            unit = ifSome(opt, async x => await DoWork());
```

I saw there is a TryOptionAsync but no OptionAsync.

So how can I execute something only if there is a value?

**Comment by feugen24** [comment]
I did something like:
```
public static class OptExtensions
    {
        public static async Task IfSomeAsync<T>(this Option<T> opt, Func<T, Task> some)
        {
            await opt
                .Some(some)
                .None(Task.CompletedTask);
        }
    }
//and called it like:
 await opt.IfSomeAsync(async x => await DoWork());
```
Does this look ok?

Also, are the following equivalent?
```
 await opt.MatchAsync(async i => await DoWorkInt(), () => Task.FromResult(0));
//and
 await opt
                .Some(async i => await DoWorkInt())
                .None(() => Task.FromResult(0));
```
I'm assuming if some is executed, opt internal state will return Some ' Task<int>' result from None() call.

**Comment by louthy** [comment]
@feugen24 

> I saw there is a TryOptionAsync but no OptionAsync.

Until yesterday `Option` was strict only, and only stored a value, so running it asynchronously didn't make sense.  It is now possible to write: `Some(_ => ....)` as well as `Some(value)` which creates a lazy `Option` in the same way `Try` and `TryOption` are lazy (because they're delegates).  

However there are extensions for dealing with `Option<Task<A>>` or `Task<Option<A>>`, but it doesn't quite cover the whole `Option` API.  Below are the list of async variants.  What you could have done (because `IfSome` is the same as `Iter`) is call `IterAsync`.

```c#
    Task<B> MatchAsync<A, B>(this Option<A> ma, Func<A, Task<B>> Some, Func<B> None)
    Task<B> MatchAsync<A, B>(this Option<A> ma, Func<A, Task<B>> Some, Func<Task<B>> None)

    Task<Option<B>> MapAsync<A, B>(this Task<Option<A>> self, Func<A, Task<B>> map)
    Task<Option<B>> MapAsync<A, B>(this Option<Task<A>> self, Func<A, Task<B>> map)
    Task<Option<B>> MapAsync<A, B>(this Task<Option<A>> self, Func<A, B> map)
    Task<Option<B>> MapAsync<A, B>(this Option<Task<A>> self, Func<A, B> map)

    Task<Option<B>> BindAsync<A, B>(this Option<A> self, Func<A, Task<Option<B>>> bind)
    Task<Option<B>> BindAsync<A, B>(this Task<Option<A>> self, Func<A, Task<Option<B>>> bind)
    Task<Option<B>> BindAsync<A, B>(this Task<Option<A>> self, Func<A, Option<B>> bind)
    Task<Option<B>> BindAsync<A, B>(this Option<Task<A>> self, Func<A, Option<B>> bind)
    Task<Option<B>> BindAsync<A, B>(this Option<Task<A>> self, Func<A, Task<Option<B>>> bind)

    Task<Unit> IterAsync<A>(this Task<Option<A>> self, Action<A> Some)
    Task<Unit> IterAsync<A>(this Option<Task<A>> self, Action<A> Some)

    Task<int> CountAsync<A>(this Task<Option<A>> self)

    Task<S> FoldAsync<A, S>(this Task<Option<A>> self, S state, Func<S, A, S> folder)
    Task<S> FoldAsync<A, S>(this Option<Task<A>> self, S state, Func<S, A, S> folder)

    Task<bool> ForAllAsync<A>(this Task<Option<A>> self, Func<A, bool> pred)
    Task<bool> ForAllAsync<A>(this Option<Task<A>> self, Func<A, bool> pred)

    Task<bool> ExistsAsync<A>(this Task<Option<A>> self, Func<A, bool> pred)
    Task<bool> ExistsAsync<A>(this Option<Task<A>> self, Func<A, bool> pred)
```

> Does this look ok?
> Also, are the following equivalent?

Yes it looks OK, and they are equivalent. (apart from one returns a value and the other it untyped).  

I will get to the `Option` API soon and give it the same async coverage at `Try` and `TryOption`, but if there's anything you'd like to see in there sooner, please let me know.

**Comment by louthy** [comment]
@feugen24 

`v2.0.40` on nu-get now has an `OptionAsync<A>` type.

From the example in your question you just need to call `ToAsync()` on the `Option`, which converts it to an `OptionAsync`:
```c#
      Option<int> opt = 4;
      Unit unit = await opt.ToAsync().IfSome(i => DoWork());
```
The full `Option` API is available for `OptionAsync`, so you can do any operation asynchronously.  There are also multiple variants for dealing with delegates that may or may not return a `Task` (for example `Map(Func<A, B>)` and `Map(Func<A, Task<B>>)`

You can also construct `OptionAsync` directly:
```c#
        var ma = SomeAsync(_ => 10);
        var mb = SomeAsync(_ => 20);

        var mr = from a in ma
                 from b in mb
                 select a + b;

        Assert.True(await mr.IfNone(0) == 10);
```


Eventually I will put `Async` suffixed variants to the `Option` type (so you won't need to call `ToAsync`), but this turned out to be a bigger change than I expected and I've run out of time to do much more.

**Comment by feugen24** [comment]
Not sure what to say about OptionAsync, typically developers are used with .CallThisAsync() like most .net libraries, so .IfSomeAsync looks better than .ToAsync().IfSome(). Also I thinks OptionAsync implementation has some issues.

I wrote some tests:

```
Console.WriteLine("OptionAsync");
            OptionAsync<int> optAsync = Some(4).ToAsync();
            var tskOptionAsync =  optAsync.IfSome(async (i) => 
            {
                var x = DoWork();
                Tasks.Add(x);//Tasks is a static list of tasks.
                Console.WriteLine($"Inner id {x.Id}");
                await x;
            });
            Console.WriteLine($"Outer id {tskOptionAsync.Id}");
            Tasks.Add(tskOptionAsync);
            await tskOptionAsync;

            WriteTaskStatuses();

            Console.WriteLine();
            Console.WriteLine("Option.IfSomeAsync");
            
            Tasks.Clear();
            Option<int> opt = 4;

            var tskIfSomeAsync = opt.IfSomeAsync(async (i) =>
            {
                var x = DoWork();
                Tasks.Add(x);
                Console.WriteLine($"Inner id {x.Id}");
                await x;
            });
            Console.WriteLine($"Outer id {tskIfSomeAsync.Id}");
            Tasks.Add(tskIfSomeAsync);
            await tskIfSomeAsync;
            WriteTaskStatuses();
```

and the output:
```

OptionAsync
Outer id 2
Inner id 7
Tasks:2 is RanToCompletion
Tasks:7 is WaitingForActivation

Option.IfSomeAsync
Inner id 12
Outer id 16
Tasks:12 is RanToCompletion
Tasks:16 is RanToCompletion
```

**Comment by louthy** [comment]
> Not sure what to say about OptionAsync, typically developers are used with .CallThisAsync() like most .net libraries, so .IfSomeAsync looks better than .ToAsync().IfSome().

Read my last sentence.

**Comment by feugen24** [comment]
:)..i missed that

**Comment by louthy** [comment]
> Tasks:2 is RanToCompletion
> Tasks:7 is WaitingForActivation

@feugen24 This issue has been fixed.  Because `ifSome` needs to return `unit`, I needed to transform `Func<A, Task>` into `Task<Unit>`.  See below:
```c#
        public static Task<Unit> ifSomeAsync<OPT, OA, A>(OA opt, Func<A, Task> f)
            where OPT : struct, OptionalAsync<OA, A> =>
            default(OPT).MatchAsync(opt, a => Task.Run(() => { f(a); return unit; }) , noneIgnoreF);
```
Basically the invocation of the inner `f(a)` wasn't being awaited, and so was returning immediately.  It now looks like this and does as you'd expect. 
```c#
        public static Task<Unit> ifSomeAsync<OPT, OA, A>(OA opt, Func<A, Task> f)
            where OPT : struct, OptionalAsync<OA, A> =>
            default(OPT).MatchAsync(opt, a => Task.Run(async () => { await f(a); return unit; }) , noneIgnoreF);
```
I've made a few other minor fixes.

**Comment by louthy** [comment]
`v2.0.42`

I've now added `*Async` extensions for `Option` and `Task<Option>` which promotes the type to an `OptionAsync`. 

e.g.
```c#
        // Option -> OptionAsync

        var mc = Some(10).MatchAsync(
            Some: x => Task.FromResult(x * 10),
            None: () => 0);

        Assert.True(await mc == 100);

        Option<int> opt = 4;
        Unit _ = await opt.IfSomeAsync(i => DoWork());

        // Task<Option> -> OptionAsync

        var mc = Task.FromResult(Some(10)).MatchAsync(
            Some: x => Task.FromResult(x * 10),
            None: () => 0
        );

        Assert.True(await mc == 100);
```

* [Option extensions](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Option.Extensions.Async.cs)

* [Task<Option> extensions](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Option/Task.Option.Extensions.cs)

**Comment by feugen24** [comment]
It works but it looks like the implementation has issues:
```
// Func<A, Task> f
Task.Run(() => { f(a); return unit; })
```

Here it looks like instead of 'await'-ing for the task you allocate/block a threadpool thread that waits, actually bypassing the utility of async.

[See here](http://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-using.html)

**Comment by louthy** [comment]
@feugen24 

You're right.  Had a bit of a brain freeze there.  Found a couple of others too, so fixed them as well.

New version on nu-get `v2.0.44`

**Comment by feugen24** [comment]
Thanks for the changes, I will use latest once it's out of beta.
