### ISSUE TITLE
LanguageExt.Trans and Option<Map<string,string>>

### ISSUE THREAD

**Issue by NickDarvey** [louthy/language-ext#212]
Hi Paul,

I'm having some trouble getting access to `.MapT()` for the data structure I'm using: `Option<Map<string,string>>`. I'd like to be able to map the values (of the Map<>) to a new value.
Is this possible? Is my `using` statement wrong? 

```c#
using static LanguageExt.Trans<LanguageExt.ClassInstances.MOption<LanguageExt.Map<string, string>>, LanguageExt.Option<LanguageExt.Map<string, string>>, LanguageExt.ClassInstances.MMap<string, string>, LanguageExt.Map<string, string>, string>;
```

Thanks,
Nick

**Comment by louthy** [comment]
@NickDarvey  `Map` (the type) isn't currently supported in the _transformer_ system.  So `Map<K, InnerMonad<A>>` and `OuterMonad<Map<K, A>>`.  The reason for this is that it can't support `Bind` and therefore can't be a monad.  The old system had dummy functions in there for `Bind` (and `SelectMany`) which threw exceptions.  The new system uses the `Trans` type which requires that the inner and outer types are monadic (using the new type-class system, which enforces constraints which the old system didn't).  

Unfortunately because the transformer system is an all or nothing affair at the moment, I can't selectively pick which functions each type implements (this will be improved), and so `Map` isn't part of the generated `Trans` extension methods.  

But because they are all just extension methods, so you can add your own trivially:
```c#
    public static Option<Map<K, B>> MapT<K, A, B>(this Option<Map<K, A>> ma, Func<A, B> f) =>
        ma.Map(a => a.Map(f));
```

**Comment by NickDarvey** [comment]
Ahah! That makes sense, thank you for explaining it.
