### ISSUE TITLE
Currying / Partial Evaluation

### ISSUE THREAD

**Issue by KodrAus** [louthy/language-ext#23]
I have a super simple partial function execution example written in C# 5:

```
	public static Func<TOut> fun<TIn, TOut>(Func<TIn, TOut> func, TIn arg)
	{
		return () => func(arg);
	}
	public static Func<TIn, TOut> fun<TIn, TOut>(Func<Func<TIn, TOut>, TIn, TOut> func, Func<TIn, TOut> arg)
	{
		return x => func(arg, x);
	}
	public static Func<TIn2, TOut> fun<TIn1, TIn2, TOut>(Func<TIn1, TIn2, TOut> func, TIn1 arg)
	{
		return x => func(arg, x);
	}

	static Func<int, int, Tuple<int, int>> tuple = (x, y) => new Tuple<int, int>(x, y);

	void Example()
	{
		var add = fun((f, x) => f(x), (Tuple<int, int> x) => x.Item1 + x.Item2);
		var addthree = fun((Func<Tuple<int, int>, int> f, int x) => f(tuple(x, 3)), add);

		var five = add(tuple(2, 3));
		var alsofive = addthree(2);
	}
```

Do you reckon it's worth cleaning up (I'd like to try and imply those generic args as much as possible) and including in the library?

**Comment by louthy** [comment]
Hi @KodrAus - Not sure I entirely follow your examples, but I have added additional functions to the `Prelude` called `curry` and `par` for currying and partial application respectively.  You will need to build from source to use it because I'm not going to be doing a release just yet as I have been making some large changes to the `SelectMany` binding.

Anyway, usage is thus:

```C#
    var add = curry((int x, int y) => x + y);

    var res = add(2)(2);
```
You can also create a partially applied function using the `curry` function:
```C#
    var add15 = curry((int x, int y, int z) => x + y + z)(10)(5);
    var res = add15(1);
```
You can do this for functions up to 7 arguments in length.  Obviously it gets a bit unwieldy if you're writing this:
```C#
    var add = curry((int a, int b, int c, int d, int e, int f, int g) 
        => a + b + c + d + e + f + g);

    var res = add(1)(2)(3)(4)(5)(6)(7);
```
So there's a partial application function called `par`.  It will allow functions of up to 7 parameters, but it also allows you to specify up to N-1 arguments:

```C#
    var add10 = par((int a, int b) => a + b, 10);
    var res = add10(1);

    var add30 = par((int a, int b, int c, int d, int e) 
        => a + b + c + d + e, 10, 20);

    res = add30(1)(2)(3);
```

If you only need to partially apply all but the last one or two arguments in a function then using `par` will be more efficient than currying with `curry` and then partially applying.   

Anyway, I hope that helps.

**Comment by KodrAus** [comment]
Looks good, I hadn't seen that on the readme. So you're supporting currying by supplying an explicit function for each possible number of arguments, up to a total of 7?

The approach I'd tried to take was to support currying of functions up to any length (at least to the max supported arguments of Tuple<>, which is 16?), but yours is much easier on the eyes.

**Comment by louthy** [comment]
@KodrAus 

> I hadn't seen that on the readme. 

I just wrote it based on your request ;)

Yes, there's an override for each number of args a function might have.  It's just a bit of upfront typing for a prettier end result.  If you need more than 7 parameters for a function then I think you could argue that's a bit of a code smell and you'd benefit from simplifying the interface / wrapping up values into records.

I mostly chose 7 as the number because I implemented the `tuple` function first (now `Tuple` in the latest version); I based it on `Tuple.Create(...)`, which has multiple overrides up to 7 items.  However it has a final override that takes an 8th argument.  The 8th argument is another `Tuple`, so that might be where you got the 16 number from?  Or it could be that `Func` itself can take up to 15 args+1 return type.

If you feel 7 isn't enough I can add some more?

**Comment by KodrAus** [comment]
I pretty well agree that 7 arguments should be heaps in most circumstances, I'm just thinking out loud about the different approaches, I was basing mine off what I've seen of compiled FSharp. 

I had actually just assumed Tuple took 16 because of Func's 15+1 generic args.

**Comment by louthy** [comment]
@KodrAus 

I decided to change the `par` function to just return a single function rather than a curried function.  I feel that's closer to the real definition of partial.  

So instead of this:

```C#
var four = par((int a, int b, int c, int d) => a  + b + c + d, 10, 20);

var res = four(1)(1);
```
You would instead do:
```C#
var res = four(1,1);
```
If you want the previous behaviour you can `curry` the result of `par`:

```C#
var four = curry(par((int a, int b, int c, int d) => a  + b + c + d, 10, 20));

var res = four(1)(1);
```

I have also added overrides for up to 10 generic arguments + 1 return.  My eyes start to go funny when I do any more!

**Comment by KodrAus** [comment]
That's really nice, I'll have to have a play with it and see what I come out with
