### ISSUE TITLE
Why do you recommend against use of Some as null validation check?

### ISSUE THREAD

**Issue by vrobinson** [louthy/language-ext#230]
In your documentation, after spending some amount of time detailing the null problem and how Option and Some help to overcome this problem you conclude the section by saying:

> NOTE: Since writing this library I have come to the opinion that Some<T> isn't that useful. It's much better to protect 'everything else' using Option<T> and immutable data structures. It doesn't fix the argument null checks unfortunately. But perhaps using a contracts library would be better.

I agree that null is a big problem but Some<T> seems like an elegant solution. It certainly feels better than this kind of nonsense being scattered throughout code:

`if (value != null) throw new ArgumentNullException(nameof(value));`

I get that Some isn't 100% (the uninitialized member you point out as well as developer awareness and discipline to use Some appropriately) but neither is the above code. I think the ease of inserting a Some would make it more likely that a developer would not leave out a null check as compared with the manual version above.

Given the currently uncertain future of code contracts as an alternative:
[https://github.com/Microsoft/CodeContracts/issues/409](url)

and until we get compiler support (in C# 8 perhaps?) Some seems like an elegant improvement.

So I'm very curious as to why you suggest taking an alternate route. What am I missing about how using Option<T> and immutable data structures on 'everything else' resolves this problem? What about interacting with other .NET code that returns reference types? Could you please elaborate?

**Comment by jeremysmith1** [comment]
One thing I have seen using this library is use cases that happen like this current issue that is open:
https://github.com/louthy/language-ext/issues/229

Because you can have nullable objects in C#, you are not completely protected from null in the use of Some. In other languages, such as Erlang, where null is not really a thing. 

I would think to work with this library and using functional concepts, you would want to avoid nullable types. But I do not see a way of guarding against its use. Similar how you can make objects in Fsharp, but that would be working against the language.

**Comment by louthy** [comment]
@vrobinson Because `Some` is a `struct` there are a number of ways that it can be created without being initialised:
```c#
    var x = new Some<int>();
    var y = new Some<int>[10];
    var z = default(Some<int>);

    class Foo
    {
        public Some<int> Bar;
    }
```
And because structs don't support co-variance it makes it awkward to use with generics.  So it can often get in the way.
