### ISSUE TITLE
Retrieve error or value from Either safely

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#231]
I'm having trouble retrieving the contents of an `Either` and passing them into another object. I understand the 'IfRight'/'IfLeft' and the safety reasons for it, but its causing me some issues. I'm sure theres a better way...

```
// Vin must be 17 characters, so if its not, I want to be forced to return an `Error`
//I've implemented a `Vin.Create` that does the check and returns an Either<Error, Vin>
var vinString = "SomeString";
Either<Error, Vin> eitherVin = Vin.Create(vinString);

//The trouble comes when I need to return another object type
if (eitherVin.IsRight)
{
    //I know this is terrible because its ugly and gets around the safety
    Vin _vin = null;
    eitherVin.IfRight(v => _vin = v);
    return new Vehicle()
    {
        Vin = _vin,
        StockNumber = sn,
    };
}
else
{
    Error err = null;
    eitherVin.IfLeft(e => err = e);
    return err;
}
//return type :: Either<Error, Vehicle>
```

I've also have an issue that seems similar, where I'm trying to merge two Lefts. Not sure if this is totally unrelated though.

```
Either<Error, Unit> ret1= call1();
Either<Error, Unit> ret2= call2();

if (ret1.IsLeft || ret2.IsLeft)
{
    return new Error("Failure") { Errors = ret1.LeftToList().Append(ret2.LeftToList()) };
}
else
{
    return new Unit();
}
```

I've run into this over and over now because I'm using lots of either's to track errors, and can't figure it out. It seems like there are a lot of helpers associated with `Option`, like match, but match doesn't seem to su I guess I'd want to use a monadic transform (is that the right term?) like `Bind`, but still green at this....

Any thoughts would be greatly appreciated.

**Comment by louthy** [comment]
@gregberns Hi Greg, you do seem to be tying yourself up in knots here.  The first example can be done with `Map`:
```c#
    static Either<Error, Vehicle> GetVehicleFromVin(string vinString, int stockNumber) =>
        Vin.Create(vinString).Map(vin => new Vehicle(vin, stockNumber));
```
What `Map` does is to only run the lambda provided if the `Either` is in ` Right` state.  So If `Vin.Create` returns an `Error` then the `new Vehicle(...)` code won't execute and the `Error` will propagate.  

You could also use `MapLeft` if you wanted to add some extra context to your error:
```c#
    Vin.Create(vinString)
       .Map(vin => new Vehicle(vin, stockNumber))
       .MapLeft(err =>  Error.New($"{err.Value} for stock-number: {stockNumber}"));
```
`MapLeft` only runs when the `Either` is in `Left` state.

With your second example you could make use of `Partition` which runs a sequence of Eithers and splits them into two sequences of Lefts and Rights:
```c#
    public static Either<Seq<Error>, Unit> Test()
    {
        Either<Error, Unit> ret1 = call1();
        Either<Error, Unit> ret2 = call2();

        var (lefts, rights) = Seq(ret1, ret2).Partition();

        return lefts.IsEmpty
            ? Right<Seq<Error>, Unit>(unit)
            : Left<Seq<Error>, Unit>(lefts);
    }
```
> Get the latest build from nu-get, as I've just made it work with `ValueTuple` and `Seq` (before it just supported `Tuple` and `IEnumerable`).

Obviously I've set it up to return `Seq<Error>`, but you could just return `new Error(lefts)` to wrap up the errors.

A lot of the point of types like `Option` and `Either` are to avoid the mess of `if then else`, they deal with that for you.  So if you ever find yourself using `if(either.IsLeft)` or similar, then you're probably doing it wrong.

The general rules are:
* If you need to get a concrete value, use `Match`
```c#
    int x = either.Match(
        Right: value => value * 2,
        Left: error => 0
    );
```
* If you want to provide functionality for the 'success' path (i.e. an error ends the computation, but positive results continue it), use `Map`.
```c#
   Either<Error, int> nextEither = either.Map(value => value * 2);
```
* If you need to flip from the success path to the fail path, use `Bind`.
```c#
   Either<Error, int> nextEither = either.Bind(
        value => value == 0 
            ? Left<Error, int>(Error.New("Value can't be zero"))
            : Right<Error, int>(value * 2)
    );
```
* If you need to work with more than one `Either` at a time, use LINQ

A series of `Map` or `Bind` calls can be seen as logical AND.  Which can also be represented using LINQ:
```c#
    from x in call1()
    from y in call2()
    select x + y;
```
^^^ `x+ y` only run if `call1` AND `call2` return `Right(int)`.

You can also use the `||` operator for _left coalescing_:
```c#
    Either<Error, int> res = eitherA || eitherB || eitherC;
```
The first `Either` to be in a `Right` state is returned.

Generally it's best to stay in context rather than trying to extract the values with `Match` or the approach you were using.

**Comment by gregberns** [comment]
@louthy Thats awesome, thanks for the fantastic feedback. I got a ton cleaned up based on your recommendations. Thanks again for a great project like this, its so helpful when trying to integrate FP into everyday work without having to switch languages.

**Comment by trbngr** [comment]
It seems that `Left` cases aren't working properly.

```


        public Task<Either<Exception, int>> Issue207_3() =>
            from us in Left<Exception, ADUser>(new Exception("fail")).AsTask()
            from mu in createUserMapping(us).AsTask()
            from id in addUser(mu)
            select id;

        public Task<Either<Exception, int>> Issue207_4() =>
            Left<Exception, ADUser>(new Exception("fail")).AsTask()
                .BindT(createUserMapping)
                .BindT(addUser);
```
both throw `LanguageExt.BottomException : Value is in a bottom state and therefore not valid.  This can happen when the value was filtered and the predicate returned false and there was no valid state the value could be in.  If you are going to use the type in a filter you should check if the IsBottom flag is set before use.  This can also happen if the struct wasn't initialised properly and then used.
`

**Comment by louthy** [comment]
@trbngr Hi Chris, what are you trying to achieve?  Perhaps I can help on a more specific question.

The reason it reports a `BottomException` in those examples is because it's doing a _trasnformer_ bind operation, which is a generalised system for monadic binding on two nested monads (in this case `Task<Either<L, R>>`).  When the inner monad bind fails (which it will do because of the initial `Left` state), then so does the outer bind operation.  The outer monad (`Task<...>`) isn't aware of the `Left` type being `Exception` so all it can do is fail with `BottomException` because the `Task` is now in a failed state. 

So essentially you're getting a general failure response from the `Task`.
