### ISSUE TITLE
Option JSON deserialization failing

### ISSUE THREAD

**Issue by vkirienko** [louthy/language-ext#245]
Hi, it seems that JSON deserialization fails for Option. 

{"Unexpected character encountered while parsing value: [. Path 'Id2', line 1, position 15."}

````
using LanguageExt;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;

namespace Fortress.FACT.Tests
{
    [TestClass]
    public class TopHatTests
    {
        public sealed class TopHat
        {
            public TopHat(int id, int? id2)
            {
                Id = id;
                Id2 = Prelude.Optional(id2);
            }

            public int Id { get; set; }
            public Option<int> Id2 { get; set; }
        }

        [TestMethod]
        public void TopHatSerialisationTest()
        {
            var t1 = new TopHat(1, 1416);

            var str = JsonConvert.SerializeObject(t1);

            var t2 = JsonConvert.DeserializeObject<TopHat>(str);

            Assert.IsTrue(t2 == t1);
        }
    }
}

**Comment by louthy** [comment]
@vkirienko This looks like a Json.NET bug.  The only way I've managed to make `Option` serialise with Json.NET is to provide a constructor that takes an `IEnumerable<A>` and then derive `Option<A>` from `IEnumerable<A>`.  That means Json.NET serialises the `Option<A>` as `[value]` for `Some(value)` or `[]` for `None`.  

I have [unit tests](https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/SerialisationTests.cs#L76) that shows this working.  So I can only assume that there is something wrong in Json.NET that causes it to fail in this scenario.  

I have tried removing the `ISerializable` implementation from `Option` to see if it was confusing Json.NET, but it doesn't seem to make any difference.  The fact that it appears to be a parsing error would tell me that it's best to raise an issue on the Json.NET repo for investigation.

**Comment by louthy** [comment]
@vkirienko So I did a bit more digging, and have found your issue.

This works:
```c#
public class TopHatTests
{
    public class TopHat
    {
        public TopHat(int one, int? two)
        {
            Id = one;
            Id2 = Prelude.Optional(two);
        }

        public int Id { get; set; }
        public Option<int> Id2 { get; set; }
    }

    [Fact]
    public void TopHatSerialisationTest()
    {
        var t1 = new TopHat(1, 1416);
        var str = JsonConvert.SerializeObject(t1);
        var t2 = JsonConvert.DeserializeObject<TopHat>(str);

        //Assert.True(t2 == t1);
    }
}
```
The reason it works is because I changed the name of the arguments to `TopHat` to `one` and `two`.  Previously they were `id` and `id2`.  Json.NET will look for constructors that have the exact same names as the fields and properties in the type.  So because you have `Id` and `Id2` and a constructor that takes `id` and `id2` it tried to deserialise the JSON to `int` and `int?`.  But `Id2`'s type isn't compatible with `id2` (which still seems like a Json.NET bug to me).  

So I think it's trying to parse an `int?`, but the string has `[1416]` in it.

You could implement `TopHat` like this:
```c#
    public class TopHat
    {
        public TopHat(int id, Option<int> id2)
        {
            Id = id;
            Id2 = id2;
        }

        public int Id { get; set; }
        public Option<int> Id2 { get; set; }
    }
```
And it would work as expected.

NOTE: I commented out `Assert.True(t2 == t1);` because you don't have any equality testing implemented, so it will never work.  If you want structural equality testing then you can derive from the new `Record` type and provide a default serialisation constructor:
```c#
    public class TopHat : Record<TopHat>
    {
        public TopHat(int id, Option<int> id2)
        {
            Id = id;
            Id2 = id2;
        }

        public TopHat(SerializationInfo info, StreamingContext context) : base(info, context)
        { }

        public int Id { get; set; }
        public Option<int> Id2 { get; set; }
    }
```
Then `Assert.True(t2 == t1);` will work perfectly.

**Comment by vkirienko** [comment]
Thanks a lot, Paul! That's very interesting. I did not know about this Json.NET behavior. I'll it try tomorrow in the original project.

As for Assert you are absolutely correct. My original TopHat class has equality methods implemented so I just forgot to correct Assert in stripped down example.

**Comment by louthy** [comment]
> LanguageExt to v2.0

The serialisation of `Option` changed from `v1` to `v2`.  With different versions of Json.NET it variously worked or not.  The most robust solution I have found was to serialise it to an IEnumerable as mentioned above.  So previously it would have serialised a value that was compatible with `int?`, but later versions are not.  I needed to bite the bullet though, because Json.NET has been a massive thorn in my side ... you can probably imagine my horror when I saw the title of this issue! 

I think it's pretty stable now though!
