### ISSUE TITLE
Understanding SelectMany and Eithers

### ISSUE THREAD

**Issue by gregberns** [louthy/language-ext#253]
I've been working more with Linq's comprehension syntax more and its really nice working with option/either types. I think I better understand how its working in that regard.

My question, I think, is how/can you combine the select and select many syntax? (It is very possible I am trying to do too much in one go)

So I have a list of things and I need to process each item in the list by passing it into two functions which will each return eithers. The problem is that when the either is returned `from s in es(i)` the `s` is of type `EitherData<string, int>` and not `int`.

Essentially I have a Map, Bind and Project going on here, and I'm not totally sure I've wrapped my head around it, but I'm also not sure this is possible. Maybe there's scope for extending this article??

https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-What-is-LINQ-really%3F

Any help would be appreciated.

```
IEnumerable<int> list = new List<int>() { 1, 2, 3 };
Func<int, Either<string, int>> es = (i) => i;
Func<int, Either<string, int>> et = (i) => i;

var r = from i in list
        from s in es(i)   //**  s is EitherData<string, int>
        from t in et(i)   //**  t is EitherData<string, int>
        select s + t;     // compiler error

//same issue
list.SelectMany(b => es(b), (s, t) => s + t);

```

**Comment by louthy** [comment]
@gregberns Hi Greg, this is a _lifting_ discussion.  You have incompatible types in your LINQ expression.  LINQ expressions are C#'s equivalent to Haskell's `do` notation.  The idea is that for the whole expression each `from ` sub-expression must have the same _outer type_.  So for `Option<A>` the outer-type is `Option<>` and the inner type is `A`.

In the first line of your expression you have:
```c#
    from i in list
```
`list` is of type `List<int>`, the base monadic type is `IEnumerable<int>`.  

In your second line you have:
```
    from s in es(i)
```
`es(i)` returns an `Either<string, int>`, which, although a monad, is not of the same type as `IEnumerable<int>`.  However `Either<string, int>` derives from `IEnumerable<EitherData<string, int>>`.  This is actually to facilitate serialisation/deserialisation with Json.NET;  normally an `IEnumerable<>` wouldn't be compatible with an `Either<>`.

`EitherData` isn't much use to you here, because it's not a monadic type, it's just a data type.  So you want to find a way of either:

1) Making every item in the expression have the same outer type, or
2) Build a sub-expression that allows you to switch _context_ (the context being the outer type).

This is the sub-expression approach, it's good because the original expression can easily be seen as having 'two halves': the first half in the `IEnumerable<>` context, and the second half in the `Either<>` context.
```c#
    var r = from i in list
            select from s in es(i)
                   from t in et(i)
                   select s + t;
```
It can be written fluently as:
```
    list.Map(i => es(i).Bind(s => et(i).Bind(t => s + t)));
```

> Its best to use `Bind` if you're going to use the fluent style, the version of `SelectMany` implemented for the various monadic types are a bit bulky for human consumption and are merely there to facilitate LINQ

The other approach is _Making every item in the expression have the same outer type_.  Now that means we need to make the `IEnumerable<>` and `Either<>` types match.  So for the `list` data we want a `IEnumerable<Either<string, int>>`, and for the `es()` and `et()` functions we want them to return the same (or be lifted manually - which is what I'll do).
```c#
    var eitherList = list.Map(x => Right<string, int>(x));

    var r2 = from i in eitherList
             from s in List(es(i))
             from t in List(et(i))
             select s + t;
```
The result of that is you get an `IEnumerable<Either<string, int>>`, which is to be expected, because that's the monadic type for the whole expression.  You can then extract the values:
```c#
// Get all right values - IEnumerable<int>
var rights = r2.Rights();

// Get all left values - IEnumerable<string>
var lefts = r2.Lefts();

// Get a tuple of the lefts and the right values (IEnumerable<string>, IEnumerable<int>)
var (lefts, rights) = r2.Partition();

// Flip the type to an Either<string, IEnumerable<int>> - which will return either the first Left or
// an IEnumerable<int> of Rights.
var succ = r2.Sequence();
```

**Comment by louthy** [comment]
@gregberns Oh, and btw, if you're not actually worried about the `Left` part of the result of `es()` and `et()`, and want the `Either` to be converted to an `IEnumerable<Right>`, then you can wrap them in `Seq(either)`:
```c#
IEnumerable<int> list = new List<int>() { 1, 2, 3 };
Func<int, Either<string, int>> es = (i) => i;
Func<int, Either<string, int>> et = (i) => i;

var r = from i in list
        from s in Seq(es(i))
        from t in Seq(et(i))
        select s + t;     
```
That will result in an `IEnumerable<int>`.  If any of the `Either`s are in a `Left` state then the `IEnumerable<int>` will be empty.

**Comment by gregberns** [comment]
> the sub-expression must have the same outer type

Ah! That makes so much more sense now. Using the sub-expression (#1) is what I was looking for, that really makes it quite easy to understand. I never really liked the comprehension syntax with lists, but with monads its brilliant. Especially in this case the fluent syntax gets pretty nasty.

The 'Seq' suggestion is interesting. In this problem I'm battling with what to do with the Eithers. I want to log them (and I keep flipping on where to do that: right after the failure or after the list of items is processed) but I'm not sure if the failure needs to be exposed out of that area of the code. The `es` and `et` are actually network calls that return `Either<Error, Unit>`.

As always, thanks for the help.
