### ISSUE TITLE
Request: Parser Combinators

### ISSUE THREAD

**Issue by ricardopieper** [louthy/language-ext#26]
Hello again!

I know very little about parsers, but what I know is that they look good in functional programming, but not so much in imperative programming (like most things do). I have adventured myself into compiler theory, and sometimes I go back to that subject. While it's interesting, I have little time (and sometimes i'm just lazy) and have to learn it all again, from scratch. 

Enough of me, let's talk about this parser thing.

Since LanguageExt is to become a functional hub for C#, do you think about creating a parser combinator library?

I know that there are C# parser combinators out there, but the real fun is to reinvent the weel :smile:

I took a look at this link: http://www.codeproject.com/Articles/235221/Monadic-Parsing-in-Fsharp

And tried to convert some of those to C#.

Here is some of what I've achieved. I'm using some LanguageExt functions.

        //could be made more general by providing a stream type, not only chars. But... 
        public delegate IEnumerable<Tuple<T, IEnumerable<char>>> Parser<T>(IEnumerable<char> str);
        public static Parser<T> MReturn<T>(T result) => new Parser<T>(str => list(tuple(result, str)));

        public static Parser<R> Bind<T, R>(this Parser<T> p, Func<T, Parser<R>> f) =>
            new Parser<R>(str =>
                p(str).SelectMany(tuple =>
                    tuple.Map((result, restChars) =>
                        f(result)(restChars))));

        public static Parser<T> Lambda<T>() => new Parser<T>(str => empty<Tuple<T, IEnumerable<char>>>());

        public static Parser<char> Satisfies(Predicate<char> condition) =>
            Bind(Item, (char c) => condition(c) ? MReturn(c) : Lambda<char>());

        public static Parser<char> IsDigit => Satisfies(c => Char.IsDigit(c));

        public static Parser<IEnumerable<T>> Many0<T>(this Parser<T> parser) => Choose(Many1(parser), MReturn(empty<T>()));

        public static Parser<IEnumerable<T>> Many1<T>(this Parser<T> parser) =>
             Bind(parser, (r1) => Bind(Many0(parser), (r2) => MReturn(r1.cons(r2))));

        public static Parser<Int64> Integer => Many1(IsDigit)
            .Bind((digits) => 
                MReturn(
                    Convert.ToInt64( //could use parseInt and match the option value, but if it reaches this point with a wrong string, the parser is wrong.
                        new String(digits.ToArray()))));

For now it looks really confusing. I'll try implement Select and SelectMany later to make it a monad, like you did with Option<T> and see if I can make it work with this parser type.

I know you have other things planned to LanguageExt, but do you think about creating parser combinators?

A quick comment: The lambda property declaration (=>) is the coolest thing in this C# release.

Another quick comment: It's incredible how much you can learn if you convert "complicated" code from a language to a more familiar one.

**Comment by louthy** [comment]
> do you think about creating a parser combinator library?

Heh, have you seen my other older library, `csharp-monad`?

https://github.com/louthy/csharp-monad

It has a pretty complete parsec library.  The error handling is a touch buggy, but it's mostly good.  I went through most of the Haskell parsec library converting the functions over.  Even the expression and operator precedence parsers.

https://github.com/louthy/csharp-monad/tree/master/CSharpMonad/src/parsec

Here's a basic language parser:

https://github.com/louthy/csharp-monad/blob/master/CSharpMonad.UnitTests/src/lex/LexerTests.cs

Since then I've built a couple of parsec libraries in F#.  It's sooo much easier, because F# has decent type inference.  Unfortunately the F# version I wrote (which is probably the most complete one I've done) was built for an internal project at my company.  So I can't share that.  I used it to build a super-charged text-interpolation system and built a dynamically typed language that looked a lot like F# for doing deployment.

But yeah, I may get around to doing an updated version for lang-ext, and in the style of lang-ext.

They are super fun to use, and were probably (for me) the biggest eye opener to the potential of functional programming.  The composable (combinatorial) nature of them really awoke me to the idea that actually pure functional programming is where true modular and reusable programming lies. 

> Another quick comment: It's incredible how much you can learn if you convert "complicated" code from a language to a more familiar one.

Indeed.  I implemented the csharp-monad library whilst teaching myself Haskell.  I turned my head inside out trying to work out the expression parser:

https://github.com/louthy/csharp-monad/blob/master/CSharpMonad/src/parsec/expr/ExprParser.cs

Here's the original Haskell version:

http://hackage.haskell.org/package/parsec-3.0.0/docs/src/Text-Parsec-Expr.html

I was turned onto the whole thing by a series of lectures by Eric Meijer (of LINQ fame).  I'd definitely recommend watching these.  He sometimes loses his way with the presentation, but stick with it, there's moments of gold in there...

https://channel9.msdn.com/Series/C9-Lectures-Erik-Meijer-Functional-Programming-Fundamentals/Lecture-Series-Erik-Meijer-Functional-Programming-Fundamentals-Chapter-1

**Comment by louthy** [comment]
I forgot to answer the reason why it's not in there now.  I wrote the csharp-monad library first, and thought the best way to write good functional code in C# was by exploiting LINQ and writing a monad library.  And it was pretty useful for a while, but after a while it was just a little bit too much effort.  A lot of the reason why it was a bit too much effort was because of the rest of C# and its 'infrastrucure'.  

The base class libraries for example, returning `void`, or using `out` or `null` references.  It makes it quite hard to chain together computations.

So with lang-ext I decided to come at it from the other angle.  Of getting the foundations right.  I wanted as many of the core constructs that you'd find in a functional language as possible.  I've probably spent as much time on `Option<T>` in lang-ext as I did on the whole of csharp-monad.  And it's paid off, because now I find it easier to use functional constructs in C# than I do the BCL stuff.  

I saw parsec as the 'next level up'.  And although you can view most things in computing as a parser or interpreter (think about request/response for example), I felt it needed the basics first.  I guess I'm coming to the end of the basics part because I'm doing the Process library.  Although again that is to try and solve another fundamental with C#: it's poor concurrency support.

So yeah, it's something I'd like to put in, but hopefully that explains the general direction :)

**Comment by louthy** [comment]
@ricardopieper - A first pass at a parser combinators library is now in git (not on nuget yet)

https://github.com/louthy/language-ext/tree/master/LanguageExt.Parsec

I'm going to be using this in the Process library for configuration scripts.  If you're interested in examples, here's the parser:

https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/ActorConfig.cs#L176

And a unit test that uses it:

https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ParsecTests.cs#L446

**Comment by mpartipilo** [comment]
This is quite similar to Sprache.

**Comment by gordonwatts** [comment]
I might also suggest that as you add more and more to this library you split it from being monolithic...

**Comment by louthy** [comment]
> This is quite similar to Sprache.

@mpartipilo it's actually based on the Haskell parsec library; I've not seen Sprache but I assume it is too as most parsec libraries are inspired by it.

https://hackage.haskell.org/package/parsec-3.1.9/docs/Text-Parsec.html

> I might also suggest that as you add more and more to this library you split it from being monolithic...

@gordonwatts Do you mean split it between repos or break the project up into smaller libraries?  There's already quite a well defined split between the Core library, Parsec library and Process library; with separate nu-get packages.  

A lot of the reason for me keeping it all together is the reason I started writing it in the first place: _in the C# world there is very little in terms of 'joined up' functional libraries._  

For example if you found a great Option library, and a great immutable-map library, the immutable-map wouldn't be able to implement `Option<V> Find(K key)` because it's not aware of the Option library - or worse, it has its own implementation.  As soon as you find something missing in the what should be the basics for a functional environment then you find yourself patching and filling the gaps, either yourself or with other libraries that are incompatible or awkward in some way.

So currently I don't see much value in breaking it up.  But I'm prepared to hear out any reasons people may have :)
