### ISSUE TITLE
Is there any example of writer and monoid?

### ISSUE THREAD

**Issue by pimier15** [louthy/language-ext#261]
I tried to use languageExt but i'm stuck in usage of writer.

I can't understand how writer is working in this Library. 

If there is any example of wirter and monoid, upload that example please.

**Comment by louthy** [comment]
@pimier15 
I'm not sure how much you know about the `Writer` monad, but its purpose is to collect _information_ along with the result.  That information needs to be _told_ to the writer using `tell`.  This can propagate through the monadic computation, and at the end you end up with two values: the bound monadic value and the aggregate data collected via `tell`.  The data can aggregated because the `Writer` knows that its working with a `Monoid`

This is an example using `Seq<string>` to collect the aggregate data.  The monoid instance used is `MSeq<string>`, the bound value is `int`.

```c#
var computation = from x in Writer<MSeq<string>, Seq<string>, int>(100)
                  from y in Writer<MSeq<string>, Seq<string>, int>(200)
                  from _1 in tell<MSeq<string>, Seq<string>>(SeqOne("Hello"))
                  from _2 in tell<MSeq<string>, Seq<string>>(SeqOne("World"))
                  from _3 in tell<MSeq<string>, Seq<string>>(SeqOne($"the result is {x + y}"))
                  select x + y;

var result = computation();

Debug.Assert(result.Value == 300);
Debug.Assert(result.Output.Count == 3);
Debug.Assert(String.Join(" ", result.Output) == "Hello World the result is 300");
```
If you [look at the `MSeq` implementation](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Monad/MSeq.cs#L17) you will see it implements `Append` and `Empty` which is the `Monoid` interface.  As you can see `Empty` is an empty sequence, and `Append` is concatenating the sequences.  You can provide your own implementation of `Monoid<string>` and pass that to the writer to get your own behaviours for `tell`.

For example:
```c#
var computation = from _1 in tell<TInt, int>(2)
                  from _2 in tell<TInt, int>(4)
                  from _3 in tell<TInt, int>(6)
                  select unit;

var result = computation();

Debug.Assert(result.Value == unit);
Debug.Assert(result.Output == 12);
```
This uses `TInt` as the monoid, where `Empty()` returns `0`, and `Append()` adds the numbers.  So it sums the results into a total.

I could create a `MProduct` monoid, that calculates the product of the values instead of summing:
```c#
struct MProduct : Monoid<int>
{
    public int Append(int x, int y) =>
        x * y;

    public int Empty() =>
        1;
}
```
Then I would get a different result:
```c#
var computation = from _1 in tell<MProduct, int>(2)
                  from _2 in tell<MProduct, int>(4)
                  from _3 in tell<MProduct, int>(6)
                  select unit;

var result = computation();

Debug.Assert(result.Value == unit);
Debug.Assert(result.Output == 48);
```
