### ISSUE TITLE
void vs. Unit / using act()

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#263]
How can I refactor to use `Unit` as return type instead of void?

This is useful especially when using Reactive Extensions / Observables. Example:

```
Observable.Interval(TimeSpan.FromSeconds(30)).Subscribe(fire);

        public void fire(long i)
        {
        }
```

I want to change `void fire(long i)` to `Unit fire(long i)` and I tried to replace Subscribe call by like `Subscribe(act(fire))`. This does not compile. Perhaps I'm missing something here?

**Comment by louthy** [comment]
Because C#'s inference of functions is rubbish, you must specify the generic arguments for `act` if you want this to work:
```c#
act<long, Unit>(fire);
```
Basically C# has two types of _functions_:

* Method groups
* First class functions (`Func`)

Method groups are not first class citizens like `Func`, they're not values.  

To show the proof of this, you could define your `fire` function thus:
```c#
public Func<long, Unit> fire = i =>
{
    return unit;
};
```
Then this wouldn't cause an error:
```c#
act(fire);
```
It's something I've complained about before on the Roslyn project.  C# programmers shouldn't have any concept of method groups, as they're artefacts from the compiler.  The compiler should be able to resolve to a single valid method within the method group and use it, but unfortunately that's just a limitation we have right now.

**Comment by StefanBertels** [comment]
Thank you for explanation, very helpful!
