### ISSUE TITLE
memo of enumerable is not lazy

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#265]
Unless I'm missing something, the enumerable `memo` implementation uses `SeqEnumerable` which evaluates the first element in the _constructor_.

`memo` as a concept is inherently lazy (at least in my mind) so this behaviour seems unexpected.

**Comment by louthy** [comment]
The first item isn't lazy, no.  The rest is.  But yes, for memo it seems wrong.

**Comment by StanJav** [comment]
Do you plan to fix it?

**Comment by louthy** [comment]
Didn't mean to close this.  Yes, I will come up with a solution.

**Comment by louthy** [comment]
@OlduwanSteve @StanJav This is fixed in `v2.1.21`

It required a bit of a refactor, and I did some additional work to make Seq more efficient in terms of memory.  All the unit tests pass, so I don't expect any problems, but it was quite a big change so just be a little wary and let me know if you see any issues
