### ISSUE TITLE
Is it worth it to create language-ext.async?

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#273]
My current problem is that I wish to upgrade to latest language-ext but the folks over at reactive-ui are still using the old RX.* packages instead of the System.Reactive.* new packages. I would like to be able to use most of LanguageExt but just not the async stuff that depends on System.Reactive.*.

Is this a bad idea to split the library?

**Comment by louthy** [comment]
@bradphelan Unfortunately it's not as simple as that because it would mean splitting the `Prelude` which removes the advantage that this library seeks - which is a simple functional prelude that can be included with one `using`.  On a personal level I am also not particularly keen on making changes to this library to support other libraries that can't be bothered to update to the latest versions.  So I would suggest posting to the reactive-ui repo asking them when they're going to update.

**Comment by bradphelan** [comment]
there is an update in 'alpha' so its not critical. C# 8 extension
everywhere feature should make it possible to fake open modules. but we
will have to wait.
