### ISSUE TITLE
Record types and .net native

### ISSUE THREAD

**Issue by jmagaram** [louthy/language-ext#306]
Do you know if the Record type works with .net native, which I think is all apps uploaded to the Microsoft app store? The [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/framework/net-native/reflection-and-net-native) says...

In addition, .NET Native doesn't allow you to reflect over private members of the .NET Framework class library. For example, a call to the TypeInfo.DeclaredFields property to retrieve the fields of a .NET Framework class library type returns only public or protected fields. 

I briefly looked through the code and it looks like IL might do this.

**Comment by jmagaram** [comment]
I didn't realize I can test this myself by turning on .net native compilation. I'll try it.

**Comment by jmagaram** [comment]
Forget .net native for a sec. Out of habit, I tried testing it with a class like the following. It does NOT work because the fields are defined as private. The documentation should be updated to indicate that the fields must be public for this to work. 

    public class PersonA : Record<PersonA>
    {
        private readonly string _firstName;
        private readonly int _age;

        public Person(string firstName,int age)
        {
            _firstName = firstName;
            _age = age;
        }

        public string FirstName => _firstName;

        public int Age => _age;
    }

This works...

    public class PersonB : Record<PersonB>
    {
        public readonly string FirstName;
        public readonly int Age;

        public PersonB(string firstName, int age)
        {
            FirstName = firstName;
            Age = age;
        }
    }

**Comment by jmagaram** [comment]
I can't test .NET Native right now. VS eats all available memory when trying to compile a COMPLETELY EMPTY UWP app project that includes LanguageExt.Core. I've submitted a bug to VS. I still wonder though if your Record class will work on .NET Native.

https://developercommunity.visualstudio.com/content/problem/152935/build-fails-with-net-native-out-of-memory.html

**Comment by louthy** [comment]
@jmagaram > Forget .net native for a sec. Out of habit, I tried testing it with a class like the following. It does NOT work 

Saying something does not work, but without specifying what doesn't work isn't particularly helpful.  However the documentation is pretty clear:

> Note that only fields or field backed properties are used in the structural comparisons and hash-code building.

By providing your own implementations to the properties you are not using field-backed properties (even if you are actually backing them with fields manually).  Field backed properties have special names given by the compiler that the Record system can spot.  

So you can either use the second example, or:

```c#
public class PersonC : Record<PersonC>
{
    public string FirstName { get; }
    public int Age { get; }

    public PersonB(string firstName, int age)
    {
        FirstName = firstName;
        Age = age;
    }
}
```
With regards to your .NET Native comment.  It seems the limitation is reflecting on 'private members of the .NET Framework class library'.  I guess the implication is that the meta-data from the core BCL isn't being included in native builds, whereas the meta-data for types within your project and third-party DLLs are.  Since the record system can't be retrospectively applied to a .NET Framework type (you can't make `DateTime` into a `Record` for example) then this limitation doesn't seem important or relevant.  

However if you want to see the code that gets the list of `FieldInfo` structures for a Record derived type, [take a look here](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Utility/Reflect.cs#L11).

**Comment by jmagaram** [comment]
Sorry I wasn’t clear. When I said it didn’t work I meant the code asserted that two records were the same when they weren’t, presumably because it couldn’t see those manual private  fields that I used to back the properties. I still think the docs could be a bit clearer since “field backed properties” sounds a lot like what I wrote that didn’t work. I’ve read about “auto implemented properties” - maybe that is what you meant. I just looked at your code.

I think the docs would be more clear if it said it works with “public fields and public auto-implemented properties; private and protected members are ignored.”

It is curious to me that the visual studio fails net native compilation on a totally empty project with language-ext as the only nuget package. Not your fault but i do wonder why.

That Record class is a clever piece of code. Super useful. I try to use immutable everywhere and the lack of support for this in C# (yet) is quite frustrating.

________________________________

**Comment by jmagaram** [comment]
One other thing. Fields are almost ALWAYS private. That is why I think clarification is helpful.

________________________________

**Comment by louthy** [comment]
> I think the docs would be more clear if it said it works with “public fields and public auto-implemented properties; private and protected members are ignored.”

Sure, if it's unclear then I'm happy for the documentation to change.  If you want to do a pull request then I'll review.

> One other thing. Fields are almost ALWAYS private. That is why I think clarification is helpful.

In your world maybe ;)

Records are very much meant to behave as record types in other functional languages - which are pure data types where all members are public.  So a type that is just `pubic readonly` fields is exactly the right behaviour (and was the only supported members on the original version, it has been expanded to work with field backed properties now).
