### ISSUE TITLE
Skipped/Missed namespace declaration in files

### ISSUE THREAD

**Issue by ijsgaus** [louthy/language-ext#320]
Part of source files don't have namespace specified. This place extensions in global scope and change behavior of compiler, when package referenced. This is list of files without namespace:

- Either.Extensions.cs
- EitherUnsafe.Extensions.cs
- HashMap.Extensions.cs
- HashMap.Extensions.Eq.cs
- Lst.Extensions.cs
- Option.Extensions.cs
- Option.Extensions.Async.cs
- Task.Option.Extensions.cs
- OptionAsync.Extensions.cs
- OptionUnsafe.Extensions.cs
- Reader.Extensions.cs
- RWS.Extensions.cs
- Seq.Extensions.cs
- State.Extensions.cs
- Task.cs
- Task.Try.Extensions.cs

**Comment by louthy** [comment]
That is intentional as all types (apart from `Task<T>`) are owned by lang-ext.  It means users get the functionality hanging off the types without having to have `using LanguageExt` in their code.  The `Task<T>` global extensions are arguable - but as `Task<T>` isn't something one would de-reference too often, I felt providing those extensions and the LINQ operators was a bigger convenience win over the pollution of intellisence.

> change behavior of compiler

What do you mean by this?  How does it change the behaviour?

**Comment by ijsgaus** [comment]
[Sample on FSharp](https://github.com/ijsgaus/Confuse) - without LanguageExt - code compiles. After reference - no. And error difficult to determine. I try make analog CSharp sample.

**Comment by louthy** [comment]
@ijsgaus I have pinged Phillip Carter on the F# team - this looks like an F# compiler issue to me.  Although I normally don't like to point fingers at compilers, there's nothing in that code which has any relation to lang-ext from what I can tell.

**Comment by ijsgaus** [comment]
You are right, changing namespaces not help.
