### ISSUE TITLE
Issues with use methods

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#328]
Does this library have a preferred way to behave when given `null`?

For example, consider the inconsistent behavior of these two `use` overloads from `Prelude_Use.cs`.  If the disposable is obtained form a `Task<>`, then we guard the disposable in case it was `null` but not so if the disposable comes from a `Func<>`.

```
public static async Task<U> use<T, U>(Task<T> computation, Func<T, U> map) where T : class, IDisposable
{
    T t = null;
    try
    {
        t = await computation;
        return map(t);
    }
    finally
    {
        t?.Dispose();
    }
}
```

```
public static R use<T, R>(Func<T> generator, Func<T, R> f)
    where T : class, IDisposable
{
    var value = generator();
    try
    {
        return f(value);
    }
    finally
    {
        value.Dispose();
    }
}
```

**Comment by louthy** [comment]
The second one is a bug.  There’s not a one size fits all policy, but in this case it’s reasonable for use to return null and so it should be protected against in the finally clause.

Data types in general don’t allow null values unless they have the Unsafe suffix.

**Comment by bender2k14** [comment]
Found another bug in the family of `use` methods.  This one is in the extension method in `TryExtensions` with signature `Try<U> Use<T, U>(this Try<T> self, Func<T, U> select)`.  The code `self().Value` should be assigned to `t`.
```
public static Try<U> Use<T, U>(this Try<T> self, Func<T, U> select)
    where T : IDisposable => () =>
    {
        var t = default(T);
        try
        {
            return select(self().Value);
        }
        finally
        {
            t?.Dispose();
        }
    };
```

I would like to repurpose this issue (#328) to address these bugs within the family of `use` methods.

Is that ok with you @louthy or would you prefer if I create separate issues?

**Comment by louthy** [comment]
Fine with me 👍

**Comment by bender2k14** [comment]
There are `use` and `tryuse` methods in `Prelude_Use.cs` as well as some `Use` extension methods.  For these methods, either the `IDisposable` is directly passed in or it is indirectly passed in via one of these monad types:
1. `Func<>`
2. `Task<>`
3. `Try<>`
4. `TryOption<>`
5. `TryAsync<>`
6. `TryOptionAsync<>`

Is there a reason that these monad types have some kind of `use` method while others (such as `Option<>`) don't?

**Comment by louthy** [comment]
> Is there a reason that these monad types have some kind of use method while others (such as Option<>) don't?

Mostly because the types you list are all delegates, the idea is you can inline a computation as an expression that you couldn't normally do with `use(...) { ... }`.  By the time an `Option` exists the computation has been done (although since that decision was made `Option` also supports lazy evaluation).

There is [another issue open](https://github.com/louthy/language-ext/issues/205) about whether `Option` (and other types) should derive from `IDisposable`.  I'm truly undecided whether that's actually a good idea or not.  But obviously if it did then `use<T, R>(T disposable, Func<T, R> f)` would work for `Option` types.

One thing that has crossed my mind is that tooling like ReSharper might complain about values not being disposed properly, so that would need to be considered.  I don't use it, so I'm not sure if it would start throwing out warnings, but from what I've seen of it before, I wouldn't be surprised.

**Comment by bender2k14** [comment]
I still don't see what is special about those monad types.  My thought would be to have a single function something like this
```
public static Func<A, B> disposing<A, B>(Func<A, B> f)
    where A : IDisposable => disposable =>
    {
        try
        {
            return f(disposable);
        }
        finally
        {
            disposable.Dispose();
        }
    };
```

and use it something like this
```
public static Func<A, B> Method<A, B>(AnyMonad<A> ma, Func<A, B> f)
    where A : IDisposable => disposable =>
    ma.Map(disposing(f)));
```

**Comment by bender2k14** [comment]
Some of the `use` family of method have the type constraint `where T : class, IDisposable` while other just have the type constraint `where T : IDisposable`.

Do you have a preference about the inclusion or exclusion of the `class` type constraint on these methods?

**Comment by bender2k14** [comment]
I will take the silence as a "no".  I decided to remove the `class` type constraints`.
