### ISSUE TITLE
Missing MatchAsync for Option<T> in prelude

### ISSUE THREAD

**Issue by SeanFarrow** [louthy/language-ext#342]
There is no MatchAsync in the prelude class for option, but an extension method exists.
I'm happy to provide one, but do we need tests for this as it will just call the extension method as other methods do.

**Comment by louthy** [comment]
If you mean `matchAsync` rather than `MatchAsync`, then sure.  But make the change in the `async-refactor` branch as that's where all the latest changes are.  You'll need to create variants for `MatchUnsafeAsync` too.

Note that (although I haven't yet done this for `Option.MatchAsync`) the delegates for `Some` and `None` should be called `SomeAsync` or `NoneAsync` if the delegate return a `Task`.
