### ISSUE TITLE
Why is there a Count extension method off of Task called Count?

### ISSUE THREAD

**Issue by faeriedust** [louthy/language-ext#344]
```
    /// <summary>
    /// Get the Count of a Task T.  Returns either 1 or 0 if cancelled or faulted.
    /// </summary>
    public static int Count<T>(this Task<T> self)
    {
        if (self.IsFaulted || self.IsCanceled) return 0;
        self.Wait();
        if (self.IsFaulted || self.IsCanceled) return 0;
        return 1;
    }
```

I had this test:
```[Fact]
public void TaskTransitionReasonQueryHandler_GetsAtLeastFiveTaskTransitionReasons() {
  var cm = new TestContainerManager();
  var taskTransitionReasons =
    cm.TaskTransitionReasonQueryHandler.Handle(TaskTransitionReasonQuery.Default);
  Assert.True(taskTransitionReasons.Count() > 5);
}
```

which compiled even though completely wrong because Handle returns a `Task<IEnumerable<>>`

Why do we have this .Count() extension method? It seems to me far more likely to be called by mistake than for the behavior here.

As a fan of using the compiler to assist me in flipping between async and sync code, a method like this that doesn't even throw a runtime error makes me extremely sad, lol. Looking through my code, I made this mistake quite a few places, several of which weren't so lucky to be in a failing test like this one.. :(

I propose we delete this method.

**Comment by bender2k14** [comment]
More important is that this method needs to return `Task<int>`.  I could write a test similar to those in issue #317 that causes this code to deadlock.  I expect that this will be fixed in the branch [`async-refactor`](https://github.com/louthy/language-ext/tree/async-refactor).

After that change, the compiler will once again assist you flipping between async and sync code.

Even so, I in favor of having a consistent set of methods across monads.

**Comment by faeriedust** [comment]
I'm in favor of having consistent set of methods across the monads this library provides as well. but `Task<>` was not provided by this library, so I think, no?  So I think some care in not actively interfering with people's current usage of Tasks would be pretty desirable.

I do like the monad-specific extension methods off of task (e.g. Map, Bind, etc), but I guess I seriously question the readability of code if they use a `.Count()` method to check if a task is faulted or cancelled, particularly if it happens to be a `Task<IEnumerable<>>`.

As an alternative, simply namespacing these extension methods, so that I can opt-in to use them would go a long ways, imo. 

E.g. perhaps all of the Task extension methods could go into a "LanguageExt.Tasks" namespace, or some such? Then it can pull all the shenanigans it wants, and I'm not forced to deal with it to get the benefit of the rest of the library.

I'm just annoyed because I think it's very nice to be able to install this library into a project, use it for a bare minimum of things, and then gradually increase that usage as I go.  It makes it more difficult if it's actively interfering with my coding process that's unrelated to this library atm.

Making the return type Task<Int> would certainly help, but I think it will likely still be pretty annoying, so yeah, I guess my new proposal is to namespace the `Task<>` extension methods.

**Comment by louthy** [comment]
@faeriedust The reason for the `Count` function existing is legacy.  The HKT template system previously relied on a consistent set of functions being implemented per-monadic type.  This allowed for the transformer functions to be generated reliably.

The requirement for it to exist now isn't as great because of the `MonadTrans` implementations that do all of the transformer work now.  

Anyway, I have already updated this function in the [async-refactor branch](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/DataTypes/Task/Task.cs#L94)

I won't be dropping the function as I don't agree that there should be any confusion with `Task<IEnumerable<A>>` - if you want to count the items in the inner `IEnumerable` you should call the transformer variant: `CountT()`:

```c#
public static Task<int> CountT< A>(this Task<IEnumerable<A>> ma) =>
    default(TransAsyncSync<MTask<IEnumerable<A>>, Task<IEnumerable<A>>, MEnumerable<A>, IEnumerable<A>, A>).Count(ma);

```

**Comment by faeriedust** [comment]
I don't understand how `.CountT` helps with the above issue.

If it's an `IEnumerable<>`, then I should call `.Count()`, and it behaves correctly.

If it's a `Task<IEnumerable<>>`, then `.Count()` silently returns me a garbage answer. If I notice this, I can call `.CountT()` sure, but I didn't notice at all, so this clearly wasn't an option.

In particular, I had someone writing tests for me, and they didn't notice that it was returning a `Task<IEnumerable>`, and just called `.Count()` without looking at the types (assuming it was IEnumerable<>), and they even had several tests passing with this mistake before we noticed anything.

**Comment by faeriedust** [comment]
Ah, I see you changed the return type to Task<int> in that branch, so that should make things much easier hopefully, thanks! :)

**Comment by louthy** [comment]
I don’t know why you’re confused. CountT is the transformer version of
Count. Task<Ienumerable<A>> is a transformer type - so if you want the
count of items in the enumerable use CountT.
