### ISSUE TITLE
Complete SelectMany implementation for WriterMonad

### ISSUE THREAD

**Issue by alaendle** [louthy/language-ext#349]
Maybe I'm missing something, but I suspect the writer monad currently doesn't support IEnumerable<T> types. If you take a look at the following code I hope my suspicion/intention gets obvious.

            var xx = Some(List(1, 2));
            var yy = from i in xx
                     from ii in i  // <<- compiles
                     select ii * 2;

            var x = Writer<TString, string, Lst<int>>(List(1, 2));
            var y = from i in x
                    from ii in i  // <<- CS1943 overload for SelectMany is missing
                    select ii * 2;

While it is relatively simple to add a overload of SelectMany to Writer.Extensions.cs so that the cited code compiles, I couldn't figure out how I should implement the method correctly. So sorry, no PR - I need help here.

**Comment by gwintering** [comment]
When writing the `from` comprehensions, you have to decide which monadic type you're going to `Bind`/`SelectMany` over.  In you're first example, that's `IEnumerable` (you can always tell by looking at the return value of the expression).

So your first example is really just binding an `IEnumberable` with an `IEnumberable`; `Option` has an implicit conversion to `IEnumberable`, which is why it's not obvious.

In your second example, you trying to operate on the value inside two different monads.  Unfortunately, this isn't possible with the `from` comprehensions, though I would love it if it were possible.  Instead, you should [Monad Transformer](https://github.com/louthy/language-ext#transformer-types) family of functions.  In this case `MapT` fits the bill:

    var x = Some(List(1, 2)).MapT(i => i * 2);

There's also other cool things you can do with transformers, like use `Sequence` to swap the monads.

**Comment by alaendle** [comment]
Thanks for your quick reply and the hint for monad transformers. While this definitely will work for the Option scenario, it's not a solution for the writer monad - or I'm not aware how I could make use of it.

Basically I want to use the writer monad for logging like suggested in https://github.com/louthy/language-ext/issues/228. But this seems to be quite hard for real world scenarios; so what I want to write would look like.

        var y = from i in x
                from _ in tell<TString, string>("global")
                from ii in i
                from __ in tell<TString, string>("local" + ii)
                select ii * 2;

So if I understand correctly monad transformation wouldn't allow me to do the "inner-loging" since the Writer will be faded out. Also a transformation to method chains - needed to use something like MapT (if available for the Writer) - would give a somehow ugly syntax since all the intermediate objects/states of the writer would get visible. So I still believe a LINQ compliant solution would be desirable - also I'm not sure if it is possible and worth the effort.

**Comment by gwintering** [comment]
In your example, what are the types of `x` and `i`?  If they are not `Writer`, then the call to `SelectMany` implicit in the `from` comprehension will not work.  And I don't think we can just write another overload to `SelectMany` because then the compiler doesn't know which one to pick.

But you shouldn't have to add all the code in #228.

When working with the monads in this library, there's generally three tricks you can use for `from` comprehensions when mixing and matching other expressions:

1. Lift non `Writer` expression into a `Writer` and put if after `in`
2. Put the non `Writer` expression into a `let` expression instead of `from ... in`
3. Transform a `Writer` that's nested inside another monad so the `Writer` is on the outside, and use that expression after `in`

So you should be able to do something like this:

    from _ in tell<TString, string>("Starting . ..")
    from l in Writer<TString,string,Lst<int>>(List(1,2)) //Trick #1
    let l2 = from i in l select i + 1 //Trick #2
    let ops = //More #1, but will be converted to #3 below
        from i in l
        select tell<TString, string>($"i was {i}")
    from __ in ops.Sequence()  //Trick #3
    from ___ in tell<TString, string>("Done")
    select l2

Right now you can use the first two tricks.  However, the third trick won't work because `Writer` doesn't have the full complement of transforms like `Sequence`.  I think it should be possible for `Writer` to have all the transforms, but maybe @louthy  can weigh in on that idea.

**Comment by alaendle** [comment]
Unfortunately I haven't real experience in functional programming, so to not get to much confused about syntax I tried to translate the example to haskell:

```
main :: IO ()
main = do
  print $ runWriter $ multWithLog [1, 2]

multWithLog :: [Int] -> Writer [String] [Int]
multWithLog input = do
  _ <- writer(0, ["Start"])
  let c = fmap (\i -> writer (i*10, ["Number: " ++ show i])) input
  sequence c
```
Prints:
`([10,20],["Start","Number: 1","Number: 2"])`

For sure real world is more complicated - I try to use the writer monad to replace the use of direct log statements so I need to carry log-level, exception objects, etc. around - but basically this what I've tried; and yes, you are absolutely right, I'm really missing a `Sequence` here. So MANY thanks for your detailed description of the problem - even if it might have been obvious for experienced functional programmers, it really helped me to get a better understanding!

So maybe we should close this issue and create a new one stating that Writer should support the full complement of transformations?

**Comment by louthy** [comment]
@alaendle There is no issue with `Writer` you can't use incompatible monads in the same LINQ expression.  That's also the case in Haskell.  It's clear from your Haskell example that the `multWithLog` function is using the `Writer` monad all the way through, but to work with the `[Int]` sequence that's inputted it uses `let c = ...` which is a non-monadic operation.  The `fmap` is projecting the sequence of ints into a sequence of Writers which then are flipped using `sequence` to make a Writer of sequence.

This is the code in lang-ext:

```c#
static Writer<MSeq<string>, Seq<string>, int> writer(int value, Seq<string> output) => () =>
    (value, output, false);

static Writer<MSeq<string>, Seq<string>, Seq<int>> multWithLog(Seq<int> input) =>
    from _ in writer(0, SeqOne("Start"))
    let c = input.Map(i => writer(i * 10, SeqOne($"Number: {i}")))
    from r in c.Sequence()
    select r;
```
I think you'll agree it looks pretty close to the Haskell version.

You can run it with:
```c#
public static void F()
{
    var (value, output, faulted) = multWithLog(Seq(1, 2, 3))();

    Debug.Assert(value == Seq(10, 20, 30));
    Debug.Assert(output == Seq("Start", "Number: 1", "Number: 2", "Number: 3"));
}
```
The one thing that's missing is the `Sequence` implementation for the `Seq<Writer<..>>` pair.  `Sequence` exists for most monad pairs in lang-ext, but it's not yet been done for `Writer`, `Reader`, `State`, or `RWS`.  But you can add the extension yourself and it will work as expected:
```c#
public static class WriterSeqExt
{
    public static Writer<MonoidW, W, Seq<A>> Sequence<MonoidW, W, A>(this Seq<Writer<MonoidW, W, A>> ma) where MonoidW : struct, Monoid<W> => () =>
        ma.FoldBack((Value: Seq<A>(), Output: default(MonoidW).Empty(), IsBottom: false), (s, w) =>
        {
            if (s.IsBottom) return s;
            var (a, output, bottom) = w();
            if (bottom) return (Value: Seq<A>(), Output: default(MonoidW).Empty(), IsBottom: true);
            return (Value: Prelude.Cons(a, s.Value), Output: default(MonoidW).Append(output, s.Output), IsBottom: false);
        });
}
```

**Comment by louthy** [comment]
`Sequence` and `Traverse` added for sequences of `Reader`, `Writer`, `State`, or `RWS` monads:

https://github.com/louthy/language-ext/releases/tag/v2.2.2-beta

**Comment by louthy** [comment]
@alaendle I have made a couple more improvements to the `Writer` API to make writing the code in your example a bit easier.

This isn't needed any more:
```c#
static Writer<MSeq<string>, Seq<string>, int> writer(int value, Seq<string> output) => () =>
    (value, output, false);
```
The `Writer` constructor previously only accepted the bound value (`int value`) and would use the `MonoidW.Empty()` as the seed for the writer `output`.

Now you can construct any writer like so:
```c#
Writer<MSeq<string>, Seq<string>, int>(0, Seq1("Start"));
```
That allows for a sequence of strings to be collected for the output and an `int` as the bound value.  You're not limited to `Seq<A>` though, you can use any monoid.  Here we'll use a string as the output value:
```c#
var ma = from _1 in Writer<TString, string, Unit>(unit, "")
         from _2 in tell<TString, string>("Hello")
         from _3 in tell<TString, string>(", ")
         from _4 in tell<TString, string>("World")
         select unit;

// ma().Output == "Hello, World";
```
And here we'll use the `Product<NumA, A>` monoid to find the product of all outputted values:
```c#
var ma = from _1 in Writer<Product<TInt, int>, int, Unit>(unit, 1)
         from _2 in tell<Product<TInt, int>, int>(2)
         from _3 in tell<Product<TInt, int>, int>(4)
         from _4 in tell<Product<TInt, int>, int>(10)
         select unit;

// ma().Output == 80;
```
However, because collecting a sequence of values is likely to be the most common usage of Writer, and the overhead of typing the generic arguments is pretty painful, I have added some convenience `Writer` constructors and `tell` functions.  

So, going back to your example, you can now do this:
```c#
static Writer<MSeq<string>, Seq<string>, Seq<int>> multWithLog(Seq<int> input) =>
    from _ in Writer(0, Seq1("Start"))
    let c = input.Map(i => Writer(i * 10, Seq1($"Number: {i}")))
    from r in c.Sequence()
    select r;
```
Instead of:
```c#
Writer<MSeq<string>, Seq<string>, int>(0, Seq1("Start"))
```
We can now write:
```c#
Writer(0, Seq1("Start"))
```
Or, if you want to start with an _empty_ output:
```c#
Writer<string, int>(0)
```
And instead of:
```c#
tell<MSeq<string>, Seq<string>>(Seq1("Another"))
```
We can now write:
```c#
tell("Another")
```
In fact this:
```c#
Writer(0, Seq1("Start"))
```
Is equivalent to:
```c#
from x in Writer<string, int>(0)
from _ in tell("Start")
select x;
```
This should make the `Writer` slightly more accessible, and reduce the burden of writing these convenience functions.

**Comment by alaendle** [comment]
Great! I just tested 2.2.9-beta and it really seems to support my scenario well.  And again many thanks for the very detailed answers to @louthy and @gwintering. Even if I annoyed you with some beginner-level questions, I hope at least the added Sequence/Traverse methods and the syntactic sugar for writer was the result of our discussion and worth the effort.
