### ISSUE TITLE
.Some overloads conflinct

### ISSUE THREAD

**Issue by feugen24** [louthy/language-ext#35]
Hi,

The following doesn't compile:

    Action< int > actionint = v => v = v * 2;
    Option< int > optional1 = Some(123);
    optional1
               .Some(actionint) //Compiler tries to call:  public static Option<T> Some(T value)
               .None(() => 0);

so I need to change to: ".Some < int >(actionint)"

The problem is that this is very confusing since when you call .Some you only see 2 signatures in visual studio:

    Action< T > someHandler
    Func< T, R > someHandler

It took me while to understand what I was doing wrong, so I can imagine others will have same problem. 
Another aspect: maybe group  in code overloads of .Some because it's hard to find them otherwise. (i only decompiled the code, but i assume method order is the same in source)

**Comment by louthy** [comment]
There were a couple of issues here.  One is a bug in LangExt and one is an issue with your example.  

1. The reason the compiler didn't pick up the correct `Some` is because you are using an `Action` type and the `Some` was specifying it needed an `R` return value.  Obviously actions don't return, so this wasn't needed. It meant that the compiler couldn't resolve the `Some` because you hadn't specified a return type.

2. Your example contains an `Action` and a `Func`.  You can only use either Actions or Funcs, not combine the two.

**Comment by feugen24** [comment]
Agreed,
I think that in the end using Action with Match(Some:, None:) and option.Some().None() should look the same:

            Action<int> actionint = v => v = v * 2;
            Action action = () => { };

            Option<int> optional1 = Prelude.Some(123);
            optional1
               .Some(actionint)
               .None(action);

            optional1.Match(
                Some: actionint,
                None: action
                );
