### ISSUE TITLE
Unable to use the Seq module when using static LanguageExt.Prelude in a code file

### ISSUE THREAD

**Issue by SeanFarrow** [louthy/language-ext#366]
The Seq module seems not to work when a code file also contains the using static LanguageExt.Prelude line.
Looking at other modules, such as the one for HashSet, it appears the class is marked as partial. 
Should this be the case for the Seq module? if yet, I'm happy to provide a pr.
Cheers
Sean.

**Comment by bender2k14** [comment]
In what way does it not work?

**Comment by louthy** [comment]
I assume because Seq the class and Seq the function clash.  It’s an annoying limitation.  I’d be surprised if it’s related to the partial nature of the class, but I’d be interested in fixing that if it’s the case (as it causes clashes elsewhere too).

**Comment by SeanFarrow** [comment]
Hi,
In order to reproduce this, add the following program class to any type of console app with the LanguageExt core package, then remove the fully qualified LangaugeExt.Prelude from the random function.
namespace TestApp2
{
    using LanguageExt;
    using System.Linq;
    
    class Program
    {
        static void Main(string[] args)
        {
            //Create a sequence of integers. I've use Enamerable.Range here as I can't use anything from the static Prelude namespace as that causes the issue.
            var intSeq = Seq.createRange(Enumerable.Range(1, 5));
            //Randomly generate a value within the previously created range. Note that I fully qualify the random function here, to reproduce the problem, remove the LanguageExt.Prelude part of the qualifier and add the using static LanguageExt.Prelude back to the top of the file.
            int number = LanguageExt.Prelude.random(6);
        }
    }
}

I'm sure making the Seq module partial would fix this. Not only that but the HashSet and HashMap modules ae both partial, so should this be a standard pattern?
Cheers
Sean.

**Comment by louthy** [comment]
@SeanFarrow Hmm, not sure I entirely follow.  If I remove `LanguageExt.Prelude` from in from of `LanguageExt.Prelude.random(6)` then I would expect it to not compile, because `LanguageExt.Prelude` is a static class.  

To be able to remove `LanguageExt.Prelude` from `LanguageExt.Prelude.random` you must first add:
```c#
using static LanguageExt.Prelude;
```
That does then make accessing the `Seq` class problematic for the reasons I mentioned in my comment above.  But you can use:
```c#
var intSeq = Seq(Enumerable.Range(1, 5));
```
To construct your sequence and then use the fluent API from there.

It's not an ideal situation, and one I plan to take up on `csharplang` at some point.  

I'm not sure where your intuition for the partial classes idea comes from though?  As partial is a compiler level construct, not something that ends up in the assembly.  So, by the time you get to use `LanguageExt.Core.dll` the partial nature of the types have been removed.

**Comment by SeanFarrow** [comment]
@louthy
You are definitely  right this isn’t ideal. The only reason I was looking at the partial class idea and tried it locally, was due to the fact that all other modules are partial and that seemed to be usable when using LanguageExt.Static.Prelude.

**Comment by louthy** [comment]
Going to close this as (bar lobbying the C# team to get their compiler to understand the difference between a function invocation and a static module dereference) there's very little I can do.
