### ISSUE TITLE
Enumerable extension method `Map` called multiple times 

### ISSUE THREAD

**Issue by cage433** [louthy/language-ext#374]
The implementation of `Map` calls `Enumerable.Select`, which for `Iterators` results in the lambda being invoked afresh each time we iterate over the result. For example the following fails

```
[Fact]
public void EnumerableMapIsCalculatedOnceTest() {
    var n = 1;

    int NextValue() {
        return n++;
    }

    var actual = Enumerable.Range(0, 5).Map(_ => NextValue());
    var expected = List(1, 2, 3, 4, 5);
    Assert.True(Enumerable.SequenceEqual(actual, expected), $"Expected {toString(expected)} but was {toString(actual)}");
            
    // ensure the result of Map isn't recalculated each time it's iterated over
    Assert.True(Enumerable.SequenceEqual(actual, expected), $"Expected {toString(expected)} but was {toString(actual)}");
}
        
```

**Comment by bender2k14** [comment]
Another way to make this test pass is to change
```
var actual = Enumerable.Range(0, 5).Map(_ => NextValue());
```

to
```
var actual = Enumerable.Range(0, 5).Map(_ => NextValue()).ToList();
```

Do you prefer the solution in your PR more than what I have suggested?  If so, why?

**Comment by cage433** [comment]
Hi

I can see that you're being consistent with `Enumerable.Select`, although
I'm not certain that's a good thing.

Enumerable.Range(0, 5) is fixed, no matter how often I compare it with
List(0, 1, 2, 3, 4) it will be identical. Given that it came as a surprise
that the result of mapping over this range wasn't also constant. Clearly
your suggestion would work, but I'm not keen on having to remember to add a
`ToList` each time I map over an enumerable.

Like yourself I have a massive bias in favour of immutablity, so I would
change your extension method IEnumerable.Map to return a Lst<T>, rather
than IEnumerable<T> - which as we see can change each time it's iterated
over. If I really want the current behaviour I'd just call `Select`.

But that's just me - you've written a cracking library, so no hard feelings
if you disagree with this very new to C# coder.

btw - I think there may be issues with your `Task` extension methods - I've
seen both `Map` and `Bind` block (not every time). In particular you don't
seem to be using `Task.Unwrap` in the latter case. When I get an hour I'll
see if I can come up with a minimal failing test and a PR


cheers,

Alex

**Comment by bender2k14** [comment]
> btw - I think there may be issues with your `Task` extension methods - I've
seen both `Map` and `Bind` block (not every time). In particular you don't
seem to be using `Task.Unwrap` in the latter case. When I get an hour I'll
see if I can come up with a minimal failing test and a PR

This is a known issue (#317) and has been fixed in the branch [`async-refactor`](https://github.com/louthy/language-ext/tree/async-refactor).  The most recent prerelease (v2.2.2-beta) includes these fixes.

**Comment by bender2k14** [comment]
> Like yourself I have a massive bias in favour of immutablity, so I would
change your extension method IEnumerable.Map to return a Lst<T>, rather
than IEnumerable<T> - which as we see can change each time it's iterated
over.

This seems backwards to me.  Your test fails because the local variable `n` is _not_ mutated.  Your desired behavior is that the local variable `n` _is_ mutated.

> If I really want the current behavior I'd just call `Select`.

I think the point of this `Map` is retain the efficient lazy behavior of `Select` while changing from database jargon to functional programming jargon.

**Comment by cage433** [comment]
The local variable is mutated - as I expect, however I was expecting the
calls to the lambda to only occur during construction, regardless of
whether it's created eagerly or lazily. I did however expect the resulting
*Enumerable* to be immutable. Clearly that's not the case for `Select`,
however I was expecting that to be the result for `Map`.

Instead Enumerable.Range(0, 3).Map(_ => NextInt()) creates an Enumerable of
fixed length 3, *whose content changes every time you iterate over it*.
It's this last fact which was surprising - at least to me. I get your point
about laziness, so my PR is clearly no good. However lazy evaluation
doesn't necessarily have to occur at the cost of immutablilty.

It's perhaps because I come from a Scala background, where it is a common
idiom to use a local mutable variable when constructing an immutable
collection.
So using our example

```

var foo =  Enumerable.Range(0, 3).Map(_ => NextInt())

foreach (v in foo)
   Console.WriteLine(v);
> 1
> 2
> 3
foreach (v in foo)
   Console.WriteLine(v);
> 4
> 5
> 6


```

Using a similar idiom in scala returns a lazily evaluated, yet *still
immutable* collection
```

val foo = Stream.fill(3)(NextInt)

val bar = Stream.fill(3)(NextInt)

foo.zip(bar).foreach(println)
> (1, 2)
> (3, 4)
> (5, 6)

foo.foreach(println)
> 1
> 3
> 5


```

cheers,

A

**Comment by NickDarvey** [comment]
>however I was expecting the
calls to the lambda to only occur during construction, regardless of
whether it's created eagerly or lazily

I think the main thing with laziness is there _is no construction_. That LINQ isn't constructing anything except for an expression of the computation you'd like to run.
(Which is great because you can do things like `Enumerable.Range(0, inf)`.)

This is less about having immutable data structure but having an immutable computation (LINQ query). Right now, your computation mutates every time it's executed.

You need to make sure you don't introduce any side effects into the computation if you want the same result every time it's executed. Otherwise, do the mutable computation once with the results going put into a list (or into one of the System.Collections.Immutable data structures if that's important).

**Comment by cage433** [comment]
*I think the main thing with laziness is there is no construction.*


That isn't exactly correct. It's perfectly possible for lazy data
structures to be immutable, constructed bit by bit whenever a new value in
that structure is called for. Haskell does this, and from the Scala Stream
example I showed you earlier you can see that does the same. Of course any
such immutable structure needs to keep around the results of previous
calculations.

Incidentally the more typical use of streams in Scala is exactly the same
as the `Enumerable.Range(0, inf)` you mention - again laziness does *not* imply
mutability. So here's an example of an infinite, lazily evaluated stream

var foo: Stream[Int] = NextInt() #:: foo.map(_ => NextInt())

println(foo.take(4).mkString(","))
> 1, 2, 3, 4
println(foo.take(4).mkString(","))
> 1, 2, 3, 4



What you are describing is not the definition of laziness - it's just one
particular implementation. I was just surprised to see this choice in a
library a large part of whose focus is on immutability. I understand
exactly what is going on, and I'm not claiming it's incorrect - I was just
surprised. However as I mentioned earlier maybe that's due to my background
in other languages where laziness is treated differently.

cheers,

A

**Comment by NickDarvey** [comment]
Ohh, ok. Interesting! Thanks for explaining.

I'm pretty sure [Seq](https://github.com/louthy/language-ext/tree/master/LanguageExt.Core/DataTypes/Seq) works like that, if it helps.

**Comment by louthy** [comment]
Closing this now.  But just for clarity:

* `Map` is just an alias for `Select`.  For `IEnumerable` it will use the standard lazy behaviour of `IEnumerable`
* The issues with multiple evaluation of lazy streams with `IEnumerable` is well documented, hence the `Seq` type in this library - which is to remove the problems of multiple-evaluations of items in the stream, but is still lazy.  It has a cost though which is that each evaluated value must be stored - so you incur a memory allocation per item (which for infinite lazy streams would obviously blow up your memory usage).
