### ISSUE TITLE
OptionalResult None 

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#378]
I needed something with three states: some, none, exception. `OptionalResult` seems fine.

After building some code I had to hunt down a nasty bug because I assumed that
`OptionalResult<A>.None` would run into `Match()` case "none". Therefore I added some extension `IfNone(Func<A> getNone)` that should return `Result<A>`.

But seems like `OptionalResult<A>.None` is "bottom" which is not a valid state and will result in `Match()` case "exception" (with exception value being null...) 

Of course `new OptionalResult<A>(Option<A>.None)` helped but that wasn't obvious.

(BTW: I noticed `Result<A>` has a similar static "None" field -- why?)

Question: is this intended? Is `None` a good name here? What's the reason for having those invalid states (mostly named `Bottom`)?

And are `Result<A>` and `OptionalResult<A>` available for arbitrary use or are those types just helper types for LanguageExt?

I personally use `Validation<Error, Option<A>>` again because this avoids confusion (for me) and I get clear intent, too.

Perhaps Related to #341.

**Comment by bender2k14** [comment]
> is this intended?

No.  The bug you linked to (#341) is definitely related.  In that case, the expected behavior is that the instance is in the bottom state, but it is in the faulted state.  In your case, the expected behavior is that the instance is in the faulted state, but it is in the bottom state.  Depending on your perspective, you can either view this as two separate bugs or one bug in which two cases have each other's behavior.

> What's the reason for having those invalid states (mostly named Bottom)?

C# presents the following trade off in type safety.  A variable with a struct for its type cannot be null, but a struct can always be created via its (possibly implicit) default constructor.  In contrast, a class can only be created via an explicitly defined constructor (unless there are no explicitly defined constructors, in which case an implicit default constructor exists), but a variable with a class for its type can be null.

Based on this, LanguageExt has the following intended behavior with its struct types.  If a struct is created via it default constructor, that struct is put into its bottom state.  Then any interaction with a struct instance in its type's bottom state causes a `BottomException` to be thrown.

> And are Result<A> and OptionalResult<A> available for arbitrary use

Yep.  They are public types, so you can use them however you'd like.

**Comment by StefanBertels** [comment]
I know of this technical reason, especially having non-null `default` for struct.

But why is Bottom used in a conceptional way? There are structs with a natural bottom state (Option etc can be Option<T>None etc.). Why not make default(OptionResult) := OptionResult.None and drop all bottom/IsValid code?

Ok, types without natural None state need to be checked for invalid (default) state. But why not fail fast (throw exceptions) when calling them? Currently seems like the bottom state is handled different, resulting in Match(...) to proceed but e.g. run something on an invalid state. Why not let Match throw exception fast? 

Is there a reason to pass invalid values around?

**Comment by bender2k14** [comment]
Oh, first, I meant to say that "both" of these bugs are fixed in the current version of the [async-refactor](https://github.com/louthy/language-ext/tree/async-refactor) branch.

> But why is Bottom used in a conceptional way? There are structs with a natural bottom state (Option etc can be Option<T>None etc.). Why not make default(OptionResult) := OptionResult.None and drop all bottom/IsValid code?

We want the type system to tell us that our code is correct.  Sometimes we make a mistake by calling the default constructor of struct when we didn't mean to....and the type system isn't able to tell us that we are wrong.  Therefore, to compensate for this weakness of the C# type system, the approach of LanguageExt with its sturcuts is that the default state is considered an invalid state.  The situation would be more complicated (and thus more bugs) if the default state of some structs were valid and other were invalid.

> Ok, types without natural None state need to be checked for invalid (default) state. But why not fail fast (throw exceptions) when calling them?

Do you mean why not explicitly define the default constructor to throw an exception?  I think that is a good question and don't know the answer to that.

> Currently seems like the bottom state is handled different, resulting in Match(...) to proceed but e.g. run something on an invalid state. Why not let Match throw exception fast?
>
> Is there a reason to pass invalid values around?

The current behavior in the master branch (aka the current released version of LanguageExt) is incorrect.  The intended behavior is that interacting with a struct in its bottom state throws an exception.

**Comment by StefanBertels** [comment]
Ok, thanks for clarifying.  I'm a bit sceptic whether making every default struct invalid is very practical. 

Will this really apply for every struct? What about container types like List, what about Option? AFAIK those types currently (master) have some decent `default` like empty or None.

A had a look at async-refactor branch. Currently it doesn't look like this change already happend everywhere. If I read this correctly then default for Option types is still mapping to None.

Another point: 

code of `Result` has this line
`public static readonly Result<A> None = default(Result<A>);`

Should this be renamed to `Bottom` to clearly separate invalid states from regular None states?

Can you or Paul say something about this issue regarding roadmap (really for every struct?) and maybe about compatibility? Normally I don't try to use `default` for this but I remember I used it somewhere... probably for some default method parameter for some Option like this:

MyMethod(...params ..., Option<string> optionalText = default)

**Comment by louthy** [comment]
Just to be clear `Result` and `OptionalResult` are types to simplify the return values of various monadic types (instead of using a tuple, for example); they're not really general purpose monadic types like `Either`, `Option`, etc. and don't conform to any common notion of what an `Either`, or `Option` type may be.

> I needed something with three states: some, none, exception

That's exactly what `TryOption` is.  If you want three different types for the states then you probably need `Either<A, B, C>` which I have created in a project I'm working on now and will add to lang-ext at some point.

**Comment by bender2k14** [comment]
> I'm a bit sceptic whether making every default struct invalid is very practical.
>
> Will this really apply for every `struct`?

To be clear, I haven't seen @louthy explicitly say anywhere that...

> the approach of LanguageExt with its structs is that the default state is considered an invalid state

...that is my current understand that I have gained by reading the code.  It seems like a fine design choice to me.

> What about container types like List

`Language.Ext.List` is a `class`, not a `struct`, so this discussion doesn't apply to it.  Did you mean to say `Language.Lst<>`?  If so, then...

> what about Option? AFAIK those types currently (master) have some decent default like empty or None.

Yes, you are correct, so these structs are inconsistent with my previous statement.

> A had a look at async-refactor branch. Currently it doesn't look like this change already happend everywhere. If I read this correctly then default for Option types is still mapping to None.

This issue was specifically for `OptionalResult<>`, so I think that is the only think @louthy fixed in the async-refactor branch.

> Another point:
> 
> code of Result has this line
> public static readonly Result<A> None = default(Result<A>);
> 
> Should this be renamed to Bottom to clearly separate invalid states from regular None states?

I think the same changes to `OptionalResult<>` should be made to `Result<>`.  For that line, the assigned expression should be change as it was in `OptionalResult<>` to match the meaning of the identifier.

**Comment by StefanBertels** [comment]
Just had a short look at async-refactor: I see changes, better code, might fix some bottom case. What is conceptionally different to master?

@louthy: I think  `public static readonly Result<A> None = default(Result<A>);` should be removed or changed. default is Bottom (identically declared below). None should be Option.None (=> success state). IMHO.

I'm not sure whether OptionalResult should default to Bottom (i.e. "have" bottom). Why not default to Option.None here (success with None value)? Of course one could argue in different ways. Maybe OptionalResult is conceptionally more like Option<Result<>> (this means Option.None is natural default) or more like Result<Option<>> (current implementation => Bottom). If this is indifferent, why not favor the case where we can throw away invalid states in as many structs as possible (favor natural defaults when they do not harm)?

Another question: I understand (and guessed from code anyway) that OptionalResult should not be data types I create in my own code as I do with Option.
You say: use TryOption. But that's a different thing because TryOption is Func<OptionalResult> and I'm looking for a return type for my own function that returns exactly something like OptionalResult.

How can I replace that by TryOption? I could create a TryOption in my function and directly invoke it to _create_ an OptionalResult typed return value. This still means I'm using OptionalResult in my code and just avoid that I call wrong constructors of OptionalResult itself.
This probably is not what you wanted to say by "use TryOption". Could you clarify?

The nearest thing I could imagine is: I could use memo in combination with TryOption to define somthing that at least guarantees that the inner function is called only once.  But I would prefer classic way and just pass values around...

Either comes to mind, of course. But Result and OptionalResult are more exact fits here because I just want to make explicit that Exceptions are catched and then returned in clean way -- ideally compatible with all your great LanguageExt things...

(Same for Try / Result, of course.)

**Comment by louthy** [comment]
I have done a slight refactor of `Result` and `OptionalResult`.  I am still considering removing the interface altogether (by making all methods `internal`) because of the confusion about how to use `Try`, `TryOption`, etc.  Although it may just be better to make the `ma.Try()` extension method internal so you can never see a `Result` or `OptionalResult`.  

The main reason why I may keep the `Result` or `OptionalResult` interface `public` is because I can see they have some real-world use, and perhaps it will break a lot of code.  The next release will have a fair amount of backwards compatibility breakages (from the async updates), so I'd like to reduce that.

I'm not sure why I exposed the `Try` extension method in the first place, it was probably because `Try` the monad (and related types) didn't originally support memoisation.  They do now and I have added `Strict` to force evaluation.  

Both `Result` and `OptionalResult` now consider the `Bottom` state to be when the `State == IsFaulted` and `Exception == null || Exception is BottomException`.  The `null` exception is never exposed or known about unless you call `IsBottom`.  

So, the types are essentially two-state types of `Faulted` or `Success`.  And even if the `Exception == null` then `IsFaulted` will still return `true`.  And any `Match` or `IfFail` call will give you a `BottomException` if the internal `Exception` is `null`.  

It's arguable whether the `IsBottom` property is even needed now, but I'm going to keep it for now.

> I'm not sure whether OptionalResult should default to Bottom

Because in the case of `OptionalResult` the `None` state represents success - so creating something that represents success implicitly is in my mind a bad idea - that's the kind of thing that leads to bugs propagating.  `None` in `Option` represents a failure value.  

Anyway, with the new version the bottom state doesn't really exist, it's now a `Faulted` state with a `BottomException`, and only knowable if you call `IsBottom`.

> You say: use TryOption. But that's a different thing because TryOption is Func and I'm looking for a return type for my own function that returns exactly something like OptionalResult.
> How can I replace that by TryOption? 

There are prelude functions for constructing them from values, exceptions, as well as funcs:
```c#
TryOption<int> YourFunc() =>
    TryOption(123);

TryOption<int> YourFailFunc() =>
    TryOption(new ArgumentNullException());
```
Obviously the preferred way would be to do:
```c#
TryOption<int> YourFunc() => () =>
    123;

TryOption<int> YourFailFunc() => () =>
    throw new ArgumentNullException();
```
But if you're not actually trying to capture an exception and you want to construct them manually then the first examples are fine.

> that at least guarantees that the inner function is called only once

If you want to guarantee that the functions are call only once, then use the func constructors:
```c#
TryOption<int> YourFunc() => TryOption(() =>
{
    // ... this code will never be called twice for the same returned TryOption
    // You can also use Memo or Strict to force it for methods that haven't been
    // wrapped with the constructor method.
    return Some(123);
});

```

**Comment by StefanBertels** [comment]
OptionalResult: I'm totally ok with this, won't use it anymore. (IMHO you realky should avoid "None" as name for bottom default state).

Using Tryoption means: I should pass a func instead of a value. It will work but my use case was a little different: I didn't need the comfort on construction (exception catching) but the expressiveness if the return value (value or exception).

I will use Either (or Validation) in those use cases. Makes a little more noise for Validation<Option> but that can be reduced by my own match extension if necessary.

For breaking compatibility: Don't know about other users but I think you still can break minor functionality like this if it helps others.

Of course it is nice to deprecate things first and wait before removing interfaces. But if compiler will throw errors I'm fine with it.

**Comment by louthy** [comment]
>IMHO you realky should avoid "None" as name for bottom default state

What do you mean?  Check [the code](https://github.com/louthy/language-ext/blob/async-refactor/LanguageExt.Core/DataTypes/Result/OptionalResult.cs#L26)
```c#
        internal static readonly OptionalResult<A> None = new OptionalResult<A>(Prelude.None);
        internal static readonly OptionalResult<A> Bottom = default(OptionalResult<A>);
```
`None` is a successful result with an `Option.None` in it, bottom is an uninitialised struct.

> Using Tryoption means: I should pass a func instead of a value

I'm not sure you've read my reply properly.  You can use it with values if you like.  `TryOption(123)`

**Comment by StefanBertels** [comment]
@louthy Sorry, I really didn't check the latest code. None is indeed well defined and have OptionalResult conceptionally behave like Result<Option> is fine (i.e. default = bottom).

Regarding TryOption: I checked out TryOption(123). I probably missed the point that I can directly use TryOption as type and e.g. directly call Match on it. And I missed the point that I can construct a TryOption by giving it some value or none or even some exception value.

So I'm perfectly happy with construction.

I used OptionalResult because I have a value (some/none/exception) and just wanted to pass this -- conceptionally equal to Option without that third exception state.

So my interface would not return something that might get evaluated lazy / has to be invoked. Looks like constructing by value just creates a function to return the value and passing a function always (?) will make use of memo to avoid duplicate evaluation.

It was just the interface return value itself (TryOption) that caused some confusion to me because I assumed that this is just a exception-catching function decorator (with multiple function evaluation).
But I understand that conceptionally it is just a data type including lazy evalution.

Also I just noticed that Option itself has similar mode when constructing it by giving a function. But the signatures differ: Option takes Func<Unit,T> and TryOption takes Func<T>. And Option does not need to be invoked. (Is there a deeper reason for these differences?)

Finally: thanks for explanation, really helped me understand this better.
