### ISSUE TITLE
Example for Ord<A> in readme.md incorrect?

### ISSUE THREAD

**Issue by thehoglet** [louthy/language-ext#380]
[This line](https://github.com/louthy/language-ext/blame/master/README.md#L1340):

```
int x = OrdArray<TInt, int>.Inst.Compare(Array(1,2), Array(1,2)); // 0
```

seems to be a problem. 1) Inst is not defined, and 2) Compare() is not static.

Adding this to the class definition:

```
public static OrdArray<ORD, A> Inst = default;
```

and providing a static Compare() doesn't immediately fix this. The compiler says:

```
Error	CS1503 Argument 1: cannot convert from 'LanguageExt.Arr<int>' to 'int[]'
```

What am I missing here? A ```using static LanguageExt...``` at the top of the file maybe?

**Comment by bender2k14** [comment]
That `Inst` property is defined [here](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/ClassInstances/Ord/OrdArray.cs#L14).  From that instance, you can call the instance (i.e. non-static) method `Compare`.

However, the line in question doesn't compile for me either.  The issue that I am experiencing is that the arguments to `Compare` should be of type `int[]` but are instead of type `Arr<int>`.

The two possible fixes that I see are to either replace both occurrences of `Array(1, 2)` with `new int[] { 1, 2 }` to get
```
int x = OrdArray<TInt, int>.Inst.Compare(new int[] { 1, 2 }, new int[] { 1, 2 }); // 0
```

or replace `OrdArray` with `OrdArr` to get
```
int x = OrdArr<TInt, int>.Inst.Compare(Array(1, 2), Array(1, 2)); // 0
```

What do you say @louthy?  Would you like one of those changes or possibly another?

**Comment by thehoglet** [comment]
Ah! Thank you. I see where I went wrong now. I wasn't using the OrdArray in the library; I had copied and pasted the definition of OrdArray in the readme. 

And yes, changing the line in question to use OrdArr instead of OrdArray allows compilation. I should have looked more closely at the library source before launching into an issue.

**Comment by bender2k14** [comment]
No worries about opening an issue.  If you were confused, then there must be others that were confused as well.  In fact, you did help us to find something that was incorrect, so thanks for that :)

**Comment by louthy** [comment]
@thehoglet I have fixed up the docs.  Thanks for the heads up.
