### ISSUE TITLE
Error in testing code examples from Combinators for Parsing

### ISSUE THREAD

**Issue by imranypatel** [louthy/language-ext#398]
Testing code snippets from [Combinators](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Combinators) examples of documentation.

```
            // see Term, Number and Word classes in documentation...

            var spaces = either(
                eof,
                many1(satisfy(System.Char.IsWhiteSpace)).Map(_ => unit)
            );

            Parser<A> token<A>(Parser<A> parserA) =>
                from res in parserA
                from spc in spaces
                select res;

            var word = from w in token(asString(many1(letter)))
                        select new Word(w) as Term;

            var number = from d in token(asString(many1(digit)))
                          select new Number(Int32.Parse(d)) as Term;

            var term = either(word, number);

            var parser = from sp in spaces
                         from ws in many1(term)
                         select ws;

            var result = parse(parser, "   4 words are here");
```

Result is Error = {error at (line 1, column 20): unexpected end of stream, expecting letter, end of input or digit}.

Tried with appending space at the end of string:

```
  var result = parse(parser, "   4 words are here ");
```

Result is Error = {error at (line 1, column 21): unexpected end of stream, expecting letter, end of input or digit}.

Any thoughts?

**Comment by bender2k14** [comment]
Could you post the necessary `using`s as well?

**Comment by imranypatel** [comment]
Here is complete code:
```
using System;
using static System.Console;
using static LanguageExt.Prelude;
using LanguageExt.Parsec;
using static LanguageExt.Parsec.Prim;
using static LanguageExt.Parsec.Char;

namespace FPLibsLanguageExtTests
{
    class Program
    {
        static void Main(string[] args)
        {
            LanguageExtParserTests.Test();
            ReadKey();
        }
    }

    public static class LanguageExtParserTests
    {
        public static void Test()
        {
            var spaces = either(
                   eof,
                   many1(satisfy(System.Char.IsWhiteSpace)).Map(_ => unit)
               );

            Parser<A> token<A>(Parser<A> parserA) =>
                from res in parserA
                from spc in spaces
                select res;

            var word = from w in token(asString(many1(letter)))
                       select new Word(w) as Term;

            var number = from d in token(asString(many1(digit)))
                         select new Number(Int32.Parse(d)) as Term;

            var term = either(word, number);

            var parser = from sp in spaces
                         from ws in many1(term)
                         select ws;

            var result = parse(parser, "   4 words are here");
            WriteLine(result.ToString());
        }
    }

    abstract class Term { }

    class Word : Term
    {
        public readonly string Value;
        public Word(string value) => Value = value;
    }

    class Number : Term
    {
        public readonly int Value;
        public Number(int value) => Value = value;
    }
}

```
Target Framework: .Net 4.6.1
LanguageExt.Core: v2.1.32
LanguageExt.Parsec: v2.1.32

**Comment by bender2k14** [comment]
I did not encounter your problem.  Everything seemed to work for me.  Specifically, I used the same package versions, same target version, and the following unit test passed.

```
using System;
using LanguageExt.Parsec;
using Xunit;
using static System.Console;
using static LanguageExt.Parsec.Char;
using static LanguageExt.Parsec.Prim;
using static LanguageExt.Prelude;

namespace Tests {
  public class TestClass {
    [Fact]
    public void OptionalNumericAppend() {
      var spaces = either(
             eof,
             many1(satisfy(System.Char.IsWhiteSpace)).Map(_ => unit)
         );

      Parser<A> token<A>(Parser<A> parserA) =>
          from res in parserA
          from spc in spaces
          select res;

      var word = from w in token(asString(many1(letter)))
                 select new Word(w) as Term;

      var number = from d in token(asString(many1(digit)))
                   select new Number(Int32.Parse(d)) as Term;

      var term = either(word, number);

      var parser = from sp in spaces
                   from ws in many1(term)
                   select ws;

      var result = parse(parser, "   4 words are here");
      WriteLine(result.ToString());
    }
  }

  abstract class Term { }

  class Word : Term {
    public readonly string Value;
    public Word(string value) => Value = value;
  }

  class Number : Term {
    public readonly int Value;
    public Number(int value) => Value = value;
  }
}
```

**Comment by louthy** [comment]
@imranypatel This is slightly misleading.  I think if you check `result.IsFaulted` you'll realise it's `false`.  And if you check `result.Reply` then you'll find the values you're expecting.  The `Parser` is recursive and some types of `Parser` will capture errors and ignore them, but still pass the error __message__ back.  For example `many` and `many1` both need to stop parsing when their 'inner parser' doesn't succeed any more.  So, you're seeing the error from the `spaces` parser when it gets to the end of the stream - it can't parse a space any more, so it errors, but the `many1` parser still succeeds because nothing additional has been consumed.  

There are four states the parser can be in:

* Consumed OK
* Consumed Error
* Empty OK
* Empty Error

`Consumed OK` means that the parser succeed without any errors.  `Consumed Error` means the parser failed, but it did consume some of the input stream before failing.  `Empty OK` means that the parser succeeded, but there's no result (you can imagine that `many` which can return zero items would use this).  `Empty Error` - means the parser failed, but didn't consume anything.

`Consumed Error` is a fatal error for the parser, one which can't be recovered from, unless you wrap the parser with `attempt(p)`, which will turn the `Consumed Error` into an `Empty Error` (and rewind the stream to the point before it tried to parse the inner parser).  Certain parsers will consider `Empty Error` to be their cue to end (`many` and `many1` for example).  So, `many(attempt(p))` will be the most reliable way to deal with the parsing of a number of items.

Use this helper extension method to get something a bit easier to consume:
```c#
        public static Either<string, T> ToEither<T>(this ParserResult<T> result) =>
            result.IsFaulted
                ? Left<string, T>(result.Reply.Error.ToString())
                : Right<string, T>(result.Reply.Result);
```
It converts a `ParserResult` to an `Either`.  `Left` is the error, `Right` is the result.

By the way, it's possible to build that parser to not return have anything at all in the `Error` field, but that was outside the scope of that tutorial.

If you're wondering why it propagates at all, it's so certain 'parent' parsers could collect a series of 'child' parser results and munge them together into something a bit more useful.  It makes sense whilst in the midst of a parser expression, but less so when you're calling the parser with a real stream: that's where the `result.ToEither()` comes in useful.

I know there's limited documentation on the lang-ext Parsec, but it is an almost 1-to-1 port of the Haskell Parsec library, so it's useful to know when looking for tips.

**Comment by louthy** [comment]
@imranypatel If you get the latest version (`2.2.27-beta`), I have updated the `ParserResult.ToString()` implementation, so it doesn't give misleading results.  You should see: `Success(x)` where `x` is the `Reply.Result`.

I have also added `ToEither()` which will convert the `ParserResult` to an `Either<string, T>`; `ToEither<ERR>(Func<string, ERR> f)` which takes a function that will convert the `string` error to an error-type of your choosing.  

If you're using `NewType` for an `Error` type:
```c#
    public class Error : NewType<Error, string>
    {
        public Error(string value) : base(value) { }
    }
```
Then you could do this:
```c#
    var res = parse(parser, "   4 words are here").ToEither(Error.New);
```
Hopefully that should remove any confusion.

**Comment by imranypatel** [comment]
@louthy Thank you for elaborated response. 

(2.2.27-beta) has addressed the problem of misleading result of ParserResult.ToString().

Not sure how significant it is but it was not clear how @bender2k14 attempt was a success with same versions of library and target framework as was mine.

Thank you again!

P.S:
I've just started using LanguageExt as one of the means to the end of reformed programmer!
Am curious whether you've have seen my request on gitter on 6th April? Or should I post it again here?
Some thoughts would help in increasing pace of learning.

**Comment by louthy** [comment]
@imranypatel  Just to be clear.  The code hasn't changed the example or the outcome - I got the same results as @bender2k14  - it's just the `ToString()` implementation was misleading.  The results were correct and as stated in the Wiki documentation - `IsFaulted` was `false`, and `Reply.Result` did contain the correct result.

> Am curious whether you've have seen my request on gitter on 6th April?

I did see it, I started writing a reply, but got pulled away on something else.  Yes, the Free Monad approach would work well in that situation.  Although if you're just getting into this stuff then you may want to keep it simple and write some basic mapping functions from one type to another.  That's all the outcome will be: a series of operations which describe map computations.  The benefit of the Free Monad approach will be that you can encapsulate the side-effecting code (printing), which will also make it easier to write unit tests.  

Btw, it's often better to ask those types of more in-depth questions on these Issues pages - it's much easier to give code examples and can serve as future reference for others looking for similar solutions.  So, feel free to open up a new issue and we can discuss it there.

**Comment by imranypatel** [comment]
@louthy Thank you for clearing it further.

I'll be adding new issue on Free Monad usecase here as well to discuss it further while keeping your advice to starting with something simpler esp when developing basic intiuition.

I admit that the level am at this stage where I find it bit challenging further transforming values from `res1` in the following:
```
var res1 = parse(parser, "   4 words are here").ToEither(Error.New);
```
I am able to tinkering like:
```
var res1a = res1.Match(Right: r => "Success", Left: l => "Failed");
```
I can explore through debug/watch that:
```res1 = {Right(LanguageExt.SeqCons`1[FPLibsLanguageExtTester.Term])}```
```Right = {LanguageExt.SeqCons<FPLibsLanguageExtTester.Term>}```
```LanguageExt.SeqCons<FPLibsLanguageExtTester.Term>``` contains at:
    ```[0] = {FPLibsLanguageExtTester.Number}```
    ```[1] = {FPLibsLanguageExtTester.Word}```
    ```[2] = {FPLibsLanguageExtTester.Word}```
    ```[1] = {FPLibsLanguageExtTester.Word}```

But finding bit challening getting access to values inside containers and map further based on actual types `Number or Word` subtypes of `Term` using `Match`. 

Hopefully things get to next levels once intiuition is improved for transforming (i.e. mapping/filtering/reducing) output of library functions.

While am digging through samples/docs, would appreciate more help to further transformations.

Thank you!

**Comment by louthy** [comment]
> But finding bit challening getting access to values inside containers and map further

It really depends on what you want to do, if you want to continue working with the results then you can just use LINQ:
```c#
var res1 = // Either<string, Seq<Term>>

var res2 = from terms in res1  // now terms == Seq<Term>
           let onlyWords = terms.Filter(t => t is Word).Map(t => t as Word)
           select onlyWords;
```
`res2` will now be an `Either<string, Seq<Word>>`.  You could also do it fluently:
```c#
var res2 = res1.Map(terms => terms.Filter(t => t is Word).Map(t => t as Word));
```
If you want to get at the raw `Seq<Term>` then you have to decide what to do if you get an error.  For example, let's say you ignored the error and decided that it represents zero terms:
```c#
var terms = res1.IfLeft(_ => Seq<Term>());
```
Then `terms` is just a `Seq<Term>` which is either empty or has the parsed terms in it.  I find it's usually best to stay in context (maintain the `Either`) for as long as possible, so if I had something that processed the terms then I would get that to return an `Either` too, and then that makes composition and error handling much easier.  For example, let's say we had a function that parsed the text and then validated the terms:
```c#
    Either<string, Unit> Validate(string text) =>
        from terms in parse(parser, text)
        from result in ValidateTerms(terms)
        select result;

    Either<string, Unit> ValidateTerms(Seq<Term> terms) =>
        term is Word word     ? ValidateWordTerm(word)
      : term is Number number ? ValidateNumberTerm(number)
      : Left("Unknown Term type");

    Either<string, Unit> ValidateWordTerm(Word word) =>
        word.Length > 1 && word.Length < 8
            ? Right<string, Unit>(unit)
            : Left("Invalid word");

    Either<string, Unit> ValidateNumberTerm(Number number) =>
        number > 100
            ? Right<string, Unit>(unit)
            : Left("Invalid number");
```
I think it's often easy if you're coming at the functional programming thing from the OO world to get into the 'must abstract' mindset.  I think it's very much the case that functional programming is more about concrete behaviour with known sets of types.  Clearly you could add inherited methods to Term/Word/Number to do the Validation, and in this instance it may well be better - but then Term, Number, and Word are 'infected' with the decision on how to validate - whereas with my example above it's contextual and the Word and Number types are just pure data.

Ultimately pick a solution that is appropriate for the problem you're trying to solve.  There are real benefits to separating data and functionality (the opposite of what we're told is good in the OO world).  Especially when the data is immutable - that's when the systems become really powerful.  It's easy to move immutable blocks of data around a system, it's easy to move immutable blocks of data between systems.  Then each sub-system can have its own local functionality that deals with those data blocks.

The costs that come with this approach is well captured by the [Expression Problem](https://en.wikipedia.org/wiki/Expression_problem), which means it's more difficult to extend a system built in the functional paradigm - for example, if I add a new type that derives from `Term` then I don't immediately get a validator, or anything like that.  

That's the cost of functional - but my personal belief is (so, you can choose to ignore) that the OO world abstracts unnecessarily 99% of the time.  And needs to extend existing types functionality rarely.  It's a myth that we need to build in abstraction layers by default _"just in case"_.   And, so the few times that it's needed (in the functional world) it does mean some additional diligence (especially as we haven't got proper discriminated unions and pattern matching with exhaustiveness checking).  

I can live with that because I believe that functional programs are significantly more robust, easier to test, and are cognitively easier to deal with when applications get to a super large scale.

**Comment by imranypatel** [comment]
While giving it another read I've observed that some correction is needed in:

1. ```ValidateTerms``` because it is passed   with ```Seq<Term>``` whereas it is operating on ```Term``` level
2.  Both ```ValidateWordTerm``` and ```ValidateNumberTerm``` because value of the parameters passed to it would be accessible through actual ```Value``` property so it has to be ```word.Value.Length ``` and ```number.Value```
