### ISSUE TITLE
Why does Option<T> allow IEnumerable extensions? Seems counter-intuitive

### ISSUE THREAD

**Issue by dgreene1** [louthy/language-ext#456]
So the following code compiles:
```
Option<string> hello = new Option<string>();
hello.First();
```

This is a simplistic example, but I'm not really sure why it's happening. Can someone provide clarity?

My concern is that it allows developers to circumvent all of the goodness that Option provides.

That wold be like doing the following:
```
Nullable<int> couldBeANumber = null;

someMethodThatRequiresAValidNumber(couldBeANumber.Value)
```

Note that I didn't check `couldBeANumber.HasValue` first. Which is why Option<T> doesn't have a `.Value` method. It only has `IfSome`, `IfNone`, `Match` etc.

**Comment by louthy** [comment]
> My concern is that it allows developers to circumvent all of the goodness that Option provides.

In your example it would throw a `Sequence contains no elements` exception.  That is a general risk with the LINQ API.

The reason for supporting this is:
1. To make the type work with Json.NET --- yes, annoying, but Json.NET kept breaking with this type so I made it support the enumerable serialiser that seems to never break.
2. It's relatively natural to think of an `Option` as a collection of zero or one items.
3. Because of the above concept it means you can easily use `Option` in LINQ expressions with other enumerable types without converting them manually.

I would prefer it to not be an `IEnumerable` and instead have manual conversion to `IEnumerable`, but unfortunately reason `1` is such a biggy in .NET-land that I need to maintain it.  The amount of times that I made `Option` work with Json.NET, only for a bug to be raised a month later that it doesn't deserialise, was ridiculous.

**Comment by louthy** [comment]
I guess a final point is this: even if it weren't an `IEnumerable` you'd still be able to do this:
```c#
   var x = option.AsEnumerable().First();
```
At some point you just need better policies in place internally to stop devs doing stupid shit.

**Comment by louthy** [comment]
Your preference is not my preference or many other’s preferences. Most
people want serialisation to ‘just work’ - especially with the most popular
method of serialisation in the .net world.

**Comment by bender2k14** [comment]
And I get the impression that most programmers prefer object oriented programming over functional programming.  Normally you prefer compile errors over runtime errors.  The purpose of my question is to get a better understanding of when you choose to forgo compile errors and permit runtime errors.

**Comment by louthy** [comment]
It’s not forgoing compile errors you are mistaken.

**Comment by louthy** [comment]
I was away from my machine, this is a more considered response:

@bender2k14 I think you have a tendency toward absolutism, which in software development is rarely useful.  

Your premise is this: You can't rely on serialisation of 3rd party types, so you must build your own, because it might change in the future.

I always come at problems from the point-of-view of a working programmer and what their needs are.

So, let's list some needs for serialisation:

* Storing settings in a file
* Storing a representation of an object in a database
* Sending a message from one service to another
* Storing a representation of an object in a cache (say Redis)

Then let's also look at the premise of lang-ext:

"To provide a functional-programming 'Base class library'"

The idea of a 'base-class library' is to be as static as possible.  No breaking changes.  Now, obviously that's not entirely true, but that it is a goal of this library to become more and more fixed over time.  Things like the format of serialised types _should never change_.

## Storing settings in a file

Ok, so the options are:

I call:
```c#
    File.WriteAllText(file, JsonConvert.SerializeObject(settings));
```
Or, I build my own serialiser.  Or, I copy the settings to a new type that doesn't have things like `Option` in and serialise that.  


Then I load them with:
```c#
    var settings = JsonConvert.DeserializeObject<Settings>(File.ReadAllText(file));
```
Or, I write my own deserializer, which then sets up the `Settings` type.

The problems I see with the first approach are the same as what you state.  If the underlying serialiser changes, then you can't load your settings.  The problems I see with the second approach is that, with each setting you add, you have to remember to update your serialiser and deserialiser.  It also uses more memory and is probably slower (although for this use-case that probably doesn't matter).

What's the mitigation strategy for the first issue?  Write a settings file migrator to migrate old to new.  Probably involves loading up the file with:
```c#
    /// Note: it's the untyped variant
    JsonConvert.DeserializeObject(File.ReadAllText(file));
```
Then manually fixing up the bad data and re-saving.  

I'd argue that isn't so bad if your settings file has a version number in it, or gains one after migration.  The alternative of building your own serialiser and maintaining a mirror structure is full of potential error vectors: copy n paste problems, missing item problems, dealing with null, etc.

## Storing a representation of an object in a database

This is pretty much the same problem as above, but I suspect that the reason the object is in a database in the first place is that there are multiple services using it.  This is where decisions need to be made:

* You can either take all services down, migrate the data, and bring them back up
* Or, you can abstract the serialisation as you advocate

Again, this will depend on the project.  Neither options are perfect.  You will still get the silent bugs with the second option, but the first has downtime implications, or on-screen user error implications with non-migrated data.

This is where the performance implications start to rear their head.  You incur costs by copying data to intermediate types, or by writing your own poorly considered serialiser.

## Sending a message from one service to another

Ok, so this will depend on whether the message is ephemeral and/or important.  Most service architectures should be designed to survive any message being lost, so if a message fails to deserialise then it seems reasonable to fire it off to dead-letters.  

So, why would you ever want to erase the important type information of something being optional? (by migrating to an intermediate 'DTO' type without the `Option`, `Either`, etc. in it)

Well, some in systems it may not be possible to update every service in the distributed architecture and therefore an Option being serialised and deserialised in different ways isn't going to help anybody.  That would be a reason to go the route you advocate.

The flip side of the argument is that `Option` serialisation and deserialisation never changes.  And if it did, then you could plan the migration of your architecture.  The reason I say this is: what do you want to spend your day on?

* Writing DTO objects that almost exactly replicate existing objects and manually writing error prone serialisers
* Or, none of the above, but once every few years you need to update all your services in one go?

I'd take the second option, but again it would entirely depend on the application.

## Storing a representation of an object in a cache (say Redis)

Caches can be flushed.  In some ways this problem is the same as the messaging one.  If the cache needs to be shared between services then the representation must match, so all serialisers must work the same.  But on the whole this is an example where just serialising an Option would make sense.

Similar list of points:
* You could update everything
* You could abstract away the problem by forcing yourself to write error prone manually written serialisers
* You could set up a second cache for the newly updates services - so old and new run side by side

The last item is new, but is an option to reduce the need to write endless boilerplate.

## DTO

Even the idea of DTO objects makes me cringe slightly, DTO is another example of a coping strategy for the problems of OO, which are:

* The attachment of functionality to classes - which often constrains the type to live in the application its in
* The use of hidden state - which means only the type itself knows how to construct itself and how it got to its current state.  Making it fundamentally un-serialisable.

Personally I write types to be like simple record types:
- Immutable
- No externally dependent functionality 
- No hidden state - other than that which can be re-calculated easily (like a hash code for example)

That means I can often create a shared 'schema' project of common record-types and then just move them around between services without having to break them down into DTO objects.  The only time I'll build, what you'd call, a DTO is to limit the amount of data moving around, so I may write another record-type that contains a subset of the fields of the larger one.

I will also build message-types for use with echo-process that use `Option`, because I don't want to be doing `null` checks at the other end.  

## Conclusion

So, it's clear that in many circumstances it's valid (and cheaper in man-hours) to use the off-the-shelf serialisation.  There are trade-offs with both approaches.  But because one of the approaches requires language-ext's types to be serialisable: they are, and they will continue to be.

**Comment by bender2k14** [comment]
Thank you very much for this thorough response.  I very much appreciate the time and effort you put into these discussions.

Your section on DTOs makes me think that we have of different understandings of what a DTO is.  To me, a [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) is syntactically a [POCO ](https://en.wikipedia.org/wiki/Plain_old_CLR_object) (i.e. no inheritance, no functionality...just public properties for members) and semantically its reason for existing is to quickly move data from one place to another.  As such, its lifetime is very short.

We might also have different ideas about about what (de)serialization is.  Is every lifting or lowering of a type considered deserialization or serialization (respectively)?  For example, is `TimeSpan ts = TimeSpan.FromMinutes(1.0)` deserializing a `double` into a `TimeSpan`?  Is `double d = ts.TotalMinutes` serializing a `TimeSpan` into a `double`?  I would say no.  I think of serialization as converting to a type like `string` or `byte[]` (and deserialization as the reverse).

I could ask several followup questions to your post, but I would like to first share three examples of "needs for serialisation" that I am familiar with to hep ensure that we both talking about the same problem and solutions.  My intention with these examples is to convey my experience and understanding of these technologies and show how they have helped to form my opinions about DTOs.  I am is not trying to inform you in some general sense about technologies that exist or what they can do.

### Data Context in WPF
In [WPF](https://en.wikipedia.org/wiki/Windows_Presentation_Foundation), the UI is written in a declarative markup language called [XMAL](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-overview-wpf).  Data is supplied to this UI by referring to properties, by name, on a class known as its data context.  If such a UI refers to a nonexistent property, then this mistake is typically found by debugging the application in Visual Studio, loading that particular view, and observing in the log a data binding error.

To avoid these runtime errors, I prefer for the data context types to be DTOs.  Then I can refacor within C# except for these DTOs and know that I haven't broken anything.  The best factoring example is the renaming a property.  With this approach, the UI should change if and only if I change something in these DTOs.

### Client-Sever Communication
Data, after being serialized, is sent from the server to the client.  When the client is written in JavaScript, the behavior is similar to the previous case.  Data is accessed in the UI by property name.  Mistakes are found by running the server, loading a page in a browser like Chrome, and observing in the console that the attempted reading of a nonexistent property.

I avoid these runtime erros in the same way using DTOs.  Again, the UI should change if and only if I change something in these DTOs.

Instead of JavaScript, one can use TypeScript and then use [TypeWriter](https://frhagn.github.io/Typewriter/) to generate TypeScript types to match the C# types.  This doesn't remove the need for the DTOs though because I still can't use  `Option<>` as the type of a property on one of these DTOs.  (As least, I think this won't work because I don't think TypeWriter knows what type to use in TypeScript for `Option<>`.)

### Database with Entity Framework
Nearly all of my experience interacting with a database has been through Entity Framework (EF).  The enities are the primary source of information used to create the model of the database used by EF (such as which column are nullable, which column is the primary key, what constraints...such as maximum string length...exist, what addition behaviors should occur when a record is deleted or updated, etc.).  It is possible to specify all this configuration using the fluent interface, but that involves lots of extra work, the work is error-prone, and those errors are runtime errors.

A nice way to ensure that this configuration is correct is to generate the entities (and any additional configuration) based on the database.  (As far as I know, this is only possible if the database is Microsoft's SQL Server.)  These autogenerated types might specify some of the configuration via property attributes.  This information is specific to this SQL Server data storage solution, so my business models will be different types.  These entities then are just DTOs for the purpose of getting data from the database and into my business models (or vice versa).

I don't want to modify these autogenerated entities by adding an `Option<>` type, nor do I want to deal with the problem of configuring EF to properly map data within an `Option<>` type to and from a database.

### Conclusion
In the sense of (de)serialization that I defined above, none of my examples include custom serialization code.  Admittedly though, they would typically include some liftings when mapping from the (short-lived) DTOs to the final (strong) type.

I always want to use "off-the-shelf serialisation" in the sense that I do want to use a standard serializer like `Newtonsoft.Json.JsonConvert` with the simplest calls like `SerializeObject(Object)` and `DeserializeObject(Object)`.  I do _not_ want to make calls like `SerializeObject(String, JsonSerializerSettings)` or `DeserializeObject(String, JsonSerializerSettings)`.  Instead, I would prefer to change the type being serialized.  I think this is easier for developers to read and understand.

**Comment by louthy** [comment]
> Your section on DTOs makes me think that we have of different understandings of what a DTO is

We don't.  I just see them as mostly unnecessary when using record-like types everywhere.  But the reason they exist in the first place is because of the problems with the OO way of doing things which makes most hidden stateful, mutable, external-dependency-carrying types unusable for data-transfer... either between application layers or between application domains.

Regardless of terminology, there is still the trade-offs that devs make between building their own serialisation primitives and just not doing it.  If you want to build DTOs great, and I understand your reasons.  I personally believe that it's unnecessary overkill nearly all of the time.  

The moment one person doesn't want to build their own serialisation abstraction then this library should allow them to get their job done.  There is no right or wrong here, only trade-offs, that's why it just isn't as black and white about whether we should support serialisation or not.  If you want it, it's there.

In the large projects I work on daily we very rarely need to build bespoke serialisation code - possibly because we just don't use any of the Microsoft mandated tech like EF, WPF, etc.  None of that is even on our radar.  We do however need to move messages around our system using `echo-process`, which is how our services talk to each other and how the client browser can talk to/from the server.  I have an absolute motivation for the serialisation of the core language-ext types, like `Option`, to stay the same, because all of our services and subsystems use serialised messages to talk to each other.  But I also would find it a minor annoyance if it were to change, the migration strategy is relatively trivial.  Not zero work, but less work than the ongoing maintenance of shadow DTO types and bespoke serialisers.

So, essentially my message is: it must be supported, but you don't have to use it.

**Comment by kdblocher** [comment]
Interesting discussion, thanks @louthy and @bender2k14!

@dgreene1 - For what it's worth, with language-ext, I've taken to simply not including the `System.Linq` namespace anywhere I don't want anything "extra" such as serialization support, and by convention use the functional-style naming for domain functionality and use the LINQ-style naming for anything that is "special" (such as EF queries, serialization, interop between `null`/`void`/OOP style). It's not a perfect solution, but it's a good convention-based approach to quickly look at the code and see what the context of data transformation is going on.

Like @louthy said, I do think it's reasonable to strike a balance between purity and practicality. Thanks for your efforts - certainly I don't think @bender2k14 would be so passionate about his contributions here if he didn't think your library is already awesome, because he's that kind of guy ;)

**Comment by dgreene1** [comment]
Thanks everyone for the input, especially this comment:

“It's relatively natural to think of an Option as a collection of zero or one items.”

Yes, that makes sense. I don’t like that it exposes .First which is essentially .Value, but at the end of the day the responsibility for writing safe code lies in the shoulders of the developer. Someday (hopefully soon) we’ll have reference types that default to non-nullable just like TypeScript, Swift, and Kotlin provide.

Until that day, Optional will help us get most of the way there.

Thank you everyone for your contributions! :)
