### ISSUE TITLE
Either vs Validation

### ISSUE THREAD

**Issue by xlecoustillier** [louthy/language-ext#457]
Validation<F, S> seems to have the same behavior as Either<L, R> except that it also collects errors.

If its functionalities are a superset of Either's, is there still an advantage to use Either rather than Validation ?
Does Either have any functionality that Validation doesn't ?
Are there some performance noticeable differences ?

Thanks!

**Comment by louthy** [comment]
I guess the idea you express that `Either` is for _a value_ or _an error_ is the main thing that needs dispelling.  It isn't really true, it's a type that can represent two values, it just happens to have monadic bind behaviour that shortcuts the computation when in a `Left` state -- which is very useful for errors, yes, but it's not essential.  

So, when it comes to being declarative, `Either` is more about saying:

> _**"I have either one a value of this type, or a value of that type"**_

It isn't opinionated in its name - only its bind function.

Whereas clearly by virtue of its name `Validation` _is_ opinionated.  It has one role to perform: validation - and is built for those reasons.  

As you've noted the types are very similar, but when it comes to being declarative they're different.

The natural next argument from then would be: "Why isn't there an `Error<Err, A>` type if you love being so declarative?".  There probably should be, but it's arguably overkill here.  

In terms of performance, there's a very slight performance benefit to using `Either`, because its _alternative_ value is just a value, whereas in `Validation<F, S>` it's a `Seq<F>` and that comes with more overheads than dealing with just a single value reference.  We're talking negligible differences here, but perhaps in a tight loop the differences would start to show.

Obviously with `Validation<MonoidF, F, S>` it depends which monoid you use to collect the failure results as to the potential performance hit, but on the whole it will have the same performance profile as `Validation<F, S>`

**Comment by xlecoustillier** [comment]
Hi Paul, 

Thanks for the answer. You're right, I should have specified that in this case I considered Either left value as an error one. In fact, I use it so much for this usage that I forgot (here only, fortunately) that it can be used another way (and the fact that the documentation states that Left cancels bindings and mappings, or is an "early out, with a message" comforted me in this idea).

Anyway, I got your point (to be honest, I was even already nitpicking on "why a Validation class?" before I discovered the difference with Either, hence my question :) ). I can therefore definitely live without an Error class.

Closing then.

Thanks again!
