### ISSUE TITLE
Replacing ImmutableCollections

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#459]
Hi,

just discovered that I can use your beautiful library with Unity 2018.2, yey! I want to replace ImmutableList and ImmutableDictionary with Lst and Map but I see API incompatibilities after simple replace: 

- no "ToLst()" (equivalent of ToImmutableList()) extension method for IEnumerable<T>, this means:

1) need to explicitly repeat T for new: new Lst<TypeName>(enumerable) as ctor params can't be deduced
2) no possible optimization if IEnumerable<T> is actually Lst<T> already as new Lst<> is always created

- for some reason Lst<T> is not implicitly cast to IEnumerable<T>. In current code I have: IObservable<ImmutableList<T>> obs;
obs.Subscribe(OnDataChanged);
// void OnDataChanged(IEnumerable<T> data);

if I replace ImmutableList<T> with Lst<T>, Subscribe Action/method group is no longer accepted as valid argument

- There is no Lst<T>.Replace(old, new), what should be used instead?

- I don't quite understand semantics of Record<T> structural equality, docs say it only considers fields or field backed properties but doesn't say about it's access restrictions (pub / priv) I also noticed that auto-properties ARE considered in comparison as well as in ToString() generation. Side question: does ToString() use exact same fields that Equals and GetHashCode uses (so can be used for debugging which fields are used and which are not)?

- last but definitely not least: just addinf LanguageExt.Core to my project increased build time from 13 to 22 sec, any idea why? Can I reduce it back in any way?

**Comment by bender2k14** [comment]
> ...semantics of Record structural equality, docs say it only considers fields or field backed properties...

> I also noticed that auto-properties ARE considered in comparison

Auto properties are indeed field-backed properties.

**Comment by slimshader** [comment]
@bender2k14 Ah I see what you mean, my understanding of wording was that it had to be explicitly field-backed

**Comment by louthy** [comment]
> no "ToLst()" (equivalent of ToImmutableList()) extension method for IEnumerable, this means:

`enumerable.Freeze()`

Not the best named method ever, but I never foresaw implementing all the collection types I have ;)

> need to explicitly repeat T for new: new Lst(enumerable) as ctor params can't be deduced

Use the static prelude:
```c#
    using static LanguageExt.Prelude;

    var list = List(enumerable);
```

> for some reason Lst is not implicitly cast to IEnumerable

It is:  https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/List/Lst.cs#L19

But you have to realise that `Lst<A>` is a `struct`, not a `class` and because of that the `A` can't be covariant or contravariant.  That means if you want to cast a `Lst<SubType>` to `IEnumerable<BaseType>`, you can't.  It's a limitation, and if you use a lot of inheritance, you'll probably hit this issue a lot with lang-ext.

I very rarely see this issue as I avoid inheritance and unnecessary abstraction.

> There is no Lst.Replace(old, new), what should be used instead?

```c#
    Lst<B> Replace<A, B>(this Lst<A> ma, A oldv, B newv) =>
        ma.Map(a => EqualityComparer<A>.Default.Equals(a, oldv)
            ? newv
            : a);
```

> Side question: does ToString() use exact same fields that Equals and GetHashCode uses (so can be used for debugging which fields are used and which are not)?

Yes.

> last but definitely not least: just addinf LanguageExt.Core to my project increased build time from 13 to 22 sec, any idea why? Can I reduce it back in any way?

I've never profiled build times, but that seems slightly surprising.  I suspect it's because of the HKT generated functions.  Not much I can do for you there (bar removing the feature).
