### ISSUE TITLE
How to create value types

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#460]
Records are fantastic tool but is there a way to also add value semantics to classes that do not want to expose public fields?

**Comment by louthy** [comment]
No, they're explicitly built for `public` record-types, rather than the OO hidden state approach.

[This is the code](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/Utility/IL.cs#L566) for building the equality method for the record types.  You can see on line 573 how it gets the public fields.  You could roll your own that worked with private fields if you want to build something similar.
