### ISSUE TITLE
Discriminated unions support

### ISSUE THREAD

**Issue by slimshader** [louthy/language-ext#471]
Hi,

is there a type (or is it maybe in plans) to support Discriminated Unions aka Sum Types. Something like [OneOf](https://github.com/mcintyre321/OneOf) maybe?

**Comment by Richiban** [comment]
Are you looking for `Either<L, R>`? It only supports two arguments but you can always nest them.

**Comment by slimshader** [comment]
@Richiban Looking for a equivalent of [this](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/discriminated-unions)

**Comment by Richiban** [comment]
@slimshader Unfortunately I don't think there's anything LanguageExt can do for you there, since implementing proper DUs would require compiler support. Perhaps there is something it could do to help reduce the boilerplate, as it does with records.

Currently, if I want to implement a DU in C# I do something like this:


```fsharp
type FavouriteColour =
	| Red
	| Green
	| Blue
	| Other of string
```


```csharp
public abstract class FavouriteColour
{
	private FavouriteColour() {}

	public static readonly FavouriteColour Red = new FavouriteColour();
	public static readonly FavouriteColour Green = new FavouriteColour();
	public static readonly FavouriteColour Blue = new FavouriteColour();

	public sealed class Other : FavouriteColour
	{
		public Other(string value) => Value = value;

		public string Value { get; }
	} 
}
```

The interesting parts are: 
* The private constructor of the base type that "closes" the type (i.e. stops any external type from inheriting it)
* Data-less cases of the union don't need to be classes themselves; they're singleton values so they can just be static readonly fields or properties
* Cases that contain data should be a class

There is an argument for making even data-less cases a class so that they can be used with C# 7's basic pattern matching, something like this:


```csharp
switch(colourChoice)
{
	case FavouriteColour.Red r => Console.WriteLine("You chose red!"); break;
	case FavouriteColour.Blue b => Console.WriteLine("You chose red!"); break;
	case FavouriteColour.Green g => Console.WriteLine("You chose red!"); break;

	case FavouriteColour.Other o => Console.WriteLine("You chose another colour: {o.Value}. Nice!"); break;

	default: break;
}
```

Unfortunately C#'s compiler has no concept of closed type hierarchies so it can't check the switch statement for completeness and you must therefore add a default case every time, but still it's a step in the right direction.

---

Obviously this contains no equality or parsing code, feel free to add those. I don't know off the top of my head whether the base type could inherit from `Record<T>` to get those working.

**Comment by slimshader** [comment]
@Richiban Yup, [smart enum / type safe enum](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types) idiom (+ C7 PM) is what I currently do also but it seems that solution along the lines of OneOf + some IL emitting magic (as in Record) could help with boilerplate and safety?

**Comment by Richiban** [comment]
@slimshader Absolutely, especially since I've just discovered that inheriting from `Record<T>`:

```csharp

public class FavouriteColour : Record<FavouriteColour>
{
	private FavouriteColour() { }

	public static readonly FavouriteColour Red = new FavouriteColour();
	public static readonly FavouriteColour Green = new FavouriteColour();
	public static readonly FavouriteColour Blue = new FavouriteColour();

	public sealed class Other : FavouriteColour
	{
		public Other(string value) => Value = value;

		public string Value { get; }
	}
}
```

...doesn't work. Equality is incorrect and `ToString` is not generated.

@louthy Do you think this is something that is possible? Supporting this idiom with a `SumType` base class or similar, that will generate the IL necessary for each child class, instead of the base (as `Record<T>` does)?

**Comment by slang25** [comment]
It might be worth looking at an approach like this: https://github.com/Galad/CSharpDiscriminatedUnion

You could have a class that's defined like above, but it would generate the code in memory to add stuff like ToString and Match. It's also generated as part of a design time build, meaning those methods would show up immediately for use (if that makes sense, a little like type providers from F#).

**Comment by slang25** [comment]
Read here for more info on how this works: https://github.com/AArnott/CodeGeneration.Roslyn

**Comment by louthy** [comment]
I don't believe in adding support for this, as it's possible to do this now (with @Richiban 's approach, and as [already discussed here](https://github.com/louthy/language-ext/issues/466)) .  The OneOf approach isn't one that interests me, because it comes with a lot of baggage (plenty of typing of generics).  

The code-gen approach is fine, but again not really in the bailiwick of this library.

**Comment by Lonli-Lokli** [comment]
So no DiscriminatedUnions support, right? Why not?

**Comment by louthy** [comment]
@Lonli-Lokli I’d suggest reading the wiki 

https://github.com/louthy/language-ext/wiki/Code-generation
