### ISSUE TITLE
Multiple implementations of the query pattern were found for source type Task<*>. Ambiguous call to SelectMany.

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#476]
This issue is based on a [recent question](https://stackoverflow.com/questions/52247863/language-ext-task-of-either-with-multiple-from-clauses) on Stack Overflow.

Consider
```
    using System.Threading.Tasks;
    using LanguageExt;
    using Xunit;
    using static LanguageExt.Prelude;
    
    public class Class
    {
        [Fact]
        public async Task Method()
        {
            var three = await from a in Some(1).AsTask()
                              from b in Some(2).AsTask()
                              from c in Some(3).AsTask()
                              select a + b + c;
        }
    }
```

The line `from b in Some(2).AsTask()` has the compile error

> [Error CS1940](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1940) Multiple implementations of the query pattern were found for source type 'Task<Option<int>>'.  Ambiguous call to 'SelectMany'.

![screenshot 2018-09-10 15 16 04](https://user-images.githubusercontent.com/34664007/45323474-cc825d80-b510-11e8-9085-3d2a89ffb2cf.png)

The images shows that the compiler is having difficultly selecting a method from among three alternatives (the one displayed there and two additional overloads).  The three overloads are the [intended one](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/HKT/AsyncSync/HKT.AsyncSync.Extensions.cs#L5140) (although that link won't display in GitHub because the file is too large), which is an extension method of `Task<Option<>>`, and two [false](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L79) [positives](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L89), which are extension methods of `Task<>`.

My understanding of this problem is that there isn't enough (local) type information involving the variable `a` .  If we modify the above code example to provide more type information for `a` like
```
var three = await from a in Some(1).AsTask()
                  from b in Some(a - a + 2).AsTask()
                  from c in Some(3).AsTask()
                  select a + b + c;
```
then the code compiles and behaves as expected.

Is this ambiguity something that we care about or should do something about?

**Comment by louthy** [comment]
> Is this ambiguity something that we care about or should do something about?

It's tough.  They're not really false positives to be honest, because the  `Option<A>` supports the `+` operator, and so the bind that belongs to `Task<A>` will produce a valid result just like the bind that works with `Task<Option<A>``.  The whole expression is valid for all bind extensions, which is obviously why we have that ambiguity.  

It's a shame that changing `var three = ...` to `Option<int> three = ...` doesn't change the inference system.  Because that's the key difference between the two possible expressions that the compiler is confused by.

My instinct would be to remove the `Task<M<A>>` bind, but that would probably be a breaking change for a number of people.  It would need some thought, which at 2am I'm probably not best to do!

I'm sure there's another issue that brought up a similar problem with `Task` bind.  Struggling to find it though.

**Comment by louthy** [comment]
I guess the best advice here is to use `OptionAsync`, `EitherAsync`, etc.  those types obviously always behave well.
