### ISSUE TITLE
Question - Composing Free monads

### ISSUE THREAD

**Issue by michael-wolfenden** [louthy/language-ext#477]
I was watching the following talk [Compositional application architecture with reasonably priced monads](
https://www.youtube.com/watch?v=M258zVn4m2M) in which the speaker demonstates [composing multiple free monads together in scala](https://gist.github.com/runarorama/a8fab38e473fafa0921d).

For example composing the free monads below

```scala
class Interacts[F[_]](implicit I: Inject[Interact,F]) {
  def tell(msg: String): Free[F,Unit] = lift(Tell(msg))
  def ask(prompt: String): Free[F,String] = lift(Ask(prompt))
}
```

```scala
class Auths[F[_]](implicit I: Inject[Auth,F]) {
  def login(id: UserID, pwd: Password): Free[F,Option[User]] =
    lift(Login(id, pwd))
  def hasPermission(u: User, p: Permission): Free[F,Boolean] =
    lift(HasPermission(u, p))
}
```

allowing a program like

```scala
def prg[F[_]](implicit I: Interacts[F], A: Auths[F]) = {
  import I._; import A._
  for {
    uid <- ask("What's your user ID?")
    pwd <- ask("Password, please.")
    u <- login(uid, pwd)
    b <- u.map(hasPermission(_, KnowSecret)).getOrElse(Return(false))
    _ <- if (b) tell("UUDDLRLRBA") else tell("Go away!")
  } yield ()
}
```

After looking through the samples ie `BankingFree` I can see how to implement a single free monad but am curious if it is possible to compose multiple free monads in C# given it's weaker type system.

**Comment by louthy** [comment]
@michael-wolfenden I haven't managed to find a way to generalise the Free monad, yet.  So, any solution would be a bit of a hack I'm sure.  Usually, if I use the _free monad technique_ to create a bespoke monadic type that abstracts intent from effect (like the `BankingFree` example) then I am doing it because I want to _put something in a box_... that is, I want it to exist is a sub-system and have an algebra that describes the subsystem (the types).  

I am yet to fully explore the idea of composition, because first of all I'd like to find an approach to generalise the Free monad itself (which I suspect would allow composition to fall out of it naturally).

I'm afraid when I look at Scala my brain just starts shutting down because I can never get over the use of `[` and `]` for generic parameter delimiters.  And so, it's not entirely clear what your example demonstrates.

I have attempted to create nested 'free' monads which allow for layered systems (like a `Free UI`, `Free Business`, and `Free Data Access`, ... with limited success).

It's something I will return to at some point, I suspect it would need something similar to the records IL generation to make everything work.

**Comment by michael-wolfenden** [comment]
Thanks for your response.

To clarify, the example was trying to demonstrate what you were alluding to, the ability to seperate out various free monads but still have the ability to combine them into a single program.

So instead of having a single free monad for all the IO in my domain, I could have seperate ones `FreeUI` and `FreeAuthentication` but still have the ability to compose them together into a single program (like the nested free monad you alluded to)

```csharp
from uid in UI.ask("What's your user ID?")
from pwd in UI.ask("Password, please.")
let user = Authentication.Login(uid, pwd)
```

**Comment by louthy** [comment]
@michael-wolfenden Yep, I thought that might be the case, but wasn't too sure.  Having them side-by-side like that in a single LINQ expression would be tough to achieve - because you'd need a way of combining the interpreters and that's messy.  

What I was alluding to would be the ability to lift one free-monad into another and then have an _adapter_ in the outer interpreter that would kick off the inner-interpreter.

Something like:
```c#
    from uid in UI.ask("What's your user ID?")
    from pwd in UI.ask("Password, please.")
    from sid in UI.Auth(
        from user in Authentication.Login(uid, pwd)
        // ... continue working in the Auth layer ...
        select user.SessionToken)
    from // ... continue working in the UI layer
    from rgt in UI.Auth(
        from r in Authentication.HasRight(sid, Rights.ViewDemographic)
        from e in Authentication.HasRight(sid, Rights.CanEmail)
        select (HasDemo: r, CanEmail: e))
    where rgt.HasDemo && rgt.CanEmail
    select ...
```
I didn't get massively far with this due to the limitation of any Free monad type to having a single generic argument.  This limitation comes about because of the pattern-matching in the bind functions and the interpreter.  It meant that `UI.Auth(...)` would have to be a `UI<Auth<object>>` or something similarly non-typesafe.  

So, I kinda stopped until I could find a cunning way to get around the type-system.  However this did spark a bit of interest again, so I had yet another go at it (I must have had a dozen attempts so far!), and I have built a prototype that uses reflection to build the `bind` function automatically.  That's the first step to making this work, but to make it efficient and useful it would have to build the IL needed for matching, dispatching, and binding without reflection.  I suspect there are also a ton of edge cases - and so don't hold your breath waiting for this, but progress is being made.
