### ISSUE TITLE
Why do coll.Find(1, p => p.Key == 1) and find(coll, 1) produce different types?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#483]
Another stupid question!

Reading the docs, I got the impression that some of the standalone functions did the same as their extension method counterparts. For example, for a list of ints, the following do the same...

`list.Reduce((s, x) => s + x)`
`reduce(list, (s, x) => s + x)`

Why then if I have a Map, do the following produce different types...

`coll.Find(1, p => p.Key == 1) // produces a Option<(int, string)>`
`find(people, 1) // produces a string`

Thanks for any explanation.

**Comment by louthy** [comment]
They're different functions, not sure why you think they're the same?

```c#
    find(map, 1);
```
Is equivalent to:
```c#
   map.Find(1);  
```
The equivalence [is pretty much guaranteed](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Map/Map.Module.cs#L443)

I think there's a typo in your example, because I think [what you've actually stumbled on](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/List/Lst.Extensions.cs#L608) is `IEnumerable.Find(Func<A, bool> predicate)`. 

`Map` is both a tree and an `IEnumerable<(K, V)>`, and so in this case you're iterating through every item in the map.

That's not to say that there is always parity between the `static` functions and the instance methods.  But, in this case there is.
