### ISSUE TITLE
Value type tuples.

### ISSUE THREAD

**Issue by orthoxerox** [louthy/language-ext#49]
To save some heapallocs it might make sense to reimplement tuples as value types (this might happen in the next CLR as well, but hasn't been done yet).

It's possible to reuse MIT-licensed https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Tuple.cs to save time.

**Comment by louthy** [comment]
Hi @orthoxerox - That's super interesting that they're considering changing it.  Normally I'd run with a solution like this, but there's a few reasons I'm not sure this is a good idea:

* A lot of tuple use is temporary (return values, local vars) and I suspect is more likely to be on the stack than the heap; and therefore is unlikely to be a huge burden.  I have to be honest, I don't know what the criteria is that the CLR uses to decide between heap and stack usage - I assume there's some cleverness in the compiler that can tell if an item is going to be assigned to a non-local variable.  I have read comments from Eric Lippert that as a coder you can't really know.  
* If the CLR team are planning to change it, then introducing a new Tuple type seems unnecessary and may lead to confusion.
* Quite a lot of this library already relies on `struct` types for `null` reference protection; I'm not sure I'd prefer `Tuple` to be a reference type for that reason.  This library is definitely more about correctness than outright performance (whether it's CPU or memory); in a past life I wrote 3D graphics engines for the Playstation and the like, I remember getting an entire graphics engine running in the 4Kb instruction cache on the PS1 and going insane maintaining it.  My preference these days is to have correct code.  If I could be assured of the same guarantees by using a reference-type and get a performance gain then I'd go for it; but I'd rather not chase it for marginal gains.   
* Finally:  What would it be called?  It's already a bit icky that I have to call the list-type `Lst` and the stack-type `Stck`.  `Tup`, `Tple`, `Tupl` ?  

Anyway, that's my brain dump.  Let me know what you think.

**Comment by orthoxerox** [comment]
To quote [Eric](http://blogs.msdn.com/b/ericlippert/archive/2010/09/30/the-truth-about-value-types.aspx):

> In particular, the storage locations of instances of reference types are always treated as though they are long-lived, even if they are provably short-lived. Therefore they always go on the heap.

Of course, he mentions that this is generally an irrelevant implementation detail, since even local instances of value types go on the heap when they are closed over or are in an iterator block.

The most important distinction is their semantics. Current tuples have value type semantics despite being implemented as classes: they are immutable, so copying by value or by reference is semantically indistinguishable, and they compare their contents when testing for equality.

I guess the difference will only add up when you will aggressively use lots of short-lived tuples. Perhaps it might be wise to wait for that `ValueTuple` type.

**Comment by louthy** [comment]
Sorry!  I just realised I've been reading this all wrong.  I could have sworn `Tuple` was already a value-type.  Even after looking at the coreclr source (I assumed I was looking at a branch!).  Wow, can't believe I missed that.  So, it seems they can be `null`.  That puts a different spin on things...

My overarching thoughts on this kind of optimisation is it's usually misplaced.  I've written garbage-collectors in the past, and they're super-fast at allocation.  So heap allocation is almost as quick as stack allocation.  Obviously the generational collection part is where things slow down, but if you're really concerned about collection stalling your app then developing in a managed language may not be the right choice.  Or you can use mitigation strategies like pre-allocating all the objects you need and build a free-list allocator (although clearly that doesn't help with immutable types).  

Hmm.  Ok, let me thing this one through a bit.  This now puts the additional 'correctness' spin on things.

The new concerns would be:

* If I re-purposed all of the existing tuple API to generate `VTuple` instead of `Tuple`, then anyone using the existing API could have their code broken
* If I provide implicit conversion operators from `VTuple` to `Tuple` and back then that could double the allocation cost for existing users
* If I provide a brand new API (apart from the epic amount of typing) would it work...

Ok, food for thought...
