### ISSUE TITLE
Raising exceptions

### ISSUE THREAD

**Issue by andyigreg** [louthy/language-ext#519]
I usually raise exceptions via failwith(), but I seem to remember a way of creating exceptions where an exception object rather than a string is passed in. But I can't seem to find any reference to it in the documentation. Did I imagine this?

**Comment by bender2k14** [comment]
There is a prelude method called `raise` that throws a given exception. Here is an example of it being used:
https://github.com/louthy/language-ext/blob/c412a962fac7110845b80d0f80a467cc929637ff/LanguageExt.Tests/TryAsyncTEsts.cs#317

**Comment by andyigreg** [comment]
@bender2k14  That's the one. Thanks.

**Comment by louthy** [comment]
Note that `raise` and `failwith` were really there to help with embedding exceptions into expressions; which isn't needed any more with the advent of expression based exceptions in C#, and so I tend to just `throw` them now - mostly because the stack-trace is slightly better.  Obviously YMMV, but I thought I'd just put in my thoughts.
