### ISSUE TITLE
Option and OptionUnsafe null handling clarification

### ISSUE THREAD

**Issue by Jagged** [louthy/language-ext#53]
Re OptionT
Some Match methods are letting nulls slip thru.  Except for MatchUnsafe, are all other Match functions supposed to never return null?  Also, why does MatchUntyped allow nulls? 

Edit: Also ToString and GetHashCode are redundantly checking for nulls when Some, which should be impossible for OptionT.  Or is my understanding of the documentation incorrect and nulls are permitted, even when the state of OptionT is Some? 

Re OptionUnsafeT
MatchObservable is failing when null is found.  Shouldn't it instead allow nulls, as this is the whole point of OptionUnsafe?  

I can supply a PR if you're happy with the above 

Cheers
- Will

**Comment by louthy** [comment]
> Also, why does MatchUntyped allow nulls?
Because it's intrinsically unsafe.  So as with `MatchUnsafe` the constraints are lifted.

> Also ToString and GetHashCode are redundantly checking for nulls when Some, which should be impossible for OptionT
As with `Some` if you have an uninitialised `Option` then it could contain a `null`.

> Also ToString and GetHashCode are redundantly checking for nulls when Some, which should be impossible for OptionT.
Yup, that's wrong.  It's purely a sanity check really.  But you're right, it shouldn't ever happen.

> MatchObservable is failing when null is found. Shouldn't it instead allow nulls, as this is the whole point of OptionUnsafe?
Correct.  That sounds like a bug.

**Comment by louthy** [comment]
I have committed a fix for `MatchObservable` btw

**Comment by Jagged** [comment]
> Also, why does MatchUntyped allow nulls?
> Because it's intrinsically unsafe. So as with MatchUnsafe the constraints
are lifted.

Just out of curiosity why do you consider it intrinsically unsafe?
By checking for nulls we'd make it safe, unless there's another angle
you're coming from?

> Also ToString and GetHashCode are redundantly checking for nulls when
Some, which should be impossible for OptionT
> As with Some if you have an uninitialised Option then it could contain a
null.

Yep the value would be null when uninitialised, but IsSome will also be
false.
If a null ever got into the value when IsSome was true it would be a bug.
Checking for "value != null" just hides any potential bug.

ps. I also have some related changes to always call the appropriate
CheckNullNone/SomeReturnValue routine (can't quite remember the name,
please excuse if wrong), instead of using the one that requires passing in
"None" or "Some" continually.  Will drop a PR later.

pps.  Something is nagging me that there's at least one other Match routine
that has snuck thru without checks, will include in the PR if I find it.

Cheers!

**Comment by louthy** [comment]
> Just out of curiosity why do you consider it intrinsically unsafe?

Because the only time you would use `MatchUntyped` is when you have an `IOptional` and you don't know the type underneath it (which could be either `Option<T>`, `OptionUnsafe<T>` or `Some<T>`.  It is purely there to help with serialisation and for libraries that need access to the option value through reflection.  The behaviour is consistent for all 3 types.  

> Yep the value would be null when uninitialised, but IsSome will also be
false.

If you read my comments you'll see I changed what I wrote.  However it really doesn't hurt to have a safety net for `ToString` and `GetHashCode`.  It's not worth worrying about in my humble opinion.

> ps. I also have some related changes to always call the appropriate
CheckNullNone/SomeReturnValue routine (can't quite remember the name,
please excuse if wrong), instead of using the one that requires passing in
"None" or "Some" continually.  Will drop a PR later.

Fine.  I spotted that the other day and hadn't gotten around to fixing it up.

**Comment by Jagged** [comment]
Cheers, thanks for clarifying things!   I was responding to the email GH sends out, however it didn't show your amendments.  Sorry for rehashing something you'd already explained!

- Will
