### ISSUE TITLE
Can you do FP in MVVM?

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#545]
Sorry if this is a dumb question (as usual!)

I'm (slowly) getting my head around the FP style of coding, and can see how it is used in non-UI code, say data being passed to a service call, and processed along the way to being saved in a database.

However, I'm struggling to see how you could use FP in something like MVVM. My experience of MVVM is that you have properties on your view model, and the view binds to these. Any changes in the one are reflected in the other. This requires mutable objects for your view model properties, which seems to preclude using FP.

Any comments? Can you write FP MVVM code, or is this one of those boundaries where you have to accept that your code does other things?

Thanks

**Comment by bender2k14** [comment]
If the UI is a web browser, then the HTTP communication channel forces [Command Query Separation](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation) (with commands like PUT, POST, and DELETE and queries like GET).

If the UI is desktop application written with [WPF](https://en.wikipedia.org/wiki/Windows_Presentation_Foundation), then as you have experienced, one way to send data to and receive data from the UI is by creating bindings with properties on view models.

Recall that properties in C# are just syntactic sugar for getter and setter methods.  These methods can be implemented in any way you like.  In particular, you can implement the getters the same way you would implement HTTP requests like GET, and you can implement the setters the same way you would implement HTTP commands like PUT, POST, and DELETE.

Therefore, there is nothing fundamentally different about MVVM from the perspective of FP.

**Comment by MrYossu** [comment]
@bender2k14 Sorry, forgot to specify that I was talking about MVVM in WPF, but your comments about a web browser were worth me forgetting!

As to your main point, that's an interesting way of looking at it. So instead of a simple INPC property, my setter would create a new object from the old one, instead of mutating the old one?

The only problem I can see here is that this would require coding up every single property individually in the view model. The way I currently work is that if I had (say) a `Product` property on the view model, then I could bind a textbox to the product's `Name` property as so...

```
<TextBox Text="{Binding Product.Name, Mode=TwoWay}" />
```

This way, I have one `Product` property, and can bind as many controls to its fields as I like. By contrast, if I understand you correctly, you are suggesting I set up a separate view model property for every field on the `Product`, which could quickly get out of hand.

Or did I miss something? Thanks for the reply.

**Comment by bender2k14** [comment]
I think I wasn't clear enough.  I will try to be more specific (and conversational).

First, MVVM is one of those things for which it is difficult for two people to have the same understanding.  For our discussion here, I will try to avoid this complication by referring to your understanding of MVVM.

Consider an application with a client and server that communicate with either other over HTTP.  For such an application, is it possible to create using your understanding of MVVM?

**Comment by MrYossu** [comment]
@bender2k14 Sorry for my assumption that you would know what I meant by MVVM!

I must come clean and say I've never contemplated MVVM over HTTP, so I can't really answer your question.

My main experience with MVVM has been in WPF desktop applications, although I've also used it in client-side Javascript code on web pages (using KendoUI in my case, but there are other frameworks that do similar things). In both cases, your view is as dumb as possible, and contains bindings to properties on the view model. The view model is UI-independent, so can be tested easily.

However, the bit I'm struggling with is that (in my experience and understanding at least), the power of MVVM comes form the fact that the binding handles the conversation between the view and view model. You set up the bindings, and the framework does all the updating. That's fine in a mutable world, but if you want to go  immutable, it seems you'd need to bind to a separate view model property for every UI element. I can see that this would get out of hand very quickly. I have some views that have hundreds of UI controls, most of which are bound to fields on one view model property.

Don't know if all of that waffle helps or makes things worse! Thanks for your reply. Any comments on what I wrote?

**Comment by MrYossu** [comment]
@bender2k14 I understand and agree with your comments, but am still not clear how you would do the binding in a WPF MVVM scenario. As I pointed out before, the way you propose it, it sounds like I would need a separate view model INPC property for every piece of data that was to be bound on the view.

For example, one of my windows has a view model property for an entity that represents a medical imaging system (a complex object graph). This is bound to the DataContext for the view, and the XAML then binds to properties on that entity, and child properties, grandchild properties etc.

I just counted up, and there are 150 controls bound to properties in the object graph for that entity, however, I only have the one view model property for the top-level entity. Are you suggesting I create 150 view model properties, and bind each of these controls to its own?

Thanks again.

**Comment by bender2k14** [comment]
> For example, one of my windows has a view model property for an entity that represents a medical imaging system (a complex object graph). This is bound to the DataContext for the view, and the XAML then binds to properties on that entity, and child properties, grandchild properties etc.

_The_ DataContext for _the_ view?...like, you only have one of each?  When I have created GUIs with WPF, I have always created many nested views that each have nested view models assigned to their `DataContext` property.  I don't see how this matters though for the purposes of our conversation.

> Are you suggesting I create 150 view model properties, and bind each of these controls to its own?

I don't think so. I don't see why you think am suggesting that or why this would be necessary for what I am suggesting.

**Comment by MrYossu** [comment]
@bender2k14 I was using one view with one view model as an example, but as you say, the principle is the same.

> Similarly, in a WPF application, new data can be received from the UI when the setter of a bound property is called.

Please can you explain what you meant by this, as I've obviously misunderstood. In my experience, data binding is done like this...

    <TextBox Text="{Binding RevisionNotes}" />

...where `RevisionNotes` is an INPC property on the current DataContext. When the user modifies the text in the textbox, the text is sent to the view model and set on the `RevisionNotes` property. I don't do anything, the text is automatically sent.

Sorry if I'm missing something obvious, but I really don't see what you mean. Maybe you could provide a small code sample to illustrate.

Thanks again

**Comment by bender2k14** [comment]
In the simplest case, `RevisionNotes` is an auto property and looks like
```
public string RevisionNotes { get; set; }
```

but it doesn't have to be an auto property.  You can make it into a non-auto property.  In which case, that `get` combined with with raising INPC for `RevisionNotes` is like sending data to a web client using a web socket, and that `set` is like the client posting data to some route on the server and some method on a controller being invoked.

**Comment by bender2k14** [comment]
You created this issue because you have a specific questions about the relationship between FP and MVVM.  If I understand all of these UI-related design patterns, then I have given a reduction from MVVM to MVC.  I think a similar reduction is possible from MVC to MVVM.

I don't see what is so special about MVVM in your question.  It seems to me that you are actually asking "Can you do FP in an application with with a UI?".

Is there a type of UI (or UI-related design pattern) for which you know how to "do" FP "in" that type of UI?

**Comment by bender2k14** [comment]
> It seems to me that you are actually asking "Can you do FP in an application with with a UI?"

To be clear, I think this is a really good question.  I recall another issue discussing this (essentially about how to properly mix pure and impure code), but I can't find it now.

**Comment by MrYossu** [comment]
> You can make it into a non-auto property. In which case, that `get` combined with with raising INPC...

Yes, it occurred to me (too late last night) that this could be one place where we were talking at cross purposes. I usually work with entities created by Entity Framework, in which case I don't write any of the getter/setter code, it's generated by the framework. Am I right in thinking that this is not going to fit with what you're suggesting? As I said, some of our entities are object graphs with hundreds of properties, I would need to think carefully before going down the route of writing the entity code by hand.

> I don't see what is so special about MVVM in your question. It seems to me that you are actually asking "Can you do FP in an application with with a UI?".

Hmm, now you mention it, I think you're right. I was thinking of MVVM for two reasons, one because that's where I spend most of my day, and two because it has the two-way automatic binding (which I've never used in MVP or MVC). However, I guess the same applies to any UI.

> Is there a type of UI (or UI-related design pattern) for which you know how to "do" FP "in" that type of UI?

Nope. As you've probably guessed by now, I'm a rank amateur with FP. I'm totally smitten with it, and have gone over to a very FP-way of coding on a micro scale, ie individual methods, but am struggling to see how to put it all together in a full end-to-end application.

Maybe this is the wrong way to think about it, but I'm wondering if the relationship between the UI and the first layer of non-UI code could be one of those boundaries (like database access) where impure coding becomes pragmatic. My impression is that unless you're using a database like Event Store, then you're stuck with impure mutable state at that end. Maybe I should treat the data coming from the UI in the same way, and have code that validates the data and converts the mutable object graph that's bound to the view to an immutable on that the rest of the code (pure FP) would use.

Does that make sense, or am I just taking the easy way out!

Thanks for all your patience. I am getting there, it's just a slow business, as FP is a totally different mindset from imperative programming, and I'm the sort of (slightly OCD) person who likes to understand what I'm doing, rather than copy someone else's code blindly.

Thanks again.

**Comment by bender2k14** [comment]
> Maybe this is the wrong way to think about it, but I'm wondering if the relationship between the UI and the first layer of non-UI code could be one of those boundaries (like database access) where impure coding becomes pragmatic. My impression is that unless you're using a database like Event Store, then you're stuck with impure mutable state at that end.

I think Event Store is a very interesting idea.  I would love to try it but haven't done so yet.

As a "recovering" object-oriented programmer, I am still trying to retrain my mind and shake off my old habits.  That said, my currently understanding of all this is that mutation must eventually happen in order for some useful work to occur.  When the user requests (at least conceptually) that some piece of persistent state should change (such as setting a different username for themself), then we must write impure code (even when using Event Store).  I think one of the main ideas of functional programming is to break that code into two parts, the pure part and the impure part while also maximizing the size of the pure part.

> As you've probably guessed by now, I'm a rank amateur with FP. I'm totally smitten with it, and have gone over to a very FP-way of coding on a micro scale, ie individual methods, but am struggling to see how to put it all together in a full end-to-end application.

I am also on that road that "ends" at the ideal functionally designed application.  However, I do get the impression that I could be further down this road than you and able to offer some suggestions.

> > You can make it into a non-auto property. In which case, that `get` combined with with raising INPC...

> ...I usually work with entities created by Entity Framework, in which case I don't write any of the getter/setter code, it's generated by the framework. Am I right in thinking that this is not going to fit with what you're suggesting?

I think this is a bad idea.  The purpose of the entities in Entity Framework is to transfer data in and out of the  datastore "behind" Entity Framework.  If you reuse those classes to also transfer data in and out of your WPF UI, then you will have to deal with competing concerns.

Instead, I recommend having Entity Framework entities that change for reasons solely to do with Entity Framework reasons, and I recommend having view models (that you set as the `DataContext` in WPF) that change for solely WPF reasons.  In addition to those two groupings of data types, I also recommend model types that only change for modeling reasons.  The business logic should only depend on these model types and not on Entity Framework's entities nor on WPF's view models.  I think of this as independent and somewhat more important that FP vs OOP (i.e. whether using FP or OOP, I would want my concerns separated like that).

Given those separations, I think the next thing to focus on is model design.  Here are [two](https://www.dotnetcurry.com/patterns-practices/1429/data-objects-csharp-fsharp) [articles](https://www.dotnetcurry.com/patterns-practices/1475/data-objects-csharp-examples) I found and read recently that think do a good job at this.

Then I would focus on extracting the pure code into (often static) methods.

I think it would be easier to learn FP if I were able to start working on a brand new application at my job.  I assume that you are like me and am doing the best you can to learn FP with the existing application in front of you.  For me, I often feel handcuffed having to debug race conditions day after day.  I would have rather spent that time trying to write new functional code and feeling the different pinpoints firsthand.

So, because I am limited by the application in front of me (the design of which is mostly contrary to FP principles), I don't currently feel the need or pressure to figure out...
> how to put it all together in a full end-to-end application

Maybe you are in a similar position and am also able to make progress on your understanding of FP without also knowing how it all comes together in a full application.

> I'm the sort of (slightly OCD) person who likes to understand what I'm doing, rather than copy someone else's code blindly.

I am the same way, and I think we are better for it :)

**Comment by MrYossu** [comment]
@bender2k14 Thanks for the reply, lots to think about there.

> I think one of the main ideas of functional programming is to break that code into two parts, the pure part and the impure part while also maximizing the size of the pure part.

Yes, which is why I was suggesting that maybe the UI/view model boundary is one of those. Looks like you agree, judging by what you said later (see below).

> However, I do get the impression that I could be further down this road than you and able to offer some suggestions.

Could be? I would say that's a certainty! I appreciate the suggestions.

> I think this is a bad idea.

Yup, but it's the way I (and most people I know) currently work. I think this is part of the OO/imperative mindset.

I'm thinking of a multi-tiered setup, where you have a repository that talks to a database via EF, a business logic layer above the repository, then a service layer, and then the WPF project which contains the view models and views. That's my most common scenario, and with that in mind, it sounds like you are suggesting something along the following lines...

* Repository - Gets objects from the database using EF-generated classes
* Data conversion layer (quite possibly not a separate layer, but something like AutoMapper) - Converts those objects into immutable data objects suitable for FP-style coding
* Business logic layer and Service layer - Same as before, but using the immutable objects
* WPF project...
  * View models, receive the immutable objects from the service layer, convert them into mutable versions and bind them to the UI
  * UI - as before

The same scenario would work in reverse when saving data. The view model would convert the mutable object into an immutable one, send it down to the service, where it would work its way down to the part that converted it to an Ef-compatible object which would get passed to EF for persisting.

Does that sound reasonable? To a large extent, it sounds very much like the approach  Scott Wlaschin laid out in _Domain Modeling Made Functional_ (an excellent book that I strongly recommend to anyone wanting to learn FP, even if you don't intend using F#).

> I think it would be easier to learn FP if I were able to start working on a brand new application at my job. I assume that you are like me and am doing the best you can to learn FP with the existing application in front of you. For me, I often feel handcuffed having to debug race conditions day after day. I would have rather spent that time trying to write new functional code and feeling the different pinpoints firsthand.

Got it in one! However, existing projects pay the wages, whereas these investigative ones are purely for my own learning. I would need to be a lot more confident of my own capabilities and understand of FP before I would risk trying it on a new project. Not that I start many new projects, 90% of what I do is on one major, well matured, very OO/imperative based project.

Thanks again for all the replies. It's all becoming clearer. What I would really like to see is a full end-to-end project that used WPF (why main UI framework) in a proper FP style. Doesn't have to be a major project, but big enough to show how it woudl be done. The problem I have is that most samples, including the ones in Enrico Buonanno's _Functional Programming in C#_, Scott Wlaschin's book (mentioned before) and the language-ext samples is that they don't show the full story. Most samples are very small isolated parts of the picture, and even the bigger ones seem to miss out the crucial bits, like the UI/view model interface that prompted this question..

There's a challenge for you! How do you fancy whiping up an end-to-end sample? Would be a huge benefit to people like me. I'm sure I'm not the only one keen to embrace FP but struggling.

Thanks again. I printed those linked articles out, and am reading them carefully. Some good stuff there!

**Comment by bender2k14** [comment]
> Does that sound reasonable?

It does.

One caution is to make sure you are aware of the difference between compile-time dependencies and runtime dependencies.  For example, the business models should not have a compile-time dependency on the Entity Framework entities.  However, you can imagine the flow data types when saving as something like "view model -> business model -> EF entities".  That is still not a runtime dependency, but it is similar to one.

> To a large extent, it sounds very much like the approach Scott Wlaschin laid out in _Domain Modeling Made Functional_ (an excellent book that I strongly recommend to anyone wanting to learn FP, even if you don't intend using F#).

For a long time, I have wanted to read a book about domain-driven design.  This looks perfect!  I just bought it :)

> How do you fancy whiping up an end-to-end sample?

I would love to., but I don't foresee it happening any time soon.  The main issue is lack of time.  The other issue is the difficulty in deciding on a good example.  It needs to be complicated enough to show the "general case" but not so complicated that the complexity distracts from the teaching.

**Comment by MrYossu** [comment]
@bender2k14 OK, so if I'm on the right lines, maybe I'll see if I can start something. I'm still not sure about the view model, but I guess that's something that I can refine as I go along. I could be ding it wrong, but I often have quite a bit of logic in the view models, usually in response to the user changing data or clicking buttons, and I either have to do that with the mutable objects, and only convert before sending them out of the view model, or I have to do a significant amount of converting backwards and forwards in the view model. Either way sounds like I'm not doing it right.

Thanks again for all the help. Enjoy the book,it really is very good.

**Comment by bender2k14** [comment]
Since February, I have become very active in [Elmish.WPF](https://github.com/elmish/Elmish.WPF) and am using it in my project at work where we are creating a WPF application for Windows desktop.  I recommend checking it out.  The repo contains many helpful samples that show how things work.

**Comment by MrYossu** [comment]
@bender2k14 Thanks for that. unfortunately, I can't move any of my main projects to Elmish, mainly due to lack of time to learn and convert, and because the program manager would have a fit if I suggested using F#! I'm stuck with C# for my day job (not that there's anything wrong with C#, but you know what I mean) and would have to leave things like this to my limited spare time.

I would be interested to hear how you get on long-term with it though. In the meantime, I still need to try and get my head around MVVM with C#.

Thanks again.

**Comment by jmurp** [comment]
I'm very much of the mindset of the OP here, trying to find a functional solution to a .NET project that must use WPF views and MVVM pattern.  I brainstormed and want to help anyone who comes upon this thread like I did.  Your welcome for the professional diagram (note the directionality of arrows).

Models <--ACID--> Commands ---(on UI thread)---> ViewModel[NotifyPropertyChanged]
|
v
ViewModel ---> Commands
^
|
v
WPF View 

____________
All data types should be immutable, except for the ViewModel, which should only hold state necessary for the functioning of the view.

The ACID transactions between Commands and Models ensure that Models is always a valid immutable state.
Since C# treats functions as first class, this could probably be wrapped into an infrastructure that will help the codebase remain simple and clear while adhering to the design principles.  ie. this step can be declarative from the programmers point of view
'I want these changes to occur to the application data and I want this to happen if that cannot occur.'
What I call 'Commands' will probably be a couple of layers. eg) EventProcessor <--> Commands

How does the application change?
1. User interacts with view
2. 
a. event triggers viewModel function which calls a command
b. view binding calls setter on viewModel which calls a command
3. command tries to update the Model and then appropriately conveys to the ViewModel what changes occurred and then the target bindings in the view are updated

Man how I wish Clojure-CLR was more mature at this point in time.  I come from Clojure(Script) land and am used to thinking in Re-Frame terms, performant thanks to React. I want to be able to pass around data as maps and not have to worry about the memory costs or how the data is structured.  I can handle and test that aspect of the application myself.

I'm not sure if this will be successful but I think it is a possible solution to what the OP had in mind.  If anyone happens to find this in meantime, do you have suggestions?

**Comment by alarya** [comment]
@jmurp - Having stateful view models would mean that it's not FP. I think the MVU paradigm for UI is more akin to FP. That said, imo, it's a bit awkward to make MVU work in WPF, but not impossible.

.NET Maui is supposed to have the MVU paradigm support which will make it very easy to have FP all the way through. Until then, I have ended up relying on stateful View models just like you have suggested. The core of the application is very much functional and the UI state (view models) is mutable. I handle all my commands in one place at the top level and return the new state of the world (application) after a command is processed. The UI thread then *updates* the affected part of the view model(bound to the view).
