### ISSUE TITLE
subscribe<T>, observe<T> don't work for ProcessFlags.ListenRemoteAndLocal and ProcessFlags.PersistState when using Process + Redis

### ISSUE THREAD

**Issue by mr-kawaii** [louthy/language-ext#55]
**Great work!**

I'm playing around with the **Process + Redis**, I'm on Mac using **Mono**.

The **RedisPublishSample** given by @louthy (https://github.com/louthy/language-ext/issues/25), the line **"subscribe<int>(pid, Console.WriteLine)"** didn't seem to work for me. I did see lots of PUBLISH commands in redid (e.g. *1446114839.593337 [0 127.0.0.1:51072] "PUBLISH" "/redis-test/user/redis-pubsub-random-test-pubsub" "1550928543"*) but absolutely nothing was printed in the terminal. The subscriber part didn't work.

What could be wrong? StackExchange.Redis? I did need to manually recompile StackExchange.Redis under mono, the nugget package didn't work.

If I change ProcessFlags.RemotePublish to **ProcessFlags.ListenRemoteAndLocal** then the subscribe part will work. But I presume they are different things / behaviour?

Actually, for **RedisStateSample**, it's the same, however in mac terminal, the number **32** was printed but that was it. So **observeState<int>(pid).Subscribe(Console.WriteLine)** worked once only. Not sure why.

I will try tomorrow on Windows and see whether the two examples will work as expected.

**Update**

I've tested below code in windows and same problem persisted. In console, nothing was printed for RedisPublishSample and RedisStateSample only printed the first number. It was exactly the same as running under mono.

Would definitely need some suggestions. Thanks.

I figured I better copy paste my test code here

```
using System;
using LanguageExt;

namespace ConsoleApp1
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            RedisCluster.register();
            Cluster.connect("redis", "redis-test", "localhost", "0");

            PubSubSample();
            StateSample();

            Console.Read();
        }

        public static void PubSubSample()
        {
            Func<Random> setup = () => new Random();
            Func<Random, int, Random> inbox = (rnd, value) =>
            {
                Process.publish(value);
                Process.tellSelf(rnd.Next());
                return rnd;
            };

            var pid = Process.spawn<Random, int>(
                          "redis-pubsub-random-test",
                          setup,
                          inbox,
                          ProcessFlags.RemotePublish);//change to ProcessFlags.ListenRemoteAndLocal, then the subscriber part will work, strange?
            
            Process.subscribe<int>(pid, x =>
                {
                    Console.WriteLine(x);
                });

            //also try using observe without any luck
            Process.observe<int>(pid).Subscribe(x =>
                {
                    Console.WriteLine(x);
                });

            Process.tell(pid, 0); 
        }

        public static void StateSample()
        {
            Func<int> setup = () => 0;
            Func<int, int, int> inbox = (state, value) =>
            {
                state += value;
                Process.tellSelf(value, TimeSpan.FromSeconds(1));
                return state;
            };

            var pid = Process.spawn<int, int>(
                          "redis-state-sample",
                          setup,
                          inbox,
                          ProcessFlags.PersistState);
            
            Process.observeState<int>(pid).Subscribe(x => {
                Console.WriteLine(x);
            });

            Process.tell(pid, 1);
        }
    }
}
```

Would be great if someone can help or shed some light. Thanks.

This issue I originally posted in 
https://github.com/louthy/language-ext/issues/25

The samples can also be found here https://github.com/louthy/language-ext/tree/master/Samples

**Comment by louthy** [comment]
Hi @mr-kawaii - Looking into it now.

**Comment by louthy** [comment]
@mr-kawaii - There's a fix submitted to the main branch (I won't get a chance to do a nuget release until next week probably, so grab from source).

It failed because `ActorContext.GetDispatcher()` would always return a local `IObservable<T>`, and not observe the Redis stream (by 'local', I mean running in the same application).  `GetDispatcher` is used to find the appropriate interface to communicate with any `ProcessId` (locally - in the same app, remotely - in another app, JS - via SignalR)    So if you had run your test and subscribed to a `Process` running remotely then it would have worked.  But because the `Process` and the subscriber were in the same app, it failed.

To keep the consistency of `GetDispatcher()`, when `ProcessFlags.RemotePublish` is used, `Publish` pushes to both Redis and the local stream.  That means the demo project doesn't do what it says any more unfortunately; because if the process is local and you subscribe to it locally, then the messages you receive won't have come from Redis.  The overall behaviour is correct though.

I'll update the demo project when I get a chance.  

Thanks for the heads up :+1:

**Comment by mr-kawaii** [comment]
Thanks for the quick response.

I got the latest but had to download visual studio 2015 community (and run in virtual box) to compile the project as vs2013 nor xamarin studio (under mac mono) wont't compile the solution.

I tested **RedisPublishSample** and **RedisStateSample** and they both worked (windows / mac mono) as exoected. I could see numbers being printed out in console / terminal.

I however didn't understand what you meant by "That means the demo project doesn't do what it says any more unfortunately; because if the process is local and you subscribe to it locally, then the messages you receive won't have come from Redis." I haven't really delved into the source yet maybe I don't have the full picture.

**Comment by mr-kawaii** [comment]
I noticed another issue, it's possibly very similar to above mentioned but it's on the **receiving end**.

If I run **RedisPublishSample** and then I manually publish via redis-cli like so (*"PUBLISH" "/redis-test/user/redis-pubsub-random-test-pubsub" "521"*) in thermal the subscriber didn't respond.

It's the same if I "publish" via below c# code, which is equivalent to the PUBLISH command above.

```
                var pid = new ProcessId("/redis-test/user/redis-pubsub-random-test");
                pid.Tell(DateTime.Now.Millisecond);
```

**Comment by louthy** [comment]
> I however didn't understand what you meant by...

Essentially it means if the system doesn't need to use Redis, it won't.  The publish system, whether it's for state-changes or user-triggered via the `publish` system uses the Redis pub/sub system which doesn't persist in the same way as sending a message to a Process' inbox - if you're not alive and listening for the publish event then you will miss it.  So it's purely an event system.  Whereas sending a message to the inbox of a Process that's offline will go into a persistent queue that will be given to the Process when it wakes up.

That means that for local-to-local publish events, the system now goes direct, without going through 
Redis.  So if you're testing the Redis publish system you should have two applications (or two AppDomains).  That's why the current publish demo will need to be updated.

> I suggest adding a test so that in future this particular scenario is covered.
Of course.  Going to be busy for a few days, so I'll get to that next week sometime.

> Maybe it would be a good idea to document and explain what each of the ProcessFlags

The intellisense documentation should be relatively clear on this.  Take a look at ProcessFlags.cs - let me know if you feel it's unclear:
https://github.com/louthy/language-ext/blob/master/LanguageExt.Process/ProcessFlags.cs

>  But I personally don't like enum being used as a switch in this way. It's not natural.

A switch?  Do you mean as a flags system?  It's pretty much the standard way to combine binary settings into a value.

**Comment by mr-kawaii** [comment]
Thanks for your reply. It's much more clear now for me.

I noticed another issue, it's possibly very similar to above mentioned but it's on the **receiving end**.

If I run **RedisPublishSample** and then I manually publish via redis-cli like so (*"PUBLISH" "/redis-test/user/redis-pubsub-random-test-pubsub" "521"*) in terminal the subscriber didn't respond (i.e. nothing was printed out).

It's the same if I "publish" via below c# code, which is equivalent to the PUBLISH command above.

```
var pid = new ProcessId("/redis-test/user/redis-pubsub-random-test");
pid.Tell(DateTime.Now.Millisecond);
```

I also tried below, both on a separate AppDomain without success. Am I doing something wrong?

In the main app I register a public name using ```pid.Register<int>();``` (pid is the "redis-pubsub-random-test" process) then in another app I do

```
var pid = Process.find(new ProcessName("redis-pubsub-random-test"));
Process.tell(a, DateTime.Now.Millisecond);
```

**Comment by louthy** [comment]
> var pid = new ProcessId("/redis-test/user/redis-pubsub-random-test");
> pid.Tell(DateTime.Now.Millisecond);

That isn't `publish`.  `tell` uses the Redis pub-sub system for notifications only (the notification wakes up the inbox so that it looks in the Redis queue for unprocessed messages) and it uses a different key in Redis.

But I do see an issue that could have come about from my fix last night.  Please grab the latest source.

If you would like to zip up your examples and attach them to this thread then I'll happily check them for you.

**Comment by mr-kawaii** [comment]
Ok, maybe I had the wrong assumption. I was hoping or expecting that if I```spawn<Random, int>("redis-pubsub-random-test"``` multiple processed with the same process name ***on different AppDomain***, they could "talk to each other" but after sometime I realised the spawned processes on different AppDomain actual has different guid, hence they won't "talk to each other" via redis.

I guess I was hoping to be able to have a setup like this:

AppDomain 1

vad pid = "abc";
pid.Subscribe(Console.WriteLine);

AppDomain 2

vad pid = "abc";
pid.Subscribe(Console.WriteLine);

if I "publish" from redis, I should see one write line in each console (AppDomain), and if I publish from either AppDomain 1 or AppDomain 2, I should see again, one write line in each console.

Maybe above is not what Process does.

**Comment by louthy** [comment]
It is absolutely possible for the processes to talk cross-AppDomain via Redis.  I suspect your code is wrong, but until you share the code I can't comment.  

> if I "publish" from redis, I should see one write line in each console (AppDomain), and if I publish from either AppDomain 1 or AppDomain 2, I should see again, one write line in each console.

The example you give above isn't valid, and I'm not even sure what it is you're trying to do?  I'd advise you to stop manually publishing in Redis and use the system as designed.  I can't support your ad-hoc direct access to Redis.

Things to watch out for:

* Make sure you have called `RedisCluster.register()` on each `AppDomain`
* Make sure you have called `Cluster.connect(...)` on each `AppDomain` *and* that the second parameter is unique for all AppDomains:

AppDomain 1:
```C#
    Cluster.connect("redis", "redis-test-app-dom-1", "localhost", "0");
```
AppDomain 2:
```C#
    Cluster.connect("redis", "redis-test-app-dom-2", "localhost", "0");
```
* If you want to 'talk' to processes in another domain, then you must know its path. 
AppDomain 1:
```C#
    var pid = spawn<string>("hello", msg => publish("Hello, "+msg));
```
AppDomain2:
```C#
    var hello = Process.Top["redis-test-app-dom-1"]["user"]["hello"];
    observe<string>(hello).Subscribe(Console.WriteLine);
    tell(hello, "Jeffrey");
```

**Comment by mr-kawaii** [comment]
Thanks for your response.

"The example you give above isn't valid, and I'm not even sure what it is you're trying to do? I'd advise you to stop manually publishing in Redis and use the system as designed. I can't support your ad-hoc direct access to Redis."

I was trying to test.

I see, you are using ```var hello = Process.Top["redis-test-app-dom-1"]["user"]["hello"];```. And I was using your example Process.find("hello") or my code Process.find("redis-pubsub-random-test").

By the way, where's Process.Top?

So there's no way to do something like below in AppDomain 2.

Instead of below, where in AppDomain 2, I need to know the name "redis-test-app-dom-1"
var hello = Process.Top["redis-test-app-dom-1"]["user"]["hello"];

I can't just do something like 
var hello = Process.Top["user"]["hello"];

**Comment by louthy** [comment]
> By the way, where's Process.Top?

`Process.Top` is `/` - it's the very root that you can use to build your paths from.

>  I can't just do something like `var hello = Process.Top["user"]["hello"];`

No, that process path wouldn't exist, you can register processes by name - but only one process on the cluster can have that name.  Otherwise the behaviour is undefined.

AppDomain 1
```C#
    var pid = Process.spawn<string>("hello", msg => publish("Hello, "+msg));
    Process.register("hello-registered", pid, ProcessFlags.PersistAll);
```

AppDomain 2:
```C#
   var pid = Process.find("hello-registered");
   Process.tell(pid, "Jeffrey");
```
What `Process.register("hello-registered", ...)` does is to create a proxy process with the process-ID of "/registered/hello-registered".  `Process.find("hello-registered")` merely builds a new ProcessId like so:  `Process.Top["registered"]["hello-registered"]`

I think because of the issue raised originally, I would avoid using `Process.register` and `Process.find` for the moment, and try and get it working with the absolute paths.  Once you have a working solution (with the latest build) then I would try the `register` and `find` option.

**Comment by mr-kawaii** [comment]
**AppDomain 1**

```
    class MainClass
    {
        const string ID = "Node A";

        public static void Main(string[] args)
        {
            RedisCluster.register();
            Cluster.connect("redis", "redis-test-1", "localhost", "0");

            var pid = Process.spawn<string>("hello", msg => Process.publish(msg));
            pid.Register<string>("hello-registered", ProcessFlags.PersistAll);
            pid.Subscribe<string>(Console.WriteLine);

            while (true)
            {
                pid.Tell(string.Format("{0} - {1}", ID, DateTime.Now.Millisecond));
                Console.Read();
            }
        }
    }
```

**AppDomain 2**
```
    class MainClass
    {
        const string ID = "Node B";

        public static void Main(string[] args)
        {
            RedisCluster.register();
            Cluster.connect("redis", "redis-test-2", "localhost", "0");

            var pid = Process.find("hello-registered");

            while (true)
            {
                Process.tell(pid, string.Format("{0} - {1}", ID, DateTime.Now.Millisecond));
                Console.WriteLine("{0} told", ID);
                Console.Read();
            }
        }

    }
```

I think it's working now. AppDomain 2 can "talk" to actor in AppDomain 1 via Redis.

Thanks!!!
