### ISSUE TITLE
How to wrap a Task in a TryAsync ?

### ISSUE THREAD

**Issue by ticofab** [louthy/language-ext#578]
Hi @louthy , Thanks for your work, I come from a JVM background and this library is helping. At the same time, there are some things that I can't get to work. For instance, does [this example](https://github.com/louthy/language-ext/issues/201) still work? I cannot make anything of this compile. In particular, I would like to achieve something like

```
Task<string> task = _httpClient.GetStringAsync(url);
---> how do I create a Try / TryAsync around this Task?
```

Basically I am looking for the same answer as this question on gitter:
https://gitter.im/louthy/language-ext/archives/2017/06/29

Thanks for any help!

**Comment by louthy** [comment]
```c#
   using static LanguageExt.Prelude;

   TryAsync<string> task = TryAsync(_httpClient.GetStringAsync(url));
```
You can't get a `Try` from a `Task` because it would make in synchronous.

**Comment by bender2k14** [comment]
I always feel unsure of the indented behavior when reading code involving `Try` or `TryAsync`.  Yes, the code that @louthy gave complies, but no additional exceptions are being caught.

To see what I mean, compare these two tests.

```
[Fact]
public void Fails()
{
    TryAsync<string> tryAsync = TryAsync(_ThrowException());
}
[Fact]
public void Passes()
{
    TryAsync<string> tryAsync = TryAsync(() => _ThrowException());
}
private Task<string> _ThrowException() => throw new Exception();
```

Therefore, I was going to suggest that @ticofab use this code
```
TryAsync<string> task = TryAsync(() => _httpClient.GetStringAsync(url));
```

**Comment by bender2k14** [comment]
Ah @ticofab, you added some additional and helpful information when you [cross posted on SO](https://stackoverflow.com/questions/55706581/c-sharp-languageext-wrap-task-with-tryasync).  For completion, you added
> I would like to wrap a `Task` in a `Try`, so that any exceptions thrown would be caught. There must be a way.

Indeed.  As @louthy said, you have to wrap the `Task` in `TryAsync` (since `Try` is only for synchronous behavior).  Then you need to lazily pass in the computation as I suggested.  Specifically,
```
TryAsync<string> task = TryAsync(() => _httpClient.GetStringAsync(url));
```

**Comment by ticofab** [comment]
Thank you so much for your responses! The key was the static import.
I am now creating two tasks, simplified version here:
```
var taskOne = TryAsync(() => _httpClient.GetStringAsync(url1));
var taskTwo = TryAsync(() => _httpClient.GetStringAsync(url2));
return await match(
                from response1 in taskOne
                from response2 in taskTwo
                select CreateResponse(response1, response2),
                Succ: resp => resp,
                Fail: error => StatusCode(500, error.Message));
```
I think this looks great. I believe that the two tasks are started as they are instantiated and executed in parallel, but haven't verified it with my eyes yet..?

**Comment by bender2k14** [comment]
I think they are executed in series in that code

**Comment by ticofab** [comment]
You are right - just checked and they run sequentially indeed. Will post updates after figuring this out!

**Comment by ticofab** [comment]
I was able to achieve parallelism by wrapping the tasks after instantiation: 
```csharp
var taskOne = _httpClient.GetStringAsync(url1);
var taskTwo = _httpClient.GetStringAsync(url2);
return await match(
    from response1 in TryAsync(() => taskOne)
    from response2 in TryAsync(() => taskTwo)
    select CreateResponse(response1, response2),
    Succ: resp => resp,
    Fail: error => StatusCode(500, error.Message));
```
Please let me know if you have any other suggestions and thanks again!

**Comment by bender2k14** [comment]
LINQ query syntax uses the monadic behavior (i.e. the `Bind` or `SelectMany` method) of the particular monad.  These implementations of these methods are similar to that of logical AND (`&&`) in that they fail fast after computing the first fail value.

Instead, you want to use the applicative (functor) behavior of the `TryAsync` monad.  This will fully evaluate all applicatives before moving on.

Specifically, you can do this:
```
var taskOne = TryAsync(() => _httpClient.GetStringAsync(url1));
var taskTwo = TryAsync(() => _httpClient.GetStringAsync(url2));
return apply(CreateResponse, taskOne, taskTwo)
    .IfFail(e => StatusCode(500, e.Message));
```

When the instance of `TryAsync<>` returned from `apply` is in its fail state, it contains the exception from the first given `TryAsync<>` to be in its fail state.  So for example, if both `taskOne` and `taskTwo` contain an exception because they are both in their fail states, then the instance of `TryAsync<>` returned from `apply` only contains the exception from `taskOne`.

For some other applicatives, it is possible to rewrite the third line as `(taskOne, taskTwo).Apply(CreateResponse)`, which I prefer, but this extension method doesn't seem to exist for `TryAsync<>`.

**Comment by bender2k14** [comment]
> I was able to achieve parallelism by wrapping the tasks after instantiation

I don't think that is the behavior that you want.  To see what I mean, try implementing `_httpClient.GetStringAsync` as `throw new Exception()`.

Instead, I think you want the behavior that I suggested in my previous post.
