### ISSUE TITLE
Bind, SelectMany, and MapAsync for Task

### ISSUE THREAD

**Issue by bender2k14** [louthy/language-ext#580]
We have extension methods for `Task<>` called [`Bind`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L121), [`SelectMany`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L79), and [`MapAsync`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/Task/Task.Extensions.cs#L209) that all do the same thing.  `Bind` is implemented by calling `SelectMany` while `SelectMany` and `MapAsync` have identical implementations.

Is this the intended API?  I did not expect to see the `MapAsync` extension method.

**Comment by slimshader** [comment]
To be able to use LINQ queries types must provide Select(), SelectMany(), Where() etc. For example ```from e in es select e.value``` is converted at compile time to Select() call, 2 consecutive "from" clauses are translated to SelectMany etc. so that is the reason they must be provided. Bind() is the usual FP lingo and basically provides same functionality as SelectMany() (Monadic binding) so it exists for consistency with other types I believe.

**Comment by bender2k14** [comment]
@slimshader, I am specifically asking about `MapAsync`.

**Comment by louthy** [comment]
It's just a consistency of interface thing.  But yes, it's redundant.  I'll probably not do anything about it, but feel free to do a PR if you feel strongly about it.
