### ISSUE TITLE
Chaining .Do off of TryOption result causes TryOption to re-evaluate

### ISSUE THREAD

**Issue by SpaceMacGyver** [louthy/language-ext#584]
For a function that returns a `TryOption`, every chained `.Do` causes the function to be re-evaluated.  Consider the following illustration:

```c#
TryOption<Unit> DoThing() => () =>
{
    Console.WriteLine("did thing");

    return Unit.Default;
};

DoThing()
    .Do(u =>
    {
        Console.WriteLine("Do.");
    })
    .Do(u =>
    {
        Console.WriteLine("Do again.");
    })
    .Match(
        Fail: e => Console.WriteLine($"Fail: {e}"),
        Some: u => Console.WriteLine("Some."),
        None: () => Console.WriteLine("None.")
    );
```

Execution of the above code results in the following output:

```
did thing
Do.
did thing
Do again.
did thing
Some.
```

Perhaps I misunderstand how Do is supposed to work; expected behavior would be something similar to a .Map statement that passes it's input through, similar to the below illustration:

```c#
TryOption<Unit> DoThing() => () =>
{
    Console.WriteLine("did thing");

    return Unit.Default;
};

DoThing()
    .Map(u =>
    {
        Console.WriteLine("Do.");

        return u;
    })
    .Map(u =>
    {
        Console.WriteLine("Do again.");

        return u;
    })
    .Match(
        Fail: e => Console.WriteLine($"Fail: {e}"),
        Some: u => Console.WriteLine("Some."),
        None: () => Console.WriteLine("None.")
    );
```

...which results in:

```
did thing
Do.
Do again.
Some.
```

(edit: This is occurring with v3.1.19 obtained via NuGet)

**Comment by bender2k14** [comment]
Since [`TryOption<>`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/TryOption/TryOption.cs#L12) is implemented as a delegate, its default [evaluation strategy](https://en.wikipedia.org/wiki/Evaluation_strategy) is [call by name](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_name).  The behavior that you were expecting is [call by need](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_need).  The `TryOption<>` returned from [`Map`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs#L503) has the call-by-need evaluation strategy because it calls [`Memo`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs#L21).  In contrast, [`Do`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs#L488) returns the same `TryOption<>` instance that it was given, so the calling convention of that instance is unchanged.

Since `Do` is eager, I think the correct fix is to call [`Strict`](https://github.com/louthy/language-ext/blob/master/LanguageExt.Core/DataTypes/TryOption/TryOption.Extensions.cs#L40) in `Do` like
```
public static TryOption<A> Do<A>(this TryOption<A> ma, Action<A> f)
{
    var strict = ma.Strict();
    strict.Iter(f);
    return strict;
}
```

I will create a PR for this.

**Comment by SpaceMacGyver** [comment]
@bender2k14 Thanks for the evaluation strategy explanation; I was unaware of those terms.

**Comment by louthy** [comment]
@bender2k14 I removed the strictness from your change.  I realised that `Do` shouldn't make the computation strict, if you want strictness then that should be under the control of the programmer by explicitly calling `.Strict()`.  

`Do` shouldn't force an evaluation either, it should have no effect on the lazy expression until evaluation.

I have reimplemented `Do` for all lazy monadic types.  They now work like so (pseudo code):
```c#
    public static Monad<A> Do(Monad<A> ma, Action<A> f) => (args) =>
    {
        var r = ma(args);  // r has the concrete result of the ma computation
        if(!r.IsFaulted)
        {
            f(ma.Value);
        }
        return r;
    }
```
That means multiple evaluations of the resulting expression will run the `Do` operation multiple times, but only once per evaluation.  Then if the coder wants a strict expression they will still need to use `.Strict()` as before.
