### ISSUE TITLE
Append, or Add?

### ISSUE THREAD

**Issue by Jagged** [louthy/language-ext#60]
This could go nowhere, so I thought I'd ask before spending any time on it.

Currently we have ``IAppendable``, which doesn't gel for adding numbers.  1 append 2 is 12, not 3.  Append has a very specific meaning in our field, ie concatenate.

So perhaps ``IAddable`` is more generic, being clearer for numbers, and also fits for lists etc too.  And it fits very nicely in with the other related interfaces.

For consistency all Append/append methods could be renamed to Add/add too.

Thoughts?

OK, I lie, I have a PR ready, just holding off submitting it until I know if it's something you'd like =)

**Comment by louthy** [comment]
`Append` is primarily to support the monadic types and is named because of `mappend` in Haskell.  This is to bring familiarity.  `Add` clashes with the default behaviour of lists, maps and sets.  There is no extension method for numeric types so it doesn't have an API effect. 
It would like to keep it as `Append` and `IAppendable`

**Comment by Jagged** [comment]
Sweet, I suspected it could have roots from other functional langages =)
