### ISSUE TITLE
Is there any sample Asp.Net Web API Framework or .Net Core available using this library?

### ISSUE THREAD

**Issue by aramkoukia** [louthy/language-ext#606]
Is there any sample Asp.Net Web API Framework or .Net Core available using this library?

I was looking for some scaffolding project or some end to end sample that demonstrates how this library can be used and how the project and code will be structured?

**Comment by louthy** [comment]
You could try looking through the `Used By` list:  https://github.com/louthy/language-ext/network/dependents?package_id=UGFja2FnZS0xNTY5MDEyMzc%3D

The button at the top of the repo unfortunately points at the wrong package (if anyone knows how to get github to use the correct package for Used By I would appreciate it, because Github's support hasn't bothered replying to me).
