### ISSUE TITLE
Bind for OptionalResult?

### ISSUE THREAD

**Issue by vinceg433** [louthy/language-ext#614]
Couldn't find a Bind extension for OptionalResult, so we wrote one.  I wonder if it should be part of the library?  Or maybe there's another way we should chain operations returning OptionalResult together?

`public static OptionalResult<R> Bind<T, R>(this OptionalResult<T> ts, Func< T, OptionalResult<R>> f) =>
            ts.Match
                (
                    None: () => None,
                    Some: (a) => f(a),
                    Fail: (a) => new OptionalResult<R>(a)
                ); `

**Comment by gwintering** [comment]
`OptionalResult` is designed as an intermediate value that powers `TryOption`, so in general you should work with `TryOption` and not `OptionalResult`.

You can check out Paul's typically voluminous answer from #298 for more details; the only difference is #298 is about `Result`/`Try` instead of `OptionalResult/TryOption`.

**Comment by vinceg433** [comment]
Very good, thanks for the help.  Basically we were trying to do a TryOption(Func1).Try().Bind(TryOption(Func2).Try), when we should have been doing TryOption(Func1).Bind(TryOption(Func2).Try().  Marking as closed.
