### ISSUE TITLE
Easier way to use void function in Linq 

### ISSUE THREAD

**Issue by qwas368** [louthy/language-ext#617]
Below example, I use fun() to wrap WriteLine function. But it's a little bit redundant ...
Is any easier way to use void function in Linq ？

```csharp
public Subsystem<string> Upgrade(string path) =>
    from fileinfo in TryGetFileInfo(path)
    let _ = fun(() => Console.WriteLine($"File {fileinfo.Fullname} size is {fileinfo.length} byte."))()
    from content  in ReadFile(fileinfo)
    select content;
```

**Comment by louthy** [comment]
Unfortunately because void is a type that has zero values there’s no way to
map it to another value.  I tend to just wrap them up in static helper
functions (or local functions), but your approach is valid too.  For simple
method groups you should be able to do stuff like fun(f)(...) - where f is
the void returning function you want to wrap.

I’m not at a machine where I can check that right now, but it should work.

**Comment by gwintering** [comment]
We can slightly improve the syntax from
```csharp
let _ = fun(() => Console.WriteLine("info"))()
```
to
```csharp
let _ = ignore(() => Console.WriteLine("info"))
```
with this additional `ignore` method
```csharp
public static Unit ignore(Action action)
{
    action();
    return unit;
}
```

**Comment by IDisposable** [comment]
Love the ignore

**Comment by louthy** [comment]
At a computer now, so this will work:
```c#
   fun<string>(Console.WriteLine)("Hello");
```
Unfortunately, you do need to provide the generic parameter.

**Comment by qwas368** [comment]
Thanks for reply.
