### ISSUE TITLE
Traverse an Either<Error, Task> 

### ISSUE THREAD

**Issue by blakeSaucier** [louthy/language-ext#619]
Hi, thanks for all the great work on this project.

A question on `Either` and `Traverse`:

Given an `Either<Error, Task<int>>`, I want to produce a `Either<Error, int>`. Naturally I would use `Traverse()` to get the inner right value.

I noticed that the following code results in a `LanguageExt.BottomException`:
```C#
Either<Error, Task<int>> eitherFail = Left<Error>("Something went wrong.");

var traversed = await eitherFail.Traverse(e => e); // Either<Error, int>

traversed.Match(
    Left: e => Assert.Pass(),
    Right: t => Assert.Fail("Should have failed"));
```
Of course there is no 'Right' value, so traversing the task doesn't do anything.

Is this expected? Is there a better way to be dealing with `Either` and `Task`s?

Thanks

**Comment by blakeSaucier** [comment]
Ok, played around a bit more:
```
var binded = await eitherFail.BindAsync<Error, Task<int>, int>(async a => await a); // Left
var mapped = await eitherFail.MapAsync<Error, Task<int>, int>(i => i); // Left
var traversed = await eitherFail.Traverse(e => e); // Bottom
```
I can use `MapAsync` and `BindAsync` to accomplish what I want however I'm still wondering about `Traverse()`

**Comment by gwintering** [comment]
> Given an Either<Error, Task<int>>, I want to produce a Either<Error, int>. Naturally I would use Traverse() to get the inner right value.

Not exactly.  `Traverse`'s main function is to flip inner and outer monads, so that `A<B<int>>` becomes `B<A<int>>`.  The other thing `Traverse` does is take a function that maps the bound value, so `A<B<int>>` can become `B<A<whatever>>`.  Usually the mapping function is of type `Func<int,whatever>`, but when the new outer type (`B`) is a `Task` or other `Async` type, you can also supply a mapping function `Func<int,Task<whatever>>`; the second form is used in your example.

> [`Traverse`] results in a LanguageExt.BottomException.  ... Is this expected?

Hmm, I guess it's reasonable to expect a `Task`, not in a `Bottom` state that yields an `Either` in `Left` state.  Is that what you were expecting?  There may be a way to get this out of `Traverse` but I'll have to think how to generalize it.

> Is there a better way to be dealing with Either and Tasks?

In general, to go from `Either<L,R>` to `Either<L,R2>`, use `Map` because it let's you project the `R` value.  In this case, you need a function from `Task<int>` to `int`, which is just `Result`

```csharp
Either<Error, int> mapped = eitherFail.Map(x => x.Result);
```
Now using `Result` is not great because you're doing sync over async, which can lead to deadlocks.  But if you know how all the threads interact by the time you need `Result`, (i.e. you're writing an application, not a library) it can work.

To avoid `Result`, or at least delay it's use, switch to `EitherAsync`:

```csharp
EitherAsync<Error, int> eitherFailAsync = eitherFail.ToAsync().MapAsync(x => x);
```

Then you can basically run whatever functions you wanted to run on `Either` on your `EitherAsync`.  When you're ready to read the bound value, you can `await` or `Result` a `.Match` or `.ToEither()`.

**Comment by blakeSaucier** [comment]
> Hmm, I guess it's reasonable to expect a Task, not in a Bottom state that yields an Either in Left state. Is that what you were expecting?
Yes, this is what I was expecting to happen.

I will continue on with `MapAsync`. I think that's more appropriate for this situation.

Thanks for your response.
