### ISSUE TITLE
FYI - Have you seen Tail.Fody?

### ISSUE THREAD

**Issue by Jagged** [louthy/language-ext#62]
It adds tail-calls to the IL automatically during build time, allowing you to write recursive C# code functionally without worrying about blowing the stack: https://github.com/hazzik/Tail.Fody

There's another for adding null checks to all methods, except for where you specify, eg. OptionUnsafe.
https://github.com/Fody/NullGuard

It's quite interesting what Fody (and related addons) can do!

Just food for thought...

**Comment by Jagged** [comment]
Any thoughts before I close this?

**Comment by louthy** [comment]
Sorry, haven't really had time to follow this up.  

> Have you seen Tail.Fody

Not that specific plugin no, but I have seen Fody.  I think Tail.Fody whilst useful for the end-user, isn't really that useful for language-ext.  Also I believe that RyuJIT is supposed to do a better job of dealing with tail-calls, so it's probably moot.  It's nearly never an optimisation in C# because loops will always be faster than recursion.  I think for the users of Language-Ext they would prefer the speed benefits of a pure functional interface hiding imperative behind-the-scenes (as long as the behaviour is referentially transparent - as with the `fold` implementations).

> There's another for adding null checks to all methods, except for where you specify, eg. OptionUnsafe.
https://github.com/Fody/NullGuard

That's definitely more interesting, but might be a painful process of retrofitting `[AllowNull]` where it _is_ allowed.  I'd be quite cautious about this, because of possible breaking changes.  I dunno, I'm torn, because it's obviously a very good idea, and I can't stand the fact that the `if(arg == null)` checks breaks expression based code.

**Comment by Jagged** [comment]
If you're interested, I could put NullGuard just into OptionT and UnsafeOptionT, and see what you think from there?

**Comment by louthy** [comment]
My understanding is that you can't opt-in, you can only opt-out by using
[AllowNull], so that would be a project-wide change.  That is my concern.
There's a ton of code that would need to be considered.  Unless you know
otherwise?

It seems to defeat the point having to opt-in.

**Comment by Jagged** [comment]
The opt-in approach would let us get used to it before we risk turning it on across the lot.  
Or we rely on the unit tests and hit the big red button...

I'll check and get back to you re project-wide opt-out.

**Comment by louthy** [comment]
It seems to me to be the kind of thing that would only be valuable project-wide.  Otherwise when you look at any cs file you won't know whether it's got the protection it needs [without looking at some project settings].  If you're prepared to take it on project-wide that'd be great, but I wouldn't underestimate the amount of work and the cautious approach you'd need to take.

**Comment by Jagged** [comment]
Yes, I hear you there.  Just read their outstanding issues and am concerned that maybe it isn't ready for Roslyn yet, which we depend on.  Probably shelve it for now methinks, sorry to waste your time there!

 (I'll keep an eye on it, it wouldn't surprise me if a patch comes sometime in the coming weeks)

**Comment by louthy** [comment]
Thanks Will, I don't think it's time wasted.  It definitely has potential.
Let's keep an eye on it.
