### ISSUE TITLE
JsonConverter for LanguageExt.Option that serializes None as null.

### ISSUE THREAD

**Issue by gmanny** [louthy/language-ext#626]
Good day to you!

For reasons of compatibility with an external system (particularly, the `play-json` deserializer in Scala), I needed to serialize `None`s as `null`s in Json.Net, so I've written [this `JsonConverter`](https://gist.github.com/gmanny/dda5fe1d6ebc9dfa6843741c568a12b9) with usage example in the second file of the gist.

I've seen your stance on the serialization code for Options breaking, and I agree that it's not critical, but writing this converter was not trivial, and so I've just wanted to put it out there for others to find and use in cases where it's needed.

I've verified the code to work with versions 3.1 and 3.3. of the library.

I guess, the only question this issue brings up is whether you could include this as part of the library itself so that people would just plug it into their JsonSerializer when they have to. No other action is needed, so you can close this issue immediately.

Other than that, would always like to hear your thoughts on the code and approach :)

Thank you!

**Comment by louthy** [comment]
It's difficult to change serialisation/deserialisation without breaking somebody's code.  If anyone's serialised an `Option` to a file then they're not going to get it back if I change it.  And so, now that the current serialisation has stabalised (since the endless pain of Json.NET changing under me), I'm not really looking to change the current code.

On the general approach: If I remember right `Option` serialises as an empty list `[]` for `None`, which I think is quite elegant, whereas `null` is a concept I've tried to actively fight against with lang-ext, so whilst it may be right for your use-case I couldn't really countenance using `null` I'm afraid.

**Comment by gmanny** [comment]
Yup, like I said, I understand both of these concerns, and don't want you to change the default behavior at all. The only mild suggestion was to consider adding it as a loose class which can be used sparingly by people who know that they need it.

And again, I get that it may unnecessarily broaden the contract of the library and add something that you won't want to support going forward, so the suggestion is only a mild one to get your thoughts on that.

This issue was created primarily because I wanted to share a thing with the world and this place looks more appropriate than the stackoverflow

**Comment by bender2k14** [comment]
@gmanny, you can post your code here. That will allow others to benefit from your code without also having to officially add that code into the library.

**Comment by louthy** [comment]
@gmanny To put the code into lang-ext I'd need to create a `LanguageExt.JsonSerialization` project (because `Core` shouldn't depend on `Json.NET`), and to be honest that's too much of a long term maintenance project and could perhaps cause confusion between the default serialisation and the more opinionated one of the `LanguageExt.JsonSerialization` project.  

One other approach is for you to create a nu-get package like @NickDarvey and @yuriylsh have done with [NickDarvey.LanguageExt.AspNetCore](NickDarvey.LanguageExt.AspNetCore) and [LanguageExt.UnitTesting](https://www.nuget.org/packages/LanguageExt.UnitTesting).  

I fully support the creation of an eco-system around lang-ext.  So if you go ahead an do that (perhaps supporting the full set of `DataTypes`) and then let us know through the issues here.  I could potentially create some links from the wiki to other libraries that work with lang-ext, and so any suitably complete library could go in that list.

**Comment by gmanny** [comment]
@louthy that's an awesome suggestion, thank you! I'll let you know here in the comments once it's live. Have a nice day!

**Comment by louthy** [comment]
I have added the two projects above to [a section on the home-page of the wiki](https://github.com/louthy/language-ext/wiki).  If anyone else has projects that directly support language-ext please get in touch and I'll add them.

**Comment by nosalan** [comment]
It was a total surprise for me that the `Option` serializes as an empty list [] for `None`. I don't find this elegant, maybe if the wrapped type was enumerable then yes. As much as I don't like nulls, in systems that have this concept, like JSON, it should be honored. Replacing nulls with empty array makes it hard to adhere to the schema, because sometimes the `Option<T>` can be serialized as a JSON object and sometimes as a JSON array.

**Comment by louthy** [comment]
> It was a total surprise for me that the `Option` serializes as an empty list [] for `None`. I don't find this elegant, maybe if the wrapped type was enumerable then yes. As much as I don't like nulls, in systems that have this concept, like JSON, it should be honored. Replacing nulls with empty array makes it hard to adhere to the schema, because sometimes the `Option<T>` can be serialized as a JSON object and sometimes as a JSON array.

You'll be pleased to hear that all support for serialisation has been removed from `v5` of language-ext, so now you can implement your own.
