### ISSUE TITLE
Intermediate results in errors and logs

### ISSUE THREAD

**Issue by koffmoff** [louthy/language-ext#642]
I struggle finding a nice solution to the following problem.  If a chain of computations is interrupted by an error, I often find the need to log not only the specific error, but also some context information, like previous intermediate steps of the computation. Take this concrete example:

```ts
public static TryAsync<T> getJson<T>(RestClient restClient, string url) =>
    from response in restClient.Get(url)
    from content in readContentAsString(response)
    from validResponse in validateResponse(response).ToAsync()
    from obj in deserializeJson<T>(content).ToAsync()
    select obj;
```

All steps above are simple Try-wrappers around non functional code. They compose beautifully. But say the last step `deserializeJson` fails. The exception message from the Json deserialization is unlikely to be very helpful in debugging the error. The reason might very well be an incorrect url. At the point of error I would like to collect not only information about the exception, but also all intermediates leading up to the exception (`url`, `response`, `content`).

Today I do something like this:

```ts
public static EitherAsync<Error, T> getJson2<T>(RestClient restClient, string url) =>
    from response in restClient.Get(url).ToEitherAsync(ex => createError(ex, url))
    from content in readContentAsString(response).ToEitherAsync(ex => createError(ex, url, response))
    from validResponse in validateResponse(response).ToEitherAsync(ex => createError(ex, url, response, content))
    from obj in deserializeJson<T>(content).ToEitherAsync(ex => createError(ex, url, response, content))
    select obj;
```

It works but I think much of the beauty is gone. Error handling is taking over and obscuring the main intent in the flow.

Are there other/better ways to approach this?

**Comment by bender2k14** [comment]
You should take your own advice:
> All steps above are _Error-wrappers around_ simple Try-wrappers around non functional code. They compose beautifully.

Adding error handling shouldn't impede upon this top-level sequence of your code.  Scott Wlaschin explains this really well in his talk called [Railway oriented programming](https://fsharpforfunandprofit.com/rop/).  In particular, see 6:20 - 6:30 in the primary recording for how correctly adding error handling barely changes the syntax at the top level.  Of course his examples are in F#, but the principles carry over to any functional programming context.

**Comment by koffmoff** [comment]
@bender2k14 , I fully agree that error handling shouldn't impede upon the top-level sequence of my code. That is really the essence of my question. In a pipeline of computations, how can I include previous intermediate values in later errors, *without* obscuring the main flow.

I've watched Scott's presentation. I appreciate everything but I don't think he really addresses my question. 

After some thought it seems to me I have three options. It all comes down to *where* the errors are created and *what* information is available at that point.

### 1. Create the errors "locally" within each function.

All information required to create the error is pushed down the "happy path". For example, the signature of `deserializeJson` would be something like:

```ts
public static Either<Error, T> deserializeJson<T>((string url, HttpResponseMessage response, string content) input)
```

`url` and `response` is passed just in case deserialization fails and we need to create an error with contextual information. `content` is really the only thing required by the happy path.

\+ The main pipeline is not cluttered with error handling.
\- Each function in the pipeline takes more input than its happy path requires, just to cope with error cases. This obscures intent.

### 2. Create the errors "globally" in the pipeline.

This is the way I do it today (see second code example in my original post). Each function is kept clean. It takes only the input it requires and returns a "local" error without context information. A new error is created by the pipeline where all intermediates are available.

\+ Each function is kept clean.
\- Pipeline becomes obscured by error handling.

### 3. Create the errors "in the glue" between the functions in pipeline.

I could imagine a new monad that collects all intermediates automatically and in case of an error, all intermediates are attached to the error. This would mean all errors would automatially get all available context information attached to it without neither the local function nor the global pipeline bothering with any extra error handling.

\+ Each function is kept clean.
\+ Pipeline is kept clean.
\- Errors become very generic with a bunch of metadata attached to them that needs to be dealt with in some "outer" scope.

Do you follow my thought? Am I lost in the woods? Any ideas? Other ways of doing it? I'm not very used to designing functionally...

**Comment by bender2k14** [comment]
As some reassurance, it was not my intention to imply that error handling is trivially easy.  Quite the opposite actually; I think certain aspects of error handling are the most complex things that I have encountered in all of programming.

Case 3 sounds great, but it seems to me like a solution for a problem that shouldn't exist.  In a perfect world, I imagine that all the necessary context for some error is immediately available because it was already necessary for the computation that "failed".  If there were true, then I think that would eliminate the only downside you listed for case 1.  For the record, I think the code I write is most often like case 1.

Without the Try-wrappers, your example code could throw exceptions.  As functional programmers, we could call such functions partial functions, and one of our goals is to only work with total functions.  There are two ways to obtain a total function from a partial function:
1. decrease the domain or
2. increase the codomain.

For example,
```
int remainder(int dividend, int divisor) =>
  dividend % divisor
```

throws an exception when `divisor` is `0`.  We can increase the codomain by returning `Option<int>` instead of `int` and return `None` when `divisor` is `0`.  Alternatively, we can decrease the domain by taking in `NonZeroInt divisor` instead of `int divisor`.  Typically, I think the latter approach is better.

You say...
> [Suppose] the last step `deserializeJson` fails. The exception message from the Json deserialization is unlikely to be very helpful in debugging the error. The reason might very well be an incorrect url.  At the point of error I would like to collect not only information about the exception, but also all intermediates leading up to the exception (`url`, `response`, `content`).

Several things strike me here.  First, of course could pass in a stronger type for URL than `string`, and you explicitly passed in the type parameter `T`.  It would make more sense to me if your custom URL type included this type parameter.  Then maybe there could be some validation earlier in the program when this string and type parameter are combined into your custom URL type.

Second, you call `validateResponse` but then ignore its return value.  I suggest that you do validation as demonstrated by [this test](https://github.com/louthy/language-ext/blob/96de33c18845ccb1566c59384984f5ebad1f7fcb/LanguageExt.Tests/ValidationTests.cs#L136) and those below it.  In particular, I recommend combining your top-level functions `validateResponse` and `deserializeJson` into one function.  Let's call this function `f`.

Third, you don't need to add the URL to an error from `f` because the caller of this function can do that.  Furthermore, this can be done by wrapping the given function with another that add the URL to the error.  Then your happy path is not crowded by your error path.  (This wrapping is isomorphic to the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern#targetText=In%20object%2Doriented%20programming%2C%20the,objects%20from%20the%20same%20class) in OOP.)  The way I see it, the ideal to strive for is to write code such that all desired "context" is easily available as function arguments.

**Comment by louthy** [comment]
First thing I would do is to try to reduce the clutter:
```c#
public static class EitherAsyncExtensions
{
    public static EitherAsync<Error, A> Track<A>(this EitherAsync<Error, A> ma, params object[] items) =>
        ma.ToEitherAsync(ex => createError(ex, items));
}
```
That assumes that `createError` takes a `params` of type `object[]` (it's not exactly clear if you have lots of `createError` functions.

Then your example looks like this:
```c#
public static EitherAsync<Error, T> getJson2<T>(RestClient restClient, string url) =>
    from response in restClient.Get(url).Track(url)
    from content in readContentAsString(response).Track(url, response)
    from validResponse in validateResponse(response).Track(url, response, content)
    from obj in deserializeJson<T>(content).Track(url, response, content)
    select obj;
```
If you want to reduce it even more then you're in the territory of creating your own monad that can carry the context through (like the `State` or `Writer` monads do).

**Comment by koffmoff** [comment]
@bender2k14 , indeed I could tie the `url` and the expected type of the response `T` together. It would reduce the likelihood of error. But not eliminate it. And when a deserialization error occurs, I believe it is vital to have the `url` in the error.

Further, the call to `validateResponse` is just a validation that the status code is 200. It does not mutate the response and should more properly be assigned to a "noname" variable like so:

```cs
from _1 in validateResponse(response).ToAsync()
```

The reason I call it *after* `readContentAsString` is because in case it fails, I want to have the `content` ready to be packed into the error.

@louthy , well actually I have a bunch of `createError` functions today. To be type safe. Different types are packed differently into the error. The same could of course be achieved by a matching bunch of `Track` overloads.

Thanks to both of you for yor advice. Think I will try out bits and pieces of each and see where it leads!
