### ISSUE TITLE
Option as a Class and Some and None derived from it

### ISSUE THREAD

**Issue by tyger** [louthy/language-ext#671]
I know the reasonin behind making the `Option` as a `Struct` (to avoid null assignment), but it seems a bit unnatural for me cause implementation of `Option `with `None `and `Some `doesn't make `Algebraic Data Type`. And given that `C# 8` is comming with improved pattern matching expression it seems even more reasonable to revisit design again.
Personally I don't see assigment of nulls to `Option `as a big deal - it's down to developer in the end and `Scala`, for instance, (and `F#` I guess) allows that, so shouldn't be end of the world, but making `None` and `Some` will make it realy easier to pattern match and reasoning about it.
What are your thoughts on this @louthy ?

**Comment by louthy** [comment]
> I know the reasonin behind making the Option as a Struct (to avoid null assignment)

The other reason is performance.  `Options` are values and shouldn't cause heap allocation.  If you're wrapping a `struct`  this is the equivalent of boxing, which isn't ideal.

> And given that C# 8 is comming with improved pattern matching expression it seems even more reasonable to revisit design again

There's a way of doing this, that I have in prototype form, without making `Option` into a `struct`.  It will cause an allocation however, which isn't ideal, but the allocated object will last for such a short time that it shouldn't cause excessive GC problems and it only needs to happen on match, which should happen less frequently than all of the other operations on `Option`.  

Allocations already happen on matching because of lambda allocation, so this wouldn't be any worse.

First, we'd need a lightweight representation of `Option` in `class` form:
```c#
    public interface IOption<A>
    { }

    public class Some<A> : IOption<A>
    {
        public A Value;
        public Some(A value) =>
            Value = value;
        public void Deconstruct(out A Value) =>
            Value = this.Value;
    }

    public class None<A> : IOption<A>
    {
        public static IOption<A> Default = new None<A>();
    }
```
Then, in the `Option<A>` struct we add a property:
```c#
    public IOption<A> This =>
        IsSome
            ? new Some<A>(Value)
            : None<A>.Default;
```
We can then use the pattern-matching feature of C# 8:
```c#
    var mx = Option<int>.Some(123);

    var rx = mx.This switch
    {
        Some<int>(var x) => x,
        _                => 0
     };

```

> Personally I don't see assigment of nulls to Option as a big deal

I do and that's why `OptionUnsafe` exists.  Much of this library has been built to defend against `null` which should never have existed.  I realise the C# team have fixed that problem (somewhat, it's not entirely solved), but this type is explicitly about a contract that says no to `null`.

**Comment by tyger** [comment]
> > I know the reasonin behind making the Option as a Struct (to avoid null assignment)
> 
> The other reason is performance. `Options` are values and shouldn't cause heap allocation. If you're wrapping a `struct` this is the equivalent of boxing, which isn't ideal.
But still most of the cases people use `Option` is for wrapping `reference types` means that allocation is laready happenning and is going to be for as long as original value. In this case I wouldn't worry to much about resource consumption, though your reasoning has a point.
> 
> > And given that C# 8 is comming with improved pattern matching expression it seems even more reasonable to revisit design again
> 
> There's a way of doing this, that I have in prototype form, without making `Option` into a `struct`.
You meant here `class`, I guess?
> It will cause an allocation however, which isn't ideal, but the allocated object will last for such a short time that it shouldn't cause excessive GC problems and it only needs to happen on match, which should happen less frequently than all of the other operations on `Option`.
> 
> Allocations already happen on matching because of lambda allocation, so this wouldn't be any worse.
Not every lambda is translated into instance method, most (should) be optimized to static methods as not having any closures. So means that only concern should be allocating classes itself.
> 
> First, we'd need a lightweight representation of `Option` in `class` form:
I like this idea and it could be good workaround, but not without concerns:
* This will add even more confusion for developers in what case use `Some` as class (you shouldn't), in what case use `Some` as method from `Prelude` and how you operate all of that.
* If you anyway kind of ready to introduce it as classes, will it make sense to review concept of `UnsafeOption` at least - make it `class` based?
> 
> > Personally I don't see assigment of nulls to Option as a big deal
> I do and that's why `OptionUnsafe` exists. Much of this library has been built to defend against `null` which should never have existed. I realise the C# team have fixed that problem (somewhat, it's not entirely solved), but this type is explicitly about a contract that says no to `null`.
I understand what you are talking about, but this is trying to fix language (C#) design issues by being too protective on the `tools` side. I would see it as instrument rather for developers to make right call and use it correctly.
Plus the only danger here if somebody will explicitly try to assign `null` to `Option<T>` variable, in all other cases compiler will prohibit that because of types and `implicit` conversion will do the rest. Again it might be good for `UnsafeOption`.

**Comment by louthy** [comment]
> But still most of the cases people use Option is for wrapping reference types means that allocation

What's evidence for that is?  Your own usage?  Allocation is absolutely a concern.  You many not consider it important, but [when developing a library] it is something that should be at the top of mind.  Unnecessary resource usage is an anathema in my mind.  

The use-cases for Option are many and there are areas where where memory performance really would become a factor.  For example an array of options where `A` is a struct.  Where possible this library is attempting to be the most performant functional framework out there.  As much as possible `Option` should be close to the performance one would expect from using a nullable reference (but with the type-safety that nullable references don't have).

Also, changing to `class` will break everybody's code who relies on `default` meaning `None`.  Backwards compatibility is absolutely a concern, especially with what is probably the most used type in the library.  

The library also has to work for more than just users of C# 8 - not everyone can live on the bleeding edge.

> You meant here class, I guess?

Yep

> Not every lambda is translated into instance method, most (should) be optimized to static methods as not having any closures. So means that only concern should be allocating classes itself.

Whilst not every lambda becomes an instance method, it is true that every lambda causes a heap allocation. Lambdas that reference free variables require two allocations per lambda (one for the instance to capture the free variables and one for the `Func`.  

This simple example shows that allocation still occurs, even without free variables.
```c#
    var mx = Some(123);
    var srx = mx.Match(
        Some: _ => 1,
        None: () => 0
    );
```
So, in theory because there are no free variables the Some and None lambdas could be `static`.  

The problem is that `Match` requires a `Func`, which is an object on the heap.  It can't take a _method group_.

Here's the IL
```c#
	IL_0013: ldloca.s 0
	// (no C# code)
	IL_0015: ldsfld class [mscorlib]System.Func`2<int32, int32> ConsoleApp27.Program/'<>c'::'<>9__0_0'
	IL_001a: dup
	IL_001b: brtrue.s IL_0034

	IL_001d: pop
	IL_001e: ldsfld class ConsoleApp27.Program/'<>c' ConsoleApp27.Program/'<>c'::'<>9'
	IL_0023: ldftn instance int32 ConsoleApp27.Program/'<>c'::'<Main>b__0_0'(int32)
	IL_0029: newobj instance void class [mscorlib]System.Func`2<int32, int32>::.ctor(object, native int)
	IL_002e: dup
	IL_002f: stsfld class [mscorlib]System.Func`2<int32, int32> ConsoleApp27.Program/'<>c'::'<>9__0_0'

	IL_0034: ldsfld class [mscorlib]System.Func`1<int32> ConsoleApp27.Program/'<>c'::'<>9__0_1'
	IL_0039: dup
	IL_003a: brtrue.s IL_0053

	IL_003c: pop
	IL_003d: ldsfld class ConsoleApp27.Program/'<>c' ConsoleApp27.Program/'<>c'::'<>9'
	IL_0042: ldftn instance int32 ConsoleApp27.Program/'<>c'::'<Main>b__0_1'()
	IL_0048: newobj instance void class [mscorlib]System.Func`1<int32>::.ctor(object, native int)
	IL_004d: dup
	IL_004e: stsfld class [mscorlib]System.Func`1<int32> ConsoleApp27.Program/'<>c'::'<>9__0_1'

	IL_0053: call instance !!0 valuetype [LanguageExt.Core]LanguageExt.Option`1<int32>::Match<int32>(class [mscorlib]System.Func`2<!0, !!0>, class [mscorlib]System.Func`1<!!0>)
	IL_0058: stloc.1
```
Notice the two `newobj` allocations for the two `Func` objects needed for `Some` and `None`.  And so all matching currently allocates.  The only way to avoid it is to avoid lambdas (by using `IfNone`, or casting, etc.)

My proposed solution would reduce the allocations in the simplest case by half, and in the most complex case (free variables referenced in both lambdas) there would be a 1/4 of the current allocations.

> This will add even more confusion for developers in what case use Some as class (you shouldn't), in what case use Some as method from Prelude and how you operate all of that.

I don't understand what you're trying to say here?  But I'll riff on what I think you might be asking...

`Some` in the `Prelude` is a constructor function, just like it is in functional languages.  Sum-types (discriminated unions) are essentially a collection of constructor functions that generate the sum-type (not the a case type).  For example, there's not really a concept of a type called `Some` in the functional world, there's only the concept of `Option a`.  Pattern-matching in compilers are a sub-language within the language itself, and when it comes to matching cases of sum-types, they're actually matching on the constructors, not the type.  

C# doesn't have the concept of constructor functions outside of a `class` or `struct` and so that's why this system is a little bit odd.  I'm sure, however, when the C# team implement sum-types properly then they'll need to have a concept of a constructor function.

In terms of when to use the `Some` class, well, you can't.  The construction is `internal`.  So, there's no way of creating one outside of the library code.  You would just use the constructor function as laid out in the documentation.

> If you anyway kind of ready to introduce it as classes, will it make sense to review concept of UnsafeOption at least - make it class based?

The same issues I've listed are a concern here also:

* Null de-reference issues
* Allocation performance issues
* Users on previous versions of C#

> I understand what you are talking about, but this is trying to fix language (C#) design issues by being too protective on the tools side

You're confusing being declarative with being protective.  There is an explicit contract that `Option` honours.  `OptionUnsafe` can't honour the contract of the parameters used to construct it, and so it instead warns of potential contract breaches by calling itself _Unsafe_.

For example
```c#
    Option<A> Some<A>(A value)
```
The expectation here is that `Option<A>` contains an `A`.  Except, because the poor C# type-system allows `null`, it might not.  And so it's a dishonest type.  The disallowing of `null` in `Option<A>` is to make the construction and manipulation of `Option<A>` honest.

```c#
    OptionUnsafe<A> SomeUnsafe<A>(A value)
```
This declaratively carries around a flag saying "watch the f**k out!".  

> I would see it as instrument rather for developers to make right call and use it correctly.

I started writing this library because developers don't make the right call.  They consistently make mistakes, because they're human.  The point of this library is to help programmers make good decisions by default.

**Comment by tyger** [comment]
We've covered pretty much everything and it's time to wrap it up. I've got your reasoning and approach. Thank you.

Small note: in OOP based (not fully functional) laguages like Scala `Some` and `None, as well as `Left` and `Right` of `Either` are implemented as real classes: https://www.scala-lang.org/api/current/scala/Some.html https://www.scala-lang.org/api/current/scala/util/Left.html

**Comment by louthy** [comment]
The Scala framework developers are, of course, free to implement their libraries however they see fit.  This library isn't a Scala framework clone.  It is certainly opinionated, but I think those opinions are made pretty explicit in the `README.md`, I have no plans to change the direction of types like `Option` because the original reasons for their implementation still holds, sorry.
