### ISSUE TITLE
Should BindAsync be chainable on Task<Either>?

### ISSUE THREAD

**Issue by Tyf0x** [louthy/language-ext#691]
I was wondering if having tan extension similar to `BindAsync(this Task<Either<L, R>> self, ...)` for `MatchAsync` would be helpful?

We currently have to do `await (await MyAsyncEitherFunc()).MatchAsync(...);`.
Adding the extension method would allow to simplify to `await MyAsyncEitherFunc().MatchAsync(...);`.

Thanks for this awesome library BTW!

**Comment by louthy** [comment]
@Tyf0x Have you considered using `EitherAsync<L, R>` instead of `Task<Either<L, R>>`?  It is designed to capture all of this in one type.  You can convert to it from a `Task<Either<L, R>>` using `ToAsync()`:
```c#
   eitherTask.ToAsync().Match(...);
   eitherTask.ToAsync().MatchAsync(...);
```
And then use `Match` or `MatchAsync` directly on the `EitherAsync`.

These are the constructors to use to create one:
```c#
EitherAsync<L, R> RightAsync<L, R>(Task<R> value)
EitherAsync<L, R> RightAsync<L, R>(Func<Unit, Task<R>> value)
EitherAsync<L, R> RightAsync<L, R>(R value)
EitherAsync<L, R> LeftAsync<L, R>(Task<L> value)
EitherAsync<L, R> LeftAsync<L, R>(Func<Unit, Task<L>> value)
EitherAsync<L, R> LeftAsync<L, R>(L value)
```

**Comment by Tyf0x** [comment]
This make sense! Thanks for the heads-up :)
