### ISSUE TITLE
Fluent API for parse<type> Functions?

### ISSUE THREAD

**Issue by msm-ms2soft** [louthy/language-ext#724]
Hello!

I'm looking to "sell" language-ext to my coworkers and noticed that `parseInt`, `parseDecimal` etc. don't seem to have "fluent" extension method versions. Is this intentional, an oversight, or am I just not importing the right namespaces?

Being able to chain parses together as methods would make things much more readable (and thus convincing) and consistent, given that methods are unfortunately the standard unit of composition in C#

Thanks in advance for any guidance you can provide. Looking forward to being able to use this library!

**Comment by bender2k14** [comment]
I think an important design philosophy with extension methods is to only create an extension method if it would make semantic sense to call that extension method in every place that it is syntactically possible to do so.

As such, I think it would be a bad idea to make `parseInt` (and friends) into an extension method because although it would be syntactically possible to to write `emailAddress.ParseInt()`, it doesn't make semantic sense to do so.

**Comment by iamim** [comment]
Maybe what you are looking for is monadic composition? If notice, `parseXXX` family of functions return `Option<XXX>`, not `XXX` itself. Thus, if you wanted to parse some sort of ID from a string with a rule that it must be greater than 1000, you could write it like this:
```
struct Id
{
    public readonly int Val;
    private Id(int id) => Val = id;

    public static Option<Id> parseId(int id) => id > 1000 ? new Id(id) : Option<Id>.None;
}

static Option<Id> parseId(string s) => from n in parseInt(s)
                                       from i in Id.parseId(n)
                                       select i;
```

**Comment by msm-ms2soft** [comment]
My primary interest is making adopting language-ext easy for my coworkers to adopt, as I "sold" it by appealing to dissatisfaction with `out` parameters and `TryParse` functions. 

Having fluent parse methods would work well with our tooling as intellisense can't seem to detect `parseInt` just written out by itself and suggest an import in the same way it would an extension method. 

I think it's also good to have methods, although when you're stuck in an OO environment to begin with, for uniformity's sake.  `x.Method1().ParseSomething().Method2()` is much less awkward than `parseSomething(x.Method1()).Method2()`, the mixing two different kinds of invocation being very visually difficult to follow.

All of that being said, @bender2k14 I definitely see the semantic argument as a design philosophy and can respect it if that's the philosophy of language-ext.

@iamim monadic composition is one of the many reasons I jumped at my recent chance to "sell" language-ext as a better way of parsing strings! Come for eliminating `out` variables, stay for the entire FP philosophy 😄

**Comment by bender2k14** [comment]
> `x.Method1().ParseSomething().Method2()` is much less awkward than `parseSomething(x.Method1()).Method2()`, the mixing two different kinds of invocation being very visually difficult to follow.

I agree.  The second example is awkward, and I would not write code like that.

I feel like you have convinced yourself of a false dichotomy: that the two code examples you gave are the only two ways to write that.  I wouldn't write it in either way.

I would write it like this
```C#
x.Method1().Apply(parseInt).Method2()
```

**Comment by louthy** [comment]
@msm-ms2soft I'm sure you'd understand that your co-worker satisfaction isn't really the driving force behind the development of language-ext, and so if they're not coming along for the ride (and you want them to) then I guess some level of mentoring is needed internally.  Rather than approach it from the, _isn't it all nice and fluent_, point-of-view, perhaps look to focus on the major benefits of taking a functional approach to development, which language-ext enables:

* Declarative - this helps developers see the intent in the code
  * `Option`, `Either`, etc. are all useful in function declarations, as it declares the intent of the function without having to open up the source
  * `Map`, `Bind`, `Fold`, and the LINQiness of the types remove the clutter for `foreach`, `for`, `if` / `then` / `else`, `try` / `catch`, etc.
* Focus on type safety and immutability for more reliable code that directs you down the correct path
  * Fewer `null` reference exceptions
  * Easier to manage data of multiple thread
  * Data treated as values means more principled mathematical expressions, which lead to more reliable code.
  * There's a [nice talk by Rich Hickey](https://www.youtube.com/watch?v=E4RarTAZ2AY) which is the best description of why this stuff is important.
* Focus on pure function composition as the ultimate way of building complex systems
  * The OO way of doing composition is bad and very manual / error prone
  * OO inheritance is nearly always bad (not always, just nearly always)
  * Language-ext is all about function composition and makes writing composable building blocks much easier
* Look into the `LanguageExt.CodeGen` and see how it's a really powerful tool for creating immutable record and union types, helping de-clutter your code from the common patterns of implementing structural equality, ordering, hashing, etc.
* Talk about how all code is a liability for any company, the more of it you have, the more liabilities you have (because of the maintenance cost and the performance degradation of any team as a code base grows).  Code is also, paradoxically, an asset.  And so, if you can reduce the amount of code you have but it still performs the same set of features, then you win.  LanguageExt is all about reducing the amount of code you need to write to build complex systems.




Some of the points made already are true.  One of the problematic elements of making extension methods to `int`, `string`, etc. is that they pollute intellisense.  The library does some of that, but I'm very wary of doing that too much.  Parsing isn't a common enough activity for it to be permanently attached to a primitive type's extension namespace.

In terms of parsing, the big sell for you would be the `LanguageExt.Parsec` library, which is a library of [parser-combinators](https://en.wikipedia.org/wiki/Parser_combinator).  There's some examples in [the wiki](https://github.com/louthy/language-ext/wiki/Thinking-Functionally:-Combinators#combinator-libraries) and some unit tests of which the [expression parser](https://github.com/louthy/language-ext/blob/master/LanguageExt.Tests/ParsecTests.cs#L572) is a really nice example of the built-in functionality.  

It's a direct clone of the famous Haskell Parsec library and is a super powerful way to parse text (or a stream of tokens if you wish).  I've used it to parse entire programming language grammars, but it's equally at home with simpler tasks.  Some of the major benefits are:

* Combinators are, by definition, combinable - so small parsers that do simple things can be composed into more complex ones.  This is really powerful.
* There's contextual errors with line-numbers, column numbers, and details of the expected items when the parser fails
* There are loads of built-in parsers, from simple things like integers, strings, tokens, etc.  to complex items like expressions with operator precedence, associativity, prefix, postfix, and infix.

I'm happy to give you some examples if you put up some examples of some complex things you'd want to parse.

**Comment by msm-ms2soft** [comment]
@bender2k14 That kind of `.Apply` is something I've wanted to introduce internally, glad to know it comes with language-ext as well!

@louthy Thank you very much for the detailed reply! I've made many of those same points in a somewhat disorganized way (including much sharing of Rich Hickey talks), and it's great to have everything in one place. I'll definitely integrate them into my next formal presentation on the topic.

At this point, the issue for me is primarily patience, as people do seem to be coming around. Parsec is actually something I haven't looked into too much yet, but I'm sure its benefits are excellent.

My primary intent with this thread just to see if I was missing something, I wouldn't want to take up any more of anyone's time with my pet issue. Thanks everyone!
