### ISSUE TITLE
Traverse for any applicatives and traversables

### ISSUE THREAD

**Issue by dgrozenok** [louthy/language-ext#760]
May we come back to the issue https://github.com/louthy/language-ext/issues/296? I noticed that I never actually use `Traverse` functions, but instead most of the time I use the combination of `Map` iterating over a collection of the plain values and elevating them, and `Sequence` to iterate them again to switch the monads. I thought however the main idea of `Traverse` was to allow to iterate, elevate and switch in the same pass. I have created a bunch of helper functions like below for different kinds of applicatives and traversables, but I'm sure they are not as efficient as the proper implementation of the `Traverse` would be.

```C#
public static TryAsync<IEnumerable<TR>> TraverseSerial<T, TR>(this IEnumerable<T> enumerable, Func<T, TryAsync<TR>> func) =>
    enumerable.Map(func).SequenceSerial();

public static TryAsync<IEnumerable<TR>> TraverseParallel<T, TR>(this IEnumerable<T> enumerable, Func<T, TryAsync<TR>> func) =>
    enumerable.Map(func).SequenceParallel();

public static TryAsync<IEnumerable<TR>> TraverseParallel<T, TR>(this IEnumerable<T> enumerable, Func<T, TryAsync<TR>> func, int windowSize) =>
    enumerable.Map(func).SequenceParallel(windowSize);
```
Even the implementations like above I think would be helpful just syntactically for the time being. And then maybe in the future we would have them gradually reimplemented more efficiently.

An example use case is when I have a list of IDs and would like to load the products by those IDs from a repository:
```C#
var products = Seq(1, 2, 3, 4).Map(LoadTryAsync).SequenceParallel();
```
With the proper Traverse it would look more natural like using `Map`:
```C#
var products = Seq(1, 2, 3, 4).TraverseParallel(LoadTryAsync);
```

**Comment by louthy** [comment]
This is in the latest `beta` (which I consider to be stable now we have unit test coverage for all of the hand-written traverse functions).  The function isn't called `Traverse` for the behaviour you want, it's called `Sequence` and takes a bind delegate:
```c#
    M<T<B>> Sequence(T<A> ma, Func<A, M<B>> bind)
```
So, for a traversable `Seq` and monad of `Option`, we'd have:
```c#
    Option<Seq<B>> Sequence(Seq<A> ma, Func<A, Option<B>> bind);
```
Most of the monads can be considered traversables, because they can return zero or more values, so I've [created extensions for all](https://github.com/louthy/language-ext/tree/hand-written-traverse/LanguageExt.Core/Transformer/Sequence):

The old `Traverse` could be deprecated, but I'll keep it for backwards compatibility.  The main reason for it not matching what you'd see in Haskell (or other languages with the same function), is that I made a mistake when interpreting it years back!

**Comment by dgrozenok** [comment]
Perfect! Thank you very much!
