### ISSUE TITLE
Nullable Extensions `SelectMany` only returns `null`.

### ISSUE THREAD

**Issue by Enigmativity** [louthy/language-ext#776]
```[EditorBrowsable(EditorBrowsableState.Never)]
public static V? SelectMany<T, U, V>(this T? self, Func<T, U?> bind, Func<T, U, V> project) where T : struct where U : struct where V : struct
{
	if (!self.HasValue)
	{
		return null;
	}
	U? val = bind(self.Value);
	if (!val.HasValue)
	{
		return null;
	}
	Prelude.Optional(project(self.Value, val.Value));
	return null;
}```

**Comment by bender2k14** [comment]
Are you asking a question?

**Comment by Enigmativity** [comment]
No, I'm making a statement. The implementation is wrong. It only ever returns null.

**Comment by bender2k14** [comment]
Can you link to this implementation?

**Comment by louthy** [comment]
That certainly looks wrong!  I won't have time over the next few days to deal with it, so I'd encourage you to convert your nullables to options, using `value.ToOption()`.

Options are much more useful anyway, because you can only use value-types (structs) with Nullable, whereas `Option` doesn't have that limitation.
