### ISSUE TITLE
Strange lazyness evaluation behaviour of Bind and Map 

### ISSUE THREAD

**Issue by Profpatsch** [louthy/language-ext#78]
When interleaving side-effecting (aka `void` returning) code with `Map` and `Bind`, strange double-evaluation happens. For example:

```csharp
        static void Main(string[] args)
        {
            var l = new List<Either<Unit,string>>();
            var a = Prelude.Right<Unit,string>("foo");
            var b = Prelude.Left<Unit,string>(Prelude.unit);
            l.Add(a);
            l.Add(b);
            //a.Map<Unit, string, Unit>(s => { Console.WriteLine(s); return Prelude.unit; });
            var nl = l.Map(ei => ei.Bind(s => { Console.WriteLine(s); return Prelude.Right<Unit, string>(s); }));
            Console.WriteLine(nl);
            Console.WriteLine(nl.First());
            Console.WriteLine(nl.Tail().First());
            System.Console.ReadLine();
        }
    }
```

This will print
```
System.Linq.Enumerable+WhereSelectListIterator`2[LanguageExt.Either`2[LanguageEx
t.Unit,System.String],LanguageExt.Either`2[LanguageExt.Unit,System.String]]
foo
Right(foo)
foo
Left(())
```

I’m not sure how exacly sure how that happens, but I suspect thunks are evaluated twice.
Is there a way to circumvent that?

**Comment by louthy** [comment]
Both `Map` and `Bind` are lazy for lists, and will evaluate each time you use them.  You can bake the result in your case by adding `.ToList()` to the end of the expression that assigns to `nl`
```C#
    var nl = l.Map(ei => ei.Bind(s => { Console.WriteLine(s); return Prelude.Right<Unit, string>(s); })).ToList();
```

**Comment by Profpatsch** [comment]
> Map and Bind are lazy for lists

Normally I would expect “true“ laziness to evaluate each thunk only once and then use the cached result for each consecutive call; of course it shouldn’t matter when there is referential transparency, but side-effects kind of destroy that. hm.

So `.ToList()` forces the LINQ thunk to be evaluated?

**Comment by louthy** [comment]
> Normally I would expect “true“ laziness to evaluate each thunk only once and then use the cached result for each consecutive call;

Indeed.  Unfortunately that's not the behaviour of `IEnumerable` and `yield return` in C#.  I suspect because it *is* a side-effecting language, so assumptions can't be made about the referential transparency of a computation - which is not the case in Haskell for example.

**Comment by louthy** [comment]
> So .ToList() forces the LINQ thunk to be evaluated?

It forces an `IEnumerable<T>` to be evaluated and stored in a `List<T>`; you can also use `ToArray()` which will give you a `T[]`.  If you want to use the immutable list type `Lst<T>` in lang-ext instead of the mutable `System.Collections.Generic.List<T>` that you have been using, then `Freeze()` is the operation to bake-in the evaluated values of an `IEnumerable<T>`.

**Comment by Profpatsch** [comment]
Thanks!

**Comment by louthy** [comment]
Hi @Profpatsch - this got me thinking a bit more.  There is a general problem with the laziness and over-evaluation of `IEnumerable<T>`.  In the list matching functions I tried to minimise it as much as possible, but it would still evaluate the head item and then the head item again to skip to the tail (which is what you saw).  It was something that stuck in my mind at the time as something I wanted to fix...

I have added 'Enumerable memoization' to lang-ext.  So instead of using `.ToList()` to force evaluation of the whole enumerable, you can now use `seq.Memo()`  or `memo(seq)` where `seq` is the `IEnumerable`.

They both return an `IEnumerable<T>`, but they don't evaluate the items in the sequence until they're needed, and once evaluated, they're cached so that repeated attempts to use the `IEnumerable` don't re-evaluate.

They can't be used to evaluate infinite sequences, because you'll run out of memory.

Here's an example of a problematic evaluation (similar to your example).  The intent of the code is clear, to print the first and second items in the list (from a sequence that is `Int32.MaxValue` items in size - so doing `ToList` would fail).  

The `Items` function however has a side effect, which is to write the current value to the console:

```C#
        static void Test()
        {
            var list = Items();

            Console.WriteLine($" -> {list.Head()}");
            Console.WriteLine($" -> {list.Tail().Head()}");
        }

        static IEnumerable<int> Items() =>
            Range(0, Int32.MaxValue).Select(x =>
            {
                Console.WriteLine(x);
                return x;
            });
```
Then output is:
```
    0
     -> 0
    0
    1
     -> 1
```
Clearly the head item has been evaluated twice.  If I change the original to use `Memo`:
```C#
        static void Test()
        {
            var list = Items().Memo();

            Console.WriteLine($" -> {list.Head()}");
            Console.WriteLine($" -> {list.Tail().Head()}");
        }
```
Then output is:
```
    0
     -> 0
    1
     -> 1
```
As expected, but also it didn't need to evaluate the whole sequence to do this.  Perhaps this will be more useful to you than using `ToList`?  

Either way, it's useful for language-ext because it improves the `IEnumerable` match functions.  

It's all rolled out to nu-get, version 1.7.24.  I'm re-opening this temporarily to give yourself and anybody else a chance to comment.

**Comment by Profpatsch** [comment]
This seems like a sensible addition, however:
The default behavior is still pretty unintuitive, in that it introduces bugs that are *very* hard to hunt down when one doesn’t know about this pitfall.

I wonder if it would be possible to enable this memoization by default?
If it is not, I’m at a loss. It should be very well documented at least, but since this concerns pretty much every function in this library, it would fit into an FAQ best probably.

**Comment by louthy** [comment]
> I wonder if it would be possible to enable this memoization by default?

It would have to be provided by the underlying sequence implementation.  For example I could probably find a way of making it work for lang-ext's `Lst<T>` (and the other collections in the library), but as far as I am aware there's no way of overriding the default `yield return` behaviour of C#.  It's debatable how 'correct' that would be even if you could.  I agree with you that memo-by-default with opt-out (if required) would be better than having to opt-in to memoization. 

> If it is not, I’m at a loss. It should be very well documented at least, but since this concerns pretty much every function in this library, it would fit into an FAQ best probably.

I'm not sure that's appropriate.  This library isn't here to make excuses for C# and its `IEnumerable` and `yield` behaviour.  I think it's quite widely understood (because LINQ is used for SQL query providers mostly) that calling `.ToList()` or `.ToArray()` causes evaluation; and repeated evaluation is a desired feature when the underlying sequence (which is often coming from a DB) could have changed.

There's no quick fix I'm afraid.  It's just a language quirk.  I will consider the implications of making it the default behaviour for lang-ext.  My concern would be that it could break existing code and it goes against what most people understand re: `IEnumerable`

**Comment by Profpatsch** [comment]
> My concern would be that it could break existing code and it goes against what most people understand re: IEnumerable

In that case always go with the Principle of Least Surprise

> I think it's quite widely understood (because LINQ is used for SQL query providers mostly) that calling .ToList() or .ToArray() causes evaluation;

Then it’s probably that I’m not well-versed enough in C# (I mostly do Haskell and C# only for a client project).
