### ISSUE TITLE
Error type (first class citizen?)

### ISSUE THREAD

**Issue by StefanBertels** [louthy/language-ext#828]
There is a type LanguageExt.Common.Error that is used by LanguageExt by e.g. RWSGenerator.
The type (already) is public and might be used by user code.

Question: Is it a good idea (or not) to make use of this type in user code furthermore?

I'm often in need of a similar type (container for some message and/or some exception) and it's a mess for interoperability.
a) Either I define a type locally (my library only) and have to convert it when it enters/leaves my code or
b) I have to create an own library with just such a type (for all my projects) which feels even more like re-inventing the wheel (see the discussion about `Unit` types that have emerged in Rx, LanguageExt etc.) or
c) I use an existing type (string, Exception) with drawbacks like `string` being totally non-specific (and nullable) and `Exception` containing some extra freight (InnerException, Data dictionary, Helplink ...) and null-ability.

Therefore I would like to make use of `Error` in my code (meaning creating it, passing it around, use it in interfaces / Api calls, serializing). Which means: I would like `Error` to be a "first class" citizen in LanguageExt which should be as stable as other things (maybe moving it to main namespace `LanguageExt`) .

Could be especially useful as left value for `Either` (and fail value for `Validation`).

It might be useful to add some helper functions to get this `Error` type for `parse` errors (which are currently `string`) more directly (but it's already acceptable: `.ToEither().MapLeft(Error.New)`)

My general extension helper for the latter (includes making sure input is consumed): 
```
internal static Either<Error, T> ParseEither<T>(this string input, Parser<T> parser) =>
            parse(from _ in parser from end in eof select _, input).ToEither().MapLeft(Error.New);
```

**Comment by louthy** [comment]
Short answer: yes.

Longer answer, I will be using Error everywhere where there are Exceptions today.  It’s already heavily built in to the new mondaic types: Fin (which is isomorphic to Either<Error, A>), and the new IO monads: Eff and Aff.

I’m building up to a version 4 release (which is why I’ve been in beta for a long time), where I’ll document all this more.

The reason Error is in its own namespace is because it has a common name, so I’ve moved it out of the main namespace to avoid conflicts.
