### ISSUE TITLE
Add QueryExtensions to Namespace

### ISSUE THREAD

**Issue by ClemensSchoppe** [louthy/language-ext#836]
I consider using language-ext at work and loved it so far. Unfortunately adding language-ext to a big project made other unrelated code fail due to QueryExtensions not beeing in the Namespace LanguageExt. Thus adding the nuget package interfered with some code havily relying on expressions and entity framework.

If this is on purpose I would love to understand why. Otherwise I can happily provide a PR.

Best regards
Clemens

**Comment by TysonMN** [comment]
You mean this code, right?
https://github.com/louthy/language-ext/blob/dad2b451211031b8ecc4746a714b30d1f6d856cc/LanguageExt.Core/Extensions/Query.cs#L138

@louthy, can that code be moved to the `Prelude` namespace?

**Comment by ClemensSchoppe** [comment]
Yes, exactly. Thanks!

**Comment by louthy** [comment]
Can you be more specific on the conflicts/errors caused?

**Comment by ClemensSchoppe** [comment]
We have some code like 

 private static Expression<Func<SomeDto, string>> DoSometing(Expression<Func<Somedata, string>> someFunc) =>
            dto => dto.SomeTable.AsQueryable().Select(someFunc).Distinct().Count() 

Some analysis shows, that this becomes something like 
... .If (.Call System.Linq.Queryable.Count(.Call **QueryExtensions.Distinct**(.Call System.Linq.Queryable.Selec ...

This leads to the following exception:
Expression of type 'System.Collections.Generic.List`1[System.String]' cannot be used for parameter of type System.Linq.IQueryable`1[System.String]' of method 'System.Linq.IQueryable`1[System.String] Distinct[String](System.Linq.IQueryable`1[System.String])' (Parameter 'arg0')

I assume that before I added language-ext, Distinct came from System.Linq.Queryable.

PS: This is my first attemt on GitHub so please mind my poor editing

**Comment by louthy** [comment]
Hmm, I'm now wondering why I even put `Distinct` in there at all, that could probably be removed and it would solve the problem.

I'm away this week, I'll follow up early next week.

**Comment by ClemensSchoppe** [comment]
I just double checked, it is indeed:
... .If (.Call System.Linq.Queryable.Count(.Call **System.Linq.Queryable.Distinct**(.Call System.Linq.Queryable.Select( 

Thanks a lot for you direct response. This is crucial for my attempt to productively use this library.

**Comment by StanJav** [comment]
It wasn't you @louthy , I added it: https://github.com/louthy/language-ext/commit/1a07e60c828f3418960f6878bfc26b6d3de1a29a 

@ClemensSchoppe  do you have any problem with the others e.g. `Count/Skip/Take` if there is none `Distinct` in the chain? I checked our code and we do not have any problem with them. Apparently I cannot find an example where `Distinct` would not be the last function so I guess we would not spot it if this is done in memory rather than translated into SQL. I can do some testing to see if this is broken in our code.

**Comment by StanJav** [comment]
I was wrong, the problem is something else.

I just quickly tested this query: 

```
// there is none Lang-ext using 

(from a in db.MyTable
 select a.SomeColumn)   // result is IQueryable<int> here
    .Distinct()         // result is IQueryable<int> here
    .Count()
```

I confirmed `Distinct()` comes from [`QueryExtennsions`](https://github.com/louthy/language-ext/blob/dad2b451211031b8ecc4746a714b30d1f6d856cc/LanguageExt.Core/Extensions/Query.cs#L203)  and I checked the query in the SQL profiler: 

```
SELECT 
   TOP(@top0) COUNT(*) AS [LPAV_] 
   FROM (
       SELECT DISTINCT [LPLA_1].[SomeColumn] AS [SomeColumn] 
       FROM [dbo].[MyTable] [LPLA_1]) [LPA_L1]
```

It looks like your `Distinct` is doing something else. I cannot see where `'System.Collections.Generic.List1[System.String]'` comes from.

Is `Distinct` is the only one which is causing a problem?

**Comment by ClemensSchoppe** [comment]
I must admit, that the broken code is somewhat awkward. 

We do not have a table but some Dto that has a member (I called it someTable above) beeing a ICollection. In the constructor a Hashset is assigned but as it has public getter and setter you never know the underlying type. The resulting expression is horribly long and hard to understand.

The issue was not easy to find in the first place and looking at the code I still do not completely understand why/how it occours (it seems to me, that this distinct call is a somehow itself related to System.Linq.Queryable.Distinct?). I will try to find some time soon to get a clearer understanding of the exact details.

Luckily, the issue came up in tests working with an inmemory database. (Otherwise my colleagues would probably be seriously angry with me now :-)) 

This is a very serious category of issue, as it appears to be very magic. In the first place I did not believe the error was introduced by me as I did not even touch the solution (unfortunately our nugets are not separated). I think for a library it might be a good idea to have some namespace for any code in it. This way users are able to keep track and have control of where it is used.

**Comment by TysonMN** [comment]
It used to be that the class `TaskExtentions` intentionally lacked a namespace.  Then it was pointed out in issue #445 that this caused problems, and the `LanguageExt` namespace was added in PR #446.

Now @ClemensSchoppe is pointing out some issue they have with `QueryExtensions` lacking a namespace.

**Comment by ClemensSchoppe** [comment]
Looking at LanguageExt.Core.dll there are several classes not contained in a namespace. Most of these seem to contain extension methods for IEnumerable. IL DASM shows following classes:
![image](https://user-images.githubusercontent.com/75070160/100584697-baa55480-32ec-11eb-8e31-e50e25f7336d.png)

I know putting these into a Namespace is a breaking change. Nevertheless I would propose to consider putting these into the LanguageExt Namespace. If you consider this a good idea I would happily do it.

Thanks a lot for your competent and fast responses. Best,
Clemens

**Comment by StanJav** [comment]
If you could find any repro example that would be great.  Could you probably try `Take(5).Count()` without `Distinct`? 
Also could you please post a stack trace? I had a similar problem here https://github.com/louthy/language-ext/pull/613  and I am wondering whether the problem is in `ExpressionUtils.ValidateOneArgument` again.

**Comment by ClemensSchoppe** [comment]
I will try to find some time to investigate this. It will probably take some days.

**Comment by ClemensSchoppe** [comment]
The issue https://github.com/dotnet/efcore/issues/18275 seems promising in understanding what exactly fails. Why this happens with the extension method in language-ext and not in Linq is a mystery to me. Also what automapper or the InMemory QueryProvider adds; with plain queryables this seems not reproducable.

**Comment by ClemensSchoppe** [comment]
@louthy: Shall I provide a PR to bring QueryExtensions to the namespace LanguageExt? And if so: shall I also put the other classes not contained in a namespace to this Namespace? 
Best regards,
Clemens

**Comment by louthy** [comment]
> shall I also put the other classes not contained in a namespace to this Namespace?

No, they're mostly extensions to lang-ext types, and therefore won't ever clash with anything else.  That would be a big breaking change for many.

It is still unclear why this is happening, and changing code when the cause isn't clear isn't good practice.  Answers to the questions @StanJav (who's one of my Principal engineers) has raised are still necessary.  We need to reproduce the issue before fixing anything.  

This is the error in your trace that seems most relevant:
```
   'System.Collections.Generic.List1[System.String]' cannot be used for parameter of type
        'System.Linq.IQueryable1[System.String]
```
It seems from the traces you've posted so far that you have a mix of `IEnumerable` and `IQueryable` in the same LINQ expression.  So even if we moved `Distinct` you'll probably find you have another bug which is that your entire table is being brought into memory, but I also suspect it's the source of your error, somehow you've got multiple query providers in the same expression (perhaps).

We use `Distinct` in our LINQ providers and haven't seen any issues.  It must be understood what happens when a LINQ expression runs.  In the case of an `IQueryable` expression the functions are called (`Distinct`, `Select`, etc.) and the result of those functions is an `Expression<A>`, that result is an Abstract Syntax Tree that represents the operation to perform.  The query provider will translate that `Expression` into `SQL`, or whatever it needs to do to process the data.

And so, calling `QueryExtensions.Distinct()`:
```c#
    public static IQueryable<T> Distinct<T>(this IQueryable<T> list) =>
        LanguageExt.Query.distinct(list);
```
Returns the result of `LanguageExt.Query.distinct(list)` which is:
```c#
        public static IQueryable<T> distinct<T>(IQueryable<T> list) =>
            Queryable.Distinct(list);
```
And that results in a call into the BCL:
```c#
        public static IQueryable<TSource> Distinct<TSource>(this IQueryable<TSource> source)
        {
            if (source == null)
                throw Error.ArgumentNull(nameof(source));
            return source.Provider.CreateQuery<TSource>(
                Expression.Call(
                    null,
                    CachedReflectionInfo.Distinct_TSource_1(typeof(TSource)), source.Expression));
        }
```
The cached-reflection is:
```c#
        public static MethodInfo Distinct_TSource_1(Type TSource) =>
             (s_Distinct_TSource_1 ??
             (s_Distinct_TSource_1 = new Func<IQueryable<object>, IQueryable<object>>(Queryable.Distinct).GetMethodInfo().GetGenericMethodDefinition()))
              .MakeGenericMethod(TSource);

```
As you can see the result is simply a `CallExpression` that invokes `Queryable.Distinct` (from the BCL) and it does so on the `source.Provider`.  

This doesn't embed anything Language-Ext specific into the query, which is why this issue is unlikely to be anything to do with namespaces and is much more likely a bug in your code.  So we really need a repro before continuing to expend more effort.

**Comment by StanJav** [comment]
The main thing I still do not understand is *Where the generic List is coming from?*.

The `Queryable.Distinct(myList);` accepts `IQueryable<T>` and cannot accept generic `List<T>`. If `myList` is `IQueryable<T>` then why does it complain about it not beeing it? 

I tested this:

```
public class Somedata
{
    public string X;
}

public class SomeDto
{
    public List<Somedata> SomeTable = new System.Collections.Generic.List<Somedata>();
}

private static Expression<Func<SomeDto, int>> DoSometing(Expression<Func<Somedata, string>> someFunc) =>
    dto => dto
            .SomeTable
            .AsQueryable() // here we jump into IQueryable<T> so List<T> is gone
            .Select(someFunc)
            .Distinct()
            .Count();

static void Main(string[] args)
{
    var myObj = new SomeDto();
    var exp = DoSometing(d => d.X);
    var res = exp.Compile()(myObj);
    Console.WriteLine(res);
    Console.ReadKey();
}
```

Obviously this code works. Could you probably tell me what type is `SomeTable`? And what framework version do you use? 

> One difference between Distinct from Language-Ext and the Distinct call as it was before is, that it seems to come from a different Microsoft library.

What library? If you remove lang-ext and you `Go to definition` on `Distinct()` where does it go? 

Could you probably rewrite the code and instead of writing `myExpression.Distinct()` you would call `Queryable.Distinct(myExpression);`. I am expecting it to fail.

**Comment by ClemensSchoppe** [comment]
Thank you very much for your answers. I do totally agree that the issue must be understood. I will need some time to digest your answers and to hopefully provide a repo.

**Comment by TysonMN** [comment]
To create a minimal reproduction, I recommend starting with your very non-minimal and proprietary reproduction.  Create a branch.  Delete some code. Test.  If the issue remains, then commit and repeat.  If not, then discard and repeat by deleting different or less code.
