### ISSUE TITLE
Do any of the immutable collections share allocated memory for previously added items?

### ISSUE THREAD

**Issue by Davidsv** [louthy/language-ext#839]
Let me put it another way:

```
var c1 = new TheCollection<Decimal>();
var c2 = c1.Add(123m);
var c3 = c2.Add(456m);
```

Is there any collection type in language-ext where `c2` and `c3` refer to the same memory location for `123m`? Or do all of them make copies of their internal collection (array, or whatever) whenever something is added?

**Comment by louthy** [comment]
They all share previous state.  The only exception is with `Seq` which will do array copying when the references are _branched_.  Branching happens less frequently, and so the cost is relatively low.

i.e. this shares:

```c#
    var xs = Seq(1, 2, 3);
    var ys = xs.Add(4);
    var zs = ys.Add(5);
```
`Seq` internally uses an array as its backing store, it doubles in size whenever space in the backing array runs out (this is how `List<T>` works in `System.Collections.Generic`).  It starts off with a minimum array size of 8 (with a `start` and `end` index, so lengths less than 8 can be represented); so once 8 items are in the array, if you add one more, the size doubles to 16 and the whole previous array is copied over.  The items are positioned in the middle of the range so that `Cons` and `Add` have space to grow into.

> This is super fast and allows for very, very fast lookup and sequential processing, because data locality (stops cache misses). 

Now obviously if the data-structure is growing into a pre-allocated array, it's problematic when two branches occur:
```c#
    var xs = Seq(1, 2, 3);
    var branch1 = xs;
    var branch2 = xs;
    var branch1 = branch1.Add(4);
    var branch2 = branch2.Add(5);    
```
The two `Add` operations want to store different values in the same array location.  Obviously this isn't allowed, because it's an immutable structure.  And so what happens is the second `Add` operation will cause the array to be cloned and then it can continue to grow as a newly branched immutable structure.  This is all lock-free.

Everything else uses either [AVL binary-trees](https://en.wikipedia.org/wiki/AVL_tree) (`Map`, `Lst`, `Set`) or [Compressed Hash-Array Mapped Prefix-trees](https://michael.steindorfer.name/publications/oopsla15.pdf) (`HashSet` and `HashMap`) which is the current state-of-the-art hash-map data-structure.

I believe `Seq` is the fastest immutable list in the .NET world (and I believe all of the immutable data-types are faster than any in the .NET world); here's some [benchmarks](https://github.com/louthy/language-ext/blob/master/Performance.md)

**Comment by Davidsv** [comment]
What a great answer! Thanks.
