### ISSUE TITLE
Data Generic Currying?

### ISSUE THREAD

**Issue by dhalsim** [louthy/language-ext#84]
Hello,

Nice library and set of tools there! But one thing I didn't get is how currying here works. I would expect functions like `map` have signature like this:

```
var x = map(v => v * 2, opt);
```

instead of 

```
var x = map(opt, v => v * 2);
```

So I can define a method `double` from `map` by currying (that would be great if it is auto curried) or partially applying, and use it wherever I want. That's the way I want to compose my functions rather than using the chain syntax.

Here is a better demonstration what I wanted to say:
[Hey Underscore, You're Doing It Wrong!](http://functionaltalks.org/2013/05/27/brian-lonsdorf-hey-underscore-youre-doing-it-wrong/)

Also Ramda.js is a great example: [Ramda.js](http://ramdajs.com/)

Thanks

**Comment by louthy** [comment]
@dhalsim 

> Nice library and set of tools there! 

Thanks :)

> But one thing I didn't get is how currying here works. I would expect functions like map have signature like this:

Yeah it was a bit of an oversight when I first wrote the library.  The currying and partial-application functions came later.  To be honest I wasn't sure whether I was going to put currying or partial-application in, because C#'s type inference just causes headaches.  

So using the `par` function to partially apply on the `map` function won't compile (if we assume that the parameters are the right way around):
```C#
    var dbl = par(map, x => x * 2);
```
C#'s type inference is basically terrible, so it can't work this out.  You'd need:
```C#
    var dbl = par<Option<float>, Func<Option<float>, Option<float>>, Option<float>>(map, x => x * 2);
```
Not pretty.  

But back to the original point: I'd love to change the parameter ordering, unfortunately I now have to be concerned about being backwards compatible.  Enough people use the library that I try to keep breaking changes to a minimum.  I suspect this might be a step too far to fix it.  I'm interested in hearing others' opinions though.  I suspect not enough people use currying or partial application to desire a change.

To try and make the curry situation less onerous there is actually a function called `lpar` that partially applies a single parameter to the left.
```C#
    var dbl = lpar(map, x => x * 2);
```
_(Without the generic types for clarity there)_

**Comment by dhalsim** [comment]
Hi @louthy,

Thanks for the response. Sorry for the delay :)

AFAI understand there is no way to dynamically create a partial function because of .NET's type system. So I think there is no point to reverse map's signature because I have to apply partial by myself so I can use `lpar` as you said.

So I'm closing the issue.

Cheers,

**Comment by dhalsim** [comment]
Hi @louthy,

Thanks for the response. Sorry for the delay :)

AFAI understand there is no way to dynamically create a partial function because of .NET's type system. So I think there is no point to reverse map's signature because I have to apply partial by myself so I can use lpar as you said.

So I'm closing the issue.

Cheers,
