### ISSUE TITLE
Feature Request: IfSuccAsync() for Result<T>

### ISSUE THREAD

**Issue by FaFre** [louthy/language-ext#843]
I use `Result<A>` quite frequently as a return-type. 
Unlike for `Option<A>` (where we have e.g. `IsSomeAsync()`) there is no async version of `IfSucc()`. 

I found a implementation of `IfSuccAsyc()` but its dedicated to work with `Try`: `Task<Unit> IfSuccAsync<A>(this Try<A> self, Action<A> Succ)`. There is no way to use it with a plain `Result<A>`.

I would be happy to contribute the necessary code for it.

What do you think about this?

**Comment by louthy** [comment]
It's not advised to use `Result<A>` directly, it's an 'intermediate value type', i.e. used temporarily by the `Try` types for the internal matching.  I kind of regret making it public tbh, and will probably deprecate it eventually, because it's continual source of confusion; especially now that the delegate types memoise results.  If you're getting the `Result<A>` from `Try<A>` or `TryAsync<A>` or similar then directly use the matching extensions rather than calling `ma.Try()` to get a result.  

```c#
    var ma = TryAsync(123);
    await ma.IfSucc(Console.WriteLine);
```

If you're looking for a type with the behaviour of `Result<A>`, then the newly _sanctioned_ type that does what `Result<A>` does (and more) is `Fin<A>`, which is isomorphic to `Either<Error, A>`  (`FinAsync<A>` will come later).

**Comment by FaFre** [comment]
Okay, now everything makes sense :+1: 
Yes, `Fin<A>` fits exactly my usage. I saw it's already included in the beta packages, great! I'll upgrade and refactor my code.
