### ISSUE TITLE
Dangerous behavior of Option.Match

### ISSUE THREAD

**Issue by Bernhard-Hiller** [louthy/language-ext#857]
It was a glitch when writing code:

    Option<IOrchestra> Orchestra;
    ...
    IOrchestra result = Orchestra.Match(
        Some: o => _Repository.UpdateOrchestra(o, Name, _Homepage, _Info),
        None:  _Repository.AddOrchestra(Name, _Homepage, _Info));

Perhaps you see it already: I forgot a `() => ` for the `None` parameter. It compiles, without any warnings. It is executed, without any exceptions. But with "weird" behavior: though the `Option` was in the `Some` state, the `None` function was executed. As you might guess from the name `_Repository.Add`, that's not a pure function.

`_Repository.AddOrchestra` returns an `IOrchestra`. It is provided as a parameter to `Option.Match`, it gets executed to retrieve the object it returns, and then the result gets converted into a function returning that object. It is not "directly" converted to function (that's my guess - might be wrong).

What can be done to prevent such glitches? Are some compiler warnings possible?

**Comment by StanJav** [comment]
It is because for `Match` there are more overloads. The one you accidentally used is 
- [`public B Match<B>(Option<A> opt, Func<A, B> Some, B None)`](https://github.com/louthy/language-ext/blob/3df8c837961a502d7a03268b6cac636a57c49056/LanguageExt.Core/ClassInstances/Monad/MOption.cs#L68) 

instead of 
- [`B Match<B>(Option<A> opt, Func<A, B> Some, Func<B> None)`](https://github.com/louthy/language-ext/blob/3df8c837961a502d7a03268b6cac636a57c49056/LanguageExt.Core/ClassInstances/Monad/MOption.cs#L64)

With the first one the `None` branch runs immeditately before you jump into `Match`. For example `IfNone` has the same combination of options - you pass value directly or via `Func`. I guess one interesting reasons would be performance so we avoid the delegate.

**Comment by louthy** [comment]
@StanJav ‘s comment is accurate, it’s to allow a none-value rather than a none-function, which saves an allocation.  It’s a fairly common use-case, so I think it’s reasonable.

**Comment by Bernhard-Hiller** [comment]
Thanks for your explanations.
When it comes to decide between performance and safety, I usually prefer safety.
Also, in the concrete place I stumbled upon it, that would be a single performance hit of surely less than 1 millisecond - in the context of some data entered by a user to be saved to the database, i.e. irrelevant.
But of course, there may be different situation where such a performance hit could come at perceptible costs. Hence I understand that you will keep this overload available.
Could there be some way of warning users like me who prefer safety over performance? E.g. some compiler directives I could turn on and get a hint if I really wanted to chose that overload, or code analysis tools?

**Comment by Bernhard-Hiller** [comment]
You caught me red-handed and I have to confess. Confiteor, peccatus sum.
That mistake can easily be detected by a simple unit test: just `assert` that in the `Some`case, only the `Some` function gets executed, and the `None` function / parameter does not.
Since it is a simple project (which took much more time than expected, surprise..) for my private use, there are no other people writing code for this project, and it is completely upto me to follow good standards.
In the end, I'll have to do the needful.
