### ISSUE TITLE
[Discussion] System.Collections.Immutable support

### ISSUE THREAD

**Issue by tvsonar** [louthy/language-ext#86]
What would it take to remove all immutable `LanguageExt` enumeration types and use `System.Collections.Immutable` NuGet package provided types instead? 

I briefly ran through the code, and saw that there are operator overloads in `LanguageExt`, which are not there in `System.Collections.Immutable`, but those can be considered syntactic sugar and could be replaced by method calls.

Alternatively, what would it take to `System.Collections.Immutable` interfaces such as `IImmutableList<T>`.

**Comment by tvsonar** [comment]
This question is unrelated to SonarLint rules. I'm not sure about the adoption of this package, but I think it would be increased if it built on top of already existing immutable enumerations, and added missing functionality through extension methods.

**Comment by louthy** [comment]
Adoption of this package seems fine to me.  The library originally used the ImmutableCollections but I removed the dependency because of the cognitive overhead of the naming.  This library is here to make functional first easier than the BCL.  For example:
```c#
    Map<string,int>
```
is significantly less eye and finger pain compared to 
```c#
    IImmutableDictionary<string, int>
```
A map of maps even more so:
```c#
    Map<string, Map<string,int>>
```
Compared to...
```c#
    IImmutableDictionary<string, IImmutableDictionary<string, int>>
```
The lang-ext libraries has functionality not available in ImmutableCollections and that can't be retro-fitted through extension methods (like range finding).

If you need to use ImmutableCollections, use them.  They're just an additional dependency.  You still get the benefit of the lang-ext extension methods (`Map`, `Fold`, etc.) because of the extension methods for `IEnumerable<T>`.  If you need interop, write some extension methods.
