### ISSUE TITLE
Q: why is Option not a readonly struct?

### ISSUE THREAD

**Issue by bert2** [louthy/language-ext#860]
I noticed that [`Option`](https://github.com/louthy/language-ext/blob/c24eb0a46738e48862fd1da1842b26806efcfc3c/LanguageExt.Core/DataTypes/Option/Option.cs#L37) (like other  language-ext types) is not a `readonly struct` and I'm wondering what the reasoning for this decision is.

As far as I can tell a `readonly` `Option` (together with the `in` modifier) might offer performance benefits in some scenarios. On the other hand `readonly` is probably not compatible with older .net frameworks.

So my guess is that the performance benefits don't outweigh the loss of backwards compatibility?

**Comment by louthy** [comment]
It was written before readonly structs existed is the main reason.  There’s not likely to be any performance improvements from making the struct readonly.  That’s because Option is 9 bytes, so any copy semantics are going to be pretty much the same as any readonly optimisation which uses ‘by ref’ behaviour (like ‘in’ parameters), which are copying 8 bytes.  Finally, I use readonly fields and not properties, which allows the compiler to avoid copying the struct before use.

That doesn’t mean there’s no value to adding readonly.  It has declarative value and for the other struct types in this lib it may well have some performance benefits; so when I’m not so hyper busy I’ll make the change and do some benchmarking.

**Comment by bert2** [comment]
So the only real performance trap is to pass an `Option<MyHugeStruct>` as a parameter into a function which will cause a copy. But in order to avoid that one would use `ref Option<MyHugeStruct>` anyway. If `Option` was `readonly` one would use `in` instead of `ref`, but the performance would still be the same.

Thanks for the explanation!

**Comment by louthy** [comment]
That’s a fair point about using Option with a struct bound type.

**Comment by louthy** [comment]
@bert2 All the major `struct` types are now `readonly` (released in `v3.5.27-beta`).

**Comment by bert2** [comment]
😯 Wow, that was fast!
