### ISSUE TITLE
Blazor RenderFragment not rendering when used with CodeGen type

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#881]
Following an excellent suggestion by @orthoxerox in [a previous issue](https://github.com/louthy/language-ext/issues/840), I was able to produce a Blazor component that renders an `Option<T>` .

My last post there included some extra code to account for the point when the data hadn't been loaded yet. This was a bit of a hack, and following a different excellent [suggestion by @louthy](https://github.com/louthy/language-ext/issues/865#issuecomment-818334519)  to use a generated type to represent the three possible states (not loaded yet, some and none), I came up with the code shown below...

I first created a `Loading<T>` union type as follows...

```c#
  [Union]
  public interface LoadingOption<T> {
    LoadingOption<T> Loading();
    LoadingOption<T> Loaded(T value);
    LoadingOption<T> NotLoaded();
  }
```

I created a Blazor component (imaginatively named `Loader`) to use this as follows...

```c#
@typeparam T

@(Data switch {
  Loading<T> => Loading,
  Loaded<T> t => Loaded(t),
  NotLoaded<T> => NotLoaded,
  _ => ""
  })

@code {

  [Parameter]
  public LoadingOption<T> Data { get; set; }

  [Parameter]
  public RenderFragment<Loading<T>> Loading { get; set; }

  [Parameter]
  public RenderFragment<Loaded<T>> Loaded { get; set; }

  [Parameter]
  public RenderFragment<NotLoaded<T>> NotLoaded { get; set; }

}
```

I then tried it out in a sample Blazor page as follows...

```c#
@page "/LoadingOptionSample"

<p><button class="btn btn-primary" @onclick="LoadCustomerFound">Existing customer</button>
       <button class="btn btn-secondary" @onclick="LoadCustomerNotFound">No such customer</button></p>

<Loader Data="_customer" Context="customer">
  <Loading>
    <p>Please wait while we look for the customer...</p>
  </Loading>
  <Loaded>
    <p>Found @customer.Value.Name (id: @customer.Value.Id), who is @customer.Value.Age years old</p>
  </Loaded>
  <NotLoaded>
    <p>Big flop, we can't find him</p>
  </NotLoaded>
</Loader>

@code {

  private LoadingOption<Customer> _customer;

  private async Task LoadCustomerFound() {
    _customer = new Loading<Customer>();
    await Task.Delay(2000);
    _customer = new Loaded<Customer>(new Customer(1, "Jim Spriggs", 42));
  }

  private async Task LoadCustomerNotFound() {
    _customer = new Loading<Customer>();
    await Task.Delay(2000);
    _customer = new NotLoaded<Customer>();
  }

}
```

When I click one of the buttons, instead of rendering the HTML, it just shows `Microsoft.AspNetCore.Components.RenderFragment`

If I do a non-generic version of the same idea (based on [the `Shape` example in the docs](https://github.com/louthy/language-ext/wiki/Code-generation#discriminated-union--sum-types)), it works fine, so it seems to be the fact that my union is generic that's the problem.

Anyone any idea what I've done wrong here? The previous component worked fine, and I seem to be doing a similar thing here.

Thanks for any help you can give.

**Comment by louthy** [comment]
I'm no Blazor expert, so if anyone else can help here that'd be appreciated? 👍

**Comment by MrYossu** [comment]
@louthy Hee hee, I know you're not a Blazor man, but maybe you can explain something. A very similar component works fine with `Option<T>`, but not when I create my own generic union. What is the difference between a built-in union like `Option<T>` and one generated by the `[Union]` attribute? I know the generated ones don't get things like `Match()`, which is a shame, but would there be any other difference that might affect this?

Thanks

**Comment by erwinkn** [comment]
[`RenderFragment<T>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.renderfragment-1?view=aspnetcore-5.0) is a delegate, which needs to be invoked with an argument of type `T`. It then returns a non-generic [`RenderFragment`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.renderfragment?view=aspnetcore-5.0), which can be rendered by Blazor.

In your example above, I would suspect that the `Loaded` case works fine, but the `Loading` and `NotLoaded` cases do not, because you are trying to render a delegate. If you replace them with a regular `RenderFragment` object, it should work fine.

Otherwise, the idea is really nice, I admit I will likely incorporate something similar in my own Blazor app!

**Comment by MrYossu** [comment]
@erwinkn Thanks for the reply. However, I don't think that even the `Loaded` case works, as if I click the button to load a customer, I still get the `RenderFragment` type, not the rendered contents.

As for the generic types, I got a bit stuck here. I need the generic parameter on all three cases in the `[Union]`, otherwise I get a compiler error "_Methods in union types must return the same type as the interface/abstract class they're defined in. (LoadingOption != LoadingOption<A>)._" However, having the generic parameter there means I can't drop it in the Blazor component. If I do, I get a complier error "_Using the generic type 'Loading<A>' requires 1 type arguments	BlazorCodeGen_" for both the `Loading` and `NotLoaded` `RenderFragment`s.

Any ideas? Thanks again.

**Comment by erwinkn** [comment]
I finally managed to setup code generation and was able to reproduce your example. (Btw, I can confirm CodeGen works with .NET 6 Preview 5. The Roslyn server on VS Code doesn't seem super fond of it though.)

@MrYossu: the core problem you have is that your `switch` pattern matching is not returning a `RenderFragment` (non-generic). There are two reasons for this:
- As mentioned, you should define `Loading` and `NotLoaded` as `RenderFragment`, not `RenderFragment<T>`, since you are not providing them with arguments.
- The catch-all case also needs to return a `RenderFragment`. Currently, it is returning a `string`, which converts all the other return values to strings - that is why you are seeing the class name of `RenderFragment` displayed.

One good way to notice those problems is to refactor the code so that you have a `Content` property explicitly returning a `RenderFragment`. In that case, the compiler would inform you that you are not returning the correct types from the `switch` statement.

With this in mind, the following code works for your `Loader`:
```razor
@typeparam T

@Content

@code {
    RenderFragment Content => Data switch {
        Loading<T> => Loading,
        Loaded<T> t => Loaded(t),
        NotLoaded<T> => NotLoaded,
        _ => NotLoaded
    };

    [Parameter]
    public LoadingOption<T> Data { get; set; }

    [Parameter]
    public RenderFragment Loading { get; set; }
    
    [Parameter]
    public RenderFragment<Loaded<T>> Loaded { get; set; }

    [Parameter]
    public RenderFragment NotLoaded { get; set; }
}
```

**Comment by louthy** [comment]
Thanks @erwinkn for helping out 👍

**Comment by MrYossu** [comment]
@erwinkn Thanks for that, works perfectly!

What I don't understand is why it works, as I'm sure I tried this along the way. The only difference I can see between your component and mine is that you removed the generic type parameters form the two `RenderFragment` parameters that don't take data. As I mentioned in my previous comment, I tried this, but got a compiler error.

Thanks again.
