### ISSUE TITLE
GenTokenParser.NaturalOrFloat returns unexpected result

### ISSUE THREAD

**Issue by erwinkn** [louthy/language-ext#889]
# Summary
Creating a `GenTokenParser` from a `GenLanguageDef` object and using its `NaturalOrFloat` parser to process an input like "3.14159" returns `Success` and "1418.9" as an output.

# Expected behavior
`GenTokenParser.NaturalOrFloat` should behave the same way as `GenTokenParser.Float` on simple decimal numbers. "3.14159" should be parsed as "3.14159".

# Actual behavior
It seems like `GenTokenParser.NaturalOrFloat` goes wrong as soon as there are more than 2 digits after the decimal point. From my tests, if it is given a number in the format `NNN.XXXY`, it will first parse `NNN`, then `XXX`, add the two together into `ZZZ = XXX + NNN` and return `ZZZ.Y`

This problem happens on the latest stable version `3.4.15`, as well as on the most recent version `3.5.35-beta`.

# Sample code
```cs
// Code adapted from the AccountingDSL example, keeping only the basic arithmetic operators
var opChars = "+-*/";

var definition = GenLanguageDef.Empty.With(
    CommentStart: "/*",
    CommentEnd: "*/",
    CommentLine: "//",
    NestedComments: true,
    OpStart: oneOf(opChars),
    OpLetter: oneOf(opChars),
    IdentStart: letter,
    IdentLetter: either(alphaNum, ch('_')),
    ReservedNames: Empty,
    ReservedOpNames: List("+", "-", "*", "/")
);

var lexer = makeTokenParser(definition);

var input = "3.14159";

Console.WriteLine(lexer.NaturalOrFloat.Parse(input));
// > Success(Right(1418.9))

Console.WriteLine(lexer.Float.Parse(input));
// > Success(3.14159)

Console.WriteLine(lexer.Natural.Parse(input));
// > Success(3)
```

**Comment by louthy** [comment]
Great report, thanks!

It seems the `NaturalOrFloat` parser was using the old float parser internally, which I had problems with before and was going to go back to and look at at some point.  I wrote another `Float` parser a while back to fix the same issue (which is why it parses successfully), but I clearly forgot to update `NaturalOrFloat` to use it; that'll teach me for leaving old code lying around!

Anyway, that's fixed in `v3.5.36-beta`
