### ISSUE TITLE
Covariance of immutable containers

### ISSUE THREAD

**Issue by Hinidu** [louthy/language-ext#91]
Hello! I've just started to use `Language.Ext.Core` and I've ran into the small inconvenience - `Either<L, R>` (like all other container types in this library) is not covariant on its type arguments. In some cases it forces me to cast returned value manually to the base class. Does this design have some purpose? If I understand everything correctly we can make immutable containers covariant essentially for free. But maybe I've missed something important...
Thank you in advance.

**Comment by louthy** [comment]
Unfortunately covariance isn't an available for generic structs, and all types like `Option`, `Either`, etc. are structs (to remove the `null` problem).  It's a limitation I'm afraid (until C# can behave a little less shit in this area).  If you need to cast the generic type then the best approach I have found is to use the `Map`, `MapLeft`, or `BiMap` operators.

**Comment by Hinidu** [comment]
Oh, it's sad, didn't know about that (or forgot)...
In that case what about `Lst<T>`, `Set<T>`, etc? They are classes. And it looks like we can create the list of mammals adding a cat to the list of dogs :smile_cat:

**Comment by louthy** [comment]
`in` and `out` invariance settings are done on interfaces, so for example I could do:

`public interface ILst<out T>` would make it covariant 
`public interface ILst<in T>` would make it contravariant

And then derive `Lst<T>` from `ILst<T>`

The problem is that most operations require inputs _and_ outputs, making the resulting `ILst<T>` pretty useless.  For example:
```c#
    ILst<T> Add(T value);
```
It's the nature of immutable value-types to have associated behaviours that require an input and generate a new value; and therefore tripping up on C#'s constraints for covariance and contravariance.  This means `out` and `in` aren't available.  

If you look at the interfaces that `Set`, `Map`, `Lst`, etc. derive from: `IEnumerable<T>`, `IReadOnlyList<T>`, etc.  They all support covariance, but they also have a tiny set of supported operations.  I have just done a quick scan of `Lst<T>`, and there's only `Reverse` that would work in a covariant interface, and none of the methods would work in a contravariant one.

Again you will either need to `Map` the collections, or work with the more abstract types from early on so that you don't need a conversion.  Personally I find that I very rarely trip up on this stuff now, but that's probably because I use inheritance much less frequently than I did in my OO days.

**Comment by Hinidu** [comment]
Thank you for detailed explanation! It's really hard to grasp all these caveats of covariance and contravariance in C# :disappointed: 
I've encountered it the cases like this:
```c#
public static Either<Error, TValue> GetEither<TKey, TValue>(
    this IDictionary<TKey, TValue> dictionary, TKey key)
{
    return dictionary.TryGetValue(key)
        .ToEither(() => (Error)new KeyNotExistError<TKey, TValue>(key));
}
```
Perhaps sometimes I'll try to define algebraic data types in F# if it will be more suitable for such tasks than inheritance.

**Comment by louthy** [comment]
@Hinidu Indeed it's sometimes a little ugly I'm afraid.  To reduce the amount of clutter from casting I tend to use the `as` operator (even if it's slightly less efficient):
```c#
    public static Either<Error, TValue> GetEither<TKey, TValue>(
        this IDictionary<TKey, TValue> dictionary, TKey key)
    {
        return dictionary.TryGetValue(key)
            .ToEither(() => new KeyNotExistError<TKey, TValue>(key) as Error);
    }
```
Or you could use `MapLeft` if you want to be more declarative:
```c#
    public static Either<Error, TValue> GetEither<TKey, TValue>(
        this IDictionary<TKey, TValue> dictionary, TKey key)
    {
        return dictionary.TryGetValue(key)
            .ToEither(() => new KeyNotExistError<TKey, TValue>(key))
            .MapLeft(x => x as Error);
    }
```

**Comment by Hinidu** [comment]
@louthy Thank you for suggestions :+1:
