### ISSUE TITLE
Not enough material around using TryAsync and all the operators in general 

### ISSUE THREAD

**Issue by RedEyedDog** [louthy/language-ext#919]
Hi I'm struggling finding any good reading material on using this library.... I cant find anywhere that describes best ways to use TryAsync for example?

All the examples do not seem to be real world examples.. like making http calls, handling the results etc.

There are not many examples on chaining these operators together, to create functional chain with success and failure paths?

Thanks

**Comment by louthy** [comment]
Use `Aff` and `Eff` instead of `TryAsync` and `Try`.  They're a more powerful superset of the functionality of `Try*` with a more opinionated approach to IO.

There's plenty of [documentation here](https://github.com/louthy/language-ext/wiki/How-to-deal-with-side-effects)

Fundamentally though, `Try*` is just a monad like Option, IEnumerable, etc.  They compose in the same way, and have the same core set of traits, like `Map`, `Bind`, `Fold`, ... and support in LINQ for composition.  The only difference is that functions are *lifted* into the monad instead of values.  So, if you know how to use one monad in this library, you pretty much know how to use them all.  

```c#
   public Try<int> Foo() => 
       () => 100;
```
Is just a delegate:
```
Func<int>
```
`TryAsync` is the same, but with an `async` function
```c#
   public TryAsync<int> Foo() => async
       () => await Task.FromResult(100);
```
