### ISSUE TITLE
Proxies can't accept nullable or option parameters

### ISSUE THREAD

**Issue by OlduwanSteve** [louthy/language-ext#92]
The proxy code deliberately prevents nulls from being used, but as Option isn't serialisable it can't be used in place of null.

Seems like the fix would either be to allow nulls or perhaps make a custom serialiser for Option.

**Comment by louthy** [comment]
@OlduwanSteve Looking into this now

**Comment by louthy** [comment]
@OlduwanSteve This is fixed in v1.8.16-beta, there was some real weirdness with how Options were being serialised by Json.NET.  It would turn `Some(123)` into `"123"`, losing all type info and property names.  So relying on `TypeNameHandling.All` to provide the type details for deserialisation didn't cut it.  

Anyway, resolved.
