### ISSUE TITLE
Request: `AtomChangedEvent<A> Change` for `AtomHashMap<K, V>` and `Ref<T>`

### ISSUE THREAD

**Issue by CK-LinoPro** [louthy/language-ext#923]
`Atom<T>` has an event `AtomChangedEvent<T> Atom<T>.Change` that emits any changes made to the atom via `Atom<T>.Swap(...)`.
Is it possible to provide the same event for `AtomHashMap<K, V>` and `Ref<T>`?

**Comment by CK-LinoPro** [comment]
Do you have an update on this topic?
Currently, what I'm doing is a error-prone workaround where I update an `Atom<T>` each time I update its `Ref<T>` instance,
but at that time the value inside the `Ref<T>` instance has not been written yet.

If you like I could look into it myself and provide a pull request.

**Comment by CK-LinoPro** [comment]
I've created a pull request: https://github.com/louthy/language-ext/pull/972.

**Comment by CK-LinoPro** [comment]
Thanks for your review of the PR, it's unfortunate my approach is too naive to be accepted.
I could convince my team to work on a fork for now, so there is no hurry for a more practical solution.
I know this request isn't without issue as the whole topic of STM is rather complicated.

**Comment by louthy** [comment]
[I've made a start with this](https://github.com/louthy/language-ext/commit/9552ef54e2bcb4403b83f57978daaa7384213b57).  I am slightly short of time right now, so I've just done the foundational work and implemented change-tracking for `AtomHashMap<K, V>`.

The underlying `TrieMap<EqK, K, V>` now has variants of all collection-transforming methods that can track changes, i.e. `Add` and `AddWithLog`.  The `*WithLog` variants will tracking insertions, deletions, and updates - even for collection wide transformations.

The `AtomHashMap<K, V>` has been updated to use these methods if the `OnChange` event is not-null.  That means for those who aren't using change-tracking feature there's no overhead.  Even for those that are, it's very optimal, and does the minimum work needed to collect the changes.

The event type looks like this:
```c#
    public delegate void AtomHashMapChangeEvent<K, V>(
        HashMap<K, V> Previous, 
        HashMap<K, V> Current,
        HashMap<K, Change<V>> Changes); 
```
So, for each atomic change you get the previous state of the hash-map, the current-state, and a `HashMap` of changes - which can be:

* `ItemUpdated<V>` - which has the old-value and the new-value for an updated key,
* `ItemMapped<A, B>` - which is similar to ItemUpdated<V>, except this is used when mapping from one value-type (A) to another (B).  Contains both the A and B values.
* `ItemAdded<V>` - Has the newly added value
* `ItemRemoved<V>` - Contains the value that was removed

This gives very fine-grained detail about what's changed, and what it's changed from for any key in the collection.

NOTE: None of this is tested and there's still quite a bit to-do, and so it won't be deployed for a little while at least:

* Add support to `AtomHashMap<EqK, K, V>`
* Try and implement a similar system (that makes sense) for `AtomSeq<EqK, K, V>`
* Consider how this could work with the STM system without adding additional processing for those who don't want change-tracking
   * This may be better as a returned set of changes from `atomic`\`snapshot`\`serial`, rather than as an event.
* Lots of unit tests are needed!

**Comment by CK-LinoPro** [comment]
Most importantly, thanks for your time. You've mentioned before that you are taking some time off from this project, so I'm really appreciating it.
I think this is a good approach for atomic collections. I wonder how well it combines with the existing patch data types.

I'm still trying to wrap my head around `STM` however.
I see the problem with lots of allocations for systems that use `Ref<T>` a lot but I'm not sure how to mitigate it.
My most intuitive approach would have been to hold an `IObservable<T>` along with each registered `Ref<T>` (which I didn't want to do because of additional dependencies), but the more I think about it the more I think the performance would be even worse than my naive approach using events.

For some background on our typical use case:
We are using a reactive approach via `Observable`-like types to model directional interaction between view models and services in a modular application.
`Atom<T>` is incidentally a very good chain link between service-internal state management written with an easily maintainable functional philosophy and inter-service messaging and updates on other components.
The only problem with `Atom<T>` is that it is limited to a single-value context, `Ref<T>` on the other hand gives us great benefit when managing the main parts of our application state that is split into multiple independent types that are big enough as they are.
Currently there is no reliable way to observe changes within `Ref<T>` instances, which causes lots of headaches within our team.

**Comment by CK-LinoPro** [comment]
Thanks a lot! Those changes are a huge help.
I'll do my best to provide some unit tests.
I like the idea of `TrackingHashMap` as its own type, that will be quite useful.

**Comment by CK-LinoPro** [comment]
I've created a [Pull Request](https://github.com/louthy/language-ext/pull/1009) containing the tests from my previous attempt.
It's far from full code coverage but I've found some issues mentioned within the PR's description.

**Comment by louthy** [comment]
Awesome, thanks.  I’ll be away from my home PC for a few days, so I’ll check it after then

**Comment by louthy** [comment]
`v4.0.8-beta` is up now.  There were a few small issues in the unit-tests, but the majority were spot-on.  I've fixed the issues that came up, and also added `Union` and `Intersect` with merging-strategies (like `Map`).  These have been added to `HashMap`, `AtomHashMap`, and `TrackingHashMap`.

I'll keep it in beta for a short time, maybe look to do a full release at the end of the month if nothing comes up.
