### ISSUE TITLE
provide the ability to store Additional data in the Error struct.

### ISSUE THREAD

**Issue by SeanFarrow** [louthy/language-ext#933]
@louthy 
It would be really nice if the Error struct could provide a Data property/field allowing a user to store data that should be available to clients when processing the error.

To give a concrete example as to why this would be nice, I'm converting a piece of code from using exceptions to using the Fin<T> construct. I'm creating an Error instance with the exceptions message, but have a need to store some additional context-specific data pertaining to such an error.

Does this sound sensible to you, if not, I'm happy to keep using the exception-based code and just wrap it, but having additional data on the Error as an Option<object> would seem to make sense.
Thanks,
Sean.

**Comment by StefanBertels** [comment]
At least you can store `Exception` within `Error` and use `Exception.Data` as dictionary... 🙄

Of source this is not a good solution (a lot of type-unsafety etc) but we should avoid moving this type-unsafety into `Error` itself.

Another (related) problem: (How) can `Error` be serialized?
Exceptions have big serialization problems: https://github.com/dotnet/runtime/issues/43482

But I like the idea to make `Error` more useful in general. 

Maybe some `Error<T>`? There could be a base type / interface `Error/IError` and then 

`Error<int>` (instead of built-in `.Code` property)
`Error<Exception>`
`Error<(int Code, Exception Exception)>`
`Error<MyCustomData>`

Maybe this is some (generic) Union?

(And: a little bit related to my #937.)

Just some thoughts.

**Comment by diab0l** [comment]
@SeanFarrow 
You can solve your problem by using `Either<(Error, B data), A>` instead of `Fin<A>`.
That way you either get an error and associated data or your success value.

**Comment by louthy** [comment]
@SeanFarrow [The new `Error` type refactor](https://github.com/louthy/language-ext/releases/tag/v4.3.0-beta) should fix this for you.  It allows for bespoke error types and much more besides!

**Comment by SeanFarrow** [comment]
@louthy,
Thanks, I’ll take a look.
