### ISSUE TITLE
"Anonymous function converted to a void returning delegate cannot return a value" trying to return a value from `Option.Match`

### ISSUE THREAD

**Issue by MrYossu** [louthy/language-ext#941]
As usual, I'm sure this is really obvious to the enlightened, but I'm not, so please humour me!

I have a method that creates a folder in Google Drive. That works fine, but the current version doesn't check if a folder of the same name exists, and will create another with the same name. I know Google allows this, but my requirement is not to.

So, I want to change my method to check if a folder exists with the given name, and if so, return the `Id` of that folder. If a folder doesn't exist, then we'll create a new one and return the `Id` of the new folder.

I have an existing method that gets the subfolders of a specified folder...

```c#
public async Task<Option<List<DriveFile>>> GetSubfolders(string folderId)
```

This returns `Some<List<DriveFile>>` if a folder exists with the `Id` of `folderId` and `None<List<DriveFile>>` if not.

I was expecting to be able to use this as follows...

```c#
public async Task<Option<string>> CreateFolder(string folderName, string parentFolderId = "root") =>
  (await GetSubfolders(parentFolderId))
  .Match(async folders => {
    if (folders.Any()) {
      return folders.First().Id;
    }
    // The implementation of CreateNewFolder isn't shown as it's not relevant to my question
    DriveFile folder = await CreateNewFolder(folderName, parentFolderId);
    return folder.Id;
  }, () => {
    return Option<string>.None;
  });
```

However, I get compiler errors on the three `return` lines...

>Anonymous function converted to a void returning delegate cannot return a value

I've done some searching on this error, but don't really understand what's going on here. I have returned values from `Match` before, and not had this issue.

Anyone able to explain what I'm doing wrong? Thanks.

**Update** If I extract the code that does the actual folder creation to a separate method as follows...

```c#
public async Task<Option<string>> CreateFolder(string folderName, string parentFolderId = "root") =>
  (await GetSubfolders(parentFolderId))
  .Match(async folders => await CreateNewFolder(folderName, parentFolderId, folders), Option<string>.None);
```

...then I'm down to one compiler error on the `Option<string>.None` at the end...

>Argument 2: cannot convert from 'LanguageExt.Option<string>' to 'System.Func<System.Threading.Tasks.Task<string>>'

OK, so let's change the code to this...

```c#
public async Task<Option<string>> CreateFolder(string folderName, string parentFolderId = "root") =>
  (await GetSubfolders(parentFolderId))
  .Match(async folders => await CreateNewFolder(folderName, parentFolderId, folders), () => Option<string>.None);
```

That changes the compiler error to...

>Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement

So I'm baffled.

**Comment by louthy** [comment]
If the compiler infers that `Match(Action, Action)` (the void returning version of match) when you're actively trying to return a value, then the two functions (`Some:` and `None:`) don't have a common-type, or the common-type can't be inferred by the compiler.

In this case you have a `Task<Option<string>>` and a `Option<string>`.  There is nothing the compiler can do to infer those as the same, as there's no common join between them.

If you instead use this on your `None` branch: `() => Option<string>.None.AsTask()` or `Option<string>.None.AsTask()` then it should work.

Note also, that if you're calling `Match` and each branch returns an `Option`, then you're effectively doing a `Bind`.  This will probably work too:

```c#
public async Task<Option<string>> CreateFolder(string folderName, string parentFolderId = "root") =>
  GetSubfolders(parentFolderId)
      .BindT(folders => CreateNewFolder(folderName, parentFolderId, folders));
```
I'm using `BindT` because it's two monads nested, so this runs the monadic bind operation for both the outer `Task<>` and the inner `Option<>`
