### ISSUE TITLE
null dereference in .GetHashCode

### ISSUE THREAD

**Issue by tfg1434** [louthy/language-ext#945]
`List<object>(null, null).GetHashCode();` throws a `NullReferenceException` is this the intentional behaviour?

Maybe you need to enforce notnull items in this method
```cs
public static int Hash<HashA, A>(IEnumerable<A> items, int offsetBasis = -2128831035) where HashA : struct, Hashable<A>
    {
      int hashB = offsetBasis;
      if (items == null)
        return hashB;
      foreach (A x in items)
        hashB = FNV32.Next(default (HashA).GetHashCode(x), hashB);
      return hashB;
    }
```

Thanks for reading, I appreciate the work you put into this!

**Comment by louthy** [comment]
It's not `Hash` that's the issue, it's the constructor function combined with usage of `null`:

This is the constructor function:
```c#
Lst<T> List<T>(T x, params T[] xs) 
```
There's another constructor function that constructs an empty `Lst`:
```c#
Lst<T> List<T>() 
```
That's why the first one needs a single argument of `T` before the `params T[]`.  It's done this way to avoid allocations for empty lists.

Anyway, when you call `List(null, null)` the C# compiler doesn't think you're passing one argument `+` a _one-element-params-array_, it thinks you're passing `null` as the array.

So, `x` is `null` and `xs` is also `null`, and not `[null]`.  

I'll need to have a think about the best way to avoid this issue, but in the meantime you should be able to call:
```c#
    toList(new object[] { null, null });
```
For two item lists with `null` as the second item.  I realise this is not ideal, but I need to consider the impact of any changes carefully.
