### ISSUE TITLE
License Information in NuGet Package

### ISSUE THREAD

**Issue by ghost** [louthy/language-ext#949]
Dear Maintainers,

please fix the License Info for the NuGet packages. I see here on Github that you are using MIT license, which I greatly appreciate. Yet, you do not use the SPDX expression `MIT` in the package, instead you provide an URL to Github. If you use the expression, it is also easier for all users, and recommended by NuGet.

Thanks in advance.

**Comment by louthy** [comment]
Could you spell this out as if I were an idiot, because I have no idea what you're talking about ;)

**Comment by lphimath** [comment]
@louthy Sorry, I thought you would what I was talking about.

Have a look at https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/LanguageExt.Core.csproj#L29. You use `PackageLicenseUrl` which is deprecated. For reference, have a look here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target.

Since your project is licensed under MIT license (thanks for that btw!), I suggest you replace the line in the `.csproj` file I marked above with the following:
```
<PackageLicenseExpression>MIT</PackageLicenseExpression>
```

You might also wanna look into the other `.csproj` files and change it there as well.

Thanks in advance for the consideration!
