### ISSUE TITLE
Add ToListT method

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#97]
Here's a useful method, not sure if it is named right.

        /// <summary>
        /// Process the enumerable and if any error is encountered then fail fast otherwise
        /// return the list with no errors.
        /// </summary>
        /// <typeparam name="TErr"></typeparam>
        /// <typeparam name="TVal"></typeparam>
        /// <param name="b"></param>
        /// <returns></returns>
        public static Either<TErr, IList<TVal>> ToListT<TErr, TVal>(this IEnumerable<Either<TErr, TVal>> b)
        {
            var output = new List<TVal>();
            foreach (var either in b)
            {
                if (either.IsLeft)
                    return either.Select(_ => (IList<TVal>) ImmutableList<TVal>.Empty);

                either.IfRight(v => output.Add(v));
            }

            return Right<TErr,IList<TVal>>(output);
        }

**Comment by louthy** [comment]
@bradphelan Hi Brad, thanks for that.  I think that's a bit too specific for the library - I'm not sure of any common functional operator that does something like this.  If I was to try and give it a name I'd probably call it `BindUntilT` or `BindWhileT`, because it's essentially doing the monadic bind for the enumerable until a predicate is true (`either.IsLeft == true`).  But then again the type it returns is fundamentally different, so that's not a great name either.

There are various things close to it in the library: 
* `IEnumerable<Either<L,R>>.BindT()`
* `IEnumerable<Either<L,R>>.Lefts()`,
* `IEnumerable<Either<L,R>>.Rights()`
* `IEnumerable<Either<L,R>>.Partition()`
* `IEnumerable<T>.FoldUntil()`
* `IEnumerable<T>.FoldWhile()`
* `IEnumerable<T>.Choose()`

This is a more functional way to implement it with the existing methods.  It's lazy, so not quite the same:
```c#
    var res = eithers.Partition()
                     .Map((ls, rs) => ls.Any()
                        ? Left<string, IEnumerable<int>>(ls.Head())
                        : Right<string, IEnumerable<int>>(rs));
```

**Comment by louthy** [comment]
Actually, `TakeWhileRight` is probably a better name for it.  It then has echos of the `Take` operator from LINQ.

**Comment by bradphelan** [comment]
Hi thanks for the advice. In the end I've decided not to use Either for error handling. We have developed a library called [Exceptional](https://github.com/Weingartner/Exceptional) which specifically encapsulates exceptions, as well as the combinators catching any exceptions thrown within themselves. The library also wraps IObservable and IExceptional as IObservableExceptional so that errors do not terminate the subscription. We still use your library for other things. It's very very nice. Thanks.
